### ISSUE TITLE
oeedger8r: Support switchless calling

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#1030]
Making calls across the host/enclave boundary uses the EENTER/EEXIT instructions which have a significant performance cost. For some applications, this code is prohibitive.

_Switchless_ calling is a mechanism to implement ecalls and ocalls using a shared buffer and lock-free host and enclave threads that allow making ecalls and ocalls without incurring the performance cost of _switching_ (transition).

EDL language supports the _transition_using_threads_ keyword/annotation that can be applied to trusted and untrusted functions. With this annotation, edger8r generates code to use switchless calling.

**Comment by radhikaj** [comment]
@anakrish @jxyang can we close this?

**Comment by anakrish** [comment]
Completed. We have implemented only switchless OCALL which has been requested by users. Switchless ecalls will be done at a later date based on requests.
