### ISSUE TITLE
oeedger8r: Support deep-copy via attributes on struct members

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#1031]
We want to enhance EDL to allow specifying the size, count attributes on struct members. Eg:
 
    struct my_struct {
         [count=10] int* p1;
         [size=40] int* p2;
         [count=p3_size] int* p3;
         [isptr, count=5] my_ptr_t p4;
         int p3_size;
    };

Using these annotations, we will do a deep-copy of all data across the host/enclave boundary.

**Comment by andschwa** [comment]
Oh sweet we have an issue for this.

**Comment by radhikaj** [comment]
@anakrish Can this be closed?

**Comment by andschwa** [comment]
@radhikaj Yup!
