### ISSUE TITLE
Re-enable tests for ELF enclave on Windows

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#1033]
Prior to PR #632, many more tests were enabled for running ELF enclaves on Windows. This issue tracks re-enabling these tests and fixing any new build breaks and issues introduced into them while they were disabled:
- abortStatus
- create-rapid
- ecall_ocall
- echo
- enclaveparam
- cppException
- getenclave
- hostcalls
- hexdump
- initializers
- libc
- libcxx
- libcxxrt
- memory
- mixed_c_cpp
- ocall
- ocall-create
- print
- report
- SampleApp
- SampleAppCRT
- sealKey
- stdcxx
- thread
- threadcxx

In addition, we should also evaluate enabling tests that were previously not enabled due to a dependency on `oegen` which has since been replaced by `oeedger8r` that has been enabled to run on Windows by PR #895:
- file
- pingpong
- pingpong-shared

**Comment by anitagov** [comment]
Enabled 16 ELF enclaves on Windows with my PR #1173

**Comment by anitagov** [comment]
Look at Issue #1008 where 16 + 6 tests were enabled.

**Comment by anitagov** [comment]
Enabled 2 more tests (cppException and sealKey) with PR #1280

**Comment by anitagov** [comment]
PR #1243 enabled VectorException

**Comment by anitagov** [comment]
PR #1289 - Enabled abortStatus for Windows after resizing ELF enclave and bypassing the result from terminate_enclave.

**Comment by anitagov** [comment]
Enabled mbed tests for Windows with my PR #1372 .
Disabled ecall_ocall for Windows as it intermittently fails with my PR #1415 .

**Comment by anitagov** [comment]
The current list of tests that are not enabled on Windows are:
**create-rapid**
**crypto_crls_cert_chains**
**ecall_ocall** - Was enabled and recently pulled out due to size issues on Windows
**libc** - Enabling in progress but unable to resize for ACC VMs
**libcxx** 
**libcxxrt**
**libunwind**
**memory**
**qeidentity** - Attestation is not supported on Windows
**report** - Attestation is not supported on Windows

**Comment by anitagov** [comment]
libc tests were enabled on Windows with PR #1508

**Comment by CodeMonkeyLeet** [comment]
Closing this as outdated and tracking remaining tests as part of parent epic #39 directly.
