### ISSUE TITLE
Support libunwind and libc tests for ELF enclaves on Windows

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#1034]
The following tests relating to libc/libunwind are currently disabled on Windows because their functionality was not appropriately supported before. 
- backtrace
- libunwind
- stdc 

The causes for their failures on a Windows host need to be investigated; in particular, issues with libunwind/backtrace suggest issues that need to be fixed for the story around parity with Linux behaviors (#376)

Also need to investigate enabling the libcxx related tests on Windows:
- libcxx
- libcxxrt

**Comment by anitagov** [comment]
Enabled both backtrace and stdc are enabled on Windows.

**Comment by johnkord** [comment]
@anitagov Do you know what the status is for libunwind support in this issue?

**Comment by anitagov** [comment]
@johnkord - No, I do not know the status of libunwind on Windows.

**Comment by anitagov** [comment]
@johnkord - No change to the status of libunwind on Windows.

**Comment by mingweishih** [comment]
#2400 for the follow-up on libunwind test support

**Comment by mingweishih** [comment]
Update: libunwind is enabled with #2400. 
The PRs for enabling libc (#2403) and libcxxrt currently depend on #2434 and #2471, respectively.
