### ISSUE TITLE
App devs have an integrated Windows dev experience with OE SDK on Visual Studio 2019

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#1041]
~~Depends on #1040 to have PE enclaves on Windows.~~
> This no longer depends on PE enclave support in Windows, debugger and other work is ongoing for **VS 2019** support with ELF on Windows.

This story tracks ensuring an integrated dev experience on Windows through VS2019 tools, which includes the following tasks:
- [ ] (External) Add VS2019 debugger support for debugging OE PE enclaves
- [ ] Add VS templates for OE app development
- [ ] Update documentation around VS2019 usage

**Comment by radhikaj** [comment]
@CodeMonkeyLeet We need to change the description.

**Comment by dthaler** [comment]
I believe this is all done now, please reopen if not
