### ISSUE TITLE
Attestation: OE_VERIFY_FAILED was overloaded for many validation failures, need define new error codes for specific failure condition

### ISSUE THREAD

**Issue by soccerGB** [openenclave/openenclave#1044]
The OE_VERIFY_FAILURE code is returned for any validation failures in the the code path of the oe_verify_report() API, which does not help narrow down the root causes, even thought the OE SDK has the exact error code for most the failure scenario. Unfortunately, the original failures were swallowed and replaced with generic  OE_VERIFY_FAILURE  code, which makes debugging attestation issues very difficult.

We need to map to original error codes to unique OE_ error code.

**Comment by johnkord** [comment]
@soccerGB We should figure out the list of error codes that we want to expose.

**Comment by jazzybluesea** [comment]
Reopening to address Simon late comments.
