### ISSUE TITLE
Fix Jenkins' GitHub auth to work with organization permissions 

### ISSUE THREAD

**Issue by andschwa** [openenclave/openenclave#1067]
As of June 24th, GitHub's API changed https://developer.github.com/changes/2015-01-07-prepare-for-organization-permissions-changes/

And per this comment:

> However if you're going to use this with a github organization you should add the application under https://github.com/organizations/ORGANIZATION/settings/applications/new

It seems we would need to move the GitHub OAuth app to the Microsoft organization for this to work.

When I last contacted the Microsoft GitHub org admins about bors, they seemed more than willing to help out with this  kind of thing. So @johnkord, I suggest we move the app, and then the Microsoft org permissions should work just fine.

For now, I have anonymous and authenticated working as intended (read-only), but I am hesitant to grant build permissions that wide, and want to restrict to just the Microsoft org (or better, a team), but can't. As it is, we have to add people manually for them to see the "Run" button in Blue Ocean (but we no longer have to do this for them to be able to see the result of a build).

**Comment by BRMcLaren** [comment]
No longer needed, closing.
