### ISSUE TITLE
what is the maximum size of memory in TrustZone

### ISSUE THREAD

**Issue by mofanv** [openenclave/openenclave#1174]
Hello,

I previous work with OP-TEE on a qemu. The memory size is very limited, usually less than 10 MB. I see the Openenclave is based on OPTEE regarding the Arm TrustZone. I'm wondering does this framework change this limitation? 10MB is too small for my project.

Thanks, any comment is appreciated.

**Comment by dthaler** [comment]
OP-TEE’s memory layout is specified at compile time by 
CFG_TZDRAM_START
CFG_TZDRAM_SIZE
CFG_SHMEM_START
CFG_SHMEM_SIZE

On an LS1012, CFG_TZDRAM_SIZE is currently 0x4000000 - 0x00200000 = 63MB.

Each individual TA can specify its data and stack size by
TA_STACK_SIZE
TA_DATA_SIZE
which are 12K and 1M, respectively, in the socket and helloworld sample TAs (e.g., see https://github.com/Microsoft/openenclave/blob/feature.new_platforms/new_platforms/samples/helloworld/HelloWorldEnc/optee/user_ta_header_defines.h)

**Comment by mofanv** [comment]
@dthaler Thank you very much for your comments! 
I could change the value of TA_STACK_SIZE and TA_DATA_SIZE now. I'm wondering could we change the value of CFG_TZDRAM_SIZE to increase the memory size? Do you think it is possible? Thanks again

**Comment by jordanrh1** [comment]
See https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/include/mm/generic_ram_layout.h for a description of the configuration directives involved in memory layout.

You may have to adjust parameters in U-Boot and PPA as well. It is worth double checking before modifying the memory layout.

**Comment by radhikaj** [comment]
@mofanv Can this issue be closed?

**Comment by mofanv** [comment]
> @mofanv Can this issue be closed?

Sure. I'm closing it. thanks!
