### ISSUE TITLE
Thread Local Storage: Optimize oe_host_malloc/oe_host_free

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#1178]
oe_host_malloc is used to allocate memory for host calls. After the ocall is made, the memory is freed using oe_host_free. Since these functions themselves are internal ocalls, it takes 6 enclave-host boundary transitions (3 to host and 3 back to enclave) to make an ocall. This makes it *a lot* slower.

With thread-local storage being available in the enclave, it should be possible to optimize this by having each enclave thread manage a host memory buffer.

@EMumau  assigning this to you to keep it in your radar of Thread Local Storage related work.
CC: @mikbras

**Comment by mikbras** [comment]
Because we lack this feature, the file system work has had to create the **oe_hostbatch_t** type.

https://github.com/Microsoft/openenclave/blob/feature.fs/fs/common/hostbatch.h

**Comment by anakrish** [comment]
Ocalls have been optimized by passing in a buffer for ocall parameters. 
https://github.com/openenclave/openenclave/commit/672e43eeb222416fc0e1408f3b4b0720127c8e68

This reduces ocalls to just 2 transitions for most cases.
