### ISSUE TITLE
OE SDK logging: Need to add logging for enclave creation

### ISSUE THREAD

**Issue by soccerGB** [openenclave/openenclave#1230]
The current OE SDK logging mechanism only turns on after an enclave was successfully created.
Need to expand current logging mechanism to the enclave creation process.

**Comment by johnkord** [comment]
Is there additional work to be done regarding this, @soccerGB ?

**Comment by soccerGB** [comment]
I don't feel very strongly about this logging support.
Feel free to close it if you agree.
