### ISSUE TITLE
Cannot mix & match C/C++ files in one CMake enclave target

### ISSUE THREAD

**Issue by jorkl** [openenclave/openenclave#127]
Having both C and C++ files in a single CMake target, such as
```
add_library(foo STATIC a.c b.cpp)
```
does not work.

# Background
The standard compiler (gcc/g++) differentiates include directories when compiling (g++ adding the C++ header dirs in front of the lib-C header dirs). OE uses its own libc/libc++ with own include dirs. Usage by a using target is controlled by adding the oelibc and oelibcxx targets to the list in target_link_libraries().
CMake does support generator expressions ($<COMPILER_LANGUAGE>) that do allowing selective additions of include-dirs depending on the language used (C v.s. C++), and adding it properly to the oelibcxx_cxx target solves the issue for the dev-tree.
When generating the export module for 3rd-party use, CMake generates an import-module with the $<COMPILER_LANGUAGE> expression correctly present in the INTERFACE_INCLUDE_DIRECTORIES property. However, using such module breaks CMake.
Details: https://gitlab.kitware.com/cmake/cmake/issues/17811

# Workaround
Do not mix C and C++ files within one target. Either convert C files to C++, or create a separate library for one language.

**Comment by anakrish** [comment]
This issue had not been completely fixed. There were problems when using C files that include an header like stdint.h and a c++ file that included list.
Fixed by #985
