### ISSUE TITLE
Run simulation tests on the same platform that non-simulation tests are run.

### ISSUE THREAD

**Issue by johnkord** [openenclave/openenclave#1294]
We should run (before or after?) simulation tests for each of the non-simulation tests that we run. This could probably allow us to reduce the number of parallel stages in our configuration.  I think we should continue to have a few stages that run simulation tests on non-ACC hardware, though.

**Comment by ionutbalutoiu** [comment]
Hello @johnkord!

Just had a chat with @oprinmarius about this one.

When the non-simulation tests are run, we should invoke the **same** tests (but with simulation enabled via `OE_SIMULATION=1` flag) exactly in the next step in the same stage.

This would indeed reduce the number of stages, and add improvements to the CI execution times. Right now, with 2 separate stages (for non-simulation and simulation), you end up building OE twice in each stage, before running `ctest`.

Would these address your concerns with this issue ?

Ionut

**Comment by anitagov** [comment]
You may be able to run ctest after (or before) doing a OE_SIMULATION=1 ctest if this is being done on ACC hardware. But necessary cleanup of the test results may need to be done without destroying the build. I am not sure of the exact steps to do this. 

On non ACC h/w, of course, only simulation runs can be done but we should continue to have this setup.

**Comment by radhikaj** [comment]
@BRMcLaren Please investigate and close.

**Comment by BRMcLaren** [comment]
@radhikaj I don't believe this is a priority. Closing.
