### ISSUE TITLE
tests/print has issues on Windows

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#1312]
This test is Linux-centric may need to be rewritten to run correctly on Windows:

- The test uses `sh` to pipe the output to fill then runs `diff` against oracle output. While the test executes in ctest, it always passes even when the oracle files have been modified to not match expected output, indicating that the `sh` errors are not correctly captured on Windows.
 
- It currently shows up in ctest on Windows but not in VS2017 Test Manager because the CMakeLists.txt declares the command with line breaks in the middle for formatting; removing the line breaks allows Test Manager to correctly pick up the test.

**Comment by yakman2020** [comment]
Is this still true?

**Comment by mingweishih** [comment]
Depend on #2471

**Comment by mingweishih** [comment]
I confirm that the problem no longer exist on Windows. Suggest closing the issue.

**Comment by radhikaj** [comment]
Thanks so much @mingweishih
