### ISSUE TITLE
Evaluate moving to mbedTLS v2.16 branch

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#1457]
mbedTLS has designated its latest update [v2.16.1](https://tls.mbed.org/download/start/mbedtls-2.16.1-apache.tgz) as of 2018-12-21 the new long-term stable production branch. We should evaluate the impact of moving to this new release:

- [ ] Reconcile breaking changes in the API surface with OE SDK use
- [ ] Evaluate whether this poses issues for link-time mbedTLS replacement for projects using mbedTLS updated with Everest TLS crypto.
- [ ] Evaluate cost-benefit of moving to 2.16.x
- [x] Determine if 2.7 branch is being EOL and timeframe for that.
- [ ] Request OSS SDL security review of new mbedTLS version.

**Comment by CodeMonkeyLeet** [comment]
Per @achamayou, there's a request to move to a newer version of mbedTLS for the expanded feature set as discussed in closed PR #1414.

**Comment by achamayou** [comment]
@CodeMonkeyLeet as far I know, the mbedTLS + Everest snapshot in use (discussed here https://github.com/Microsoft/openenclave/pull/1419) is based on 2.16, so I would not expect us to hit any issues. I'd be happy to help with testing that though, and report any problems.

We have been using a build of OE with this snapshot successfully for some time now (with a source swap though, not a link-time swap), so I do not think any OE code changes will be necessary (or at least not on Linux).

**Comment by vlaza** [comment]
**Determine if 2.7 branch is being EOL and timeframe for that.**
Mbed TLS 2.7
As such, we are pleased to announce that Mbed TLS 2.7 will now become our next LTS (Long Term Support) branch, and that we will continue to maintain it for the next 3 years, until at least February 2021.

https://tls.mbed.org/tech-updates/blog/our-next-lts-branch-mbedtls-2.7

**Comment by vlaza** [comment]
**Announcing Mbed TLS 2.16 Long Term Support**
We are pleased to announce that Mbed TLS 2.16.0 will be the basis of our next Long Term Support branch, and will be maintained for at least 3 years up until the **end of 2021**.
During that time, no new features will be added to the branch, the API and ABI will be maintained, and only bug fixes will be made to maintenance releases of 2.16.0.

**Comment by vlaza** [comment]
After some tweaking we were able to run tests but main issue is the PASS percentage, only 77% of tests are Passing using this version.

The following tests FAILED:
	 14 - tests/mbed/asn1write (Child aborted)
	 15 - tests/mbed/base64 (Child aborted)
	 16 - tests/mbed/ccm (Child aborted)
	 17 - tests/mbed/cipher.aes (Child aborted)
	 18 - tests/mbed/cipher.ccm (Child aborted)
	 19 - tests/mbed/cipher.des (Child aborted)
	 20 - tests/mbed/cipher.gcm (Child aborted)
	 21 - tests/mbed/cipher.padding (Child aborted)
	 22 - tests/mbed/cmac (Child aborted)
	 23 - tests/mbed/ctr_drbg (Child aborted)
	 24 - tests/mbed/debug (Child aborted)
	 25 - tests/mbed/des (Child aborted)
	 27 - tests/mbed/ecdsa (Child aborted)
	 28 - tests/mbed/ecp (Child aborted)
	 29 - tests/mbed/entropy (Child aborted)
	 30 - tests/mbed/error (Child aborted)
	 31 - tests/mbed/gcm.aes128_en (Child aborted)
	 32 - tests/mbed/gcm.aes192_en (Child aborted)
	 33 - tests/mbed/gcm.aes256_en (Child aborted)
	 34 - tests/mbed/gcm.aes128_de (Child aborted)
	 35 - tests/mbed/gcm.aes192_de (Child aborted)
	 36 - tests/mbed/gcm.aes256_de (Child aborted)
	 37 - tests/mbed/hmac_drbg.misc (Child aborted)
	 38 - tests/mbed/hmac_drbg.no_reseed (Child aborted)
	 39 - tests/mbed/hmac_drbg.nopr (Child aborted)
	 40 - tests/mbed/hmac_drbg.pr (Child aborted)
	 42 - tests/mbed/mdx (Child aborted)
	 43 - tests/mbed/mpi (Child aborted)
	 44 - tests/mbed/pem (Child aborted)
	 45 - tests/mbed/pkcs1_v15 (Child aborted)
	 46 - tests/mbed/pkcs1_v21 (Child aborted)
	 47 - tests/mbed/pkcs5 (Child aborted)
	 48 - tests/mbed/pk (Child aborted)
	 49 - tests/mbed/pkparse (Child aborted)
	 50 - tests/mbed/shax (Child aborted)
	 51 - tests/mbed/ssl (Child aborted)
	 52 - tests/mbed/rsa (Child aborted)
	 53 - tests/mbed/version (Child aborted)
	 54 - tests/mbed/x509parse (Child aborted)

**Comment by anitagov** [comment]
It appears that these tests are either using readv or another unsupported File I/O functions. The test should be enhanced to support these. But the upcoming IO Feature will provide support for all File I/O. So, good to hold off until the feature I/O branch is merged to master.

**Comment by vlaza** [comment]
@anitagov thank you for the input; will be holding until IO Feature is merged.

**Comment by vlaza** [comment]
I have updated the PR #1716 with the following changes:

* Mbed TLS 2.16.1 LTS
* rebase on top of latest master changes

After re-testing nothing changed regarding the list of failing tests.

**Comment by ionutbalutoiu** [comment]
Syncing the issue milestone with the [pull request](https://github.com/microsoft/openenclave/pull/1716) milestone as changed by Bruce.

/cc @yakman2020
