### ISSUE TITLE
SegFault when throwing exception over std::function boundary

### ISSUE THREAD

**Issue by eddyashton** [openenclave/openenclave#1503]
We've been tracking down a SEGFAULT inside our enclave, and we've narrowed in on precise but weird repro steps:
- Create a std::function which has spilled some arguments onto the heap (ie - more than 6 args) inside the enclave, which exits by throwing an exception.
- Call that function within a try...catch block. It is successfully caught.
- Try to call it again, it will SEGFAULT.

The working theory is that one of the modifications to libunwind or libstdcxx is not correctly restoring the function state.

Here's a small patch demonstrating the issue, piggybacking on the stdcxx test:
```
diff --git a/tests/stdcxx/enc/enc.cpp b/tests/stdcxx/enc/enc.cpp
index 5ed1e9f9e..e6a6d837a 100644
--- a/tests/stdcxx/enc/enc.cpp
+++ b/tests/stdcxx/enc/enc.cpp
@@ -81,6 +81,38 @@ void my_at_exit()
     oe_host_printf("my_at_exit()\n");
 }
 
+template <typename R, typename... Ts>
+void test_exception_handling(Ts&&... ts)
+{
+    using F = std::function<R(Ts...)>;
+
+    auto foo = F([](Ts...) {
+        throw std::logic_error("BROKEN");
+        return R();
+    });
+
+    try
+    {
+        // Call function which will throw
+        foo(ts...);
+    }
+    catch (const std::exception& e)
+    {
+        // It is successfully caught
+    }
+
+    try
+    {
+        // Call it again, resulting in SegFault
+        foo(ts...);
+    }
+    catch (const std::exception& e)
+    {
+    }
+
+    printf("%llu params: Reached end\n", sizeof...(Ts));
+}
+
 int enc_test(bool* caught, bool* dynamic_cast_works, size_t* n_constructions)
 {
     /* Register at-exit handler */
@@ -220,6 +252,13 @@ int enc_test(bool* caught, bool* dynamic_cast_works, size_t* n_constructions)
         OE_TEST(bad_alloc_caught == true);
     }
 
+    /* Test exceptions from std::functions */
+    {
+        using Return = size_t;
+        test_exception_handling<Return>(1, 2, 3, 4, 5, 6);
+        test_exception_handling<Return>(1, 2, 3, 4, 5, 6, 7);
+    }
+
     return 0;
 }
 ```

Produces the following test failure:
```bash
$ ctest -VV -R stdcxx

…

71: Test timeout computed to be: 10000000
71: constructor()
71: g::g()
71: g::g()
71: g::g()
71: f::f()
71: f::f()
71: f::f()
71: std::bad_alloc caught
71: 6 params: Reached end
1/1 Test #71: tests/stdcxx .....................***Exception: SegFault  0.16 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.17 sec

The following tests FAILED:
         71 - tests/stdcxx (SEGFAULT)
Errors while running CTest
```

So far we've established this doesn't happen if you throw from a static function or lambda, only a std::function. It doesn't happen if no arguments are spilled (6 or fewer size_t args, or some other combination of struct args). It also doesn't occur in DEBUG builds.

**Comment by anakrish** [comment]
@anitagov @CodeMonkeyLeet

**Comment by anakrish** [comment]
@eddyashton Thanks a lot for the reproduction steps. Gives me something to play with.

Findings so far:

- Cannot reproduce this with release build in GCC. Seems to be clang specific.
- Can reproduce in clang even with Spectre mitigation flags disabled.

**Comment by anakrish** [comment]
I was able to reproduce the crash with a single call to throw. Additionally
It seems that when the exception is caught, the stack pointer (rsp and/or rbp) is corrupt and therefore the code to access the local variables ends up reading incorrect memory locations.
In the following patch, the dbg_foo function is called twice; passing the address of the foo local variable each time. dbg_foo stores the address of foo in a global variable in the first call and in the second call asserts that the address is the same. This assertion is triggered indicating that the stack pointer is corrupted.



diff --git a/cmake/compiler_settings.cmake b/cmake/compiler_settings.cmake
index 55ff0db94..92b10bc1a 100644
--- a/cmake/compiler_settings.cmake
+++ b/cmake/compiler_settings.cmake
@@ -54,7 +54,7 @@ include(CheckCXXCompilerFlag)
 set(SPECTRE_MITIGATION_FLAGS "-mllvm;-x86-speculative-load-hardening")
 check_c_compiler_flag("${SPECTRE_MITIGATION_FLAGS}" SPECTRE_MITIGATION_C_FLAGS_SUPPORTED)
 check_cxx_compiler_flag("${SPECTRE_MITIGATION_FLAGS}" SPECTRE_MITIGATION_CXX_FLAGS_SUPPORTED)
-if (SPECTRE_MITIGATION_C_FLAGS_SUPPORTED AND SPECTRE_MITIGATION_CXX_FLAGS_SUPPORTED)
+if (false) #(SPECTRE_MITIGATION_C_FLAGS_SUPPORTED AND SPECTRE_MITIGATION_CXX_FLAGS_SUPPORTED)
   message(STATUS "Spectre 1 mitigations supported")
   add_compile_options(${SPECTRE_MITIGATION_FLAGS})
   # Allows reuse in cases where ExternalProject is used and global compile flags wouldn't propagate.
diff --git a/tests/stdcxx/enc/enc.cpp b/tests/stdcxx/enc/enc.cpp
index 5ed1e9f9e..0167f5ce3 100644
--- a/tests/stdcxx/enc/enc.cpp
+++ b/tests/stdcxx/enc/enc.cpp
@@ -81,6 +81,42 @@ void my_at_exit()
     oe_host_printf("my_at_exit()\n");
 }
 
+using F=std::function<size_t(int, int, int, int, int, int, int)>;
+F* g_f = NULL;
+
+__attribute__((optnone))
+OE_NEVER_INLINE
+void dbg_foo(F* f)
+{
+  if (g_f == NULL){
+    g_f = f;
+  } else {
+    OE_TEST(g_f == f);
+  }
+}
+
+template<typename R, typename... Ts>
+void test_exception_handling(Ts&&... ts)
+{
+  using F=std::function<R(Ts...)>;
+
+  auto foo = F([](Ts...) {
+		 throw 5;
+		 return R();
+	       });
+
+  dbg_foo(&foo);
+ 
+  try {
+    foo(ts...);
+   
+  }
+  catch (int x) {
+    dbg_foo(&foo);
+  }
+
+}
+
 int enc_test(bool* caught, bool* dynamic_cast_works, size_t* n_constructions)
 {
     /* Register at-exit handler */
@@ -220,6 +256,12 @@ int enc_test(bool* caught, bool* dynamic_cast_works, size_t* n_constructions)
         OE_TEST(bad_alloc_caught == true);
     }
 
+    /* Test exceptions from std::functions */
+    {
+      using Return = size_t;
+      test_exception_handling<Return>(1, 2, 3, 4, 5, 6, 7);
+    }
+
     return 0;
 }

**Comment by yakman2020** [comment]
@anakrish Is this a blocker for 0.6?

**Comment by anakrish** [comment]
@yakman2020 
No this is not a blocker. This is a very specific scenario that needs a lot of investigation to fix.
We don't yet have resources for it. 
CC @jxyang

**Comment by eddyashton** [comment]
Hey @anakrish. Now that v0.6 is released, is there any ETA on a fix for this?

**Comment by radhikaj** [comment]
Hi @eddyashton. We appreciate that this is something you would like to see fixed, but as it is a very tricky issue, we need to take the time to fix it correctly. We don't currently think it will make it into the next release(v0.7), but we will keep you updated. Thank you for your understanding! Please let us know if this issue is blocking progress on your end. Thanks!

**Comment by achamayou** [comment]
@radhikaj this issue was first reported in February, and 0.8 is not due until December. We definitely do not understand why it is taking so long to look into this bug, when there is time for many new features.

It is extremely worrying that exception handling leads to memory corruption, this is at best a correctness problem and at worst a possible security issue, I think it deserves to be fixed, or at least investigated seriously before next year!

**Comment by radhikaj** [comment]
@achamayou Thanks for the information and we would also like to fix this bug and agree that is worrisome.  We plan to do it by the end of v0,.8. Just wont be able to do it in time for v0.7. Thanks!

**Comment by jxyang** [comment]
I just tried out the tip of OE, and the problem is not reproduced. This may have something to do with commit https://github.com/openenclave/openenclave/commit/f0b322fa1af59205f20a5e6504f8ba93d7a08f72.

@eddyashton Could you verify my finding with the latest OE?

**Comment by eddyashton** [comment]
@jxyang I'm also unable to reproduce this on OE v0.6.0, so it appears to have been fixed.

I don't think the fix is just from the libunwind update though: I tried reverting f0b322fa1af59205f20a5e6504f8ba93d7a08f72 and 48c6097b89512a6aaf27f1ca776fa312cd8bcc70 from v0.6.0 but the test still passed, and tried applying those updates to v0.5.0 but the segmentation fault still occurred. It would be good to know exactly what the cause and fix were, so a unit test could be added to ensure this (or similar issues) don't come back in future.

**Comment by jxyang** [comment]
@eddyashton We have also upgraded libcxx with this commit https://github.com/openenclave/openenclave/commit/438f3cb470500a0d4fc10255a9dd763acf40e0cc, that may be the reason. Thanks for verifying.

**Comment by achamayou** [comment]
@jxyang thanks for taking a look at this, it's great to see 0.7 doesn't exhibit the bug. We'll try to see if we can bisect the fix still because it would be nice to be confident this is fixed permanently.

**Comment by radhikaj** [comment]
Thanks @achamayou @jxyang.

**Comment by radhikaj** [comment]
@achamayou Closing this for now. Please reopen if you find a problem.

**Comment by achamayou** [comment]
@radhikaj sorry, we didn’t find the time to isolate the issue. It never happened on 0.7 or 0.8 so it can definitely be closed.
