### ISSUE TITLE
Decide and document official supported GCC version

### ISSUE THREAD

**Issue by ionutbalutoiu** [openenclave/openenclave#1516]
As part of the work from [Add Ubuntu 18.04 support to libcxx_tests](https://github.com/Microsoft/openenclave/pull/1324), we found out that the GCC testing stages from 18.04 fail due to the fact that the default GCC version shipped with Ubuntu 18.04 is GCC 7, and it causes our libcxx tests to fail.

This doesn't happen on Ubuntu 16.04 since the default is GCC 5. To have https://github.com/Microsoft/openenclave/pull/1324 unblocked, I installed the GCC 5 on Ubuntu 18.04 as well.

We should decide what's the official OE supported GCC version and document it.

The CI seems to be stable with GCC 5 (on both 18.04 and 16.04), and this is what we have there installed right now.

CC @andschwa @johnkord @anitagov

**Comment by johnkord** [comment]
@ionutbalutoiu We'll disable the libcxx tests that fail to build with GCC 7.*, and because our standard build works with GCC 7, we'll continue forward with that for this 0.5.0 release. As for supporting a specific version of GCC in the future, this is still to be decided.

**Comment by johnkord** [comment]
This is related to issue #937.

**Comment by anitagov** [comment]
@ionutbalutoiu - Can you also document why the libcxx tests fail to build with GCC 7.*? This can be part of an issue or documented in the libcxx folder. Thanks.

**Comment by ionutbalutoiu** [comment]
@anitagov

The libcxx test failure with GCC 7.* has been described by @aserdean in the issue https://github.com/Microsoft/openenclave/issues/1559.

I just reopened the issue, and associated the milestone `Future` to it for further tracking. So far, this is not blocking anything, since we disabled the test (PR https://github.com/Microsoft/openenclave/pull/1560) as a workaround.

**Comment by johnkord** [comment]
Let's move all of our GCC versions to one standard version across the Ubuntu platforms. Is GCC 7 available on Ubuntu 16.04? @ionutbalutoiu

**Comment by ionutbalutoiu** [comment]
@johnkord 

GCC-7 or GCC-8 are not available in the standard Ubuntu 16.04 PPAs, while the default Ubuntu 18.04 PPAs have them. The default 16.04 PPAs offer only GCC-5.

However, we can have GCC-7 / GCC-8 on Ubuntu 16.04 installed via the 3rd party [ppa:ubuntu-toolchain-r/test](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test). From what I've read this is an official PPA from the [Ubuntu ToolChain](https://wiki.ubuntu.com/ToolChain) team, and it should be safe to use.

So, we can move both platforms builds on either GCC-7 or GCC-8.

Just as a side node: If we choose to use GCC-8, there are a couple of warnings to be ignored from the tests (otherwise they are treated as fatal), see my commit https://github.com/ionutbalutoiu/openenclave/commit/892af1048fc7c31db8688a9f93ab26c824800c4f. I'm willing to submit this change if we choose GCC-8, and they look good to you guys.

**Comment by CodeMonkeyLeet** [comment]
@johnkord please follow up as needed to make a decision on this.
