### ISSUE TITLE
Provide script or packages list for porting to platforms where ansible may not work

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#1527]
While ansible works nicely, it does not work on all platforms.
To help compiling/porting OE to such platforms it would be good to:
1) Provide a shell-script that installs necessary packages
2) Document the list of packages needed somewhere so that they can be manually installed.
     Reading the scripts/ansible folder, it is not really obvious what packages I need to install manually 
     to get a system up and running.

@johnkord @CodeMonkeyLeet @ionutbalutoiu @aserdean

**Comment by ionutbalutoiu** [comment]
@anakrish

1. As far as I know, we support Ubuntu 16.04, Ubuntu 18.04 and Windows Server 2016 ACC for the OE project.

    On Ubuntu 16.04 & 18.04 you can run Ansible locally just as any shell script ([this section](https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/SGX1FLCGettingStarted.md#install-project-requirements) has instructions for this).

    On Windows Server 2016 topic, unfortunately Ansible supports Windows only as a target remote machine to configured via WinRM. That means, you cannot run Ansible locally on Windows, and you need to target it from a Linux sandbox. I understand that this is not desirable, since the Windows devs will be happier to just run a local script, and get all their OE requirements ready. Do you think that a simple PowerShell script will do here ?

2. Currently, there is documentation in the [docs/GettingStartedDocs](https://github.com/Microsoft/openenclave/tree/master/docs/GettingStartedDocs) directory about this.
    So far, I noticed this:
    * Info to the packages to be installed on Ubuntu platform [here](https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk.md)
    * Info for all the requirements necessary to be setup on Windows [here](https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/GettingStarted.Windows.md)

    Maybe it's worth looking if anything is outdated there, but that's the place for official docs.

**Comment by ionutbalutoiu** [comment]
Quick update on something related to the issue described here, and a discussing started at PR https://github.com/microsoft/openenclave/pull/1865#discussion_r291387496.

We are working on a PowerShell standalone script to configure a clean ACC Windows VM. This script would allow someone to quickly configure a Windows dev environment, and it will be called by Ansible as well.

We'll go with this approach to overcome the fact that Ansible doesn't run natively on Windows.

**Comment by ionutbalutoiu** [comment]
CC @johnkord @CodeMonkeyLeet @anitagov for the above update.
