### ISSUE TITLE
libcxxtest-std_containers_associative_map_map.access_at.pass fails on GCC release builds

### ISSUE THREAD

**Issue by aserdean** [openenclave/openenclave#1559]
```libcxxtest-std_containers_associative_map_map.access_at.pass``` fails on GCC 7 Release builds (although it passes on Debug builds).

One can see the log of the error [here](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-sandbox/detail/OpenEnclave-sandbox/933/pipeline/267).

The test fails because of the exceptions i.e.: https://github.com/Microsoft/openenclave/blob/master/3rdparty/libcxx/libcxx/test/std/containers/associative/map/map.access/at.pass.cpp#L47-L54.

I'm not sure what is really behind the scenes but I will send a PR out to disable the test on Release builds, although I'm not confident about the direction.

CC: @johnkord , @andschwa

**Comment by aserdean** [comment]
PR to disable: https://github.com/Microsoft/openenclave/pull/1560

**Comment by aserdean** [comment]
CC: @ionutbalutoiu

**Comment by ionutbalutoiu** [comment]
@johnkord @andschwa

What do you think about disabling this test (proposed at https://github.com/Microsoft/openenclave/pull/1560) ?

This will allow us to use the default GCC compiler (version 7.3) from Ubuntu 18.04 for the full libcxx tests suite.

**Comment by ionutbalutoiu** [comment]
Fixed by https://github.com/Microsoft/openenclave/pull/1560

**Comment by ionutbalutoiu** [comment]
Reopening this issue for further tracking and submitting a proper fix.

For now, we disabled the failing test as a workaround in the https://github.com/Microsoft/openenclave/pull/1560.

**Comment by ionutbalutoiu** [comment]
Quick update on this: Looks like the failures skipped by https://github.com/microsoft/openenclave/pull/1560 are solved if we upgrade to GCC 8.

**Comment by mingweishih** [comment]
Closing this issue as we're deprecating the GCC support. See #3555
