### ISSUE TITLE
Need to replace the cert re-ordering workaround with correct chain building logics  during the quote validation 

### ISSUE THREAD

**Issue by soccerGB** [openenclave/openenclave#1593]
There is a upcoming Intel root certificate update change that could create a condition that would break our current cert validation logics ( the cert root might new date than its descendant certs)

**Comment by soccerGB** [comment]
[https://github.com/Microsoft/openenclave/issues/864](url)

**Comment by johnkord** [comment]
@soccerGB Is there any more work to be done for this issue, or can we close this out?

**Comment by soccerGB** [comment]
This is a nice to have feature - non-essential.
