### ISSUE TITLE
Add support compiler runtimes in the enclave

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#1766]
The enclave runtime currently avoids linking in the compiler runtimes (e.g. libgcc, ~~libclang~~ compiler-rt) and instead includes portable subsets of them (e.g. libunwind) to keep the TCB small and the portability issues manageable.

This creates compatibility issues that create developer friction where existing apps they need to avoid use of particular intrinsics (e.g. we don't support many math intrinsics) or provide missing linker dependencies themselves. For example:

- https://github.com/microsoft/openenclave/pull/531#issuecomment-415430684
- https://github.com/microsoft/openenclave/pull/603#issue-211443232
- #1729 

As OE SDK tries to support more transparent porting of apps into the enclave, this is something we should investigate if this is something that we should support to reduce the friction of dealing with missing compiler runtime functions & intrinsics. This can be relatively expensive as it would involve rationalizing libunwind against each compiler runtime we choose to support, but there may also be some things we can do in the tooling/dev environment to mitigate some of the developer pain in the meantime.

**Comment by letmaik** [comment]
@CodeMonkeyLeet You mentioned libclang, which this is unrelated. You probably mean compiler-rt.

Good overview: https://clang.llvm.org/docs/Toolchain.html and https://compiler-rt.llvm.org/. Note in the latter link: "provides full support for the libgcc interfaces". Also, libunwind is not part of compiler-rt but separate to that. libgcc does have built-in unwind functionality on the other hand.

In my opinion, adding just the [`builtins` part](https://github.com/llvm-mirror/compiler-rt/tree/master/lib/builtins) of compiler-rt to OE would be a big step forward and deal with all relevant use cases that came up in the past. It's a fairly small math library and is compatible both with GCC and Clang. There would be no conflict with libunwind as well. Maybe someone from OE could just give it a try? I don't see much complexity here to be honest, but maybe I'm missing something.

**Comment by letmaik** [comment]
I finally gave it a try and it's really too simple...

```cmake
enable_language(ASM)
set(COMPILER_RT_DEFAULT_TARGET_TRIPLE x86_64-pc-linux-unknown CACHE STRING "" FORCE)
add_subdirectory(external/compiler-rt EXCLUDE_FROM_ALL)
add_library(compiler-rt-builtins ALIAS clang_rt.builtins-x86_64)
```
where `external/compiler-rt` is the [compiler-rt](https://github.com/llvm-mirror/compiler-rt) repo. Now just link your enclave binary against `compiler-rt-builtins` and you're good to go.

For the record, I still think this should be offered by OE out of the box, but in the meantime it's not hard to include it in downstream applications as I've shown above.

@Lusitanian

**Comment by achamayou** [comment]
Perhaps an additional argument in favour of having it out of the box is that it's what the Intel SDK does: https://github.com/intel/linux-sgx/tree/master/sdk/compiler-rt

**Comment by dthaler** [comment]
There are two permissively licensed code bases we can pull from:
a) https://github.com/intel/linux-sgx/blob/master/sdk/compiler-rt/  (MIT license)
b) https://github.com/llvm-mirror/compiler-rt/blob/master/lib/builtins  (Apache license)

Comparing https://github.com/intel/linux-sgx/blob/master/sdk/compiler-rt/divti3.c and https://github.com/llvm-mirror/compiler-rt/blob/master/lib/builtins/divti3.c the implementations look identical and only differ in MIT vs Apache license headers.   If that's true in general, I would take the Intel copies under the MIT license, since OE SDK is already MIT licensed.
