### ISSUE TITLE
Sample helloworld enclave_create fails with OE_PLATFORM_ERROR

### ISSUE THREAD

**Issue by sp21** [openenclave/openenclave#1783]
I am trying to test openenclave on Ubuntu 18.04.

After following [instructions](), I tried to launch helloworld enclave host.

However, I got `OE_PLATFORM_ERROR` as below:
```
$ make run
host/helloworldhost ./enclave/helloworldenc.signed
03:58:44:746197 tid(0x7f98028c9740) (H)[ERROR]enclave_create with ENCLAVE_TYPE_SGX1 type failed (err=0x1) (oe_result_t=OE_PLATFORM_ERROR)[/home/jenkins/work_dir/workspace/OpenEnclave-v0.5.x_packages/host/sgx/sgxload.c oe_sgx_create_enclave:533]
03:58:44:746216 tid(0x7f98028c9740) (H)[ERROR]:OE_PLATFORM_ERROR[/home/jenkins/work_dir/workspace/OpenEnclave-v0.5.x_packages/host/sgx/create.c oe_sgx_build_enclave:558]
03:58:44:746397 tid(0x7f98028c9740) (H)[ERROR]:OE_PLATFORM_ERROR[/home/jenkins/work_dir/workspace/OpenEnclave-v0.5.x_packages/host/sgx/create.c oe_create_enclave:675]
oe_create_helloworld_enclave(): result=21 (OE_PLATFORM_ERROR)
Makefile:13: recipe for target 'run' failed
make: *** [run] Error 1
```

I think my machine and installation isn't wrong.

1. `cat /proc/cpuinfo`
```
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
stepping	: 10
microcode	: 0x96
cpu MHz		: 800.013
cache size	: 12288 KB
physical id	: 0
siblings	: 12
core id		: 5
cpu cores	: 6
apicid		: 11
initial apicid	: 11
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
```

AVX is enabled #1511 

2. `oesgx`
```
$ oesgx
CPU supports SGX_FLC:Flexible Launch Control
CPU supports Software Guard Extensions:SGX1
MaxEnclaveSize_64: 2^(36)
EPC size on the platform: 98041856
```

3. Driver 
```
$ dkms status | grep sgx
sgx, 1.10, 4.18.0-18-generic, x86_64: installed
```

I really cannot figure out what's the problem. Is there anything that I am missing?

Thanks!

**Comment by johnkord** [comment]
The instructions link above doesn't seem to link to any page. Can you send us a link to what instructions you used?

Also, can you show us what /dev looks like on your system? You should have the /dev/sgx device if the driver installed properly.

**Comment by gupta-ak** [comment]
I'm not sure if FLC is actually supported on consumer SKU coffelake machines like the i7-8700. @CodeMonkeyLeet FLC shouldn't work on this machine right due to motherboard support?

**Comment by CodeMonkeyLeet** [comment]
FLC is a largely BIOS-enabled feature. Consumer SKUs of Coffeelake don't have hardware differences with regards to FLC AFAIK, but I'm not aware of Intel shipping any consumer SKU with FLC enabled. I don't believe it's in their reference BIOS for consumer boards.

@johnkord's question is a reasonable one; I don't believe the FLC-enabled SGX driver will be correctly installed if FLC is not BIOS enabled, whereas oesgx is specifically detecting is detecting that CPUID reports the hardware support for it.

**Comment by dwizzzle** [comment]
I seem to have the same issue, how do we determine if FLC is enabled in bios?

**Comment by radhikaj** [comment]
Please refer to documentation here
https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/SGXSupportLevel.md

**Comment by radhikaj** [comment]
I am closing this issue for now. Please let us know if you have any more questions.

**Comment by ivan-homoliak-sutd** [comment]
I had the same issue on Ubuntu 18.04 desktop machine that does not support FLC. FLC seems to be supported only by server CPUs which is Intel focusing on as an SGX mainline. Therefore, to run SGX on a desktop, one needs to install only *isgx.ko* kernel module, which is intended for non-FLC CPUs. However, on top of isgx.ko, I accidentally (maybe automatically) installed also *intel_sgx.ko*, which is intended for FLC-supported CPUs. So, I just unplugged it from the kernel by _rmmod_ and believed that things are resolved. But after a longer time I've realized that _dmesg_ still contains some messages from intel_sgx driver, so I removed it incorrectly. To correctly remove and disable the intel_sgx driver, I did:

- $ sudo systemctl stop aesmd.service
- $ sudo /sbin/modprobe -r intel_sgx
- delete  "intel_sgx.ko" for the current kernel. In my case "sudo rm -rf /lib/modules/5.3.0-40-generic/updates/dkms/intel_sgx.ko"
- $ sudo /sbin/depmod
- $ sudo /bin/sed -i '/^intel_sgx$/d' /etc/modules

**Sources:**
https://github.com/intel/linux-sgx-driver#uninstall-the-intelr-sgx-driver

**Comment by jhand2** [comment]
@ivan-homoliak-sutd thanks for letting us know. To follow up:

1. Are you still blocked on anything or is everything working find for you now?
2. Do you think there were parts of the documentation that were unclear/should be changed to keep people from tripping over this in the future?

Thanks!

**Comment by maverick-zhn** [comment]
I got the same error on Ubuntu 18.04 desktop machine that does not support FLC. I followed @ivan-homoliak-sutd which seems to work nicely.
Thank you.

**Comment by maverick-zhn** [comment]
I do have some issues on Ubuntu 18.04 Server **_with_** FLC support. https://github.com/openenclave/openenclave/issues/2401#issuecomment-612536706
