### ISSUE TITLE
Prereqs build should checkout specific versions, not latest master

### ISSUE THREAD

**Issue by Lusitanian** [openenclave/openenclave#1788]
The [prereqs build Makefile for aesmd](https://github.com/microsoft/openenclave/blob/master/prereqs/aesm/Makefile) doesn't checkout a specific version when getting the `dynamic-application-loader-host-interface` and `linux-sgx` repositories. It seems that the top of master for `dynamic-application-loader-host-interface` is currently broken on Ubuntu 16.04, which is breaking our CI build. 

```
[ 80%] Building CXX object CMakeFiles/jhid.dir/service/LinuxService.cpp.o
&#x2F;usr&#x2F;local&#x2F;openenclave&#x2F;prereqs&#x2F;aesm&#x2F;dynamic-application-loader-host-interface&#x2F;service&#x2F;LinuxService.cpp: In function &#x27;int main(int, char**)&#x27;:‌
/usr/local/openenclave/prereqs/aesm/dynamic-application-loader-host-interface/service/LinuxService.cpp:79:24: error: 'JHI_VERSION' was not declared in this scope
             std::cout<<JHI_VERSION<<std::endl;
                        ^
```

**Comment by radhikaj** [comment]
@paulcallen @BRMcLaren Please take a look at this.

**Comment by jhand2** [comment]
I don't think this mechanism exists anymore. I believe it is replaced by ansible.
