### ISSUE TITLE
InitializeEnclave on Windows occasionally fails due to SGX_UNMASKED_EVENT

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#1794]
Every so often a test run on Windows will fail during the call to Windows' `InitializeEnclave()` system call with the underlying SGX `EINIT` error `SGX_UNMASKED_EVENT` (0x80). We need to either mitigate this with retry logic, or ensure that `oe_sgx_initialize_enclave()` or the underlying Windows `InitializeEnclave()` methods inhibit the unmasked events.

[The Intel SDM vol 3D](https://software.intel.com/sites/default/files/managed/7c/f1/332831-sdm-vol-3d.pdf) states:

> Periodically, EINIT polls for certain asynchronous events. If such an event is detected, it completes with failure code (ZF=1 and RAX = SGX_UNMASKED_EVENT), and RIP is incremented to point to the next instruction. These events includes external interrupts, non-maskable interrupts, system-management interrupts, machine checks, INIT signals, and the VMX-preemption timer. EINIT does not fail if the pending event is inhibited (e.g., external interrupts could be inhibited due to blocking by MOV SS blocking or by STI).

[OpenEnclave-Bors#865](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/865/pipeline) has a repro of this:

```
test 73
        Start  73: tests/pthread

73: Test command: D:\Jenkins\workspace\Bors_staging\build\tests\thread\host\Release\thread_host.exe "D:/Jenkins/workspace/Bors_staging/build/tests/thread/host/pthread_enc"
73: Test timeout computed to be: 10000000
73: : d:\jenkins\workspace\bors_staging\tests\thread\host\host.cpp(306): error: oe_create_thread_enclave(): result=21
73: 18:09:31:000000 tid(0xbac) (H)[ERROR]InitializeEnclave failed (err=0x80) (oe_result_t=OE_PLATFORM_ERROR)[d:\jenkins\workspace\bors_staging\host\sgx\sgxload.c oe_sgx_initialize_enclave:929]
73: 18:09:31:000000 tid(0xbac) (H)[ERROR]:OE_PLATFORM_ERROR[d:\jenkins\workspace\bors_staging\host\sgx\create.c oe_sgx_build_enclave:577]
73: 18:09:31:000000 tid(0xbac) (H)[ERROR]:OE_PLATFORM_ERROR[d:\jenkins\workspace\bors_staging\host\sgx\create.c oe_create_enclave:681]
 73/101 Test  #73: tests/pthread .........................................***Failed    0.08 sec
test 74
        Start  74: tests/threadcxx

74: Test command: D:\Jenkins\workspace\Bors_staging\build\tests\threadcxx\host\Release\threadcxx_host.exe "D:/Jenkins/workspace/Bors_staging/build/tests/threadcxx/host/threadcxx_enc"
74: Test timeout computed to be: 10000000
74: : d:\jenkins\workspace\bors_staging\tests\threadcxx\host\host.cpp(208): error: oe_create_threadcxx_enclave(): result=21
74: 18:09:31:000000 tid(0x1c4) (H)[ERROR]InitializeEnclave failed (err=0x80) (oe_result_t=OE_PLATFORM_ERROR)[d:\jenkins\workspace\bors_staging\host\sgx\sgxload.c oe_sgx_initialize_enclave:929]
74: 18:09:31:000000 tid(0x1c4) (H)[ERROR]:OE_PLATFORM_ERROR[d:\jenkins\workspace\bors_staging\host\sgx\create.c oe_sgx_build_enclave:577]
74: 18:09:31:000000 tid(0x1c4) (H)[ERROR]:OE_PLATFORM_ERROR[d:\jenkins\workspace\bors_staging\host\sgx\create.c oe_create_enclave:681]
 74/101 Test  #74: tests/threadcxx .......................................***Failed    0.11 sec
test 75
        Start  75: tests/thread_local

76: Test command: D:\Jenkins\workspace\Bors_staging\build\tests\thread_local\host\Release\thread_local_host.exe "D:/Jenkins/workspace/Bors_staging/build/tests/thread_local/host/thread_local_enc_exported" "--exported-thread-locals"
76: Test timeout computed to be: 10000000
76: : d:\jenkins\workspace\bors_staging\tests\thread_local\host\host.cpp(84): error: oe_create_enclave(): result=21
76: 18:09:31:000000 tid(0x1458) (H)[ERROR]InitializeEnclave failed (err=0x80) (oe_result_t=OE_PLATFORM_ERROR)[d:\jenkins\workspace\bors_staging\host\sgx\sgxload.c oe_sgx_initialize_enclave:929]
76: 18:09:31:000000 tid(0x1458) (H)[ERROR]:OE_PLATFORM_ERROR[d:\jenkins\workspace\bors_staging\host\sgx\create.c oe_sgx_build_enclave:577]
76: 18:09:31:000000 tid(0x1458) (H)[ERROR]:OE_PLATFORM_ERROR[d:\jenkins\workspace\bors_staging\host\sgx\create.c oe_create_enclave:681]
 76/101 Test  #76: tests/thread_local_exported ...........................***Failed    0.09 sec
```

This has also been previously reported in #1476

**Comment by anitagov** [comment]
Good find Simon. With regard to your suggestions on ways to mitigate this, I hope we can inhibit the unmasked events.

**_We need to either mitigate this with retry logic, or ensure that oe_sgx_initialize_enclave() or the underlying Windows InitializeEnclave() methods inhibit the unmasked events._**

**Comment by CodeMonkeyLeet** [comment]
It turns out that Windows already has an internal retry loop for this in its implementation, so there may be an underlying issue here where something is causing a large number of external interrupts to be fired in succession.

Modifying the interrupt flags would require Windows kernel support, and their response to us so far is that we should simply retry at the level of OE SDK. Thus far, we have not seen the same issue on Linux, which has more retries and also does a 20ms sleep between each EINIT attempt, so that may be sufficient.

**Comment by anitagov** [comment]
ok. Great info.

**Comment by yakman2020** [comment]
This is only happening on CI/CD.

**Comment by jxyang** [comment]
Pipeline [871](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/871/pipeline/) also failed due to this issue:

```
73: Test command: D:\Jenkins\workspace\Bors_staging\build\X64-Release\tests\thread\host\thread_host.exe "D:/Jenkins/workspace/Bors_staging/build/X64-Release/tests/thread/enc/pthread_enc"
73: Test timeout computed to be: 10000000
73: : ..\..\tests\thread\host\host.cpp(306): error: oe_create_thread_enclave(): result=21
73: 17:49:47:000000 tid(0x1530) (H)[ERROR]InitializeEnclave failed (err=0x80) (oe_result_t=OE_PLATFORM_ERROR)[..\..\host\sgx\sgxload.c oe_sgx_initialize_enclave:929]
73: 17:49:47:000000 tid(0x1530) (H)[ERROR]:OE_PLATFORM_ERROR[..\..\host\sgx\create.c oe_sgx_build_enclave:577]
73: 17:49:47:000000 tid(0x1530) (H)[ERROR]:OE_PLATFORM_ERROR[..\..\host\sgx\create.c oe_create_enclave:681]
 73/103 Test  #73: tests/pthread .........................................***Failed    0.10 sec
```

**Comment by CodeMonkeyLeet** [comment]
Also seen in bors run [866](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/866/pipeline) ... It seems like we're hitting this pretty often in CI/CD.

**Comment by johnkord** [comment]
Tagging @ionutbalutoiu for a heads up about this

**Comment by anitagov** [comment]
Saw these platform errors with 75% of my recent CI runs and occurred with the mbed test.
The following pipeline had 2 failures: https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-sandbox/detail/OpenEnclave-sandbox/1456/pipeline/88/
The following tests FAILED:
	 15 - tests/mbed/ccm (Failed)
	 16 - tests/mbed/cipher.aes (Failed)

**Comment by ionutbalutoiu** [comment]
> Tagging @ionutbalutoiu for a heads up about this

Thank-you for the heads-up!

> Also seen in bors run [866](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/866/pipeline) ... It seems like we're hitting this pretty often in CI/CD.

Yep, these are some recent CI runs where I noticed this issue:

* [Bors-trying#907](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/907/pipeline/89)
* [Bors-trying#908](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/trying/908/pipeline/89)
* [Bors-staging#927](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/927/pipeline/88)

**Comment by andschwa** [comment]
Just keeps happening. I can't merge doc updates in #1972.

**Comment by jxyang** [comment]
@anitagov The simplest way to mitigate this, per @CodeMonkeyLeet, is to implement the retry logic in our code. Specifically in sgxload.c, we retry `CreateEnclave` after wait a while. Note this path is windows only, so it won't affect the performance on Linux.
```
#elif defined(_WIN32)

        /* Ask OS to create the enclave */
        DWORD enclave_error;
        void* base = CreateEnclave(
            GetCurrentProcess(),
            NULL, /* Let OS choose the enclave base address */
            secs->size,
            secs->size,
            ENCLAVE_TYPE_SGX,
            (const void*)secs,
            sizeof(ENCLAVE_CREATE_INFO_SGX),
            &enclave_error);

        if (!base)
            OE_RAISE_MSG(
                OE_PLATFORM_ERROR,
                "CreateEnclave failed (err=%#x)",
                enclave_error);

        secs->base = (uint64_t)base;

#endif
```

**Comment by anitagov** [comment]
Hi Andy, 
     I got hit with this once while trying to merge my PR this morning. Can you point to the tests or your pipeline that failed?

Will fix this.

- Anita

**Comment by andschwa** [comment]
@anitagov Happened twice in a row [here](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/981/pipeline) and [here](https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/982/pipeline).

**Comment by anitagov** [comment]
Testing in progress and will issue PR later tonight if 4 Jenkins CI runs come out clean.

**Comment by anitagov** [comment]
Completed fix and testing in progress and will issue PR later tonight if 4 Jenkins CI runs come out clean.

**Comment by anitagov** [comment]
PR #1976 has been checked into master.

**Comment by jxyang** [comment]
Haven't observed any random CI failures on Windows since the merge. Nice!

https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/activity/

**Comment by anitagov** [comment]
Thanks @jxyang
