### ISSUE TITLE
Need a way to test quote validation on non-SGX machine in CI.

### ISSUE THREAD

**Issue by gupta-ak** [openenclave/openenclave#1819]
When PR #1818 is merged, we removed a bunch of `OE_USE_LIBSGX` to enable quote verification on non-SGX machines. We should make sure that 1) kabylake features are not regressed and 2) we have a test to report verification on non-SGX machines.

**Comment by johnkord** [comment]
We should figure out #1 now that #1818 has been merged. For #2, we should add that test when we merge #1575

**Comment by CodeMonkeyLeet** [comment]
@gupta-ak please work with @johnkord/cloudbase to fill this for v0.6

**Comment by jazzybluesea** [comment]
John added a non-sgx nodes VM as part of CI/CD.  The unbuntu node is called "nonSGX" and the windows node is called "nonSGX-Windows".  The way I designed the test is to compile the binaries in an SGX machine and then copy the changes (via jenkins) to the non SGX machines.  For an example see ACCHostVerificationTest() in the Jenkinsfile.

See PR #2126 
https://github.com/openenclave/openenclave/commit/a47b6192b5b818f6bd362824f60240baf0653e06#diff-9b83915ce4a53a5b3cc01b9f39d6a984
