### ISSUE TITLE
Need KabyLake platform in CI

### ISSUE THREAD

**Issue by anitagov** [openenclave/openenclave#1821]
The KabyLake platform is needed in our CI runs. It was removed from CI for various reasons but primarily since it was a lab machine and hence required too much maintenance.

Since this is one of the flows that we still support in Open Enclave and a KabyLake ACC VM can be deployed outside of the Azure Portal, we should add at least one KabyLake Linux CI configuration. Additionally, KabyLake is used by developers for various reasons too.

If the usage of OE_USE_LIBSGX (eg. PR #1818) is changed in core/tests , then we do not currently have CI to test that KabyLake machines still function correctly.

Suggestion is to remove one or more of the Linux Ubuntu 16.04 CI configurations (simulation perhaps) to not overload CI.

**Comment by anitagov** [comment]
Not having an ACC VM managed by Azure Portal requires extra maintenance and so doesn't seem like a great option.

However, how about getting a CoffeeLake ACC Linux VM from Azure Portal and installing the AESM Intel SGX drivers instead of DCAP? This will mimic KabyLake functionality without any extra overhead. Just name the VM as PseudoKabyLake or something. 

The prereqs script do support building/installing the Intel AESM drivers and the ansible scripts will need to be enhanced to support these KabyLake flows.

For Windows, we are currently following the non-DCAP/AESM flows (soon to be rectified).
Trust this helps.

**Comment by radhikaj** [comment]
@paulcallen @BRMcLaren  Please take a look at this issue.

**Comment by BRMcLaren** [comment]
@anitagov Is this still an issue?

**Comment by BRMcLaren** [comment]
@radhikaj This issue is stale, do we intend to support KabyLake moving forwards? If not, I would like to close the issue.

**Comment by jhand2** [comment]
I don't think we can run on KabyLake in azure, right? In theory you could run it in a lab but that seems like way too much work to support an old platform.

IMO this can be closed.

**Comment by radhikaj** [comment]
Closing. Thanks @BRMcLaren @jhand2
