### ISSUE TITLE
Need Jenkins CI to test OE Windows with DCAP libraries

### ISSUE THREAD

**Issue by anitagov** [openenclave/openenclave#1866]
PR #1865 once merged to master will provide a way to build and test ELF enclaves on Windows using DCAP libaries when the build flag USE_LIBSGX is enabled. Need Jenkins CI stages to provide capability to build and test.

**Comment by anitagov** [comment]
@ionutbalutoiu - PR #1865 is in master. Please work on this issue.

**Comment by ionutbalutoiu** [comment]
> @ionutbalutoiu - PR #1865 is in master. Please work on this issue.

Awesome! We'll come with a PR for this as soon as possible.

**Comment by ionutbalutoiu** [comment]
Syncing the issue milestone with the [pull request](https://github.com/microsoft/openenclave/pull/1945) milestone as changed by Bruce.

/cc @yakman2020

**Comment by ionutbalutoiu** [comment]
Fixed by https://github.com/openenclave/openenclave/pull/1945
