### ISSUE TITLE
With MBEDTLS_NET_C component enabled, need to make sure all the relevant mbedtls test code are fully enabled.

### ISSUE THREAD

**Issue by soccerGB** [openenclave/openenclave#1893]
mbedtls has several test programs or samples in various directories. The options enabled are listed in config.h. With MBEDTLS_NET_C enabled, networking I/O routines are enabled in enclaves and hence several tests can now be enabled.

**Comment by anitagov** [comment]
Trying to capture the places that the mbedtls tests reside at:
1) 3rdparty\mbedtls\mbedtls\tests 
          **test_suites (Being run)** - The various test_suite_XXX programs from this directory include test cases (reference test vectors, sanity checks, malformed input for parsing functions, etc) for all modules except the SSL modules. 
           **compat.sh (Not run)** - This script checks interoperability with OpenSSL and GnuTLS and mbedTLS for every common ciphersuite, in every TLS version, both ways (client/server), using client authentication or not. For each ciphersuite/version/side/authmode it performs a full handshake and a small data exchange. _**I don't see a need to run this now or later.**_
            **ssl_opt** (Not run) - this script checks various options and/or operations not covered by compat.sh: session resumption, renegotiation, SNI, etc. **_I don't see a need to run this now or later._**

2) 3rdparty\mbedtls\mbedtls\programs\test
        **selftests (Being run)** - This runs the XXX_self_test() functions of each individual module. Most of them are included in the respective test suite, but some slower ones are only included here.
         **ssl_cert_test.c (Will not be run)** - SSL certificate Functionality certificates => Created a new test infrastructure for this but this test does not come with test certificates and these will need to be generated. Since, we have several other tests that generate certificates and are time consuming, team consensus was to abandon this test.
          **udp_proxy.c (Not being run)** - Emulates an unreliable UDP connection for DTLS testing
          **benchmark.c (Not being run)** - Benchmark demonstration program. No plans for running this.

3) 3rdparty\mbedtls\mbedtls\programs\ssl 
       The following sample SSL client/server tests can be converted to enclave tests. ssl_client1.c and  ssl_client2.c were converted to tests by @mikbras and reside in the IO2 branch. This issue will get the working ones in the master.
![image](https://user-images.githubusercontent.com/16311437/59317504-0dfa9180-8c78-11e9-8490-6c9bdb63d4bd.png)

**Comment by anitagov** [comment]
My recent updates: 
1) Created new test mbedssl which uses ssl_server.c and ssl-client1.c. However, ssl_server.c requires MBEDTLS_FS_IO to be enabled in config.h. This is not yet enabled in master and so cannot get into Release 0.6.
2) Created new test mbedssl which uses ssl_server2.c which does not have dependency on MBEDTLS_FS_IO. However, this test is failing.

**Comment by CodeMonkeyLeet** [comment]
@jhand2 With the Windows socket changes, can you take a look and see whether we're in a position to enable these tests uniformly across OS platforms now? IIRC, one of the blockers was the lack of equivalent Windows support breaking build.

**Comment by jhand2** [comment]
I double checked and mbedtls tests are already running for all platforms. Closing this issue
