### ISSUE TITLE
Investigate and choose available open source queue/ringbuffer implementations

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#1896]
Switchless calling feature requires a ring-buffer or queue or a memory-pool to efficiently share data between host and enclave.
We need to evaluate any available open source libraries before shipping the feature.

Here are the constraints:

- It has to be in C and should work in Linux since that is what can go in oecore or other oelibraries
- It has to be light and should not introduce any bloat
(Note we could create a separate library for switchless calls, and that could relax the bloat constraint a bit)
- It should be fast. The goal of switchless calling is to tremendously speedup ecall/ocall implementation while being correct.

The implementation can be locked or be lock free or whatever; but it has to be fast enough for our purposes.

Coco has a ring-buffer implementation in C++ that would require some work to port to C.

Eric has an implementation of lock-free queues in https://github.com/microsoft/openenclave/pull/1838/files .

CC: @lilyfang

**Comment by achamayou** [comment]
@anakrish you are right about the CCF (ex-Coco) ringbuffer. snmalloc has an extremely fast, lock-free, and pure C MPSC queue that seems like a perfect fit: https://github.com/microsoft/snmalloc/blob/master/src/ds/mpscq.h

**Comment by anakrish** [comment]
@achamayou 
It would be great if we can reuse existing production quality components.

> pure C MPSC queue 

Can you double check your link? The page it points to is C++.

**Comment by anakrish** [comment]
@achamayou 

Reading the enqueue operation:

https://github.com/microsoft/snmalloc/blob/b033587ce8386040152679f49166203fa12af765/src/ds/mpscq.h#L51-L60

Since the enqueue operation uses only a release fence, what is the guarantee that when two threads simultaneously perform the enqueue operation, they see each other's modifications in the correct order? 

Do you have a document describing the design of the class you pointed to? 
Do you have performance measurements?

CC: @EMumau @gupta-ak

**Comment by achamayou** [comment]
@anakrish sorry, you are right, the current implementation is C++.

**Comment by anakrish** [comment]
@achamayou No worries.

The question I have about the enqueue operation still stands. Typically, fences are used in pairs. A release fence must be combined with an acquire fence so that both threads see the intended ordering.
In the implementation you linked to, enqueue and dequeue have release-acquire pairing. Whereas simultaneous enqueue operations only have release-release pairing.

**Comment by radhikaj** [comment]
I am closing this as we dont need queues and ringbuffers in our current implementation
