### ISSUE TITLE
Bugs in Getting Started docs

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#1914]
1)	https://github.com/microsoft/openenclave/blob/master/docs/GettingStartedDocs/using_oe_sdk.md says, under Samples:

cp -r /opt/openenclave/share/openenclave/samples ~
cd ~/samples
make world

The “make world” won’t work since there’s no makefile in the samples directory, and there’s nothing called “world”, only helloworld.

2)	https://github.com/microsoft/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md has bad instructions in step 2 that won’t work.
They install the /dev/intel_sgx device not the /dev/isgx device and it breaks OE.   Even after following the instructions here after doing the bad step 2, I still couldn’t get it to work.
The only way I could get it to work was to replace step 2 with the instructions there.   I have no idea how to do it without building from source, but anyone following the first
page will never get OE to work.

**Comment by CodeMonkeyLeet** [comment]
@andschwa for #1 this looks like it was missed as part of the v0.5 doc-a-thon after the building samples from root was removed. What did you expect to replace as the high level instructions for building a sample in using_oe_sdk. I would just redirect to the samples/README.md if there's no succinct way to do this without talking about cmake/gnu make differences and openenclaverc.

@dthaler It sounds like #2 resulted from you landing on that page which was not intended for the configuration you're trying to execute (non-FLC SGX1) and the Platform Requirements section was not sufficiently obvious where it should have redirected you to [check if your existing device supports SGX with FLC](https://github.com/microsoft/openenclave/blob/master/docs/GettingStartedDocs/Contributors/building_oe_sdk.md#1-determine-the-sgx-support-level-on-your-developmenttarget-system). That should have led you to [SGX1GettingStarted.md](https://github.com/microsoft/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1GettingStarted.md) instead.

@johnkord I think the updated taxonomy of GettingStartedDocs came from you, and this might be a sign it should be reconfigured. If nothing else, it seems like there needs to be a refactoring of the Contributor docs that repeat much of the same information, with the v0.5 top level docs.

**Comment by dthaler** [comment]
I don't think SGX1GettingStarted.md is a good place to send people, which requires building the SGX from source.  The other pages just consume it in binary form, which is what I was looking for.   It sounds like you have no non-FLC SGX1 page for consuming OE SDK in binary form, which should be the point of this bug.

**Comment by CodeMonkeyLeet** [comment]
The first issue has been addressed by #1973

**Comment by CodeMonkeyLeet** [comment]
@dthaler Spent some time looking at this and it's more than a documentation issue if you want us to support consuming OE SDK as a packaged drop on top of non-FLC SGX1. I've opened #1983 to track the request instead and closing this out.
