### ISSUE TITLE
include/openenclave/bits/module.h contains oe_load_module_host_epoll which is not implemented

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#1917]
oe_load_module_host_epoll is not implemented in any lib.

**Comment by radhikaj** [comment]
@mikbras please let me know if I can just remove oe_load_module_host_epoll

**Comment by radhikaj** [comment]
Also oe_load_module_sgx_file_system is not implemented.

**Comment by yakman2020** [comment]
@radhikaj Does #2001 fix this?
