### ISSUE TITLE
Improve "How to Submit a PR" / add "How to Review a PR"

### ISSUE THREAD

**Issue by andschwa** [openenclave/openenclave#1920]
# Improve "How to Submit a PR" / add "How to Review a PR"

While we have some "Do's and Do not's" for [PRs](https://github.com/microsoft/openenclave/blob/master/docs/Contributing.md#dos-and-donts-for-pull-requests), we should rewrite this section as a step-by-step guide on "How to Submit a PR" with a list of checkboxes (later we can even consider putting these in the PR template), and another section on "How to Review a PR" (again, with a checklist!)

Notes from @paulcallen, with my own commentary:

* feature work design meeting will be announced in teams under Open Enclave teams discussion

> Andy: is this an open channel? If not, we should use the existing Gitter so as to not exclude the community
>> Paul: This sounds fair. @andschwa is there somewhere specific on Gitter where we can do this? Can we create dedicated areas on there specifically for design or is it all dumped into one big open chat? If there is no organization then maybe something like Teams can be used, and we can create a public channel specific for design discussions... maybe even one per design discussion to keep things more organized.

* the design must be agreed upon before a code review, generally before major amount of code is even written

> Andy: This is pretty loose. What does it mean to submit a design? What does it mean for it to be agreed upon? Who are the decision makes for each design review? We have a little bit of this [here](https://github.com/microsoft/openenclave/blob/master/docs/GovernanceModel.md#accepting-contributions), and could learn from [PowerShell's RFC process](https://github.com/PowerShell/PowerShell-RFC)
>> Paul: @andschwa - You have already added a location in git for [design documents](https://github.com/openenclave/openenclave/blob/master/docs/Contributing.md#design-discussion). Thanks.

* each PRs need to get at least 2 reviewers in the related key areas to sign-off.

> Andy: This sounds reasonable to me, and we can even enforce a total of 2 reviewers using GitHub/Bors; however, what are the key areas and who are the owners? Sounds like we need a maintainers doc like [Apache Mesos](https://github.com/apache/mesos/blob/master/docs/committers.md#maintainers).
>> Paul: Yes!

* the reviewers should be chosen ahead of time.

> Andy: Again, sounds like we need a maintainers doc!
>> Paul: Yes!

* Please make sure the PR is broken into small chunks for review. Reviewing large pull requests is hard. For big features design documents, mentioned above is critical. , it’s reviewee’s responsibilities to bring reviewers together with their development milestones, for example, hosting CRs for the existing code implementation, walk-through the code logic during the development, rather than waiting for the last minute, thus give code reviewers enough time to digest the big change.

> Andy: What does this mean? It sounds good but I think it's vague.
>> Paul: @andschwa - Do you have suggestions? The same design gitter/teams channel would be a good discussion forum to help reviewers get through the review. Obviously the design document is also critical.

* a feedback window will be set at the time of posting a code review, 5 days should be sufficient in most cases. Feedback can be addressed during that time. The window for review input closes on the fifth day at EOD. Once the time is up, only follow-up comments given by the reviewer on any changes made during this time should be made, hopefully they are sign-offs that they are good, but if they are still actually broken then obviously that would need to be addressed.

> Andy: I like this a lot! Any way we can automate it?
>> Paul: I don't know of anything, but any suggestions are welcome. Otherwise it is mostly up to the person doing the pull request. If nothing else sending nag mail would be good. I know Mesos DCOS bot sends nag messages to a pull request if no one looks at it. Maybe there is something we can use to do the same?

* Feedback that does not fall into these areas or time periods is recommended to move to a new issue that get addressed after the check-in happens. The reviewer creates requests for outstanding issues. The PR is checked in with the agreement that issues will be resolved (or not).

> Andy: This is great, I think a lot of people already do this (I know I do). Is there anyway we can make this more visible as _the_ accepted development practice?
>> Paul: I do not know of an automated way of doing this. Previous projects this has been up to the code reviewer to point out, and the owner of the pull request to carry out.

* Feedback is recommended to be limited to actual coding problems, not design, esthetics, or philosophical questions (Actual code bugs, Incorrect API usage and error handling, as long as they do not go into design discussions, Anything that is design related is a feature request and an issue should be created, Security issues, And more, but be realistic)

> Andy: I'm going to start looking for a good write-up on how to perform code reviews. We certainly can't be alone in having thought of this, and while this is a good start, sounds like we need a whole piece of educational material. Let me know if ya'll find anything.
>> Paul: Indeed. I think a 'reviewers guide' is needed for those folks granted the ability to review and sign off pull requests.

* Anything that is not tested should not be there. If it is a pull request it should be removed, or tests need to be added

> Andy: I don't think anyone _disagrees_ with this, but just stating it as fact won't enforce it. We need to research and implement code coverage tools in our CI so we can practically assert the test coverage of PRs.
>> Paul: I think this just needs to be put in a 'Reviewers Guide'. Assuming not just anyone is allowed to sign off and merge pull requests, those assigned this task are then made responsible for enforcing this.

**Comment by dthaler** [comment]
Re "a feedback window will be set at the time of posting a code review, 5 days should be sufficient in most cases. Feedback can be addressed during that time. The window for review input closes on the fifth day at EOD."

This appears to contradict "each PRs need to get at least 2 reviewers in the related key areas to sign-off."
If 2 reviewers don't submit reviews for a long time, then there's an issue that needs to be addressed in the process.

**Comment by andschwa** [comment]
I am not sure why people were unassigned from this last month: I'm still seeking feedback so we can move this forward, and it's becoming increasingly important.

**Comment by andschwa** [comment]
For design documents, I opened #2085.

**Comment by paulcallen** [comment]
I have added comments above.

**Comment by andschwa** [comment]
Committer technical areas were added in #2088.

**Comment by andschwa** [comment]
@paulcallen the Gitter is there and open, feel free to do what you want with it! I would, however, caution against making a lot of different rooms/channels. In my experience this kind of fragmentation leads to worse communication instead of better, as it makes harder both to ask and answer questions (Mesos had a bad habit with this, whereas PowerShell did it well with mostly a single channel).

**Comment by andschwa** [comment]
I would suggest that the ask to move to 2 sign-offs for PRs be presented at the next (the inaugural!) Community Maintenance Meeting. I'm forming an agenda...I'll try to remember to add it.

**Comment by andschwa** [comment]
I'm planning to write "How to Submit a PR", who wants to write "How to Review a PR"?

**Comment by dthaler** [comment]
Also a comment on "Feedback is recommended to be limited to actual coding problems, not design, esthetics, or philosophical questions (Actual code bugs, Incorrect API usage and error handling, as long as they do not go into design discussions, Anything that is design related is a feature request and an issue should be created, Security issues, And more, but be realistic"

I think the point about design above is incorrect.   If someone submits a PR that contains a badly designed implementation of a feature, then it should be in scope to say so.  Requiring a separate feature request to be filed to fix a design flaw in a "bug fix" would be process overkill.

Similarly, if there are typos in output messages or variable names or comments, I don't think such comments should be disallowed on the basis of "just esthetics".

**Comment by andschwa** [comment]
Some of the guidelines mentioned in https://github.com/intel/linux-sgx/issues/433 I think we could apply too (especially like Include What You Use).

**Comment by achamayou** [comment]
For code coverage, we're using codecov.io in CCF (eg. https://github.com/microsoft/CCF/pull/329#issuecomment-525763693). It has a few rough edges, but on the whole it's pretty good at catching regressions. If we think this might be useful, I'll have a look at making it work in OE (might need some access to the CI though).

**Comment by andschwa** [comment]
That would be _awesome_.

**Comment by CodeMonkeyLeet** [comment]
Per [CGC](https://aka.ms/openenclave/cgc) meeting, processes we will introduce as part of this:

- We will require 2 approvals and an approval to come from CODEOWNERS as enforced by tooling.
- This is only a baseline that is automated, it is still the responsibility of committers to ensure that appropriate review coverage is provided before merging PRs.

**Comment by jhand2** [comment]
Now that we will require 2 approvals, I propose core OE developers do the following:

### Look through stalled* open PRs and do one of the following:

* Review it and either approve or request changes
* Ask for more clarification from the author
* If the author has not responded to request for changes in 10 days, ask the author to either provide updates or close the PR. Close 2 days after request if still no response.
 
### *What is a stalled PR?

* The PR has no blockers but only 1 approval (I’m most worried about these)
* The PR has had no comments or changes for 10 days
* The PR does not have a “do not merge” label
 

If a PR cannot be merged because it is pending some decision or other blocker, but it still needs to remain open for merging later, please leave a comment and apply the “do not merge” label so that we know it does not need to be treated as stalled.


This should help keep things moving, improve response times for the couple of external contributors we have, and keep the number of PRs from getting too out of control as more people contribute.

**Comment by radhikaj** [comment]
@jhand2 assigning to you.

**Comment by radhikaj** [comment]
Let us include wordind around how bors should be used in this process and who can finally merge the PR.

**Comment by CodeMonkeyLeet** [comment]
Per latest CGC meeting, closing this issue as stale:
* enforcement of multiple approvals has been implemented for PRs
* any additional documentation pending for this issue should be submitted as a PR and will be reviewed there.
