### ISSUE TITLE
Some libc tests fail 

### ISSUE THREAD

**Issue by yakman2020** [openenclave/openenclave#1924]
We currently test approximately half of the musl libc-tests. The other half fail for various reasons.

This issue is to keep a tally of what doesn't work and why.

**Comment by yakman2020** [comment]
flock-list fails because it uses umap syscall. We currently do not support umap.

**Comment by yakman2020** [comment]
functional/fcntl.c
functional/ipc_msg.c
functional/ipc_sem.c
functional/ipc_shm.c
functional/vfork.c
regression/daemon-failure.c
regression/fflush-exit.c
regression/pthread_atfork-errno-clobber.c
regression/pthread_exit-dtor.c
regression/raise-race.c

Fail due to the use of fork

**Comment by radhikaj** [comment]
@yakman2020 We expect these to fail- fork etc. Could you please elaborate or close?
