### ISSUE TITLE
SGX1GettingStarted doc page ansible instruction might fail

### ISSUE THREAD

**Issue by jiria** [openenclave/openenclave#1925]
https://github.com/microsoft/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1GettingStarted.md

Ansible script fails when ocamlbuild is already preinstalled.

**Comment by ionutbalutoiu** [comment]
Hello @jiria,

I believe you encountered this at the [Install project prerequisites](https://github.com/microsoft/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1GettingStarted.md#install-project-prerequisites) section.

Did you get the failure for the Ubuntu 16.04 or Ubuntu 18.04 ?

Regards,
Ionut

**Comment by jiria** [comment]
Correct. 18.04. Note that this was not a fresh VM, but my Linux host with some preexisting state. I still have a stable repro:

localhost | FAILED | rc=31 >>
The following actions will be performed:
  ∗ install ocamlbuild  0.14.0 [required by fpath]
  ∗ install topkg       1.0.0  [required by fpath]
  ∗ install astring     0.8.3  [required by fpath]
  ∗ install fpath       0.7.2  [required by ocamlformat]
  ∗ install ocamlformat 0.8
===== ∗ 5 =====

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[astring.0.8.3] found in cache
[fpath.0.7.2] found in cache
[ocamlbuild.0.14.0] found in cache
[ocamlformat.0.8] found in cache
[topkg.1.0.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>


<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ocamlbuild 0.14.0
└─
╶─ No changes have been performed[WARNING] Running as root is not recommended
[ERROR] The compilation of ocamlbuild failed at "/usr/local/opam/opam-init/hooks/sandbox.sh build make check-if-preinstalled all opam-install".

#=== ERROR while compiling ocamlbuild.0.14.0 ==================================#
# context              2.0.4 | linux/x86_64 | ocaml-system.4.05.0 | https://opam.ocaml.org#ea999124
# path                 /usr/local/opam/default/.opam-switch/build/ocamlbuild.0.14.0
# command              /usr/local/opam/opam-init/hooks/sandbox.sh build make check-if-preinstalled all opam-install
# exit-code            2
# env-file             /usr/local/opam/log/ocamlbuild-9023-548b09.env
# output-file          /usr/local/opam/log/ocamlbuild-9023-548b09.out
### output ###
# if test -d /usr/lib/ocaml/ocamlbuild; then\
#   >&2 echo "ERROR: Preinstalled ocamlbuild detected at"\
#        "/usr/lib/ocaml/ocamlbuild";\
#   >&2 echo "Installation aborted; if you want to bypass this"\
#         "safety check, pass CHECK_IF_PREINSTALLED=false to make";\
#   exit 2;\
# fi
# ERROR: Preinstalled ocamlbuild detected at /usr/lib/ocaml/ocamlbuild
# Installation aborted; if you want to bypass this safety check, pass CHECK_IF_PREINSTALLED=false to make
# Makefile:410: recipe for target 'check-if-preinstalled' failed
# make: *** [check-if-preinstalled] Error 2non-zero return code

**Comment by yakman2020** [comment]
@ionutbalutoiu  Can I get an ETA?

**Comment by ionutbalutoiu** [comment]
Sorry for the late response on this issue.

@yakman2020 
/TLDR: This issue only affects existing environments already configured outside Ansible, and I'm not sure this is something we should take care of. See my concerns below for more info. Since the Ansible scripts to configure clean machines work without any problem, I'd say we can push this to `v0.7`.

@jiria 
This is my pull request to have this fixed: https://github.com/microsoft/openenclave/pull/1962

However, I am not confident of the approach here. You would end up with 2x `ocamlbuild` binaries on the system:
* The system `/usr/bin/ocamlbuild` (version `0.11.0`)
* The `ocamlbuild` (version `0.14.0`) from the `opam` environment at `/usr/local/opam/default/bin/ocamlbuild`

On the other hand, the Ansible code creates the file `/etc/profile.d/opam-env.sh` after finishing the `opam` setup:
https://github.com/microsoft/openenclave/blob/ede304d32b426b2f41e8f077795f03829a7a04f2/scripts/ansible/roles/linux/openenclave/tasks/opam-setup.yml#L55-L65

This file loads the environment variables to have `opam` used, and it gets automatically loaded when you login into an interactive shell console. This is how `ocamlformat` is consumed via the `opam` (we had to add `ocamlformat` to solve https://github.com/microsoft/openenclave/issues/1738).

My only concern with my [proposed pull request](https://github.com/microsoft/openenclave/pull/1962) is that you end up with two different `ocamlbuild` installations on the system:
* `0.11.0` from APT default PPAs
* `0.14.0` from `opam` (since it's required to have `opamformat` installed)

This doesn't look consistent to me.

Moreover, what if some other systems have other packages preinstalled besides `ocamlbuild` ? We would probably have to do the same approach if we want to have `opam` properly setup.

Coming back to your scenario: Do you really need `ocamlbuild 0.11.0` specifically ? If you don't really need `ocamlbuild 0.11.0` from the system, you can uninstall it and use the `ocamlbuild 0.14.0` from the `opam` environment after Ansible finishes its execution.

In my opinion, I would have documentation added to instruct that Ansible supports configuring only clean machines, or machines already configured with Ansible (since Ansible is idempotent, and it doesn't conflict with previous Ansible runs).

**Comment by ionutbalutoiu** [comment]
@jiria @johnkord 

Dropped PR https://github.com/openenclave/openenclave/pull/1962 in favor of PR https://github.com/openenclave/openenclave/pull/2011.

We agreed that our Ansible scripts should be used when configuring clean SGX-enabled machines, or any machines that were already previously configured with these Ansible scripts.

However, if you prefer to use an existing system, it is advisable to use our official Docker images, and mount the SGX device.

The Docker images have already the environment prepared. These are our Docker images published to Docker Hub:
* https://hub.docker.com/r/oeciteam/oetools-full-16.04
* https://hub.docker.com/r/oeciteam/oetools-full-18.04

Once you pulled the images, you can start a container with the SGX device mounted:
```
docker run -it --cap-add=SYS_PTRACE --device /dev/sgx:/dev/sgx oetools-full-18.04
```

I believe that the only requirement to have OE inside a Docker container with the SGX device is to have the SGX device already available on the host. This means that you have to install the Intel SGX driver, and the rest of the environment is already setup with the Docker image.

**Comment by johnkord** [comment]
Here is a relevant document that adds to @ionutbalutoiu 's comment: https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/BuildingInADockerContainer.md

**Comment by maverick-zhn** [comment]
I have some issues following this document:
I have a freshly installed version of Ubuntu Linux 18.04 LTS bare-metal not VM. I am interested in working on some SGX projects on my computer. My CPU is an Intel Core i5 8th Generation.
[CPU used](https://ark.intel.com/content/www/us/en/ark/products/124967/intel-core-i5-8250u-processor-6m-cache-up-to-3-40-ghz.html)

Following this document I get the following:
```
➜  openenclave git:(master) ✗ sudo ansible-playbook scripts/ansible/oe-contributors-setup-sgx1.yml
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] *******************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************
ok: [localhost]

TASK [linux/openenclave : Gather Ansible facts] *******************************************************************************************************************
ok: [localhost]

TASK [include_role : linux/common] ******************************************************************************************************************

...

TASK [linux/intel : Download Intel SGX DCAP Driver] *******************************************************************************************************************
skipping: [localhost]

TASK [linux/intel : Download Intel SGX1 Driver] *******************************************************************************************************************
ok: [localhost]

TASK [linux/intel : Install the Intel SGX DCAP Driver] *******************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/tmp/sgx_linux_x64_driver.bin"], "delta": "0:00:03.412127", "end": "2020-02-05 22:41:31.205975", "msg": "non-zero return code", "rc": 3, "start": "2020-02-05 22:41:27.793848", "stderr": "", "stderr_lines": [], "stdout": "Unpacking Intel SGX Driver ... done.\nVerifying the integrity of the install package ... done.\nInstalling Intel SGX Driver ...\n/tmp/sgx-driver-nas7FY ~/repos/openenclave/scripts/ansible\ninstall -d /opt/intel/sgxdriver/package\ninstall -d /opt/intel/sgxdriver/scripts\ninstall package/* /opt/intel/sgxdriver/package\ninstall scripts/* /opt/intel/sgxdriver/scripts\n~/repos/openenclave/scripts/ansible\n/opt/intel/sgxdriver/package ~/repos/openenclave/scripts/ansible\nmake -C /lib/modules/5.0.0-23-generic/build M=/opt/intel/sgxdriver/package modules\nmake[1]: Entering directory '/usr/src/linux-headers-5.0.0-23-generic'\n  CC [M]  /opt/intel/sgxdriver/package/sgx_main.o\n  CC [M]  /opt/intel/sgxdriver/package/sgx_page_cache.o\n  CC [M]  /opt/intel/sgxdriver/package/sgx_ioctl.o\n  CC [M]  /opt/intel/sgxdriver/package/sgx_vma.o\n  CC [M]  /opt/intel/sgxdriver/package/sgx_util.o\n  CC [M]  /opt/intel/sgxdriver/package/sgx_encl.o\n  CC [M]  /opt/intel/sgxdriver/package/sgx_encl2.o\n  LD [M]  /opt/intel/sgxdriver/package/isgx.o\n  Building modules, stage 2.\n  MODPOST 1 modules\n  CC      /opt/intel/sgxdriver/package/isgx.mod.o\n  LD [M]  /opt/intel/sgxdriver/package/isgx.ko\nmake[1]: Leaving directory '/usr/src/linux-headers-5.0.0-23-generic'", "stdout_lines": ["Unpacking Intel SGX Driver ... done.", "Verifying the integrity of the install package ... done.", "Installing Intel SGX Driver ...", "/tmp/sgx-driver-nas7FY ~/repos/openenclave/scripts/ansible", "install -d /opt/intel/sgxdriver/package", "install -d /opt/intel/sgxdriver/scripts", "install package/* /opt/intel/sgxdriver/package", "install scripts/* /opt/intel/sgxdriver/scripts", "~/repos/openenclave/scripts/ansible", "/opt/intel/sgxdriver/package ~/repos/openenclave/scripts/ansible", "make -C /lib/modules/5.0.0-23-generic/build M=/opt/intel/sgxdriver/package modules", "make[1]: Entering directory '/usr/src/linux-headers-5.0.0-23-generic'", "  CC [M]  /opt/intel/sgxdriver/package/sgx_main.o", "  CC [M]  /opt/intel/sgxdriver/package/sgx_page_cache.o", "  CC [M]  /opt/intel/sgxdriver/package/sgx_ioctl.o", "  CC [M]  /opt/intel/sgxdriver/package/sgx_vma.o", "  CC [M]  /opt/intel/sgxdriver/package/sgx_util.o", "  CC [M]  /opt/intel/sgxdriver/package/sgx_encl.o", "  CC [M]  /opt/intel/sgxdriver/package/sgx_encl2.o", "  LD [M]  /opt/intel/sgxdriver/package/isgx.o", "  Building modules, stage 2.", "  MODPOST 1 modules", "  CC      /opt/intel/sgxdriver/package/isgx.mod.o", "  LD [M]  /opt/intel/sgxdriver/package/isgx.ko", "make[1]: Leaving directory '/usr/src/linux-headers-5.0.0-23-generic'"]}

NO MORE HOSTS LEFT *******************************************************************************************************************

PLAY RECAP *******************************************************************************************************************
localhost                  : ok=31   changed=6    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   
```
Can you please provide some guidance? Thank you in advance.

**Comment by jhand2** [comment]
Hey @maverick-zhn could you open a new issue and copy and paste your message there? I believe these are separate issues.

**Comment by BRMcLaren** [comment]
This issue has not been updated in nearly a year, we have also moved away from OCAML dependencies during this time. If this resurges let's create a new issue and track closer.

Closing issue.
