### ISSUE TITLE
Add documentation for using Ninja as a build engine

### ISSUE THREAD

**Issue by johnkord** [openenclave/openenclave#1947]
Our getting started page should mention that it's possible to use Ninja as a build engine

**Comment by yakman2020** [comment]
There is a PR on this (#1978) Will it suffice?

**Comment by yakman2020** [comment]
@johnkord Can we close?

**Comment by johnkord** [comment]
Yes once that PR gets merged, we can close this!

**Comment by yakman2020** [comment]
Closed. Fixed by PR 1978
