### ISSUE TITLE
test crypto_crl_cert_chains fails to build on Windows with new openssl

### ISSUE THREAD

**Issue by anitagov** [openenclave/openenclave#1955]
The fix for #1932 got merged into master before the final solution to fix crypto_crl_cert_chains was made by @mikbras to support the newer openssl which introduces CR/LF to PEM certificates. This issue is to get the final change into the master.

The Windows cross-compile debug/release will PASS with the newer openssl but the Linux-Elf-build has issues. The failing pipeline is at: https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/946/pipeline

**Comment by anitagov** [comment]
https://oe-jenkins.eastus.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/946/pipeline

Here are the details from the failing pipeline:
"D:\Jenkins\workspace\Bors_staging\build\ALL_BUILD.vcxproj" (default target) (1) ->

"D:\Jenkins\workspace\Bors_staging\build\tests\crypto_crls_cert_chains\data\crypto_crls_cert_chains_test_data.vcxproj" (default target) (32) ->

(CustomBuild target) -> 

  8788 : error : 02001002:system library:fopen:No such file or directory:../openssl-1.1.1a/crypto/bio/bss_file.c:72:fopen('./root_index.txt.attr','r') [D:\Jenkins\workspace\Bors_staging\build\tests\crypto_crls_cert_chains\data\crypto_crls_cert_chains_test_data.vcxproj]

  8788 : error : 2006D080:BIO routines:BIO_new_file:no such file:../openssl-1.1.1a/crypto/bio/bss_file.c:79: [D:\Jenkins\workspace\Bors_staging\build\tests\crypto_crls_cert_chains\data\crypto_crls_cert_chains_test_data.vcxproj]

  7532 : error : 02001002:system library:fopen:No such file or directory:../openssl-1.1.1a/crypto/bio/bss_file.c:72:fopen('./root_index2.txt.attr','r') [D:\Jenkins\workspace\Bors_staging\build\tests\crypto_crls_cert_chains\data\crypto_crls_cert_chains_test_data.vcxproj]

  7532 : error : 2006D080:BIO routines:BIO_new_file:no such file:../openssl-1.1.1a/crypto/bio/bss_file.c:79: [D:\Jenkins\workspace\Bors_staging\build\tests\crypto_crls_cert_chains\data\crypto_crls_cert_chains_test_data.vcxproj]

  6728 : error : 02001002:system library:fopen:No such file or directory:../openssl-1.1.1a/crypto/bio/bss_file.c:72:fopen('./intermediate_index.txt.attr','r') [D:\Jenkins\workspace\Bors_staging\build\tests\crypto_crls_cert_chains\data\crypto_crls_cert_chains_test_data.vcxproj]

  6728 : error : 2006D080:BIO routines:BIO_new_file:no such file:../openssl-1.1.1a/crypto/bio/bss_file.c:79: [D:\Jenkins\workspace\Bors_staging\build\tests\crypto_crls_cert_chains\data\crypto_crls_cert_chains_test_data.vcxproj]

  2916 : error : 02001002:system library:fopen:No such file or directory:../openssl-1.1.1a/crypto/bio/bss_file.c:72:fopen('./intermediate_index2.txt.attr','r') [D:\Jenkins\workspace\Bors_staging\build\tests\crypto_crls_cert_chains\data\crypto_crls_cert_chains_test_data.vcxproj]

  2916 : error : 2006D080:BIO routines:BIO_new_file:no such file:../openssl-1.1.1a/crypto/bio/bss_file.c:79: [D:\Jenkins\workspace\Bors_staging\build\tests\crypto_crls_cert_chains\data\crypto_crls_cert_chains_test_data.vcxproj]

  8512 : error : 02001002:system library:fopen:No such file or directory:../openssl-1.1.1a/crypto/bio/bss_file.c:72:fopen('./root_index2.txt.attr','r') [D:\Jenkins\workspace\Bors_staging\build\tests\crypto_crls_cert_chains\data\crypto_crls_cert_chains_test_data.vcxproj]

  8512 : error : 2006D080:BIO routines:BIO_new_file:no such file:../openssl-1.1.1a/crypto/bio/bss_file.c:79: [D:\Jenkins\workspace\Bors_staging\build\tests\crypto_crls_cert_chains\data\crypto_crls_cert_chains_test_data.vcxproj]

  2136 : error : 02001002:system library:fopen:No such file or directory:../openssl-1.1.1a/crypto/bio/bss_file.c:72:fopen('./intermediate_index2.txt.attr','r') [D:\Jenkins\workspace\Bors_staging\build\tests\crypto_crls_cert_chains\data\crypto_crls_cert_chains_test_data.vcxproj]

  2136 : error : 2006D080:BIO routines:BIO_new_file:no such file:../openssl-1.1.1a/crypto/bio/bss_file.c:79: [D:\Jenkins\workspace\Bors_staging\build\tests\crypto_crls_cert_chains\data\crypto_crls_cert_chains_test_data.vcxproj]

"D:\Jenkins\workspace\Bors_staging\build\ALL_BUILD.vcxproj" (default target) (1) ->

"D:\Jenkins\workspace\Bors_staging\build\tests\crypto\data\crypto_test_data.vcxproj" (default target) (33) ->

  6408 : error : 02001002:system library:fopen:No such file or directory:../openssl-1.1.1a/crypto/bio/bss_file.c:72:fopen('./intermediate_index.txt.attr','r') [D:\Jenkins\workspace\Bors_staging\build\tests\crypto\data\crypto_test_data.vcxproj]

  6408 : error : 2006D080:BIO routines:BIO_new_file:no such file:../openssl-1.1.1a/crypto/bio/bss_file.c:79: [D:\Jenkins\workspace\Bors_staging\build\tests\crypto\data\crypto_test_data.vcxproj]

  6528 : error : 02001002:system library:fopen:No such file or directory:../openssl-1.1.1a/crypto/bio/bss_file.c:72:fopen('./root_index.txt.attr','r') [D:\Jenkins\workspace\Bors_staging\build\tests\crypto\data\crypto_test_data.vcxproj]

  6528 : error : 2006D080:BIO routines:BIO_new_file:no such file:../openssl-1.1.1a/crypto/bio/bss_file.c:79: [D:\Jenkins\workspace\Bors_staging\build\tests\crypto\data\crypto_test_data.vcxproj]

  6656 : error : 02001002:system library:fopen:No such file or directory:../openssl-1.1.1a/crypto/bio/bss_file.c:72:fopen('./intermediate_index.txt.attr','r') [D:\Jenkins\workspace\Bors_staging\build\tests\crypto\data\crypto_test_data.vcxproj]

  6656 : error : 2006D080:BIO routines:BIO_new_file:no such file:../openssl-1.1.1a/crypto/bio/bss_file.c:79: [D:\Jenkins\workspace\Bors_staging\build\tests\crypto\data\crypto_test_data.vcxproj]

  4316 : error : 02001002:system library:fopen:No such file or directory:../openssl-1.1.1a/crypto/bio/bss_file.c:72:fopen('./root_index.txt.attr','r') [D:\Jenkins\workspace\Bors_staging\build\tests\crypto\data\crypto_test_data.vcxproj]

  4316 : error : 2006D080:BIO routines:BIO_new_file:no such file:../openssl-1.1.1a/crypto/bio/bss_file.c:79: [D:\Jenkins\workspace\Bors_staging\build\tests\crypto\data\crypto_test_data.vcxproj]

**Comment by johnkord** [comment]
We can't repro this, so we're closing this and will reopen it if it occurs again!
