### ISSUE TITLE
Reduce the simulation stages in Jenkins CI

### ISSUE THREAD

**Issue by anitagov** [openenclave/openenclave#1965]
We have 12 simulation stages in Jenkins for Ubuntu 16.04 and 18.04. This is definitely overkill especially as we are phasing out simulation. One thought is to reduce this to half by eliminating Ubuntu 16.04 simulation stages entirely.

**Comment by ionutbalutoiu** [comment]
@anitagov 

I agree with you on this one, and I'll take care of this.
