### ISSUE TITLE
Provide packaged OE SDK support for SGX configurations without FLC

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#1983]
Per @dthaler, there are developer scenarios they would like to support relying only on packaged OE SDK releases.

The existing OE SDK package today explicitly does not support the SGX without FLC configuration since it has explicit build time dependencies on Intel components that require FLC. The degree of support provided by OE SDK on platforms without FLC is also incomplete and undocumented (e.g. attestation support is notably broken), so the current expectation is that developers who require this configuration will need to build from sources using the instructions at [SGX1GettingStarted.md](https://github.com/microsoft/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1GettingStarted.md)

To address this, OE SDK would need to:
- [ ] Configure and release a new OE SDK package for non-FLC configurations.
- [ ] Update documentation such as [install_oe_sdk-Ubuntu_18.04.md](https://github.com/microsoft/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md) with instructions for the new scenario.
- [ ] Document the differences in supported behavior between the configurations.

As Intel converges their DCAP and legacy stacks on top of their enclave common library, there should be a consolidated stack underneath OE with the optional DCAP libraries as add-ons. This would make it possible to refactor OE SDK code to make runtime instead of build time decisions about its dependency on FLC, and is something we should consider moving forwards.

**Comment by radhikaj** [comment]
#3162 and #3155 fix this issue.
