### ISSUE TITLE
Update the default download URL for the Azure-DCAP-Client nupkg file

### ISSUE THREAD

**Issue by ionutbalutoiu** [openenclave/openenclave#1988]
The default download URL for the Azure-DCAP-Client nupkg file used in the PowerShell setup script (proposed in [PR-1934](https://github.com/openenclave/openenclave/pull/1934)) points to the internal OE storage account.

We need an official source for this 3rd party dependency. There's an [open issue](https://github.com/microsoft/Azure-DCAP-Client/issues/74) to the Azure-DCAP-Client GitHub repository to have this published with the releases there. Once this gets fixed, we can update the default URL in our OE PowerShell setup script.

**Comment by CodeMonkeyLeet** [comment]
We should do this as part of the v0.7 work for setting up a consistent Windows test environment.

**Comment by radhikaj** [comment]
It looks like the powershell script now uses https://www.nuget.org/api/v2/package/Azure.DCAP.Windows/0.0.3
