### ISSUE TITLE
Cache any external 3rd party dependencies used in the setup scripts

### ISSUE THREAD

**Issue by ionutbalutoiu** [openenclave/openenclave#1989]
This is a follow-up to the comment https://github.com/openenclave/openenclave/pull/1934#pullrequestreview-253075696.

The [PR-1934](https://github.com/openenclave/openenclave/pull/1934) proposes a PowerShell script to setup a clean SGX enabled Windows machine. There are multiple Windows installers downloaded from the internet official sources when doing the setup.

So far, only the Intel PSW installer, the Intel DCAP installer, and the Azure-DCAP-Client nupkg file are already cached into our internet storage account: https://oejenkins.blob.core.windows.net/oejenkins

We need to cache any 3rd party dependency files downloaded from the internet. This should apply for the Linux setup scripts as well.

Check-list:

- [x] Cache any external 3rd party installers / files used in Windows setup scripts
- [ ] Cache any external 3rd party dependencies files used in the Linux setup scripts

**Comment by ionutbalutoiu** [comment]
Pull request https://github.com/openenclave/openenclave/pull/2018 updated Ansible to use any cached 3rd party Windows installers.

**Comment by radhikaj** [comment]
@BRMcLaren  @paulcallen  please track this issue
