### ISSUE TITLE
ACC VM does not come with cmake

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#1993]
OE now supports building samples via make and cmake.
ACC VMs don't come with cmake by default.

I'd recommend that we pre-install the cmake version that can be used to build the OE SDK itself.

**Comment by achamayou** [comment]
That's installed by the ansible scripts that take care of OE dev dependencies though: https://github.com/openenclave/openenclave/blob/master/scripts/ansible/roles/linux/openenclave/tasks/environment-setup.yml#L63

It's documented here: https://github.com/openenclave/openenclave/tree/master/scripts/ansible#open-enclave-deployment-options-via-ansible, and at least some users (like us ;)) are very happy to use that on top of vanilla images.

**Comment by anakrish** [comment]
Ansible scripts are intended for a _contributor_. A _user_ is not required to run them to build samples.

**Comment by achamayou** [comment]
But would a user build the OE SDK?

**Comment by anakrish** [comment]
A _user_ installs a release from a package. A _user_ will likely  build the samples using cmake or make.

**Comment by andschwa** [comment]
I also think that most users of the SDK are going to be using CMake to build their code and build against the SDK.

**Comment by johnkord** [comment]
Closing this as we are getting away from the "Install SDK option" in the ACC Marketplace.

Creating an issue in oe-engine to add a CMake install to the deployed ACC system.
