### ISSUE TITLE
handles should be declared as void*

### ISSUE THREAD

**Issue by yakman2020** [openenclave/openenclave#2004]
From isvan haller:

https://github.com/openenclave/openenclave/blob/master/enclave/asym_keys.c#L545 sizeof(T*) == sizeof(void*)

https://github.com/openenclave/openenclave/blob/master/enclave/asym_keys.c#L616 sizeof(T*) == sizeof(void*)

oe_get_enclave should only return a void* since only the base pointer was validated, not the typed struct. Handles are best left as void* to highlight that care needs to be taken before using them in a typed manner.

**Comment by mikbras** [comment]
I verified that **oe_get_enclave** returns a pointer that is guaranteed to be of type **oe_enclave_t**. This pointer is passed down from the host during initialization. What am I missing?

**Comment by ihaller** [comment]
The pointer returned by oe_get_enclave is verified such that its base address is outside the enclave, but not its full content range. Having access to the full type can incentivize users to attempt to poke into data. Ideally the method returns an opaque handle as the data behind said handle is only meaningful to the host.

**Comment by yakman2020** [comment]
@mikbras pls discuss with isvan.

**Comment by radhikaj** [comment]
We are closing this issue since we will not be fixing at it this time. Can you please reopen with updates to what the security issues in the current code base are if you feel it is necessary.
