### ISSUE TITLE
Need pthreads create/delete/join support in the enclaves

### ISSUE THREAD

**Issue by anitagov** [openenclave/openenclave#2015]
Now that we have greatly increased compatibility with POSIX and C API software on Linux
enclaves, including network name resolution, sockets and file system, we need to add support for pthreads create/delete/join in the enclaves. This will enable applications to be ported very easily to Linux enclaves.

**Comment by anitagov** [comment]
@johnkord - Curious why this was closed without any reason for closing.

**Comment by jxyang** [comment]
@anitagov This is closed with the expectation that we will open a set of issues under the same story related to enabling more complete POSIX functionalities in enclaves, not just pthread, but also signal handling etc.

**Comment by anitagov** [comment]
@jxyang - Thanks for the info.
