### ISSUE TITLE
Debugger Contract Phase 2

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#2022]
This issue captures items to be implemented in second phase:

-  Unify wpath/path and add a path length field. 
-  Update README files to describe rationale/implementation. 
-  Build debugrt as a DLL in Windows and install to appropriate location.
- Revisit whether we need to install the object library target.
- Remove dependency on oe headers.
- Determine if it is OK to only create debug information for debug enclaves. Will that affect taking coredumps on Windows?
- Change enclave list navigation to use new global enclave list (attach scenario)
- Remove oe types and includes from debugrt
- Document debugrt/host.h
- Consider using platform's spinlocks/futexes instead of writing our own.

**Comment by radhikaj** [comment]
@anakrish Can we close this?

**Comment by anakrish** [comment]
I went through this list again. All of this is addressed
- There is just one path field (const char*) for enclave path. OE SDK currently doesn't support wide char enclave path.
- Rationale/Implementation is described in Debugger Contract instead of README.
- Debugrt is shipped as a DLL in Windows. Installed via nuget.
- Debugrt is currently internal header and therefore can take dependency with OE's basic headers (bits/types)
- debugrt.h is commented/documented.
The other items are not relevant for now.
