### ISSUE TITLE
Remove <openenclave/bits/safe*.h> from the installed header list.

### ISSUE THREAD

**Issue by mikbras** [openenclave/openenclave#2032]
The **safecrt.h** and **safemath.h** headers are installed and visible to end-users. These should be removed. I suggest adding extern function definitions to generated edger8r code to work around.

**Comment by jhand2** [comment]
Only need to be there for oeedger8r code, not to be used by enclave developers.

Options:
1. Consider removing these headers from installation, however removing public headers is a breaking change to the SDK.
2. Mark as experimental.
3. Move to edger8r's include files (at least as a first step)

**Comment by jxyang** [comment]
Some library code other than oeedger8r use safe math functions, for example the elf loader and the arena-based allocator. I'd vote for option 2.

**Comment by radhikaj** [comment]
I am moving this to V0.9.

**Comment by dthaler** [comment]
@radhikaj in the triage meeting we agreed that if this was moved to 0.9 that we could not remove the functions in 0.9, only in the next release after that.  That's why triage didn't move it to 0.9.  If you believe we must not remove them in 0.9, cam you elaborate on why?  (since no decision was made during triage)

**Comment by anakrish** [comment]
oeedger8r does not use these headers. oeedger8r defines and uses its own safe addition https://github.com/openenclave/openenclave/blob/30cc09cc3a41deebd852de2b63a0eaa373f75655/include/openenclave/edger8r/common.h#L40-L67

**Comment by radhikaj** [comment]
> @radhikaj in the triage meeting we agreed that if this was moved to 0.9 that we could not remove the functions in 0.9, only in the next release after that. That's why triage didn't move it to 0.9. If you believe we must not remove them in 0.9, cam you elaborate on why? (since no decision was made during triage)

It is in V0.8
