### ISSUE TITLE
Deprecate support for insecure mbedTLS options in OE SDK package

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#2038]
OE SDK currently ships with a stripped down version of the mbedTLS libraries for applications to use inside the enclave. In reviewing the security posture of what is supported in the default build of the libraries, a few options we considered keeping for app compatibility reasons in the mbedTLS `config.h` are going to be increasingly unsafe moving forwards, and we would like to deprecate them.

- `MBEDTLS_TLS_DEFAULT_ALLOW_SHA1_IN_KEY_EXCHANGE`
    - Considerable advances have been made in breaking SHA1 since our original review and we would like to be more prescriptive in recommending the use of SHA256. 

- `MBEDTLS_KEY_EXCHANGE_RSA_ENABLED`
    - This option provides no perfect forward secrecy and is generally becoming less popular as this is recognized. The ECDHE variants are also more performant.

**Comment by radhikaj** [comment]
@radhikaj  @CodeMonkeyLeet  Lets add release note that we are deprecating this.

**Comment by jhand2** [comment]
Completed in #2239
