### ISSUE TITLE
Use consistent git version tags for releases

### ISSUE THREAD

**Issue by letmaik** [openenclave/openenclave#2039]
0.6.0: `v0.6.0-release`
0.5.0: `v0.5.0`
0.4.1: `v0.4.1`
0.4.0: `v0.4.0`
...

If possible, please create a `v0.6.0` tag. That would make life easier.

**Comment by johnkord** [comment]
Thanks @letmaik, this is correct, we made a mistake here. We'll fix it up soon!

**Comment by johnkord** [comment]
This has now been fixed!
