### ISSUE TITLE
oesign does not protect signing key in an enclave

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#2042]
The oesign tool loads a private key out of a PEM file into host application memory, and uses it to sign enclaves.  Since the signing key is key to the security of enclaves, this should be improved by having oesign only use keys inside its own enclave.   The signing key can then be protected so it is only available within the enclave, not to host code.

**Comment by anakrish** [comment]
CC: @radhikaj

**Comment by johnkord** [comment]
There is current work to enable digest signing with oesign #525 
Also, we need to allow signing to occur on systems that don't have SGX or TrustZone (etc).

**Comment by dthaler** [comment]
Currently the description of #525 does not cover this issue.  If this is to be closed as a duplicate, then this discussion should be copied there first.  As is, I don't agree that #525 will automatically resolve this issue.

**Comment by johnkord** [comment]
Thanks for the quick feedback, @dthaler !  I think I misunderstood this issue as a requirement that oesign must sign enclave images from an enclave.  Is the intention of this issue to have _an extra option_ to support signing an enclave image from inside an enclave?

**Comment by dthaler** [comment]
@johnkord, yes that would be an acceptable resolution.   Part if the issue is really explaining where the signing key is stored... in #525 it's in a different device than the one running the tool.  In oesign today, it's in the untrusted app.  In this issue, it's in an enclave on the same device.  The user running the tool should be able to specify which key to sign with, without leaking the key to the normal world on the device.

**Comment by CodeMonkeyLeet** [comment]
Split the concerns expressed in this issue into separate tracking tasks.
- #2089 Support digest signing workflow in oesign for production signing
- #2090 Support crypto extensions in oesign tool
- #2091 Document appropriate use of oesign and key management
