### ISSUE TITLE
Update Windows DCAP & PSW dependencies

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#2051]
The scripts/install-windows-prereqs.ps1 needs to be updated with the latest dependency links:

- DCAP 1.2
http://registrationcenter-download.intel.com/akdlm/irc_nas/15650/Intel%20SGX%20DCAP%20for%20Windows%20v1.2.100.49925.exe

- PSW 2.4
http://registrationcenter-download.intel.com/akdlm/irc_nas/15654/Intel%20SGX%20PSW%20for%20Windows%20v2.4.100.51291.exe

Note that we're already broken AESM support with the current use of PSW v2.3 (#1810) and this is not expected to introduce new issues.

**Comment by CodeMonkeyLeet** [comment]
Partially addressed by #2087, Ansible scripts still need to be updated.

**Comment by johnkord** [comment]
This has been fixed by #2106
