### ISSUE TITLE
"enclave_create with ENCLAVE_TYPE_SGX1 type failed"

### ISSUE THREAD

**Issue by Kushg02** [openenclave/openenclave#2053]
Was able to run the provided samples by following the SG1gettingstarted.md earlier this week. Almost sporadically, I got the following issues when attempting to build and run any sample, including the basic hello world: 

Sourcing and building ran fine, but running gave the following:
```bash
kush@kush-desktop:~/openenclave/samples/helloworld$ make run
host/helloworldhost ./enclave/helloworldenc.signed
23:13:41:653535 tid(0x7feefe64a740) (H)[ERROR]enclave_create with ENCLAVE_TYPE_SGX1 type failed (err=0x1) (oe_result_t=OE_PLATFORM_ERROR)[/home/jenkins/work_dir/workspace/OpenEnclave-v0.6.x_packages/host/sgx/sgxload.c oe_sgx_create_enclave:535]
23:13:41:653578 tid(0x7feefe64a740) (H)[ERROR]:OE_PLATFORM_ERROR[/home/jenkins/work_dir/workspace/OpenEnclave-v0.6.x_packages/host/sgx/create.c oe_sgx_build_enclave:558]
23:13:41:653878 tid(0x7feefe64a740) (H)[ERROR]:OE_PLATFORM_ERROR[/home/jenkins/work_dir/workspace/OpenEnclave-v0.6.x_packages/host/sgx/create.c oe_create_enclave:681]
oe_create_helloworld_enclave(): result=21 (OE_PLATFORM_ERROR)
Makefile:17: recipe for target 'run' failed
make: *** [run] Error 1
```

Using the cmake method and got the same result. Not sure if this is related or could be the cause, but I have downloaded Graphene-SGX on the same system. Other than this, I am not sure what I could have done to have created this issue. 

After a fresh re-install, the issue persists. Not sure what I am doing wrong. I would very grateful if anyone could shed some light on what is happening. Thank you in advance.

**Comment by Kushg02** [comment]
Same as issue #2054 except I am running on Ubuntu 16.04

**Comment by Kushg02** [comment]
Having same issues as #2054, except running on Ubuntu 16.04 on a SkullCanyon NUC. Is this designed only for use in Azure?

**Comment by johnkord** [comment]
We're going to close this issue. If you continue to experience any issue, can you reopen this and tag me? :)
