### ISSUE TITLE
oegdb: finding the text section.

### ISSUE THREAD

**Issue by mikbras** [openenclave/openenclave#2056]
The SGK-LKL had modified the oegdb plugin. Here is the note from Peter.

"The oegdb plug-in uses ‘.find(“.text”)’ to find the text section in the enclave image, which incorrectly matches “.init.text” in the SGX-LKL enclave image. We changed this to ‘== “.text”’. "

**Comment by yakman2020** [comment]
@mikbras Pls add detail....
