### ISSUE TITLE
Enable /WX on Windows compilation and fix existing issues

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#2075]
Builds of OE SDK on Windows today spew a lot of build warnings and these need to be cleaned up. At the same time, we need to stop introducing new build warnings on Windows by enabling the `/WX` flag (treat warnings as errors) to enforce this.

**Comment by jhand2** [comment]
#2374 fixes /W1 warnings across the codebase and enables /WX for W1 warnings.

I'll consider this issue closed when we have /W3 /WX enabled but this is a good first step.

**Comment by jhand2** [comment]
#2389 fixes W2 warnings

**Comment by radhikaj** [comment]
@ryanhsu19 please continue looking  into this

**Comment by ryanhsu19** [comment]
#2654 fixes /W3 warnings
