### ISSUE TITLE
dl and crypto libraries not namespaced in CMake

### ISSUE THREAD

**Issue by letmaik** [openenclave/openenclave#2082]
Currently, `find_package(openenclave)` pollutes the global namespace with the `dl` and `crypto` targets, which means I can't develop an application which has a target named `crypto`. That's bad. Please put all targets that you create during `find_package` in the `openenclave::` namespace.

Concrete example: Pulling in boringssl via `add_subdirectory`: https://github.com/google/boringssl/blob/81080a729af568f7b5fde92b9170cc17065027c9/crypto/CMakeLists.txt#L187-L188 Can't do it because it also has a `crypto` target.

**Comment by andschwa** [comment]
Good catch, thanks!

**Comment by mingweishih** [comment]
Fixed by #2391
