### ISSUE TITLE
Support crypto extensions in oesign tool

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#2090]
To accommodate a wider range of key management scenarios when using oesign, it would be valuable to take advantage of existing crypto library infrastructure for interfacing with Hardware Security Modules (HSM) and other custom crypto providers. For example:

- OpenSSL on Linux supports [ENGINE](https://github.com/openssl/openssl/blob/master/README.ENGINE) plug-ins 
- BCrypt on Windows supports custom [Cryptographic Providers](https://www.microsoft.com/en-us/download/details.aspx?id=30688) such as key storage providers (KSP)

In addition to enabling the use of custom hardware for acceleration and key storage, this mechanism can also be used to accommodate developers who want to do local secure caching of keys and signing operations inside an enclave (#2042), where the custom provider can be tailored to also account for the attestation endpoint, authentication, sealing and key escrow behaviors on a per enclave basis. 

This task requires a command line interface change to support pass-through of parameters to the engines (see OpenSSL's implementation).

**Comment by radhikaj** [comment]
May be fixed by #2455
