### ISSUE TITLE
CA certificate with Basic Constraints pathlen:0 detected in windows, but not in linux.

### ISSUE THREAD

**Issue by jazzybluesea** [openenclave/openenclave#2131]
Steps to repro:
 1. Create an attestation certificate where the Intel CA cert has a pathlen of 0:
     X509v3 Basic Constraints: critical CA:TRUE, pathlen:0

2. Pass certificate to oe_verify_attestation_certificate() for verification.
3. In Linux, this error is not detected, but in windows this error is detected.

**Comment by jazzybluesea** [comment]
[bad_certs.zip](https://github.com/openenclave/openenclave/files/3560762/bad_certs.zip)

**Comment by jhand2** [comment]
@jazzybluesea Can you confirm if this is still an issue? If so we should do some more investigation and try to get it fixed as soon as possible.

**Comment by jazzybluesea** [comment]
Yes, I believe this issue still exists.  It can be verified with the attached certificates that I have attached to this issue.

**Comment by jazzybluesea** [comment]
If I can recall correctly, the reason for the difference is due to the different encryption libraries.  In windows we use bcrypt and in Linux we use mbed TLS.

**Comment by douglasism** [comment]
Not an authority on mbedtls, but in `x509_get_basic_constraints` there's a curious, uncommented `    (*max_pathlen)++;`, and then subsequently this is ++ action is special-cased elsewhere. I did not review it further.

**Comment by jazzybluesea** [comment]
Thank you Doug for pointing this out.  Given that we are upgrading the version of mbedTLS, we should retest using the attached certificates.

**Comment by radhikaj** [comment]
@yentsanglee Can we please retest this?

**Comment by ryanhsu19** [comment]
The issue still exists on my Ubuntu 18.04 VM, after assigning the paths of the files provided in a previous comment to variables `CERT_EC_BAD_FILENAME` and `CERT_RSA_BAD_FILENAME` in `tests/host_verify/host/host.cpp`:

Start  56: tests/host_verify
56/296 Test  #56: tests/host_verify .....................................................................................................................Child aborted***Exception:   0.08 sec
Test failed: /home/ryan/openenclave/tests/host_verify/host/host.cpp(76): _validate_file fp != __null

**Comment by ryanhsu19** [comment]
@jazzybluesea and I discussed the issue and agreed that the results should be the same on Windows and on Linux, i.e., both should either succeed or fail. On the other hand, @yentsanglee mentioned that the self-signed certificate should be `CA:FALSE`, as we do not use it to sign other certificates.

After running it on Ubuntu 18.04 and Windows 2016 (I did not test it on Windows 2019 because currently there is an ongoing compilation problem, as is mentioned in #3734 ), both tests failed after assigning the paths of the files provided in the zip file to variables `CERT_EC_BAD_FILENAME` and `REPORT_BAD_FILENAME`. Therefore, if there is no further issue, I believe the problem can be closed based on the discussion.

On Ubuntu 18.04:
```
ryan@ryhsu-61:~/openenclave/build$ sudo ctest -R tests/host_verify -VV
UpdateCTestConfiguration  from :/home/ryan/openenclave/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/ryan/openenclave/build/DartConfiguration.tcl
Test project /home/ryan/openenclave/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 56
    Start 56: tests/host_verify

56: Test command: /home/ryan/openenclave/build/tests/host_verify/host/test_host_verify
56: Test timeout computed to be: 10000000
56: Test failed: /home/ryan/openenclave/tests/host_verify/host/host.cpp(76): _validate_file fp != __null
1/1 Test #56: tests/host_verify ................Child aborted***Exception:   0.08 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.09 sec

The following tests FAILED:
         56 - tests/host_verify (Child aborted)
Errors while running CTest
```

On Windows 2016:
```
PS C:\Users\ryan\openenclave\build> ctest -R tests/host_verify -VV
UpdateCTestConfiguration  from :C:/Users/ryan/openenclave/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :C:/Users/ryan/openenclave/build/DartConfiguration.tcl
Test project C:/Users/ryan/openenclave/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 44
    Start 44: tests/host_verify

44: Test command: C:\Users\ryan\openenclave\build\tests\host_verify\host\test_host_verify.exe
44: Test timeout computed to be: 10000000
44: Test failed: ..\tests\host_verify\host\host.cpp(76): _validate_file fp != 0
1/1 Test #44: tests/host_verify ................***Failed    2.00 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   2.15 sec

The following tests FAILED:
         44 - tests/host_verify (Failed)
Errors while running CTest
```

**Comment by yentsanglee** [comment]
Makes sense.
