### ISSUE TITLE
From scratch -DUSE_LIBSGX=OFF build errors

### ISSUE THREAD

**Issue by deeglaze** [openenclave/openenclave#2136]
Hi y'all, first time looking at building open enclave, and I don't want to depend on Intel's source. 

I cloned at 2a49ba881 and ran
```
cmake -DUSE_LIBSGX=OFF .
make
```
And got the following error output
```
/home/dionnaglaze/gitrepos/openenclave/tests/cppException/enc/cppException.cpp: In function ‘bool BasicVerification()’:
/home/dionnaglaze/gitrepos/openenclave/tests/cppException/enc/cppException.cpp:250:23: error: catching polymorphic type ‘class BarClass02’ by value [-Werror=catch-value=]
     catch (BarClass02 ex_obj)
                       ^~~~~~
/home/dionnaglaze/gitrepos/openenclave/tests/cppException/enc/cppException.cpp:325:23: error: catching polymorphic type ‘class BarClass02’ by value [-Werror=catch-value=]
     catch (BarClass02 ex_obj)
                       ^~~~~~
/home/dionnaglaze/gitrepos/openenclave/tests/cppException/enc/cppException.cpp: In function ‘void bar02()’:
/home/dionnaglaze/gitrepos/openenclave/tests/cppException/enc/cppException.cpp:412:12: error: catching polymorphic type ‘class BarClass03’ by value [-Werror=catch-value=]
     catch (BarClass03)
            ^~~~~~~~~~
/home/dionnaglaze/gitrepos/openenclave/tests/cppException/enc/cppException.cpp: In function ‘bool NestedException()’:
/home/dionnaglaze/gitrepos/openenclave/tests/cppException/enc/cppException.cpp:495:23: error: catching polymorphic type ‘class BarClass02’ by value [-Werror=catch-value=]
     catch (BarClass02 ex_obj)
                       ^~~~~~
```
I double-checked make clang version, saw it was 6, so installed clang-7 and set
```
export CC=clang-7
```
Then make clean; make led to this
```
make[2]: *** No rule to make target '3rdparty/musl/musl/src/prng/rand.c', needed by 'enclave/core/CMakeFiles/oecore.dir/__/__/3rdparty/musl/musl/src/prng/rand.c.o'.  Stop.
```

I might not have looked hard enough for a "how to build" document, so I'm not sure what I'm supposed to do for a first time build. Please advise.

**Comment by andschwa** [comment]
Hi @deeglaze! Thanks for checking out Open Enclave. That "how to build" document you're looking for (presumably in simulation mode, as you disabled SGX support) is [here](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Simulation.md).

Let me know how that goes, and feel free to ping me or @johnkord with any questions!

**Comment by johnkord** [comment]
Hey @andschwa SGX is still enabled even if USE_LIBSGX=OFF!  That just means that openenclave won't be using the Intel libsgx libraries for launching enclaves (and instead, on Linux, interfacing with the aesm service). That's the only supported mechanism for launching enclaves on systems with SGX that don't have Flexible Launch Control!

Hi @deeglaze, welcome! One thing I noticed is that you're running cmake in the same directory as the source. I think I tried that once accidentally, and it didn't work.  Make a build directory in the openenclave directory, cd into this new build directory, and then run `cmake -DUSE_LIBSGX=OFF ..`

That might resolve your build issue! (maybe 🤞)

**Comment by johnkord** [comment]
By the way @deeglaze, which scenario interests you more from these two? :
1. Utilizing the OE SDK for building enclave images for use in an application
2. Building the OE SDK from the OE source

If you want scenario #1, you can follow the link from Andy's comment above.
If you want scenario #2, you will need some prerequisites and you can follow the instructions here: https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/building_oe_sdk.md . You probably want the link on this page "Setup Open Enclave SDK for SGX1 mode"

**Comment by deeglaze** [comment]
That worked, thanks! I did get a few failed tests in simulation mode. Are these expected currently?

The following tests did not run:
	  6 - tests/aesm (Skipped)
	 85 - tests/debug-unsigned (Skipped)
	 86 - tests/debug-signed (Skipped)
	 87 - tests/nodebug-signed (Skipped)
	 88 - tests/nodebug-unsigned (Skipped)
	 98 - tests/sealKey (Skipped)
	104 - tests/fs2 (Skipped)
	115 - tests/VectorException (Skipped)
	188 - tests/qeidentity (Skipped)
	189 - tests/report (Skipped)
	190 - tests/report_attestation_without_enclave (Skipped)
	191 - tests/attestation_cert_api (Skipped)
	192 - tests/tls_e2e (Skipped)

The following tests FAILED:
	  7 - oegdb-test (Failed)
	  8 - oegdb-test-simulation-mode (Failed)
	107 - tests/ids (Child aborted)
	194 - samples (Failed)
Errors while running CTest

**Comment by johnkord** [comment]
Interesting @deeglaze! I just ran the `OE_SIMULATION=1 ctest` command and got a full set of test passes on my system, and our CI & nightly builds seem to be passing simulation tests (Linux, at least).

```
        Start 194: samples
194/194 Test #194: samples .....................................................................................................................................   Passed   16.49 sec

100% tests passed, 0 tests failed out of 194

Total Test time (real) = 178.79 sec

The following tests did not run:
          6 - tests/aesm (Skipped)
         82 - tests/attestation_cert_api (Skipped)
         84 - tests/bigmalloc (Skipped)
         86 - tests/debug-unsigned (Skipped)
         87 - tests/debug-signed (Skipped)
         88 - tests/nodebug-signed (Skipped)
         89 - tests/nodebug-unsigned (Skipped)
         97 - tests/qeidentity (Skipped)
         98 - tests/report (Skipped)
         99 - tests/report_attestation_without_enclave (Skipped)
        102 - tests/sealKey (Skipped)
        108 - tests/fs2 (Skipped)
        119 - tests/VectorException (Skipped)
        192 - tests/tls_e2e (Skipped)
```

A few questions for you:
What Linux distro are you running?
Can you re-run the simulation ctest command with the "-V" flag and send the output? That should give all stdout/stderr during the tests, and may help us diagnose why those 4 tests failed!

**Comment by deeglaze** [comment]
I'm running my employer's internal distro it uses for employees, which I believe is based on Ubuntu.

The output is close to 1mb, so here it's on drive.
https://drive.google.com/file/d/1p4lsodxOPX9EkFKpqsCQjvnbqJhM8M5k/view?usp=sharing

**Comment by johnkord** [comment]
Thanks for the quick info @deeglaze!

Here's my quick analysis of the test errors:

1.The  oegdb-test & oegdb-test-simulation-mode test failures look to be associated with python 2/3 differences. I believe the gdb we tend to use internally uses python 3 for its extensions (as oegdb is just a python extension for gdb), but your system's gdb may be using python 2.  Python 3 has the `from_bytes` function defined, and I don't think python 2 does (since the bytes type I believe is a python 3 data type, IIRC)
```
7: Breakpoint 1, main (argc=2, argv=0x7fffffffda28) at /usr/local/google/home/dionnaglaze/gitrepos/openenclave/tests/debugger/oegdb/host/host.c:19
7: 19	    oe_enclave_t* enclave1 = NULL;
7: ** Hit breakpoint in main** enclave = enc/oe_gdb_test_enc
7: Python Exception <type 'exceptions.AttributeError'> type object 'int' has no attribute 'from_bytes': 
```

2. The tests/ids test fails, and I'm not sure why yet. Specifically the `getgroups` function is behaving oddly in a simulated enclave. Unfortunately our simple test framework just tells us if a test fails and doesn't give us more information as to what the values were when they failed (we should improve this!). Let me follow up next week on this one (woohoo, labor day)!

```
        Start 107: tests/ids

107: Test command: /usr/local/google/home/dionnaglaze/gitrepos/openenclave/trybuild/tests/syscall/ids/host/ids_host "/usr/local/google/home/dionnaglaze/gitrepos/openenclave/trybuild/tests/syscall/ids/enc/ids_enc"
107: Test timeout computed to be: 1500
107: Test failed: /usr/local/google/home/dionnaglaze/gitrepos/openenclave/tests/syscall/ids/enc/enc.c(37): test_ids getgroups((int)num_groups, list) == (int)num_groups
```

3. The samples test fails because I think it's trying to use the `c++` compiler with the -mllvm flag, expecting it to be `clang++-7`. I'd suggest setting:
```bash
export CXX=clang++-7
```

Here's the error:
```
194: -- Samples test 'file-encryptor' in simulation with CMake running...
194: [ 33%] Built target file-encryptor_host
194: [ 41%] Building CXX object enclave/CMakeFiles/enclave.dir/ecalls.cpp.o
194: c++: error: unrecognized command line option ‘-mllvm’
```

**Comment by yakman2020** [comment]
@deeglaze  Is this still an issue?

**Comment by deeglaze** [comment]
Nope! :D thanks for your assistance.
