### ISSUE TITLE
Regression tests are failing in linux with USE_LIBSGX=OFF

### ISSUE THREAD

**Issue by jazzybluesea** [openenclave/openenclave#2137]

**Comment by yakman2020** [comment]
More info please

**Comment by jazzybluesea** [comment]
> More info please

In an ACCVM compile the source code with USE_LIBSGX=OFF.
mkdir build
cd build
cmake -G "Unix Makefiles" -DUSE_LIBSGX=OFF ..
make

**Comment by radhikaj** [comment]
@jazzybluesea It is expected that attestation would fail at this time with USE_LIBSGX=OFF. Is this what you are seeing? Could you please try it and update this issue?

**Comment by jazzybluesea** [comment]
The original problem was with USE_LIBSGX=OFF in a system that supports FLC.  After PR #2250,  all tests are passing with HAS_QUOTE_PROVIDER=ON and HAS_QUOTE_PROVIDER=OFF.  So I think the original problem no longer applies.
