### ISSUE TITLE
Logging format

### ISSUE THREAD

**Issue by olgavrou** [openenclave/openenclave#2147]
Hi!

In trying to make use of the logs (e.g. via uploading them to Azure Log Analytics) it is nice to be able to parse and display all of the available logs including the ones generated by OE.

I have played around with the formatting of the OE logs a bit and without too much code modification would like to propose the below changes to the logging

(1) User defined format

It would be very useful for users to be able to define their own format given the log line info. I propose doing this when logging to a user specified file via the existing `OE_LOG_DEVICE` environmental variable.

If the var is not specified then logging goes on as usual.

If the var is specified then we look for an extra environmental variable `OE_LOG_FORMAT`.

If `OE_LOG_FORMAT` is specified we call a method where we pass in the log line information and it is formatted by the `OE_LOG_FORMAT` string. If it is not then we use the default format string to log in the file.

When logging to a separate file we can decide if we want to keep the normal logs directed to stdout AND log with the user specified format to the file. This is useful if you want to keep the human readable logs, but also redirect a machine-readable format (e.g. JSON) to a file. The other option would be to turn off stdout logging when we redirect logs to a user defined file, as is done now.

Here is an example of the logs in json format defined by setting `export OE_LOG_FORMAT="{\"e_ts\":\"%s.%06ldZ\",\"level\":\"(%s)%s\",\"tid\":\"tid(0x%lx)\",\"msg\":\"%s\",\"file\":\"%s\",\"func\":\"%s\",\"number\":\"%s\"}"`

{
  "e_ts": "2019-09-04T13:24:17.562606Z",
  "level": "(E)ERROR",
  "tid": "tid(0x7efdeaffd700)",
  "msg": "switchless_enc:log message",
  "file": "../tests/switchless/enc/enc.c",
  "func": "enc_echo",
  "number": "57"
}

(2) OE logging format

I took the liberty of playing around with the OE logging format and brought it to this:

`2019-09-04T13:52:51.868071Z [(E)ERROR] tid(0x7eff067fc700) switchless_enc:log message [../tests/switchless/enc/enc.c:enc_echo:57]`

so `timestamp [(E|H)log_level] thread_id log_message [file:function:line]`

where timestamp is ISO 8601 UTC. This is not strictly needed for this issue but it would be nice to have at least the full timestamp.

I have made some code modifications so if there are no objections to this I could open a PR so that we can discuss further in detail.

Thanks!

**Comment by andschwa** [comment]
Thanks @olgavrou! This looks like a great idea to me, let me loop in @johnkord and @mikbras.

**Comment by andschwa** [comment]
Yay! We finally addressed this is today's PR. People are in agreement with making the logging format configurable (but are wary of changing the default logging format). Please do open a PR!

**Comment by yakman2020** [comment]
Pls issue a PR. It looks like a reasonable idea.
