### ISSUE TITLE
Compiling sdk on other Linux distributions

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2148]
Is there a particular reason this project is listed as supported on only Ubuntu 16.04/18.04 and not other Linux distributions (in the build instructions)? For example, I just built and ran tests and samples in simulation mode on Fedora 29 and it seems to work mostly out of the box.

If there is no technical reason, I am happy to add documentation with instructions on building on Fedora (mostly just which packages need to be installed).

**Comment by dthaler** [comment]
I think there's two possible categories of platforms:
a) "Supported" platforms, where "supported" includes the fact that CI runs tests on every PR to try to prevent regressions.
b) "It might work" platforms, where someone tried it once and got it working, but there's nothing to automatically verify that it will still work after new PRs get merged.

Sounds like you have anecdotal data saying Fedora is now in category (b), whereas Ubuntu is in category (a) at present.

**Comment by jhand2** [comment]
I see. In that case I don't think it makes sense to add build documentation since it is not yet an officially supported distro (in CI, promise not to break).

Thanks!
