### ISSUE TITLE
SGX-LKL-PORT: conflict with definition of __cxa_atexit

### ISSUE THREAD

**Issue by prp** [openenclave/openenclave#2151]
`liboecore` exports `__cxa_atexit`, which is needed for OE's C++ support. This symbol, however, conflicts with the implementation in SGX-LKL. SGX-LKL cannot use the OE version of `__cxa_atexit` because it needs an implementation that handles the `vdso` argument correctly.

Ideally, the OE implementation of `__cxa_atexit` should be internal/part of the C++ support only.

**Comment by mikbras** [comment]
PR #2164 addresses this issue.

**Comment by wintersteiger** [comment]
PR #2164 was abandoned because it was redundant. Did that also fix this problem?

**Comment by jhand2** [comment]
This is fixed by https://github.com/openenclave/openenclave/pull/2562

Thanks!
