### ISSUE TITLE
Standardize thread routine signature across Windows and Linux

### ISSUE THREAD

**Issue by jxyang** [openenclave/openenclave#2162]
The Linux `pthread_create` and Windows `CreateThread` functions expect the function pointer to have different signatures. This causes type mismatch with the newly added `oe_thread_create`, which aims to launch threads on both platforms.

@mikbras Suggested the following:

> My point is that we need a single thread routine signature:
> typedef void (*oe_thread_proc_t)(void* arg);
> On both Linux and Windows we need a static wrapper thread routine that calls this function. In this way the thread routine passed in the Linux and Windows case will be appropriate for the platform.

**Comment by johnkord** [comment]
We'll go with a POSIX approach, but on Windows we'll use a TLS/thread-specific-data variable.

**Comment by jhand2** [comment]
@jxyang is this closed by #2125?

**Comment by radhikaj** [comment]
Closing this issue after discussing with @jxyang
