### ISSUE TITLE
Inconsistent process for determining PR assignees

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#2168]
GovernanceModel.md explains:

> We define "maintainer" as members of the Open Enclave "Community Maintenance                                            Committee", as listed in the [maintainers document](Maintainers.md). A                                                  "committer" is anyone with direct write access to the Open Enclave repository on                                        GitHub, as granted by the Committee. All maintainers are committers, but not all                                        committers are maintainers.

Maintainers.md says regarding maintainers:

> maintainers are committers that are trusted to grant new committer rights

and regarding committers:

> The area column describes which technical areas each committer is most interested in, and                              therefore should usually be consulted for changes relating to that area.  However, it is up to each committer to determine who should review which PR, and when to merge it. Remember that a PR must not be merged if a committer objects; instead, it should be brought up with the Community Maintenance Committee.

Contributing.md on the other hand says:

> **DO** submit all code changes via pull requests (PRs) rather than through a                                            direct commit. PRs will be reviewed and potentially merged by the repo                                                  **maintainers** after a peer review that includes at least one **maintainer**.

Note the requirement about maintainers being here but not mentioned in the maintainer responsibilities on other pages.

> - **DO** tag any users that should know about and/or review the change.

The above does not say how to determine who that should be.  (The Maintainers.md page implies it should be all committers with an area related to the PR, but this isn't clear.)

and

> When a PR is ready to be merged, a maintainer will comment on it with `bors r+`.

So the above says that only maintainers (not committers in general) can merge PRs, which seems to contradict the other pages.

It would also streamline the process if we had git groups per area so one didn't need to look up the current list of relevant committers, one could just pick "security-committers" and/or "build-committers" or whatever other relevant groups exist.

**Comment by dthaler** [comment]
It's also unclear whose responsibility it is to follow the "DO tag any users that should know about and/or review the change."   Is every contributor expected to know this (seems hard for new contributors)?  Is every committer responsible for reviewing the set of assignees?

**Comment by andschwa** [comment]
Yeah that's exactly what happened.

**Comment by andschwa** [comment]
I think we've actually resolved this between #2173 and #2166. The wording is now correct, and auto review tagging is happening.

**Comment by dthaler** [comment]
Contributing.md still says 'DO tag any users that should know about and/or review the change."
If auto-review tagging is sufficient, then this DO can go away.
If it is not sufficient, then this DO is still insufficient in terms of being actionable.

**Comment by dthaler** [comment]
I see you're updating the wording of that in PR #2190

**Comment by andschwa** [comment]
Closing, let me know if it’s insufficient.
