### ISSUE TITLE
Release process is unclear

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#2169]
Releasing.md says:

> We want to release `v0.7.0` in about a week, so we choose a release manager from                                        the committers.

Who is the "we"?  Is it the Community Maintenance Committee?

How is the choice made?

Why is "release" not one of the areas of responsibility on the Maintainers.md page?

**Comment by johnkord** [comment]
As for the term "we" in the example context, I think it would be a consensus of committers. Should this be the CMC's role? What do you all think?

The choice of release manager was previously made by our manager. In the future, I imagine someone can use our automated build job in Jenkins to produce the bits, then propose for a vote from the committers on the produced bits, and if the vote passes, publish a new tag & then release to the GitHub release page. We should probably sort that out.  As for what gets merged to a given release branch, how should we handle this? I genuinely am not sure.

By the way, we're working on making the build as fully reproducible as possible (with @yakman2020 's efforts) , so each committer should one day be able to reproduce the exact bits of a release themselves, but we're not there yet.

**Comment by andschwa** [comment]
Definitely it's left to the committers. The whole committer group is primarily responsible for the technical direction of the project (which includes releases, in my opinion). It should not be on the CMC. The CMC exists primarily to resolve disputes among the committers.

**Comment by johnkord** [comment]
I will add an item for the next CGC meeting to discuss this.

**Comment by dthaler** [comment]
Done in commit bd84ad93b75a9898b69683e06180705c31451d04
