### ISSUE TITLE
Add support for Intel's DCAP client and document support 

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#2177]
As of now, the getting instructions speak of Azure DCAP Client. This is because Intel's DCAP client is not tested. 
Please test and update instructions and pre-install scripts.

Intel's DCAP client should be default and documented as such in Getting Started.

**Comment by yentsanglee** [comment]
Tasked.

**Comment by jhand2** [comment]
@yentsanglee On issues where someone is actively working on it can you asign that person here?

**Comment by yufjiang** [comment]
Intel DCAP client was supported and the document was added. Please see the document at https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/NonAccMachineSGXLinuxGettingStarted.md

**Comment by yentsanglee** [comment]
Issue is resolved.
