### ISSUE TITLE
install-windows-prereqs.ps1 hangs during server set up

### ISSUE THREAD

**Issue by BRMcLaren** [openenclave/openenclave#2199]
During Windows server set up, the prereq script gets stuck while installing LLVM

```
Installing C:\Users\brmclare\AppData\Local\Temp\2\packages\LLVM-win64.exe with
-ArgumentList:
/S
-FilePath:
C:\Users\brmclare\AppData\Local\Temp\2\packages\LLVM-win64.exe
-PassThru:
True
-Wait:
True```

This has happened in both ACC deployments as well as MSR deployments. While this is reproducible automatically with

```.\LLVM-7.0.1-win64.exe -ArgumentList "/S"
.\install-windows-prereqs.ps1  -InstallPath /drives/c/openenclave -LaunchConfiguration SGX1 -DCAPClientType None```

On both ACC and MSR windows servers, it is not reproducible with a manual installation.

It can be resolved by terminating the task but will pose an issue with the automated build environment set up process.

Assigning to myself and adding to the backlog for the time being.

**Comment by jazzybluesea** [comment]
I am also getting hang during installation:

PS C:\Users\sewong\Sources\jazzybluesea\openenclave\scripts>  .\install-windows-prereqs.ps1 -InstallPath C:\nugetpkg -La
unchConfiguration SGX1FLC -DCAPClientType Azure
**** Installing PSW 2.4 ****
Downloading all the packages to local directory: C:\Users\sewong\AppData\Local\Temp\2\packages


    Directory: C:\Users\sewong\AppData\Local\Temp\2


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        10/7/2019   5:55 PM                packages
Downloading: https://shellcheck.storage.googleapis.com/shellcheck-v0.7.0.zip
[2019-10-07T17:55:44.2335128+00:00] Start-ExecuteWithRetry attempt 0
[2019-10-07T17:55:44.7837033+00:00] Start-ExecuteWithRetry terminated
Computed hash (@{Algorithm=SHA256; Hash=02CFA14220C8154BB7C97909E80E74D3A7FE2CBB7D80AC32ADCAC7988A95E387; Path=C:\Users\sewong\AppData\Local\Temp\2\packages\shellcheck.zip}) matches expected hash (02CFA14220C8154BB7C97909E80E74D3A7FE2CBB7D80AC32ADCAC7988A95E387)
Downloading: https://aka.ms/vs/15/release/vs_buildtools.exe
[2019-10-07T17:55:44.8618598+00:00] Start-ExecuteWithRetry attempt 0
[2019-10-07T17:55:45.0805814+00:00] Start-ExecuteWithRetry terminated
Downloading: https://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe
[2019-10-07T17:55:45.0805814+00:00] Start-ExecuteWithRetry attempt 0
[2019-10-07T17:55:45.1899838+00:00] Start-ExecuteWithRetry terminated
Computed hash (@{Algorithm=SHA256; Hash=681BE3E5BA9FD3DA02C09D7E565ADFA078640ED66A0D58583EFAD2C1E3CC4064; Path=C:\Users\sewong\AppData\Local\Temp\2\packages\vcredist_x64.exe}) matches expected hash (681BE3E5BA9FD3DA02C09D7E565ADFA078640ED66A0D58583EFAD2C1E3CC4064)
Downloading: https://www.ocamlpro.com/pub/ocpwin/ocpwin-builds/ocpwin64/20160113/ocpwin64-20160113-4.02.1+ocp1-mingw64.zip
[2019-10-07T17:55:45.2681363+00:00] Start-ExecuteWithRetry attempt 0

**Comment by jazzybluesea** [comment]
I ran it again and it's failing to install vs_buildtools.exe.

Failed to install: C:\Users\sewong\AppData\Local\Temp\2\packages\vs_buildtools.exe
at Install-Tool, C:\Users\sewong\Sources\jazzybluesea\openenclave\scripts\install-windows-prereqs.ps1: line 292
at Install-VisualStudio, C:\Users\sewong\Sources\jazzybluesea\openenclave\scripts\install-windows-prereqs.ps1: line 426
at <ScriptBlock>, C:\Users\sewong\Sources\jazzybluesea\openenclave\scripts\install-windows-prereqs.ps1: line 649
at <ScriptBlock>, <No file>: line 1
