### ISSUE TITLE
[ERROR]sgxquoteprovider: sgx_ql_set_logging_function not found

### ISSUE THREAD

**Issue by santoshx** [openenclave/openenclave#2201]
USERx2@VMs-Demo:~/openenclave/samples/remote_attestation$ make run
host/attestation_host ./enclave_a/enclave_a.signed ./enclave_b/enclave_b.signed
Host: Creating two enclaves
Host: Enclave library ./enclave_a/enclave_a.signed
Enclave: ***../common/crypto.cpp(76): mbedtls initialized.
Host: Enclave successfully created.
Host: Enclave library ./enclave_b/enclave_b.signed
Enclave: ***../common/crypto.cpp(76): mbedtls initialized.
Host: Enclave successfully created.
Host: requesting a remote report and the encryption key from 1st enclave
Enclave: ***ecalls.cpp(43): enter get_remote_report_with_pubkey
Enclave: ***../common/dispatcher.cpp(96): get_remote_report_with_pubkey
00:53:25:304937 tid(0x7fa7f8968540) (H)[ERROR]sgxquoteprovider: sgx_ql_set_logging_function not found

**Comment by santoshx** [comment]
No symbol "sgx_ql_set_logging_function" found in Intel sgx sdk (github.com:intel/linux-sgx).

**Comment by prp** [comment]
@santoshx Did you install the az-dcap-client library?

```
echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main" | sudo tee /etc/apt/sources.list.d/msprod.list
wget -qO - https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

sudo apt -y install az-dcap-client
```

**Comment by santoshx** [comment]
@prp 
I get the same error even after installing az-dcap-client library.

$ dpkg -l az-dcap-client | grep az-dcap
ii  az-dcap-client 1.1          amd64        Intel(R) SGX DCAP plugin for Azure Integration

**Comment by prp** [comment]
@santoshx Did you try updating the linker invocation? I think that library provides that missing symbol, no?

**Comment by santoshx** [comment]
@prp It worked after I switched to newer driver kernel module 'intel_sgx' from 'isgx'.
