### ISSUE TITLE
Samples: Change function params of type size_t to unsigned int

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#2212]
Certain function params which are of type size_t in samples need to be explicitly cast to unsigned int. This is because the crypto libraries expect the param to be of type unsigned int. Changing the params to unsigned int in the edl will get rid of the need to cast the params from size_t to unsigned int.. See PR #2204

**Comment by radhikaj** [comment]
It is fine to cast as long as we check that it is safe to cast (check < max_unsigned_int). 
Check that all places where it is being cast are performing this check.

**Comment by radhikaj** [comment]
@ryanhsu19 will look into it.

**Comment by ryanhsu19** [comment]
After discussion with Jordan, the unsigned int cast check on variables not of type size_t was deemed redundant so I have reverted the commit. As for the other variables having type size_t (see samples/data-sealing/common/dispatcher.cpp) there is already a check before each of them. Therefore, it is done.

**Comment by jhand2** [comment]
ah, I understand now 😄 

For the future, it is good to link the issue in the PR (you can just include the issue number with a pound sign - #2212 in this case - in a comment). Then when reviewers are looking at your change it is easier to understand what the PR is trying to accomplish and they can refer to any discussion in the issue comments.

**Comment by ryanhsu19** [comment]
Hi Jordan,

Got it. I will do it next time 😊

Ryan

**Comment by ryanhsu19** [comment]
As discussed with Radhika, if there is no further problem with this issue, I will close this issue shortly.
