### ISSUE TITLE
API docs are too hard to find

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#2214]
Currently they're hidden in the obscure "Versions" link at openenclave.io

There's nothing about docs, or APIs, or anything else that one would be looking for to find API docs.   And the main GitHub/openenclave readme docs just point to openenclave.io.

**Comment by radhikaj** [comment]
Please suggest what we should use instead of "Versions" on openenclave.io. Would "API Versions" be better?

**Comment by dthaler** [comment]
How about "API Documentation"

**Comment by radhikaj** [comment]
https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/APIs_and_Libs.md has a pointer to the docs. Would you like it to be on the README on github.com/openenclave/openenclave?

**Comment by dthaler** [comment]
No preference on that question.  It's currently reachable via this path starting from https://github.com/openenclave/openenclave:
* Click on either "Ubuntu 18.04 with SGX hardware" or "Ubuntu 16.04 with SGX hardware"
* Scroll to the bottom and click on "Using the Open Enclave SDK"
* Scroll to the bottom and click on "Please look here." under APIs and Supported Libraries

Issues:
* The ARM TrustZone getting started page, reachable from the main readme, does not seem to have any corresponding link to the APIs page
* Having the word "here" be clickable is considered poor form for web page design

So either making the API docs link be in a common location, such as on the README, or else making it be consistently discoverable across all more specific pages, would in my opinion suffice in addition to fixing the label on the openenclave.io site.

**Comment by radhikaj** [comment]
Promote API docs to README. 
Open a new issue to ensure that each API's doxygen annotation is corrected to reflect that its support on trustzone.
C/C++ APIs tables should also be fixed to speak of support on Trustzone.
__oe_sgx_set_minimum_crl_tcb_issue_date is not public but shows up in public API documentation
https://github.com/openenclave/openenclave/blob/master/docs/DevelopmentGuide.md should be updated to say how APIs should be documented correctly.

**Comment by radhikaj** [comment]
Versions on openenclave.io has been renamed to "API Documentation"
README.md contains a link to API docs.
Closing this issue. Other issues arising from the discussions around this issue have been filed.
