### ISSUE TITLE
Add @experimental doxygen custom tag

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#2216]
@CodeMonkeyLeet wrote:
> We probably need additional guidance as to how to clearly reflect that an API or header is "experimental" in doxygen. AFAIK, there's no @experimental property in doxygen for example, so we'll need to set guidelines.

@experimental can be done in doxyger after putting into Doxyfile the following:
```
ALIASES                += experimental="\xrefitem experimental \"This feature is marked as experimental\" \"Experimental List\"\n"
ALIASES                += experimental{1}="\xrefitem experimental \"Experimental\" \"Experimental List\" \1\n"
```
This uses the custom tags mechanism explained in the stackoverflow thread: https://stackoverflow.com/questions/537043/custom-tags-with-doxygen

Example use of @experimental in another GitHub project: https://github.com/blynkkk/blynk-library/commit/579545d1662c6285dc14cb145ce77b36ee9573fa

**Comment by radhikaj** [comment]
We are in agreement with this suggestion.

**Comment by andschwa** [comment]
I don't know why this didn't auto-close.
