### ISSUE TITLE
Investigate why we are implementing padding in the data-sealing sample.

### ISSUE THREAD

**Issue by johnkord** [openenclave/openenclave#2219]
As per @CodeMonkeyLeet 's comments in PR #2204, "It seems like that should have been a part of the encipherment process rather than something the app does."

**Comment by gupta-ak** [comment]
I think it's because the aes mbedtls module doesn't add padding in automatically. You need to use the cipher module and set the encryption mode to AES and the padding mode to PKCS7

**Comment by radhikaj** [comment]
@ryanhsu19 will look into this.

**Comment by ryanhsu19** [comment]
I agree with Akash. Also for the memset part mentioned in PR #2204, it seems from the library files that, while a padding length of characters must be filled for the PKCS7 case, it does not mention which characters to fill (unlike other padding cases). I try changing the 2nd argument from (int)padded_byte_count to 0 and it does not affect the whole testing either.
