### ISSUE TITLE
Not able to sign CLA with the link provided

### ISSUE THREAD

**Issue by tehsiuhuang** [openenclave/openenclave#2235]
https://cla-assistant.io/openenclave/openenclave?pullRequest=2233

Following is the detail error mg:

Error
There is no CLA to sign for openenclave/openenclave

(<!DOCTYPE html>     <html class="no-js" lang="en-US">  <head> <meta http-equiv="refresh" content="0"> <title>cla-assistant.io | 524: A timeout occurred</title> <meta charset="UTF-8" /> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" /> <meta name="robots" content="noindex, nofollow" /> <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" /> <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />  <style type="text/css">body{margin:0;padding:0}</style> </head> <body> <div id="cf-wrapper"> <div id="cf-error-details" class="cf-error-details-wrapper"> <div class="cf-wrapper cf-error-overview"> <h1> <span class="cf-error-type">Error</span> <span class="cf-error-code">524</span> <small class="heading-ray-id">Ray ID: 52094c00ff207965 &bull; 2019-10-04 18:44:18 UTC</small> </h1> <h2 class="cf-subheadline">A timeout occurred</h2> </div> <div class="cf-section cf-highlight cf-status-display"> <div class="cf-wrapper"> <div class="cf-columns cols-3"> <div id="cf-browser-status" class="cf-column cf-status-item cf-browser-status "> <div class="cf-icon-error-container"> <i class="cf-icon cf-icon-browser"></i> <i class="cf-icon-status cf-icon-ok"></i> </div> <span class="cf-status-desc">You</span> <h3 class="cf-status-name">Browser</h3> <span class="cf-status-label">Working</span> </div> <div id="cf-cloudflare-status" class="cf-column cf-status-item cf-cloudflare-status "> <div class="cf-icon-error-container"> <i class="cf-icon cf-icon-cloud"></i> <i class="cf-icon-status cf-icon-ok"></i> </div> <span class="cf-status-desc">Seattle</span> <h3 class="cf-status-name">Cloudflare</h3> <span class="cf-status-label">Working</span> </div> <div id="cf-host-status" class="cf-column cf-status-item cf-host-status cf-error-source"> <div class="cf-icon-error-container"> <i class="cf-icon cf-icon-server"></i> <i class="cf-icon-status cf-icon-error"></i> </div> <span class="cf-status-desc">cla-assistant.io</span> <h3 class="cf-status-name">Host</h3> <span class="cf-status-label">Error</span> </div> </div> </div> </div> <div class="cf-section cf-wrapper"> <div class="cf-columns two"> <div class="cf-column"> <h2>What happened?</h2> <p>The origin web server timed out responding to this request.</p> </div> <div class="cf-column"> <h2>What can I do?</h2> <h5>If you're a visitor of this website:</h5> <p>Please try again in a few minutes.</p> <h5>If you're the owner of this website:</h5> <p><span>The connection to the origin web server was made, but the origin web server timed out before responding. The likely cause is an overloaded background task, database or application, stressing the resources on your web server. To resolve, please work with your hosting provider or web development team to free up resources for your database or overloaded application.</span> <a href="https://support.cloudflare.com/hc/en-us/articles/200171926-Error-524">Additional troubleshooting information here.</a></p> </div> </div> </div> <div class="cf-error-footer cf-wrapper"> <p> <span class="cf-footer-item">Cloudflare Ray ID: <strong>52094c00ff207965</strong></span> <span class="cf-footer-separator">&bull;</span> <span class="cf-footer-item"><span>Your IP</span>: 2001:4898:80e8:2:bd4a:4957:fb81:5b6a</span> <span class="cf-footer-separator">&bull;</span> <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span> </p> </div> </div> </div> </body> </html> )

**Comment by andschwa** [comment]
@CodeMonkeyLeet I am going to close this now as we're replacing CLA with DCO.
