### ISSUE TITLE
Windows get started doc errors

### ISSUE THREAD

**Issue by jxyang** [openenclave/openenclave#2240]
On the Windows get started docs [1](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsSGX1FLCGettingStarted.md) and [2](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsSGX1GettingStarted.md), we state:
```
As an example, if you cloned Open Enclave SDK repo into C:\openenclave, you would run the following:

cd scripts
.\install-windows-prereqs.ps1 -InstallPath C:\path\to\where\you\would\like\to\install\intel_and_dcap_nuget_packages -LaunchConfiguration SGX1 -DCAPClientType None
```

Shouldn't we replace `C:\path\to\where\you\would\like\to\install\intel_and_dcap_nuget_packages` with `c:\openenclave\prereqs`?

**Comment by jxyang** [comment]
It is probably worth mentioning the above command needs to be run from a administrator Power Shell prompt.

**Comment by radhikaj** [comment]
Fixed this in https://github.com/openenclave/openenclave/pull/2273
