### ISSUE TITLE
Windows 10 Update pushed down PSW2.5 breaking Windows 10 client systems with SGX1 support

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#2241]
Client systems running Windows 10 Update got an update which installed Intel PSW 2.5 on their systems.  Open Enclave SDK is only compatible with Intel PSW 2.2 for SGX1 hardware.Windows Client systems usually do not run on SGX1+FLC enabled hardware. They generally only run on SGX1 hardware. 

Currently, The Open Enclave SDK is supported on the following Windows configurations:
Windows Server 2016 on SGX1 systems. This is with PSW 2.2
Windows Server 2016 on SGX1 with FLC systems.  This is with PSW 2.4 or PSW 2.5

In the short term, we will fix the docs to remove Windows 10  from supported Operating Systems. 

See a related issue #1810. A long term fix is to ensure that the SDK can operate with PSW 2.4 or higher on SGX1 hardware.

**Comment by dthaler** [comment]
Is there a way to downgrade PSW on windows 10 back to version 2.2?

**Comment by radhikaj** [comment]
> Is there a way to downgrade PSW on windows 10 back to version 2.2?

No Dave, there is not one that we have found.

**Comment by radhikaj** [comment]
Closed by "Consolidate SGX1 and SGX1FLC flows #2258"
