### ISSUE TITLE
Allow building only hostverify library and with minimal build dependencies

### ISSUE THREAD

**Issue by letmaik** [openenclave/openenclave#2263]
OE provides roughly two parts: a) multiple libraries to develop and manage enclaves (target: platform that runs enclaves), and b) the hostverify library to ensure secure communication with remote enclaves (target: any platform, e.g. lightweight clients without enclave support).

Building clients that use the hostverify library currently is unnecessarily complicated. In many cases the provided Ubuntu packages are not enough, either because a different distribution needs to be supported or because there are policies to build all dependencies from source. Building from source is hard because OE's CMake scripts don't allow to build *only* the hostverify library and hence many unneeded build dependencies are required, including Intel's SGX libraries and an up-to-date version of the OCaml compiler.

IMO easily building the hostverify library from source should have first-class support.

**Comment by johnkord** [comment]
Completely agree with this. We should offer a simple interface for building only the hostverify library, and to make sure it doesn't link to any unnecessary libraries.

Thanks for filing this issue @letmaik !

**Comment by dthaler** [comment]
+1.  For libraries designed to run on non-TEE platforms, we should also provide a way for developers who want to just consume them in binary form, rather than requiring compiling them at all.

**Comment by letmaik** [comment]
What's the progress on this?

**Comment by ryanhsu19** [comment]
> What's the progress on this?

I will come back to work on this issue as long as other hostverify-library-related issues are done.

**Comment by soccerGB** [comment]
@letmaik 
Are you looking for an easy way to build host verifier package?
Here is what we have currently:
cpack -G DEB -D CPACK_DEB_COMPONENT_INSTALL=ON  -D CPACK_COMPONENTS_ALL=OEHOSTVERIFY

or you are asking for above package building process more efficient?

**Comment by letmaik** [comment]
@soccerGB I'd like to build the host verifier library, not as package. And I need to build without any Intel SGX library dependencies available. The use case is to build redistributable Python binary wheels (which means manylinux wheels, building on CentOS) which make use of the host verifier library.

**Comment by achamayou** [comment]
@letmaik are you making a Python library for quote verification? Is it going to be on pypi? Can we steal it/help with it? :)

**Comment by letmaik** [comment]
@achamayou It's not standalone yet but I guess it could be. Ideally I'd like a pure-Python library but looks like this is not happening any time soon.

**Comment by letmaik** [comment]
What's the progress on this?

**Comment by ryanhsu19** [comment]
@letmaik Testing my work on Windows builds now (fine on Linux builds). After it is done I'll soon open a PR for everyone to review it. Then you will be able to use cmake and cpack to build desired minimal hostverify library without further modifications to the files installed by the library.

**Comment by letmaik** [comment]
@ryanhsu19 Can you re-open this? PR #3193 is not the full solution.

**Comment by ryanhsu19** [comment]
I don't think I can re-open an issue not created by myself. Let me ask others in the team to do so.

**Comment by dthaler** [comment]
Reopening per @letmaik's request

**Comment by yentsanglee** [comment]
> @ryanhsu19 Can you re-open this? PR #3193 is not the full solution.

@letmaik  What's missing? Can you explain?

**Comment by ryanhsu19** [comment]
@yentsanglee I think it is due to the part where `oehost` could not be fully separated.

**Comment by letmaik** [comment]
As long as https://github.com/openenclave/openenclave/pull/3123 is still open, this issue has to be open.
