### ISSUE TITLE
oesign is dynamically linked to sgx_enclave_common and other libs

### ISSUE THREAD

**Issue by johnkord** [openenclave/openenclave#2264]
oesign shouldn't need any of the symbols in sgx_enclave_common or other Intel libraries, so it shouldn't be dynamically linked against them

oesign being dynamically linked to some sgx_* libraries causes an issue on Windows, because the Intel SGX PSW cannot be installed on systems without SGX, and those libraries are provided by the Intel SGX PSW, but oesign.exe requires them to run. It is therefore impossible to use oesign.exe on a Windows system without SGX support without manually copying the sgx_* libraries from another system onto it.  (And because oesign.exe is used during the normal build of the Open Enclave SDK, one cannot build the Open Enclave SDK from source in this situation too)

**Comment by radhikaj** [comment]
Lets target v0.9 for this.

**Comment by jxyang** [comment]
Likewise, `oehostverify` should not depend on `sgx_enclave_common` either. We have customers simply want to verify the quote on a non-SGX machine.

**Comment by radhikaj** [comment]
> Likewise, `oehostverify` should not depend on `sgx_enclave_common` either. We have customers simply want to verify the quote on a non-SGX machine.

@jxyang please open a new issue for that.
