### ISSUE TITLE
tests/samples fail on Windows

### ISSUE THREAD

**Issue by jxyang** [openenclave/openenclave#2282]
Running `ctest` after build on Windows, all tests are passing except for `samples`, with the following error message:
```
CMake Error: The source directory "C:/openenclave/build/C:/openenclave/share/openenclave/samples/helloworld" does not exist.
```

I believe that's because the command we use to test samples is as follows:
```
cmake.exe" "-DHAS_QUOTE_PROVIDER=ON" "-DSOURCE_DIR=C:/openenclave/samples" "-DBUILD_DIR=C:/openenclave/build" "-DPREFIX_DIR=C:/openenclave" "-DNUGET_PACKAGE_PATH=c:\prereqs\nuget" "-P" "C:/openenclave/samples/test-samples.cmake"
```
And in `test-samples.cmake`, we concatenate `BUILD_DIR` and `PREFIX_DIR` to generate `INSTALL_DIR`, resulting in the illegal path `C:/openenclave/build/C:/openenclave/...`

This is not an issue on CI machines because the build script there somehow sets `PREFIX_DIR` to a relative path.

**Comment by BRMcLaren** [comment]
@jxyang 

This was fixed a while ago. Have you had any reoccurrences?

**Comment by jhand2** [comment]
@BRMcLaren Can you point to where this was fixed. I am seeing this locally but not in any CI.

Thanks!
