### ISSUE TITLE
oe_verify_report (enclave) takes seconds to execute

### ISSUE THREAD

**Issue by jumaffre** [openenclave/openenclave#2283]
In CCF, we've recently observed that a call to `oe_verify_report()` in the enclave can take a significant amount of time to execute (about 2 seconds). We rely on this function to verify the quote of new nodes joining a CCF network.

This is an issue (https://github.com/microsoft/CCF/issues/480) for us as the CCF's enclave code is single-threaded for now and such calls block execution of other commands. Since CCF uses consensus algorithms that are sensitive to time (Raft election timeout in particular), this creates unwanted behaviours in many of our tests and real scenarios as Raft elections get triggered when `oe_verify_report()` takes too long to execute.

This is something that we observed very rarely a while back (probably on OE v0.5.0 or v0.6.0) but it seems to have got worse/more frequent with v0.7.0 RCs. 

Looking at the logs briefly (`OE_LOG_LEVEL=verbose`), it seems that most of the time is spent during the `curl`s in the DCAP client code and the many `clock_gettime` (that I believe are used by mbedtls for the certificates/CRL verification?):

```
2019-10-28T10:38:40.500037Z [(E)WARN] tid(0x7f78e51ff700) | libloggingenc.so.signed:syscall num=228 not handled [../syscall/syscall.c:_syscall:815]
```

**Related issues:**
DCAP client caching of collaterals:  microsoft/Azure-DCAP-Client#88
Code optimization for new collaterals: #2792

**Comment by CodeMonkeyLeet** [comment]
@jazzybluesea Can you take a look at the profile of the `oe_verify_report()` call chain?

**Comment by jumaffre** [comment]
@soccerGB @jazzybluesea Any news on this?

**Comment by jazzybluesea** [comment]
Hi @jumaffre, currently there is a plan to update caching in the Azure DCAP client, this should save us around 400 to 500ms when getting the revocation info and about 88ms when getting QE identity info.  Here is the breakdown for everyone else:

Here is the timing breakdown for oe_verify_report():

1.	Oe_get_collaterals_internal() takes 622ms. 
a.	88ms for fetching the QE Identity info.
b.	487ms for fetching the Revocation Info (TCB Info and CRLs).  If called from the host, this only makes 1 single call to the provider.
i.	1st call to get revocation info is to get the sizes.  This takes 265ms.
ii.	2nd call takes 222ms.
c.	47ms not categorized.
2.	Oe_validate_revocation_list() takes 144ms.  This takes 3ms if called from the host.
a.	125ms to do CRL validation.
b.	19ms to check TCB.
3.	oe_get_quote_validity_with_collaterals_internal() takes 228ms. Note that this takes 3ms if called from the host.
a.	Oe_validate_revocation_list() and oe_validate_qe_identity() take 187ms.
b.	Rest of the time used for fetch certificates from the PCK Cert chain and parse quote.

**Comment by jazzybluesea** [comment]
@jumaffre What is your timeline?

**Comment by achamayou** [comment]
@jazzybluesea am I right in thinking that once the new oe_verify_report() API is in place, callers (ie. we) will be able to provide their own collateral? If so, we should be able to store it inside the CCF store, refresh it at an interval, and not pay the cost synchronously on every verify call.

At the moment, we've mitigated this problem in tests, but it's still painful in actual use and something we'd like to see resolved sooner rather than later.

**Comment by jazzybluesea** [comment]
> @jazzybluesea am I right in thinking that once the new oe_verify_report() API is in place, callers (ie. we) will be able to provide their own collateral? If so, we should be able to store it inside the CCF store, refresh it at an interval, and not pay the cost synchronously on every verify call.
> At the moment, we've mitigated this problem in tests, but it's still painful in actual use and something we'd like to see resolved sooner rather than later.

@achamayou, Yes, the asynchronous caching should help with your timing requirements.  As I mentioned, currently the collaterals are not getting cached by the Azure DCAP client, and the plan is to add this caching to the Azure DCAP client.  Also note that we recently added an attestation plug-in model (Please see #2298).

**Comment by radhikaj** [comment]
@jazzybluesea Is this issue with AZDCap Client only? Can we tag this as external and request a fix from AZDCap client? Please help clarify so we can triage this appropriately.

**Comment by jazzybluesea** [comment]
> @jazzybluesea Is this issue with AZDCap Client only? Can we tag this as external and request a fix from AZDCap client? Please help clarify so we can triage this appropriately.

I already made requests to the AzDcap client team about a month ago and they are aware of this.  I have opened https://github.com/microsoft/Azure-DCAP-Client/issues/88 for tracking purposes.

**Comment by yentsanglee** [comment]
This is in the backlog but not in current sprint.

**Comment by jazzybluesea** [comment]
There are new collaterals for SGX. See #2792.
Given that #2792 only covers code optimization, I will leave this one open to cover the caching of the **new** SGX collaterals.

**Comment by yufjiang** [comment]
I just did some profiling in my vm node against the issue discussed here.
oe_create_sgx_endorsements: 8.5 microseconds
oe_get_sgx_endorsements(): 973,200 microseconds. oe_get_sgx_endorsements is a host side API. 
oe_get_sgx_quote_verification_collateral(): 1,810,167 microseconds. oe_get_sgx_quote_verification_collateral is an in-enclave API. It makes ocall to oe_get_sgx_endorsements(). So its running time roughly equal to oe_get_sgx_quote_verification_collateral running time + context switching. By caching the collateral at local, we can vastly reduce the time took by oe_get_sgx_endorsements()

**Comment by yufjiang** [comment]
Did a bit more profiling against oe_verify_report() running in enclave and involving remote collateral fetching. 

oe_verify_report(): 2,010,000 microseconds (around 2 seconds).

Combining the data break down mentioned in the comment above, we can see the running time of oe_verify_report() == network communication to Azure PCK caching service (roughly 1s) + ocall context switching (roughly 0.85s) + all other operations. 

While context switching is almost unavoidable, local caching optimization buys us 1 second. Optimization on other operations is trivial.

**Comment by yentsanglee** [comment]
For each oe_veriy_report(), we makes 2 attempts to retrieve PCK collaterals - first time to get sizes and the second time to fill the buffers. The double call has been reported in issue 2049 and will be fixed. The ultimate fix will have to be done by caching PCK collaterals -https://github.com/microsoft/Azure-DCAP-Client/issues/88

**Comment by yentsanglee** [comment]
Azure DCAP Client now caches all collateral. The work was done by [Azure-DCAP-Client PR 105](https://github.com/microsoft/Azure-DCAP-Client/pull/105). The reported performance of a remote attestation is less than 10 ms.
