### ISSUE TITLE
Spurious syscall warnings

### ISSUE THREAD

**Issue by wintersteiger** [openenclave/openenclave#2285]
Some syscalls trigger spurious warning messages. The warnings are emitted here: https://github.com/openenclave/openenclave/blob/0deb7c67911e22b3151997f4f631ed5cf4ad7e30/syscall/syscall.c#L815

However, some system calls _are_ handled, but elsewhere:
https://github.com/openenclave/openenclave/blob/0deb7c67911e22b3151997f4f631ed5cf4ad7e30/libc/syscalls.c#L257

In our case, this message is triggered rather frequently because of calls to `clock_gettime`. Further, the log level is set to `OE_LOG_LEVEL_ERROR` initially, until global initialization is done. Thus, the exact number and the timing of those warning messages varies and makes it a little hard to debug.

In the interest of wasted debugging time, I'd like to suggest to change this behavior. For example, those four syscalls could be handled before `_dispatch_oe_syscall` is called, or that function could have logging disabled temporarily, until it is known whether there is a real warning to report, e.g. if `errno != ENOSYS` at this point: https://github.com/openenclave/openenclave/blob/0deb7c67911e22b3151997f4f631ed5cf4ad7e30/libc/syscalls.c#L248

CC @letmaik

**Comment by CodeMonkeyLeet** [comment]
@mikbras can you take a look at the syscall handling for nanosleep?

**Comment by jhand2** [comment]
Fixed here #2377

@mikbras just to double check, are we ok with this behavior? In the event that a syscall can be handled both inside the enclave and via ocall, we will no longer prefer the ocall version. Today there are no incidences where this is the case, so effectively we get the same behavior.
