### ISSUE TITLE
esy requirement

### ISSUE THREAD

**Issue by letmaik** [openenclave/openenclave#2294]
As part of our CI we also build OE master and then build apps against that, just to be aware of cutting edge breaking changes etc.
I noticed that "esy" is now required instead of the ocaml tools. I couldn't find clear/easy instructions on how to install esy in Ubuntu within a Docker container. I'd like to avoid using Ansible for this if possible. Any thoughts on this? The ocaml compiler was easily installable via apt-get.

**Comment by CodeMonkeyLeet** [comment]
@andschwa Can you provide @letmaik with steps that do not require Ansible?

The Ansible solution is generally considered the supported solution so the easiest way would certainly be to run:

```bash
sudo ansible-playbook scripts/ansible/oe-linux-esy-setup.yml
```

Looking at the implementation in [scripts/ansible/roles/linux/openenclave/tasks/esy-setup.yml](https://github.com/openenclave/openenclave/blob/master/scripts/ansible/roles/linux/openenclave/tasks/esy-setup.yml) it seems non-trivial to do manually.

**Comment by andschwa** [comment]
@letmaik if you don't want to use Ansible, you can use the original Bash script I ported to Ansible (this playbook is pretty trivial, download and extract two tarballs and move some files around). It's here: https://github.com/esy/esy/blob/15f593510ea078b4b392b931c9572bc07a306119/scripts/install-esy.sh

You can also follow the instruction on [esy.sh](https://esy.sh/) to install via `npm` (it would just be `npm install -g esy@0.5.8`, once you have `npm`), but I didn't want to introduce `npm` as a dependency to Open Enclave, when it's not really necessary.

**Comment by andschwa** [comment]
Just for some background, most of this was driven by the fact that OCaml on Windows was absolutely not easy to get. While Ubuntu has OCaml compilers in the apt repos, the only easily installed version of OCaml for Windows was OCPWin, which is a third-party and unmaintained distribution.

**Comment by letmaik** [comment]
Thanks, I'm now using the script https://github.com/esy/esy/blob/15f593510ea078b4b392b931c9572bc07a306119/scripts/install-esy.sh which works fine. The only issue is that it got removed from the repository. For reference, I tried to install esy also via npm by installing npm via apt install, but apparently this package is broken as it conflicts with other library versions.

**Comment by andschwa** [comment]
@letmaik which package is broken and conflicting with other library versions, `npm`?

**Comment by andschwa** [comment]
@letmaik also I don't think it's that it was removed from the repo, but that it has yet to be added (it's from an open PR). If the script works well for you, I'm sure they'd appreciate the feedback.

I am going to close this issue as you were able to get it installed without adding any dependencies you didn't want. Thanks!
