### ISSUE TITLE
Make entropy.h public

### ISSUE THREAD

**Issue by achamayou** [openenclave/openenclave#2328]
Can entropy.h be made public? https://github.com/openenclave/openenclave/blob/71edd2cf92f52017410d5e3262628b962067560a/include/openenclave/internal/entropy.h

This would be convenient for users who want a reliable, cross-enclave source of randomness.

**Comment by achamayou** [comment]
To clarify, I'm happy to do the PR if we think this is acceptable.

**Comment by CodeMonkeyLeet** [comment]
It's worth considering although there's already an outstanding issue #892 to make `oe_random()` simply redirect directly to the TEE implementation of RNG (i.e. `rdrand` in the case of SGX). Did you just want a TEE source of randomness, or did you want to seed your own DRNG?

`oe_get_entropy()` was designed to fill a gap for seeding DRNG with better entropy (i.e. as an internal interface for mbedtls or other crypto libraries to consume, rather than an end user app), whereas #892 was specifically about providing a TEE-provided RNG function for enclave apps to use directly.

**Comment by achamayou** [comment]
@CodeMonkeyLeet I suspect both are useful in general, but at the moment we specifically want entropy to seed existing DRNGs that we would prefer not to replace (mostly because that's what the components we use have provisions for replacing, not for any fundamental reason).

**Comment by dthaler** [comment]
I don't see why we'd want two separate public functions that return a cryptographically random set of bytes, so I'd vote for either oe_random() or oe_get_entropy() but not both.  I think oe_random is a better name though.

**Comment by jhand2** [comment]
Consider an infrastructure for exposing APIs as "Internal Public APIs" (or some other name) to expose functions which have very limited use and general enclave applications won't use but some very specific ones may want to use.

In general we just need to be careful of how `oe_get_entropy` is documented and and how developers are guided to get randomness.

**Comment by radhikaj** [comment]
@dthaler 
Suggestion per triage was to annotate this as @advanced (just as we use @experimental). Please let me know if you are OK with this direction. If so, @achamayou can issue a PR.

**Comment by jhand2** [comment]
Does making it public just mean moving `oe_get_entropy()` to enclave.h? Or moving the entropy.h header to `include/openenclave/corelibc/"?

I also also have questions about the API itself being platform dependent (`oe_entropy_kind_t` allows for rdrand, rdseed, or optee). I want to make sure we're aware of the fact that the enclave application then has to care which platform its running on.

**Comment by radhikaj** [comment]
Thank you @jhand2. The request is to make entropy.h public. 
Regarding the API itself being platform dependent, I agree its weird. @HernanGatta could you please comment on why the enclave needs to specify the type of entropy it needs. This should be something the enclave can figure out itself. For trust zone enclaves, is it possible for the enclave to call this API with any oe_entropy_kind_t  value?

**Comment by jhand2** [comment]
Add thorough documentation to explain how the API works prior to making it public. This includes a usage sample either in samples/ or in the doxygen comment.
