### ISSUE TITLE
Problem with function "fopen" in enclave

### ISSUE THREAD

**Issue by sword03** [openenclave/openenclave#2352]
I have run the helloworld successfully, and then,  I add some codes to enc.c as follow:

```
    FILE * fpub = NULL;
    if( ( fpub = fopen( "/home/max/rsa_pub.txt", "w" ) ) == NULL )
    {
        fprintf(stdout, " failed\n  ! could not open rsa_pub.txt for writing\n\n" );
        fflush(stdout);
        goto exit;
    } 
```

I built it and run in simulation mode, then it crashed:

```
2019-12-02T11:50:58.719393Z [(E)ERROR] tid(0x7f7868f84d40) | enclave.signed:path=/home/max/rsa_pub.txt oe_errno=2 [/home/jenkins/work_dir/workspace/OpenEnclave-v0.7.x_packages/syscall/mount.c oe_mount_resolve:119]
2019-12-02T11:50:58.719423Z [(E)ERROR] tid(0x7f7868f84d40) | enclave.signed:oe_errno=2 [/home/jenkins/work_dir/workspace/OpenEnclave-v0.7.x_packages/syscall/fcntl.c oe_open:43]
 failed
  ! could not open rsa_pub.txt for writing
```

Is there some bugs with the function "fopen" in enclave?

**Comment by BRMcLaren** [comment]
Hi @sword03, no bugs have been reported to my knowledge.

Could you provide more information regarding the file, including OS, encrypted or not, etc? 

Generally, when I have encountered errors such as this, it is due to either incorrect file permissions or incorrect folder structure and would like to rule that out.

**Comment by andschwa** [comment]
@sword03 in the example you provided, I don't see the host file system module being mounted. Have you reviewed the instructions on using the I/O subsystem [here](https://github.com/openenclave/openenclave/blob/master/docs/UsingTheIOSubsystem.md)?

**Comment by sword03** [comment]
@andschwa  Thanks for your answer. I add some codes to enc.c today:
```
    oe_result_t result;
    if ((result = oe_load_module_host_file_system()) != OE_OK)
        return -1;
    if (mount("/", "/", OE_HOST_FILE_SYSTEM, 0, NULL) != 0) //OE_HOST_FILE_SYSTEM
        return -1;
    return 0;
```

I open a file like this:

```
    FILE * fpub = NULL;
    if( ( fpub = fopen( "./rsa_pub.txt", "w" ) ) == NULL )
    {
        fprintf(stdout, " failed\n  ! could not open rsa_pub.txt for writing\n\n" );
        fflush(stdout);
        goto exit;
    } 
```

I rebuild the program and run, and get the error message as follow:

```
2019-12-03T12:24:16.007716Z [(E)ERROR] tid(0x7f2e81706d40) | enclave.signed:pathname=./rsa_pub.txt oe_errno=13 [/home/jenkins/work_dir/workspace/OpenEnclave-v0.7.x_packages/syscall/fcntl.c oe_open:46]
 failed
  ! could not open rsa_pub.txt for writing
```

**Comment by jhand2** [comment]
@sword03 so the new error would suggest a permissions error. oe_errno is 13 which is `OE_EACCES`.

If you call fopen from the host in your code on the same file, does it work?

**Comment by jhand2** [comment]
Hey @sword03, do you have any more details on this issue/are you still seeing this repro? If not I'll go ahead and close.

**Comment by jhand2** [comment]
Closing. Please reopen if you still have an issue.
