### ISSUE TITLE
Build for attested_tls sample fails transiently on Windows

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2367]
The attested_tls sample build fails transiently on Windows with the following error:

`identity_verifier.cpp:8:10: fatal error: '../../common/tls_server_enc_mrenclave.h' file not found`

`tls_server_enc_mrenclave.h` is autogenerated by a bash script during the build for the sample. On Linux, cmake runs the bash script in-process, which ensures that when that specific build target completes, the header file has been generated.

**On Windows** cmake opens bash in a separate process and then moves on. This means there is a race condition where compilation may take a dependency on this header file before it has been generated.

cc @BRMcLaren @radhikaj @anakrish

**Comment by jhand2** [comment]
Original hypothesis was wrong. Dependencies just weren't properly expressed. Fix is in PR #2368

**Comment by BRMcLaren** [comment]
@jhand2 Thanks for documenting and explaining this!

This leads to nightly builds failing transiently, unfortunately. Hence the red badge.

**Comment by BRMcLaren** [comment]
@nonpolarity This is the issue we talked about.

**Comment by jhand2** [comment]
Closed by #2368
