### ISSUE TITLE
OE is not C99 compliant

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2376]
From discussing with @mikbras, OE should compile against C99. Unfortunately, it does not.

In particular, the main thing I haven't been able to overcome is OE_STATIC_ASSERT:

```{C}
#define OE_STATIC_ASSERT(COND)       \
    typedef unsigned char OE_CONCAT( \
        __OE_STATIC_ASSERT, __LINE__)[(COND) ? 1 : -1] OE_UNUSED_ATTRIBUTE
```

It depends on type redefinition (`__OE_STATIC_ASSERT<line_number>` can be defined multiple times). Type redefinition is a C11 feature and using it fails the build when the C standard is set to C99.

We'll need to come up with something else if we want OE to be compilable with C99. If we don't care, we can just set the standard to C11 and document that.

**Comment by jxyang** [comment]
Do we have customers working a platform that doesn't allow upgrade to a C11 compiler? @mikbras

**Comment by dthaler** [comment]
My opinion: I believe that OE needs to support apps that need to consume the SDK, and need C99.  However, if they consume OE SDK in binary form, that does not mean that OE SDK needs C99 to compile.   Thus, I care that public headers and samples are C99 compliant, but internal code may not need to be.

**Comment by jhand2** [comment]
>  I care that public headers and samples are C99 compliant, but internal code may not need to be.

Agreed

As for enforcing that this stays true.

Most of the samples are C++. `samples/helloworld` and `samples/switchless` are C, I'll check if those two can compile with C99 as-is.

As for public headers, I'm not totally sure how to enforce that via a static/build time check. Open to any options people know of.
