### ISSUE TITLE
Document typo: "cmake -G ninja..." should be "cmake -G Ninja"

### ISSUE THREAD

**Issue by Francis-Liu** [openenclave/openenclave#2392]
There is a typo in the **cmake build command** this [wiki](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsSGX1FLCGettingStarted.md).

```
cmake -G ninja -DNUGET_PACKAGE_PATH=C:/oe_prereqs -DCMAKE_INSTALL_PREFIX=install ../..
```

and the next one

```
cmake -G ninja -DCMAKE_BUILD_TYPE=Release -DNUGET_PACKAGE_PATH=C:/oe_prereqs -DCMAKE_INSTALL_PREFIX=install ../..
```

where `cmake -G ninja` should be `cmake -G Ninja` (`N` capitalized)

Otherwise, you will see this error.

```
CMake Error: Could not create named generator ninja
```

**Comment by jhand2** [comment]
Thanks @Francis-Liu!

Hey @mingweishih, your PR last week fixed a couple instances of this but there are a few other instances of this error in other .md files. Can you submit a PR to take care of the rest of these (you can probably just search the who codebase for `-G ninja`.

I'll assign to you.

**Comment by mingweishih** [comment]
Thanks @Francis-Liu for reporting the issue.

@jhand2 I just create PR #2393 for the fix.
