### ISSUE TITLE
Started getting OE_PLATFORM_ERROR

### ISSUE THREAD

**Issue by lakiw** [openenclave/openenclave#2401]
I have several Dell Precision 7520 systems. Two run Ubuntu 16.04, and one runs Ubuntu 18.04. Previously I was able to compile and run SGX enclaves on them using OpenEnclave, but over the last couple of weeks all three of them now return an OE_PLATFORM_ERROR. I assumed this was because I was playing around with Google's Asylo, so I reinstalled the OSs from scratch and am still receiving the same error.

Info:
oesgx
CPU supports Software Guard Extensions:SGX1
MaxEnclaveSize_64: 2^(36)
EPC size on the platform: 98041856

The following occurs when I attempt to run the sample helloworld enclave:

make run
host/helloworldhost ./enclave/helloworldenc.signed
2020-01-03T18:46:49.701219Z [(H)ERROR] tid(0x7fa4c5d93740) | enclave_create with ENCLAVE_TYPE_SGX1 type failed (err=0x1) (oe_result_t=OE_PLATFORM_ERROR) [/home/jenkins/work_dir/workspace/OpenEnclave-v0.7.x_packages/host/sgx/sgxload.c:oe_sgx_create_enclave:459]
2020-01-03T18:46:49.701233Z [(H)ERROR] tid(0x7fa4c5d93740) | :OE_PLATFORM_ERROR [/home/jenkins/work_dir/workspace/OpenEnclave-v0.7.x_packages/host/sgx/create.c:oe_sgx_build_enclave:631]
2020-01-03T18:46:49.701440Z [(H)ERROR] tid(0x7fa4c5d93740) | :OE_PLATFORM_ERROR [/home/jenkins/work_dir/workspace/OpenEnclave-v0.7.x_packages/host/sgx/create.c:oe_create_enclave:753]
oe_create_helloworld_enclave(): result=21 (OE_PLATFORM_ERROR)
Makefile:17: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by jhand2** [comment]
Hmm. OE_PLATFORM_ERROR means that libsgx threw an error. For the error spew (`enclave_create with ENCLAVE_TYPE_SGX1 type failed (err=0x1)`), we can see that it failed with error 0x1 during the PSW function `create_enclave`. The error code is `ENCLAVE_NOT_SUPPORTED`.

Can you share what version of libsgx-enclave-common you have installed? The output of `apt list --installed | grep sgx` should do.

**Comment by zhaoxuyang13** [comment]
I meet the same issue, and same error code.
this is what i get from "apt list --installed | grep sgx"
libsgx-dcap-ql/now 1.0.101.48192-xenial1 amd64 [installed,local]
libsgx-dcap-ql-dbg/now 1.0.101.48192-xenial1 amd64 [installed,local]
libsgx-dcap-ql-dev/now 1.0.101.48192-xenial1 amd64 [installed,local]
libsgx-enclave-common/now 2.7.101.3-xenial1 amd64 [installed,local]
libsgx-enclave-common-dev/now 2.4.100.48163-xenial1 amd64 [installed,local]
libsgx-urts/now 2.4.100.48163-xenial1 amd64 [installed,local

**Comment by jhand2** [comment]
Thanks @zhaoxuyang13,

One thing to note, your libsgx-enclave-common and libsgx-enclave-common-dev have mismatched versions. This could be causing problems.

How did you install OpenEnclave? Did you install via a deb package or are you building and installing it from source?

**Comment by zhaoxuyang13** [comment]
Thanks  for your reply : D
It turn out to be my SGX driver's problem,  I reinstall SGX SDK and the driver
then samples works out fine.

**Comment by jhand2** [comment]
Thanks! @lakiw are you still seeing this issue?

**Comment by jhand2** [comment]
@lakiw I am closing this issue. Please reopen if the above solutions don't work for you.

**Comment by maverick-zhn** [comment]
Hello

I have the same error with a platform that supports FLC. I have a **Ubuntu Server 18.04.4**.
```
/opt/openenclave/bin/oesgx
CPU supports SGX_FLC:Flexible Launch Control
CPU supports Software Guard Extensions:SGX1
MaxEnclaveSize_64: 2^(36)
EPC size on the platform: 98041856
```

When running the simplest test:
```
make run
[ 40%] Built target enclave
[ 60%] Built target sign
[100%] Built target helloworld_host
2020-04-11T23:26:35.175919Z [(H)ERROR] tid(0x7fc58bc83740) | enclave_load_data failed (addr=0x8834c000, prot=0x1, err=0x9) (oe_result_t=OE_PLATFORM_ERROR) [/source/host/sgx/sgxload.c:oe_sgx_load_enclave_data:686]
2020-04-11T23:26:35.175932Z [(H)ERROR] tid(0x7fc58bc83740) | :OE_PLATFORM_ERROR [/source/host/sgx/loadelf.c:_add_relocation_pages:504]
2020-04-11T23:26:35.175935Z [(H)ERROR] tid(0x7fc58bc83740) | :OE_PLATFORM_ERROR [/source/host/sgx/loadelf.c:_add_pages:596]
2020-04-11T23:26:35.175936Z [(H)ERROR] tid(0x7fc58bc83740) | :OE_PLATFORM_ERROR [/source/host/sgx/create.c:oe_sgx_build_enclave:652]
2020-04-11T23:26:35.176123Z [(H)ERROR] tid(0x7fc58bc83740) | :OE_PLATFORM_ERROR [/source/host/sgx/create.c:oe_create_enclave:763]
oe_create_helloworld_enclave(): result=21 (OE_PLATFORM_ERROR)
```
```
lsmod | grep sgx
intel_sgx              28672  0
```

## service status
```
service aesmd status
● aesmd.service - Intel(R) Architectural Enclave Service Manager
   Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-04-09 20:52:45 UTC; 2 days ago
 Main PID: 21004 (aesm_service)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/aesmd.service
           └─21004 /opt/intel/sgx-aesm-service/aesm/aesm_service

Apr 09 20:52:44 hostname systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
Apr 09 20:52:44 hostname usermod[20989]: add 'aesmd' to group 'sgx_prv'
Apr 09 20:52:44 hostname usermod[20989]: add 'aesmd' to shadow group 'sgx_prv'
Apr 09 20:52:45 hostname systemd[1]: Started Intel(R) Architectural Enclave Service Manager.
Apr 09 20:52:45 hostname aesm_service[21004]: The server sock is 0x55856c9f71b0
```
When I run `apt list --installed | grep sgx`

```
libsgx-ae-le/unknown,now 2.9.101.2-bionic1 amd64 [installed,automatic]
libsgx-ae-pce/unknown,now 2.9.101.2-bionic1 amd64 [installed,automatic]
libsgx-ae-qe3/unknown,now 1.6.100.2-bionic1 amd64 [installed,automatic]
libsgx-ae-qve/unknown,now 1.6.100.2-bionic1 amd64 [installed,automatic]
libsgx-aesm-launch-plugin/unknown,now 2.9.101.2-bionic1 amd64 [installed,automatic]
libsgx-dcap-ql/unknown,now 1.6.100.2-bionic1 amd64 [installed]
libsgx-dcap-ql-dev/unknown,now 1.6.100.2-bionic1 amd64 [installed]
libsgx-enclave-common/unknown,now 2.9.101.2-bionic1 amd64 [installed]
libsgx-enclave-common-dev/unknown,now 2.9.101.2-bionic1 amd64 [installed]
libsgx-launch/unknown,now 2.9.101.2-bionic1 amd64 [installed,automatic]
libsgx-pce-logic/unknown,now 1.6.100.2-bionic1 amd64 [installed,automatic]
libsgx-qe3-logic/unknown,now 1.6.100.2-bionic1 amd64 [installed,automatic]
libsgx-urts/unknown,now 2.9.101.2-bionic1 amd64 [installed,automatic]
sgx-aesm-service/unknown,now 2.9.101.2-bionic1 amd64 [installed,automatic]
```

@jhand2  Should I reinstall the SGX Driver and SDK?

Thank you in advance.

**Comment by jhand2** [comment]
Can you get me the output of `dmesg | grep -i sgx`? I'm interested in the driver version you have installed. Also what version of OE?

Newer versions of the SGX driver require source addresses of memory being loaded into the enclave to be page-aligned which we only added about a month ago: https://github.com/openenclave/openenclave/pull/2566

**Comment by maverick-zhn** [comment]
@jhand2 this is the requested output `dmesg | grep -i sgx`:
```
[85554.131561] intel_sgx: loading out-of-tree module taints kernel.
[85554.131598] intel_sgx: module verification failed: signature and/or required key missing - tainting kernel
[85554.132036] sgx: EPC section 0x70200000-0x75f7ffff
[85554.133092] sgx: intel_sgx: Intel SGX DCAP Driver v1.32
```
OE version is: `v0.8.2` (taken from the VERSION file in the root directory.)

Thank you.

**Comment by jhand2** [comment]
@maverick-zhn ya so #2566 wasn't merged until after v0.8 was released (DCAP driver v1.32 was also released after OE v0.8).

Would you be able to build the SDK from source instead of using the APT package and let me know if that solves the problem?

Otherwise, we have a v0.9 release planned for April 20th which will contain this patch.

**Comment by maverick-zhn** [comment]
@jhand2, I will do my best to build the SDK from source. I will use [this](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/LinuxInstallInfo.md#basic-install-on-linux) doc. Please let me know if you recommend another documentation.

Thank you.

**Comment by jhand2** [comment]
@maverick-zhn this doc would be better https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1FLCGettingStarted.md

Let me know if you get stuck anywhere, I'm happy to help :smile:

**Comment by maverick-zhn** [comment]
@jhand2 seems to be working after building the SDK from source. 

```
98% tests passed, 5 tests failed out of 215

Total Test time (real) = 268.68 sec

The following tests did not run:
        167 - tests/report_attestation_without_enclave (Skipped)

The following tests FAILED:
         19 - tests/tls_e2e (Child aborted)
         25 - tests/attestation_cert_api (Failed)
         26 - tests/attestation_plugin (Child aborted)
        166 - tests/report (Failed)
        215 - samples (Failed)
Errors while running CTest
```
Is it recommended to install the **APT** package after `v0.9` release?

Thank you for your help.

**Comment by jhand2** [comment]
Yes, the v0.9 package will contain this fix. Thanks!
