### ISSUE TITLE
Fix support for just "out" parameters in deep copy

### ISSUE THREAD

**Issue by andschwa** [openenclave/openenclave#2412]
I discovered while adding further tests that when using deep copy for parameters that are only "out" parameters that it does not work. It works for "in" and "in/out" (the latter of which are both tested), but for "out" parameters there is a bit of logic to add to layout the host side pointers correctly (very similar to what's done for "in/out"), I think.

I had to prioritize in my remaining time working on this project, and so I prioritized making oeedger8r maintainable with the updated build system and isolated modules instead. Sorry for not being able to get to this part @anakrish, please let me know if you have any questions.

/cc @radhikaj

**Comment by mingweishih** [comment]
Fixed by #2427.
