### ISSUE TITLE
Unit test "tls_e2e" hangs on win19

### ISSUE THREAD

**Issue by Francis-Liu** [openenclave/openenclave#2414]
**Environment**
- AccImage: windows-server-2019
- VmSize: Standard_DC2s
- Debug build

**Test Output**
```
test 82
        Start  82: tests/tls_e2e

82: Test command: C:\Users\feliu\workspace\openenclave\build\x64-Debug\tests\tls_e2e\host\tls_e2e_host.exe "C:/Users/feliu/workspace/openenclave/build/x64-Debug/tests/tls_e2e/server_enc/tls_server_enc" "C:/Users/feliu/workspace/openenclave/build/x64-Debug/tests/tls_e2e/client_enc/tls_client_enc"
82: Test timeout computed to be: 10000000
82: Test case: Server:
82: ------positive_test
82:  This is a positive test case. Expect no errors
82: 2020-01-08T07:28:13.000000Z [(H)ERROR] tid(0x75c) | quote3_error_t=0xe035
82:  (oe_result_t=OE_PLATFORM_ERROR) [..\..\host\sgx\sgxquote.c:oe_sgx_qe_get_target_info:21]
82: 2020-01-08T07:28:13.000000Z [(H)ERROR] tid(0x75c) | :OE_PLATFORM_ERROR [..\..\host\sgx\quote.c:sgx_get_qetarget_info:31]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc::OE_PLATFORM_ERROR [..\..\enclave\core\sgx\report.c:oe_get_remote_report:182]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc::OE_PLATFORM_ERROR [..\..\enclave\core\sgx\report.c:_oe_get_report_internal:276]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc::OE_PLATFORM_ERROR [..\..\enclave\core\sgx\report.c:oe_get_report_v2:329]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc:oe_get_report failed with OE_PLATFORM_ERROR
82:  (oe_result_t=OE_PLATFORM_ERROR) [..\..\enclave\tls_cert.c:oe_generate_attestation_certificate:148]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc: failed with OE_PLATFORM_ERROR
82:  (oe_result_t=OE_PLATFORM_ERROR) [..\..\tests\tls_e2e\common\utility.cpp:generate_certificate_and_pkey:126]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc:failed with OE_PLATFORM_ERROR
82:  [..\..\tests\tls_e2e\server_enc\server.cpp:configure_server_ssl:126]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc: failed
82:   ! Configure server SSL settings: configure_server_ssl returned 1
82:  [..\..\tests\tls_e2e\server_enc\server.cpp:setup_tls_server:259]
82: 2020-01-08T07:28:13.000000Z [(E)ERROR] tid(0x75c) | tls_server_enc:Last error was: 1 - UNKNOWN ERROR CODE (0001)
82:
82:  [..\..\tests\tls_e2e\server_enc\server.cpp:setup_tls_server:413]
```

**Questions**
- I was able to reproduce this error in multiple VMs. Was this test passing in our CI/CD?
- How long is 10000000 timeout? If it is too long, shall we shorten it?

**Comment by BRMcLaren** [comment]
Hey @Francis-Liu 

We don't have any tests in our CI/CD for this currently as support for Windows 2019 is not officially supported yet, unless this changed?

My one recommendation is to try on a DC_4, as that solves this issue quite often. This is especially true if you have concurrent executors, depending on what you are doing.

**Comment by Francis-Liu** [comment]
@BRMcLaren Thanks for the clarification about Windows 2019. Okay, I will give DC4s a try.

What about the 10000000 timeout? Is that 10 seconds? Why would this test case hang, instead of fails and moves on to the next test case.

**Comment by Francis-Liu** [comment]
Same failure with DC4s.

```
test 82
        Start  82: tests/tls_e2e

82: Test command: C:\Users\feliu\workspace\openenclave\build\x64-Debug\tests\tls_e2e\host\tls_e2e_host.exe "C:/Users/feliu/workspace/openenclave/build/x64-Debug/tests/tls_e2e/server_enc/tls_server_enc" "C:/Users/feliu/workspace/openenclave/build/x64-Debug/tests/tls_e2e/client_enc/tls_client_enc"
82: Test timeout computed to be: 10000000
82: Test case: Server:
82: ------positive_test
82:  This is a positive test case. Expect no errors
82: 2020-01-08T21:11:52.000000Z [(H)ERROR] tid(0x14e8) | quote3_error_t=0xe035
82:  (oe_result_t=OE_PLATFORM_ERROR) [..\..\host\sgx\sgxquote.c:oe_sgx_qe_get_target_info:21]
82: 2020-01-08T21:11:52.000000Z [(H)ERROR] tid(0x14e8) | :OE_PLATFORM_ERROR [..\..\host\sgx\quote.c:sgx_get_qetarget_info:31]
82: 2020-01-08T21:11:52.000000Z [(E)ERROR] tid(0x14e8) | tls_server_enc::OE_PLATFORM_ERROR [..\..\enclave\core\sgx\report.c:oe_get_remote_report:182]
82: 2020-01-08T21:11:52.000000Z [(E)ERROR] tid(0x14e8) | tls_server_enc::OE_PLATFORM_ERROR [..\..\enclave\core\sgx\report.c:_oe_get_report_internal:276]
82: 2020-01-08T21:11:52.000000Z [(E)ERROR] tid(0x14e8) | tls_server_enc::OE_PLATFORM_ERROR [..\..\enclave\core\sgx\report.c:oe_get_report_v2:329]
82: 2020-01-08T21:11:52.000000Z [(E)ERROR] tid(0x14e8) | tls_server_enc:oe_get_report failed with OE_PLATFORM_ERROR
82:  (oe_result_t=OE_PLATFORM_ERROR) [..\..\enclave\tls_cert.c:oe_generate_attestation_certificate:148]
82: 2020-01-08T21:11:52.000000Z [(E)ERROR] tid(0x14e8) | tls_server_enc: failed with OE_PLATFORM_ERROR
82:  (oe_result_t=OE_PLATFORM_ERROR) [..\..\tests\tls_e2e\common\utility.cpp:generate_certificate_and_pkey:126]
82: 2020-01-08T21:11:52.000000Z [(E)ERROR] tid(0x14e8) | tls_server_enc:failed with OE_PLATFORM_ERROR
82:  [..\..\tests\tls_e2e\server_enc\server.cpp:configure_server_ssl:126]
82: 2020-01-08T21:11:52.000000Z [(E)ERROR] tid(0x14e8) | tls_server_enc: failed
82:   ! Configure server SSL settings: configure_server_ssl returned 1
82:  [..\..\tests\tls_e2e\server_enc\server.cpp:setup_tls_server:259]
82: 2020-01-08T21:11:52.000000Z [(E)ERROR] tid(0x14e8) | tls_server_enc:Last error was: 1 - UNKNOWN ERROR CODE (0001)
82:
82:  [..\..\tests\tls_e2e\server_enc\server.cpp:setup_tls_server:413]
```

To whom to be assigned to look at this issue. Feel free to close it if win19 isn't officially supported. Or, if it is of your interest, please take a quick look at why the timeout mechanism doesn't work when this test fails.

**Comment by BRMcLaren** [comment]
10000000 in milliseconds would be nearly 3 hours.
Nanoseconds would be 0.1 of a second.
This is likely in microseconds, so 10 seconds.

Windows 2019 is not officially supported, as an immediate issue this can be closed for now.

However, this is of interest and as it may be supported in the future so I don't want to move on from this yet.

Out of curiosity, what happens when changing the timeout to something incredibly small? incredibly big and disabling the test?

TLS versioning may also be coming into play here however I am not familiar with intricacies. I am not personally familiar with Windows 2019, but I believe it has settings to disable weak TLS versioning which might result in a hang, as you are seeing.

**Comment by jhand2** [comment]
I do think there is a legitimate issue with the test that it hangs indefinitely (until killed by ctest) on failure rather than simply exiting.

We should keep this issue open at least until that is fixed.

**Comment by CodeMonkeyLeet** [comment]
This is not Windows or WS2019 specific. I can repro this failure on a Linux VM where the quote provider is unable to acquire a PCK for the device. The test likely has a bug that causes it to block indefinitely on a failure condition instead of failing out immediately as expected.

@Francis-Liu, you can try to double check this hypothesis by running `ctest -V -R report` on the failing device to skip the tls_e2e test and verifying whether the report tests themselves also fail.

**Comment by radhikaj** [comment]
There are two issues
1. Fix test so it does not hang
2. Investigate why it consistently hangs on Windows Server 2019. It is likely a setup problem. @yakman2020 reports that tests passed on his Windows Server 2019. @Francis-Liu could you please verify your setup is correct and report back?  Thanks.

**Comment by radhikaj** [comment]
@mingweishih please work with @Francis-Liu to verify that the setup is correct and then investigate.

**Comment by Francis-Liu** [comment]
@radhikaj I think what @yakman2020 said was, after he ran the following command, all the tests pass. He didn't mention all tests would pass without setting this reg key. On my side, I can also verify that `tls_e2e` pass after setting the following reg key.

`reg add HKEY_LOCAL_MACHINESYSTEMCurrentControlSetServicessgx_lc_msrParameters /v "SGX_Launch_Config_Optin" /t REG_DWORD /d 1`
