### ISSUE TITLE
Use OE with DCAP for remote attestation

### ISSUE THREAD

**Issue by VictorDebray** [openenclave/openenclave#2418]
Hi,

I have worked on a broader sample that integrates file encryptor and remote attestation.
However, the remote attestation part does not seem to remotely attest reports.

Recently I picked up of the DCAP driver and see it is the project.
Unfortunately I was not able get any documentation about how to use it with open enclave.

Has someone has started work on documenting this ?
I'd be happy to contribute

**Comment by jhand2** [comment]
We have a few samples that are in the areas you mention:

* Remote attestation: https://github.com/openenclave/openenclave/tree/master/samples/remote_attestation
* File encryption: https://github.com/openenclave/openenclave/tree/master/samples/file-encryptor
* Attested TLS: https://github.com/openenclave/openenclave/tree/master/samples/attested_tls

Is this what you're looking for?

**Comment by VictorDebray** [comment]
No, I used the remote attestation and file-encryptor sample, so I am well aware of your links.

While setting the OE_REPORT_FLAGS_REMOTE_ATTESTATION the enclave does not use any attestation services. In the end it only does a local attestation.

So my question is how to configure openenclave to make remote attestations correctly ? With DCAP ?
Where do I put the secrets ?

**Comment by radhikaj** [comment]
@VictorDebray are you using an ACC VM in Azure. Remote attestation does not work currently in machines outside ofAzure.
Adding @yentsanglee to investigate issue

**Comment by yentsanglee** [comment]
If you are not running on Azure ACC VM, follow the [instruction](https://software.intel.com/en-us/articles/get-started-with-azure-confidential-computing) to create a VM.

**Comment by VictorDebray** [comment]
Yes I am using ACC VM, I have followed those exact steps.
Are you saying that open enclave remote attestation works out of the box when used in ACC VM ?
Because other than creating the VM in Azure I have done no other configuration for open enclave.

**Comment by jhand2** [comment]
Are you using the Azure DCAP client or the Intel DCAP client?

**Comment by VictorDebray** [comment]
My understanding is that using the Azure CC template it sets up the intel DCAP by default.
In /opt/azure/acc/ I see the  sgx_linux_x64_driver_dcap.bin, I guess I have Intel one then.

Should I uninstall and replace my DCAP client ?

**Comment by yentsanglee** [comment]
You need Azure DCAP client to perform remote attestation on Azure ACC VMs. If you follow the instruction -
https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1FLCGettingStarted.md

and install required projects, Azure DCAP client will be installed.

Follow all steps in the instruction and run all unit tests to verify the build.

**Comment by VictorDebray** [comment]
I will try this and will back to you soon !

**Comment by VictorDebray** [comment]
@yentsanglee I created a new Azure VM without preinstalling openenclave.
Then following the steps in your link, successfully installed openenclave.

I relaunched the remote-attestation sample. I still don't think I understand how the remote attestation works here.
Reading this, I want to make sure I understand right:
https://github.com/microsoft/azure-dcap-client
Does Azure DCAP caches misc enclave info so that remote reports generated are attested with this service ? And all this without needing configuring secrets ?

**Comment by yentsanglee** [comment]
Azure DCAP client retrieves attestation info from Azure PCK cache service who caches all attestation information from Intel SGX Provisioning Certification Service. The technology behind it is based on Intel SGX DCAP. If you are interested in detail, you may search in Intel website for articles such as [this one](https://software.intel.com/en-us/sgx/attestation-services).

**Comment by VictorDebray** [comment]
Ok thanks for your time !
By the way, do you know about any tool that I could use to trace the remote attestation flow/calls from OE to Azure DCAP ?

**Comment by yentsanglee** [comment]
I am not aware of an easy way to trace Azure DCAP client. However, if you set OE_LOG_LEVEL to a more verbose level, oe_quote_provider_log() should capture some logs from Azure DCAP client. Just be aware that the logging callback might be unavailable in future releases.

**Comment by VictorDebray** [comment]
OE_LOG_LEVEL=INFO was enough for what I was looking for.
Could see the url called and operations done by both OE and dcap !
