### ISSUE TITLE
Commits should have a useful description and be well organized

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2419]
OE commit history is hit-or-miss for being useful in understanding past changes.

We should improve documentation to describe how detailed commits should be and be strict about enforcing this before PRs are merged.

In general:

"More changes" is not an acceptable commit message. Even something like "Added memory management" could use more details.

In particular:

1. Commits should have a description that properly captured what happened. What changed, why did it change. A commit shouldn't do work that is not in the commit message.
2. Commits should be split up by work done. If a PR is large and does many things, each piece should be in a separate commit. This does not need to be too granular but a change that touches multiple libraries should not in 1 commit.
3. No extraneous commits. If a change is made in one commit and then modified in another to fix some issue, the commits should be squashed into a single commit.

I'll formalize this a little more when I write the documentation. I'll also add instructions for some git commands folks can use to clean up their commit history before merging a PR.

**Comment by jhand2** [comment]
Related to #1920

**Comment by dthaler** [comment]
Suggest updating this section:
https://github.com/openenclave/openenclave/blob/master/docs/Contributing.md#dos-and-donts-for-pull-requests
