### ISSUE TITLE
Debugging: Expose backtrace functionality for users

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#2421]
OE currently supports oe_backtrace and oe_backtrace_symbols modeled after the GNU functions (backtrace and backtrace_symbols). oe_backtrace is used internally in debug builds to report memory leaks.

Backtrace functionality is in general useful feature for the end user to help debug their systems both in debug builds and production builds.

**Comment by anakrish** [comment]
CC: @radhikaj @mikbras @CodeMonkeyLeet @jhand2

**Comment by anakrish** [comment]
Prototype to make backtraces work in release mode: https://github.com/openenclave/openenclave/compare/anakrish/backtrace?expand=1

**Comment by radhikaj** [comment]
Add 'backtrace' and 'backtrace_symbols' to oelibc. It will currently only work for SGX. It can be made to work on ARM, but would need more work. Currently, this work will be scoped to SGX. When C++ exceptions are made to work on ARM, this can be made to work on ARM as well. Create another issue to track this for ARM.

Thanks @anakrish for prototyping
