### ISSUE TITLE
Unable to compile the samples

### ISSUE THREAD

**Issue by anahitH** [openenclave/openenclave#2424]
After installing open-enclave following the steps [here](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md) I'm trying to compile the _helloworld_. The compilation of the _enclave_ succeeds however the host fails in the linker with the following error:

`/opt/openenclave/share/pkgconfig/../../lib/openenclave/host/liboehost.a(init.c.o): In function _initialize:
/home/jenkins/work_dir/workspace/OpenEnclave-v0.7.x_packages/host/crypto/openssl/init.c:13: undefined reference to OPENSSL_add_all_algorithms_noconf
/home/jenkins/work_dir/workspace/OpenEnclave-v0.7.x_packages/host/crypto/openssl/init.c:15: undefined reference to ERR_load_crypto_strings
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`
The openssl is installed on my machine and I'm able to compile a simple ssl client program successfully.

Have you seen this issue previously? Or do you have any clue what can be the problem here?

**Comment by BRMcLaren** [comment]
Hello @anahitH ,

Thanks for checking out OpenEnclave

Could you provide and confirm more details about your machine? is it Ubuntu 18.04 or 16.04?

I have seen this before when there is an incorrect version OpenSSL of OpenSSL installed and causes the linker issues. I believe we are using different versions for 16.04 and 18.04

**Comment by anahitH** [comment]
@BRMcLaren, I have Ubuntu 18.04 and OpenSSL version 1.1.1

**Comment by anahitH** [comment]
Hi @BRMcLaren . 
Could you please advise what is the correct version of OpenSSL to use with Ubuntu 18.04?
Thanks!

**Comment by jhand2** [comment]
OpenSSL 1.1.1 should be the correct version. @anahitH could you share the following:

1. The compiler/linker commandline invocation? If using GNU make you can do `make VERBOSE=1`. For ninja you can do `ninja -v`.
2. Where are you compiling the sample from? Are you using the sample from the install location (/opt/openenclave/share/openenclave/samples/)?

**Comment by anahitH** [comment]
@jhand2 thanks for the response. 

For your second question, yes I'm using the samples from the install location. I've copied them to another directory and trying to compile from there. But I did not make any changes in the sources and/or Makefiles.


This is the compiler/linker commands. I'm posting those for the host only, as the enclave compiles and links fine.
```
`make[1]: Entering directory '/home/anahitik/TUM/helloworld/host'
Compilers used: clang-7, g++
oeedger8r ../helloworld.edl --untrusted
Generating edge routines for the Open Enclave SDK.
Success.
clang-7 -g -c -fstack-protector-strong -mllvm -x86-speculative-load-hardening -I/opt/openenclave/share/pkgconfig/../../include -I/usr/local//include host.c
clang-7 -g -c -fstack-protector-strong -mllvm -x86-speculative-load-hardening -I/opt/openenclave/share/pkgconfig/../../include -I/usr/local//include helloworld_u.c
clang-7 -o helloworldhost helloworld_u.o host.o -L/opt/openenclave/share/pkgconfig/../../lib/openenclave/host -L/usr/local//lib -rdynamic -Wl,-z,noexecstack -loehost -ldl -lpthread -lsgx_enclave_common -lsgx_dcap_ql -lsgx_urts -lssl -lcrypto
/opt/openenclave/share/pkgconfig/../../lib/openenclave/host/liboehost.a(init.c.o): In function '_initialize':
/home/jenkins/work_dir/workspace/OpenEnclave-v0.7.x_packages/host/crypto/openssl/init.c:13: undefined reference to 'OPENSSL_add_all_algorithms_noconf'
/home/jenkins/work_dir/workspace/OpenEnclave-v0.7.x_packages/host/crypto/openssl/init.c:15: undefined reference to 'ERR_load_crypto_strings'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:21: recipe for target 'build' failed
make[1]: *** [build] Error 1
make[1]: Leaving directory '/home/anahitik/TUM/helloworld/host'
Makefile:9: recipe for target 'build' failed
make: *** [build] Error 2
`
```

This is my openssl version
![image](https://user-images.githubusercontent.com/23015948/73010448-bb3ea600-3e12-11ea-9f5f-19663dfbeaae.png)

When comparing the compile/link commands on my local machine and on the Azure Confidential Computing VM, I can see some differences. Specifically, there are some flags in my machine that are missing from the compile commands in the VM.  I've also tried to link with the exact same command as in the VM, but still am getting the same error, i.e. undefined symbols. Here are the commands from the VM
```
make[1]: Entering directory '/home/anahitik/helloworld/host'
Compilers used: clang-7, g++
oeedger8r ../helloworld.edl --untrusted
Generating edge routines for the Open Enclave SDK.
Success.
clang-7 -g -c -mllvm -x86-speculative-load-hardening -I/opt/openenclave/include host.c
clang-7 -g -c -mllvm -x86-speculative-load-hardening -I/opt/openenclave/include helloworld_u.c
clang-7 -o helloworldhost helloworld_u.o host.o -L/opt/openenclave/lib/openenclave/host -rdynamic -loehost -ldl -lpthread -lsgx_enclave_common -lsgx_dcap_ql -lsgx_urts -lssl -lcrypto
make[1]: Leaving directory '/home/anahitik/helloworld/host'
```

Another difference between my local machine and the VM is openssl install location. It's /usr/local/ in my machine and /usr/ in the VM. But I don't think this could be the problem, can it?

**Comment by jhand2** [comment]
Oh, I see the problem (sort of). In openssl 1.1.1, `OPENSSL_add_all_algorithms_conf` does not actually exist. It is defined with a macro in evp.h for compatibility reasons and is an alias for `OPENSSL_init_crypto`. Likewise, `ERR_load_crypto_strings` is also a compatibility alias for `OPENSSL_init_crypto`.

So it looks like the version of OE you have was compiled against a different version of openssl, however I am not able to reproduce this issue with the version of OE in the package repository. Did you install OE via apt-get from the apt repository mentioned here? https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md

**Comment by anahitH** [comment]
Yes, I've installed OE with apt-get just as it's told in the link you sent.

**Comment by jhand2** [comment]
Apologies, I'm at a bit of a loss for why this would be happening. Could you share the output of

`apt list --installed | grep open-enclave`

and

`objdump -t /opt/openenclave/lib/openenclave/host/liboehost.a | grep -i openssl`

**Comment by anahitH** [comment]
@jhand2 , here are the outputs of the commands you've requested
![image](https://user-images.githubusercontent.com/23015948/73136438-faa50680-404d-11ea-82d5-861736d16c64.png)

**Comment by jhand2** [comment]
Interesting. So OE isn't actually installed through apt. Can you try to install it with `sudo apt install open-enclave`? And if it fails, paste the message?

**Comment by anahitH** [comment]
After removing open-enclave with apt remove, installed it again with apt. Here is the output for the installation as well as the two commands from above. The output for those commands are the same as before.
![image](https://user-images.githubusercontent.com/23015948/73213344-4dff7d80-4150-11ea-9dfb-20f7b31ad6a4.png)

Still getting the same error when compiling the sample
![image](https://user-images.githubusercontent.com/23015948/73213433-78513b00-4150-11ea-9fcf-883a4c32e3ce.png)

**Comment by jhand2** [comment]
Hm. You're using Ubuntu 18.04 right? xenial would be the ubuntu 16.04 package which could make a difference. Could you check you `/etc/apt/sources.list.d/msprod.list` file and make sure it says bionic?

If the wrong package repo is referenced then the steps would be:
1. delete `/opt/openenclave` (maybe not necessary but just to be sure)
2. Remove open-enclave package
3. Update msprod.list file
    The line should be
    `deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main`
4. Install open-enclave again, use apt list to ensure the bionic version is installed
5. Compile sample again

**Comment by anahitH** [comment]
@jhand2 , it was `16.04 xenial `in the` mdprod.list` file. I modified it with your instructions and the samples are compiling now.
Thank you very much for your help :)
