### ISSUE TITLE
EDL does not support macros

### ISSUE THREAD

**Issue by ryanhsu19** [openenclave/openenclave#2431]
This is related to the comments in PR #2220. In samples/data-sealing/datasealing.edl, you can tell the edger8r the size of a pointer, but you cannot assign a macro to it because the edger8r treats it as a new member of the corresponding struct; that is,
 - it works by changing [in, size = sealed_data_size] to [in, size = 16], but
 - it does not work by changing [in, size = sealed_data_size] to [in, size = IV_SIZE], where IV_SIZE is defined as 16 in the header file included in the enclave.

**Comment by anakrish** [comment]
CC: @mingweishih

**Comment by mingweishih** [comment]
This feature is supported by the current oeedger8r implementation.

**Comment by anakrish** [comment]
The recommended oeedger8r syntax is to use arrays with macro/enum dimension:
```c
  public void fun([in] int data[IV_SIZE]);
```
