### ISSUE TITLE
The in-enclave exception handler does not support ocalls

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2448]
Inside the enclave, applications can catch hardware exceptions by registering an exception handler with `oe_add_vectored_exception_handler()`. When this exception handler is called, the host stack is not properly in sync with the enclave stack, so ocalls fail.

OE should support making ocalls during exception handler execution.

**Comment by radhikaj** [comment]
@jhand2 please investigate if this is possible.

**Comment by jhand2** [comment]
So after more investigation I'm not convinced this is something we should do. I looked at other exception handling mechanisms (windows Vectored Exception handling, POSIX signals) and neither restore the stack prior to calling the handler. The recommendation for both is that only simple things like accessing and updating the context struct be done in the handler.

The root need for this is to catch illegal instructions (like cpuid) and make an ocall. But I think there is a better way to implement this in the enclave app code rather than in the exception handler mechanism.

I'll come up with a prototype for how you could do this with cpuid.

**Comment by jhand2** [comment]
Fixed by https://github.com/openenclave/openenclave/pull/2553 and https://github.com/openenclave/openenclave/pull/2553
