### ISSUE TITLE
Trouble executing sample projects

### ISSUE THREAD

**Issue by IvillanuevaItba** [openenclave/openenclave#2449]
Hello,
I'm having trouble executing helloworld sample project in Windows 10. Whenever I run the ninja command in the build folder I get the following pop up and console error. I'll also leave the CMakeErrorLog, which I'm not sure if it's normal, because it seems build without problem.
Any recommendations on what I should do? Is it an installation problem? The Intel SGX SDK sample project is able to run normally, so maybe I'm missing something from OE?

![image (1)](https://user-images.githubusercontent.com/40722107/72934143-e3120900-3d41-11ea-8fbe-6f75c7023b60.png)
![image](https://user-images.githubusercontent.com/40722107/72934156-e73e2680-3d41-11ea-9c91-bb001e9da194.png)

[CMakeError.log](https://github.com/openenclave/openenclave/files/4099949/CMakeError.log)

**Comment by jhand2** [comment]
Hi @IvillanuevaItba,

Can you provide the following details:

1. How did you install OE dependencies?
Note that you can find instructions for building OE on windows here: https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsSGX1GettingStarted.md
In particular the `install-windows-prereqs.ps1` script will install needed dependencies.

2. How did you install OE itself? Did you build it from source or simply install the binaries? Where is it installed on the machine

3. Please provide the cmake command-line you used to build this sample

**Comment by IvillanuevaItba** [comment]
> 1. How did you install OE dependencies?
>    Note that you can find instructions for building OE on windows here: https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsSGX1GettingStarted.md
>    In particular the `install-windows-prereqs.ps1` script will install needed dependencies.

I didn't not see that part of the documentation, I was following the docs inside GettingStartedDocs. I'll check that out and get back to you.

Thank you!

**Comment by IvillanuevaItba** [comment]
When running install-windows-prereqs.ps1 it's getting hung up at:

`Start-ExecuteWithRetryRetryMessage: Failed to download http://registrationcenterdownload.intel.com/akdlm/irc_nas/16115/Intel%20SGX%20PSW%20for%20Windows%20v2.5.101.3.exe. Retrying`

`Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."`

Seems to be the download link for Intel SGX DCAP for Windows, which requires logging in to Intel's website.

**Comment by jhand2** [comment]
Can you update to the latest master and rerun the script? The current PSW version was updated a couple days ago and is at http://registrationcenter-download.intel.com/akdlm/irc_nas/16115/Intel%20SGX%20PSW%20for%20Windows%20v2.6.100.2.exe

**Comment by IvillanuevaItba** [comment]
Sorry to be a bother. I got the last version from git, it got through the last problem, but now I'm getting this error. I have Windows 10 Pro Version 1909. PSW should be already installed, since  Intel Software Guard Extensions appears in Device Manager under Software Components and System Devices. 

![image](https://user-images.githubusercontent.com/40722107/72949125-1feff700-3d66-11ea-9994-f0ad2f845718.png)

**Comment by jhand2** [comment]
Ah. It looks like newer versions of Windows 10 install the PSW via  Windows Update rather than though this installer. Can you add the option `-LaunchConfiguration SGX1FLC-NoDriver` to skip the step to install PSW?

**Comment by IvillanuevaItba** [comment]
I did that, and it sort of works! (I think...)

**Comment by jhand2** [comment]
There are currently some issues with attestation on non-Azure machines that we are working with Intel to resolve.

As for the PATH issue, feel free to open an issue describing what you had to change and I'll take a look (or feel free to open a PR if you want).

I'll leave this issue open until I fix up this Windows 10 instructions to skip PSW installation.

Glad things are mostly working now!
