### ISSUE TITLE
oesign requires OpenSSL engine support

### ISSUE THREAD

**Issue by yakman2020** [openenclave/openenclave#2457]
oesign does not currently support getting keys from an openssl engine. This support allows for signing by arbitrary keys that are not owned by the developer. 

This is a blocking issue, as the use of pem files for signing is not permitted.

**Comment by jhand2** [comment]
Please avoid referencing internal and proprietary requirements/processes in this github organization.

**Comment by radhikaj** [comment]
Also tracked by #2090.
