### ISSUE TITLE
Document oeedger8r build issues on Windows: ocaml/cygwin dependencies

### ISSUE THREAD

**Issue by douglasism** [openenclave/openenclave#2459]
(This is related to [issues/838](838)(closed).)

**Description**
I'm new to the project, and I set out to build the OE SDK on Windows, mostly following the [SGX build flow](../blob/master/docs/GettingStartedDocs/Contributors/WindowsSGX1GettingStarted.md) and the [manual Windows prereqs instructions](../blob/master/docs/GettingStartedDocs/Contributors/WindowsManualInstallPrereqs.md). (Thanks for that documentation.)  I ran into problems building oeedger8r that were difficult to troubleshoot: ocaml has package dependencies on cygwin versions of curl and tar, as described in [issues/838](838). (ocaml package dependencies also require elevated-administrator privileges due to symlink creation.)

**Requested Action**
Short of resolving the root cause, it would be helpful to highlight this problem in the GettingStartedDocs and describe the recommended manual steps to solve it.

**Comment by anakrish** [comment]
@andschwa Sorry to bother you. Does esy take care of this?

**Comment by andschwa** [comment]
@anakrish @douglasism There should no longer be any requirements on Cygwin or OCPWin at all. It should just be on [esy](https://esy.sh/). Given an installation of NPM on Windows, use `npm install -g esy` and ensure `esy` is in your path.

**Comment by anakrish** [comment]
Thanks @andschwa 

@douglasism Which version of the SDK were you trying out? The [manual Windows prereqs instructions](../blob/master/docs/GettingStartedDocs/Contributors/WindowsManualInstallPrereqs.md) points to use of esy which solves cygwin dependencies.

**Comment by anakrish** [comment]
oeedger8r has been rewritten in C++ and we no longer need special tools (ocaml/cygwin/esy) on Windows.
