### ISSUE TITLE
Some scan-build errors are false positives

### ISSUE THREAD

**Issue by ryanhsu19** [openenclave/openenclave#2464]
[Update: this issue has been resolved in PR #2468 by setting certain functions as noreturn functions.]

This is related to PR #2379 and PR #2407. About 90% of the rest of the bugs are found in third-party files and those generated by third-party test functions, while the other 10%, in my opinion, are due to `OE_ABORT()` either not recognized or not considered normal exit by scan-build.

Scan-build classifies these errors into four categories: dereference of null pointer, Unix API, double free and memory leak.

**enclave/core/sgx/td.c** (lines 96 and 105):
In function `td_pop_callsite()`, scan-build assumes either condition of the first if-statement is true, yet continues to follow the statement after `oe_abort()`. Therefore, either `td` (line 96) or `td->callsites` (line 105) results in dereference of a null pointer.

**tests/attestation_plugin/plugin/tests.c** (lines 370, 380, 408 and 421):
In brief, in each of the four “dereference of null pointer” errors, scan-build tries to continue the program even though an `OE_TEST()` fails (each in line 556 and in line 559) somewhere before the bug arises.

**tests/oeedger8r/enc/testdeepcopy.cpp** (line 226):
The “dereference of null pointer” occurs when scan-build assumes that `n` is not equal to zero and `iov` is null in line 221. This mean that the condition of `OE_TEST()` is false. However, it continues until line 226 when `iov` gets dereferenced.

**tests/crypto/utils.c** (line 36):
Like above, it assumes `str` is not null and `buf` is equal to null in line 27 and keeps going until it reaches line 36 where `buf` gets dereferenced.

**tests/argv/enc/enc.c** (line 43):
**tests/crypto/asn1_tests.c** (line 362):
**tests/crypto/ec_tests.c** (line 913):
Same here, three Unix API errors found in these three files are due to scan-build not aborting when the condition of the first `OE_TEST()` is false yet attempting to execute the second `OE_TEST()`, which uses the false condition of the first `OE_TEST()`.

**tests/memory/enc/basic.c** (lines 40, 104 and 107):
**tests/stdc/enc/enc.cpp** (line 276):
There are four memory errors in both files. Each allocation test ensures that allocation fails at the end of the test. Despite its purpose, scan-build worries that memory leaks when the condition of the last `OE_TEST()` fails. Note that in line 107 in tests/memory/enc/basic.c, the section where `ptr` is freed is reachable only if `OE_TEST()` succeeds (and, therefore, `ptr` is not null), but not if `OE_TEST()` fails (and, therefore, the program already aborts), so in my opinion the double-free problem does not exist.

**Comment by jhand2** [comment]
For the oe_abort one, can you try annotating the function with the noreturn attribute. You can do it like:

```
// In the declaration in the include/openenclave/enclave.h file
#include <openenclave/corelibc/bits/defs.h>

void oe_abort() OE_NO_RETURN;
```

Let me know if that fixes the warning. I'll take a look at the others when I get a chance.

**Comment by radhikaj** [comment]
Please change the pdf into markdown.

**Comment by ryanhsu19** [comment]
Since this issue has been resolved, I will close it shortly.
