### ISSUE TITLE
Document core ocalls made by the OE SDK implementation

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2467]
OE contains many ocalls which may be called by the implementation rather than being called explicitly by the enclave application.

Document what these ocalls are and how an enclave developer can opt out of including them when possible.

**Comment by radhikaj** [comment]
@jhand2 Please prototype approaches for opting into ocalls and figure out the best approach. Document as appropriate and submit a design PR.

**Comment by radhikaj** [comment]
This is not needed any more since we are publishing the edl files for all the ocalls that oeruntime makes
