### ISSUE TITLE
Standardize clang-8 support for OE SDK

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#2476]
Clang 8 and Clang 9 are now publicly available
Enclaves are compiled currently with Clang-7 on both Windows and Linux. Hosts are also compiled with Clang-7 on Linux.

This would mean:
1. Released packages are built with Clang-8
2. CI/CD uses Clang-8
3. Ansible and prereqs scripts use Clang-8

Some additional background here:
 VS 2019 uses Clang-8
 RHEL 8 comes with Clang-8.

**Comment by jhand2** [comment]
Consider intermediate update to clang-8

**Comment by BRMcLaren** [comment]
- [ ] Add Clang 8 to ansible https://github.com/openenclave/openenclave/pull/3574

- [ ] Reference clang 8 in global libraries for linux Test and merge in: openenclave/openenclave-ci#22

- [ ] Update Jenkins files for linux to refer to clang 8 https://github.com/openenclave/openenclave/pull/3578

- [ ] Remove clang 7 from ansible (need all the above complete first)

- [ ] Add LLVM 8 for windows https://github.com/openenclave/openenclave/pull/3580

- [ ] Change reference in Windows jenkins files to use clang 8 https://github.com/openenclave/openenclave/pull/3579

- [ ] Documentation changes

**Comment by CodeMonkeyLeet** [comment]
Additional tasks:
- [ ] Update devx vscode & vs extensions and CMakeSettings.json
- [ ] Update changelog
- [ ] Investigate re-enabling libcxx nodiscard_extensions test under clang-8
- [ ] Update Jenkinsfile for oeedger8r-cpp project

**Comment by CodeMonkeyLeet** [comment]
SIG-Arch is moving out of SIG-arch project as this is approved for implementation at this point and does not require further input from SIG-Arch.

**Comment by dthaler** [comment]
Removing from SIG-Arch per SIG-Arch meeting.   (Might be part of SIG-Tools or SIG-CI though)

**Comment by BRMcLaren** [comment]
Thanks, @CodeMonkeyLeet  @dthaler. Absorbing into SIG-CI.
