### ISSUE TITLE
Consider deprecating oeedl_file cmake function

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2481]
The oeedl_file cmake function is an 88 line file and all it does is slightly abstract something like this:

```
add_custom_command(
  OUTPUT safecrt_t.h safecrt_t.c
  DEPENDS ${EDL_FILE} edger8r
  COMMAND edger8r --trusted ${EDL_FILE} --search-path ${CMAKE_CURRENT_SOURCE_DIR}
```

Additionally, oeedl_file is pretty inflexible. It only allows passing a single edl search path and adding support for `n` paths is probably not worth the work. It would be better to just have each enclave app to call edger8r however they want.

The main motivation is for supporting installation of system edl (such as syscall.edl and tee.edl). If there is a system edl path then most enclaves will need to reference the installed paths, with oeedl_file wouldn't support.

**Comment by mingweishih** [comment]
Is it similar to #2325?

**Comment by mingweishih** [comment]
Seems like a dependency. After resolving #2325, we can remove oeedl :)

**Comment by jhand2** [comment]
Ah you're right. Closing this issue as a duplicate and assigning the other to myself.
