### ISSUE TITLE
Ensure compiler portability in public headers

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2486]
Compile all the samples and tests with `-Werror` and don't turn off any warnings. This will help ensure that our public headers don't trigger warnings regardless of how an enclave developer chooses to compile their enclave.

To support #2376 it would be great if we could also compile these things with C99

**Comment by jhand2** [comment]
A more comprehensive solution would be to have a test that includes every public header and makes use of every macro but this seemed operationally prohibitive.

**Comment by dthaler** [comment]
Every public API should have a test.   See PR #2163 and comments there from CGC members expressing support for that requirement.

**Comment by mingweishih** [comment]
Add note: `-Werror` has already been a default option to all the tests. #2892 adds a test that includes all the public headers (excluding 3rd party ones) and compiles them against C99 standard.

**Comment by radhikaj** [comment]
@mingweishih Can this be closed?

**Comment by mingweishih** [comment]
Sure, closing.
