### ISSUE TITLE
The mix of justified and non-justified text on the GitHub Pages docs is a major eye-sore

### ISSUE THREAD

**Issue by colemickens** [openenclave/openenclave#2488]
I sort of hate justified text in every usage online, but it's particularly grating on the OpenEnclave page: https://openenclave.io/sdk/

It's very weird to see this square blocks of text with inconsistent spacing, mixed right along in with normal non-justified text. At least one or the other would be less jarring. Removing it entirely makes it considerably easier to digest, but I realize that might be personal.

**Comment by jhand2** [comment]
That's fair, just left-aligning the text would probably be more readable.

@radhikaj You're listed as the maintainer for the website. Are you ok with this change?

**Comment by jhand2** [comment]
Addressed in https://github.com/openenclave/openenclave-site/pull/3

**Comment by radhikaj** [comment]
Thanks @jhand2. I merged the PR.
