### ISSUE TITLE
Community Resources (Matrix/Slack room?)

### ISSUE THREAD

**Issue by colemickens** [openenclave/openenclave#2489]
Hi!

Is there a Matrix room, possibly, for OpenEnclave? Less ideally, maybe there's a Slack room?

I'm just starting to dip my toes in this arena, so maybe there are better resources or a better place for me to start at, but OpenEnclave has my attention and I have some quick check-my-understanding style questions that would be useful to discuss in an IRC-style-chat setting.

Thanks!

**Comment by jhand2** [comment]
Hi Cole,

Welcome! We do have a gitter channel here: https://gitter.im/openenclave/community

I would be happy to answer what I can

**Comment by colemickens** [comment]
thanks!
