### ISSUE TITLE
A nuget package's Description property may not be more than 4000 characters long.

### ISSUE THREAD

**Issue by BRMcLaren** [openenclave/openenclave#2496]
The OE current description is too long and is causing issues with releases when uploading Nuget Packages.

Currently, the description is 4005 characters long. When packaged, it becomes 4036, as it stands our packaging description comes from the README. When viewed in plain text, this could be improved by providing a description.md that we build from to keep the attention focused on what the product accomplishes.

**Comment by jhand2** [comment]
Suggest creating a separate document with a package description in plaintext
