### ISSUE TITLE
Support TEE-based implementation of random_internal for TrustZone

### ISSUE THREAD

**Issue by mingweishih** [openenclave/openenclave#2498]
This is the follow-up of #892 and #2497. The `oe_random` now depends on the hardware-supported RNG. For the case of sgx, it uses `rdrand` instruction. For the case of TrustZone, there should be an equivalent implementation (e.g., using `TEE_GenerateRandom`).

**Comment by jhand2** [comment]
Look into getting op-tee on QEMU into CI/CD as well so we can test w/o arm hardware

**Comment by mingweishih** [comment]
Fixed by #2497
