### ISSUE TITLE
Forum for CI/CD Issues Encountered after 2/5/2020

### ISSUE THREAD

**Issue by BRMcLaren** [openenclave/openenclave#2503]
Please post issues of anything encountered.

There are Bors and SandBox support currently, only. Bors should only be able to run through PR's currently as this is expected behavior. Currently, non-admin users cannot use Sandbox. If this is needed to unblock you, please use https://oe-jenkins.eastus.cloudapp.azure.com/job/OpenEnclave-sandbox/

We want to ensure stability before rolling out every job, every permission, etc.

New CI/CD location is: https://oe-jenkins-dev.westeurope.cloudapp.azure.com/

Logs and outputs should be viewable to anonymous users.

**Comment by jhand2** [comment]
Since the update I am seeing `bors try` runs time out sporadically when trying to do a docker pull.

For example: https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/7/pipeline

**Comment by BRMcLaren** [comment]
@jhand2 Thanks for letting us know.

I discussed this with @ionutbalutoiu and believe it looks like a networking issue happening from time to time when pulling the Docker images for the tests.

A change will be coming to allow pre-cached docker images to fix the requirements of pulling down an image anytime. Please bear with us.

**Comment by ionutbalutoiu** [comment]
> Since the update I am seeing `bors try` runs time out sporadically when trying to do a docker pull.
> 
> For example: https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/7/pipeline

The Docker images are cached now, and the `docker pull` issue shouldn't pop up again.

**Comment by BRMcLaren** [comment]
Thanks @ionutbalutoiu!

**Comment by BRMcLaren** [comment]
Closing after a week as no other issues have surfaced.
