### ISSUE TITLE
Host verification package does not include a sample

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#2512]
We would like samples for the host verification package to be written and installed. Jenkins, as part of package release, can install the host verification package and then build/run the sample.

We should also address the documentation in  https://github.com/openenclave/openenclave/issues/2513 at the same time.

**Comment by Francis-Liu** [comment]
I have downloaded open-enclave.0.7.0.nupkg and open-enclave.0.8.0.nupkg. It seems the missing folder @radhikaj was referring to is `openenclave\`.

**Comment by jhand2** [comment]
@Francis-Liu that isn't relevant to this issue right? This issue is there currently there are no samples written for how to use the host verification library

**Comment by radhikaj** [comment]
@jhand2 is right. Since there is no sample, there is no easy way to test the host verification package

**Comment by radhikaj** [comment]
@yentsanglee i am assigning this back to yoy
