### ISSUE TITLE
Add documentation of host verification package

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#2513]
There is no documentation on how the host verification package can be used. If we are releasing these packages, there should be clear docs on how to consume them.
Recommend adding a new page here: https://github.com/openenclave/openenclave/tree/master/docs/GettingStartedDocs

**Comment by BRMcLaren** [comment]
https://github.com/openenclave/openenclave/pull/2462

Might be of some help.

**Comment by yentsanglee** [comment]
oe_verify_remote_report() is mentioned in docs\DesignDocs\RemoteAttestationCollaterals.md a little but it should be described better.

**Comment by dthaler** [comment]
The draft API guidelines say:
> All public APIs must be used in some sample code or snippet. Ideally, the sample
> should be one that is compiled as part of the build, and uses no experimental APIs. For rarely 
> used public APIs, the sample might simply be a snippet in the doxygen comments.

I don't see any such sample, is there one?   If not, should oe_verify_remote_report() be tagged as Experimental?

**Comment by jhand2** [comment]
I think that would be covered by #2512. I agree adding a sample should be prioritized.

**Comment by soccerGB** [comment]
Merged with https://github.com/openenclave/openenclave/issues/2512

**Comment by jhand2** [comment]
@soccerGB #2512 is an issue not a PR. Is there a PR was merged that documents this library/package? I didn' see anything

**Comment by soccerGB** [comment]
The plan is to provide documentation along with the sample we are going to add.

**Comment by jhand2** [comment]
Ok, we should wait to close this issue until that is merged.
