### ISSUE TITLE
CI/CD to test host verification package

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#2519]
We are missing tests in the Jenkins pipeline to test the host verification package. Once #2152 is fixed, a Jenkins job can be added to test the host verification package.

**Comment by soccerGB** [comment]
Merged with https://github.com/openenclave/openenclave/issues/1819

**Comment by jhand2** [comment]
I don't think this is necessarily a duplicate. Specifically we need a CI/CD pipeline that tests installation of the host verification nuget package. Is this done?

**Comment by yentsanglee** [comment]
Similar to ACCPackageTest() in .jenkins\pipelines\Azure\Linux\Jenkinsfile, except
. create in node(AGENTS_LABELS["ubuntu-nonsgx"])
. cmake with host-verify specific definitions

**Comment by BRMcLaren** [comment]
@yentsanglee, could you explain? Will this add a sample to be tested in CI?

**Comment by ryanhsu19** [comment]
@BRMcLaren I will open a pull request to integrate the host-verify sample test to the host verification test of the CI/CD soon. The package installation will take more time though.

**Comment by ryanhsu19** [comment]
#3305 includes building and installing of `host-verify` package as well as testing of `host-verify` sample on `Azure-Linux` pipeline. Is it sufficient, or should I also modify the `cpack` routine on `Azure-Nightly` pipeline?

**Comment by BRMcLaren** [comment]
Thanks @ryanhsu19  this is sufficent!
