### ISSUE TITLE
Document workflow for submitting a PR and getting it merged

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#2528]
Aeva found that our documentation on the process from submitting a PR to it actually getting merged is unclear. Some areas missing were related to bors merging it, how one could use bors try etc. Opening  an issue to track this.

**Comment by jhand2** [comment]
dup of #1920?

**Comment by radhikaj** [comment]
> dup of #1920?

I will go and add comments around bors to 1920. And close this issue.
