### ISSUE TITLE
Document behavior of time APIs inside enclave

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#2535]
The system calls to get time(gettimeofday, time, clock_gettime) are insecure but currently the only way we have to check if a cert is expired. Document so developers are aware.

**Comment by jxyang** [comment]
Do we have plan to enable trusted time in enclave? We received customer request that a contract with expiry has to be enforced inside enclave. @pushkarcMS

**Comment by jhand2** [comment]
We should consider providing a secure time API in OE and fail if it is not supported. (Maybe open a suggestion issue to track this if one doesn't already exist).

**Comment by radhikaj** [comment]
Closing issue since I found documentation related to time APIs being unsecure: 

time.h | Partial | All time functions implicitly call out to untrusted host for   time values. The resulting time values should not be used for security   purposes.   Supported functions: time(), gettimeofday(), clock_gettime(),   nanosleep(). Please note that clock_gettime() only supports   CLOCK_REALTIME
-- | -- | --
