### ISSUE TITLE
Jenkins set file's modification time in the future.

### ISSUE THREAD

**Issue by nonpolarity** [openenclave/openenclave#2536]
These files are from the nuget package of cpack on Jenkins.
alvin@weichenv081 MINGW64 /c/open-enclave.0.8.1/openenclave/share/openenclave/samples/attested_tls
$ stat CMakeLists.txt
  File: CMakeLists.txt
  Size: 1386            Blocks: 4          IO Block: 65536  regular file
Device: 14abd27bh/346804859d    Inode: 1125899907054474  Links: 1
Access: (0644/-rw-r--r--)  Uid: (197108/   alvin)   Gid: (197121/ UNKNOWN)
Access: 2020-02-10 15:38:43.752300400 -0800
**Modify: 2020-02-10 18:47:16.000000000 -0800**
Change: 2020-02-10 15:38:43.752300400 -0800
 Birth: 2020-02-10 15:38:43.752300400 -0800

alvin@weichenv081 MINGW64 /c/open-enclave.0.8.1/openenclave/share/openenclave/samples/attested_tls
$ date
**Mon, Feb 10, 2020  3:39:08 PM**

alvin@weichenv081 MINGW64 /c/open-enclave.0.8.1/openenclave/share/openenclave/samples/attested_tls
$ TZUTIL //g
Pacific Standard Time

Since cmake/make/ninja use the modify time to check the necessity of compiling, this will trigger some error if the pack is used before file's modification time.

**Comment by BRMcLaren** [comment]
The build happened in GMT, which is how this was caused.

I am not certain this is fix-able, because even if we compile in a different time zone, someone somewhere needs to wait.

@radhikaj @jhand2 @nonpolarity, I think the only fix here is to build the packages a day before release?

**Comment by nonpolarity** [comment]
@BRMcLaren no matter what is the local timezone, the corresponding UTC for the system clock should keep punctuality. Actually file's modification time is recorded as UTC. The local time is the human-friendly way for people to interpret the UTC time.

**Comment by jhand2** [comment]
Ya we should just always use UTC timestamps for everything in the build system and tooling

**Comment by BRMcLaren** [comment]
So, this was a weird issue.

I looked into all the Jenkins servers and tooling that was used. Everything was UTC, it ended up being part of the image creation that we use for our ci agent hosts.

I added an init script that double-checks that all servers are using UTC moving forwards. Forgot to close the issue and doing so now.

**Comment by nonpolarity** [comment]
Administrator@wechen3 /cygdrive/c/Users/Administrator/Downloads
$ stat open-enclave.0.10.0-rc1/openenclave/share/openenclave/samples/helloworld//CMakeLists.txt
  File: open-enclave.0.10.0-rc1/openenclave/share/openenclave/samples/helloworld//CMakeLists.txt
  Size: 1474            Blocks: 4          IO Block: 65536  regular file
Device: 42e55cbbh/1122327739d   Inode: 1970324837651657  Links: 1
Access: (0700/-rwx------)  Uid: (197108/Administrator)   Gid: (197121/    None)
Access: 2020-07-15 10:48:40.289055500 -0700
**Modify: 2020-07-14 18:56:40.000000000 -0700**
Change: 2020-07-15 10:48:40.290052700 -0700
 Birth: 2020-07-15 10:48:40.289055500 -0700

Administrator@wechen3 /cygdrive/c/Users/Administrator/Downloads
$ stat open-enclave.0.10.0-rc1.nupkg
  File: open-enclave.0.10.0-rc1.nupkg
  Size: 8267235         Blocks: 8076       IO Block: 65536  regular file
Device: 42e55cbbh/1122327739d   Inode: 6755399441399370  Links: 1
Access: (0700/-rwx------)  Uid: (197108/Administrator)   Gid: (197121/    None)
Access: 2020-07-15 10:47:04.017727900 -0700
Modify: 2020-07-15 10:47:04.017727900 -0700
Change: 2020-07-15 10:48:15.871540900 -0700
 **Birth: 2020-07-14 12:42:24.000000000 -0700**

@BRMcLaren I think the system clock was still in the future. Could you reopen this issue?

**Comment by BRMcLaren** [comment]
@nonpolarity that build was not from Jenkins.
