### ISSUE TITLE
After realloc, clear contents of the old buffer

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#2537]
After realloc, clear the contents of the old buffer to prevent leaking secrets.

void* pNew = realloc(pOldBuffer, newSize);
memcpy(pNew, pOldBuffer, oldSize);
memset(pOldBuffer, 0, oldSize); //This is what we should take care of in this issue.
free(pOldBuffer);

**Comment by jhand2** [comment]
Consider adding a secure realloc function rather than changing the libc realloc function.

**Comment by douglasism** [comment]
Hi @radhikaj I'm probably stating the obvious, but be sure to use oe_memset_s to ensure the memset isn't optimized away by the compiler.

**Comment by radhikaj** [comment]
With the OE SDK, developers can choose to memset the memory themselves. Consistently, the OE SDK does not clear memory on free and realloc. We expect developers to take care of it.
