### ISSUE TITLE
Support semantic versioning by OE release 1.0

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2543]
We should support (semantic versioning)[https://semver.org/] by the time we reach a v1.0 release of OE.

Reasoning from @AevaOnline
> Breaking public API changes damage the community's trust in a project, so I'd like us to follow a deprecation cycle that's consistent and clear -- and I like that this proposal makes it clear. I suggest that we adopt a strong stance on guaranteeing the stability of public APIs as early as is reasonably possible, but no sooner.
However, if we adhered to SemVer, then a breaking API change -- and that includes the removal of a public stable API -- must always be accompanied by a major version change in the API.

**Comment by jhand2** [comment]
Also look into `Releasing.md` to figure out what is documented and what we are doing incorrectly as of now.

**Comment by andschwa** [comment]
Just FYI:
- https://github.com/openenclave/openenclave/blob/master/CHANGELOG.md#changelog
- https://github.com/openenclave/openenclave/blob/master/docs/Releasing.md#version-bump

**Comment by jhand2** [comment]
Ya it sounds like from triage we already document that we do this. But the deprecation model has maybe not been followed in the past.

I'll double check the documentation to make sure we aren't missing anything and then close this. Beyond that, its just a matter of following the rules we've outlined 😄

**Comment by radhikaj** [comment]
Everything is pretty well documented now.
