### ISSUE TITLE
oesign fails on non-FLC machine

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#2544]
The OE SDK can be used to build for either FLC or legacy SGX machines.  However, even if you built for legacy SGX, and want to sign for legacy SGX, the oesign tool will fail unless it's run on a machine with sgx_dcap_ql.dll installed, which is only required for FLC machines.

Expected behavior is that oesign works either way and only requires FLC support when signing an FLC enclave.   That is, a dev/build machine that is just doing legacy SGX enclaves should not need sgx_dcap_ql.dll installed.

In the future, if oesign is able to sign OP-TEE enclaves as well, it should also be runnable without installing any SGX prerequisites, unless you are explicitly trying to sign an SGX enclave.

**Comment by radhikaj** [comment]
This is likely the same issue reported here: #2264

**Comment by jxyang** [comment]
This issue is different from #2264, which wants to take out dependency on sgx_enclave_common and other intel libraries, but not including sgx_dcap_ql.dll.

In 0.7, we already took out the dependency on sgx_dcap_ql.dll for oesign. I just ran oesign built from 0.7 on a SGX1 machine (without FLC), and it is fine. The dependency walker also shows there is dependency on sgx_enclave_common but not sgx_dcap_ql.dll for 0.7 oesign.

Maybe we introduced the dependency back mistakenly lately?

**Comment by jhand2** [comment]
Indeed, running `ldd oesign`on oesign built from master does not show sgx_dcap_ql.so as a dependency. 

Likewise `dumpbin /dependents oesign.exe` doesn't show sgx_dcap_ql.dll as a dependency on Windows

Linux:
```
$ ldd oesign 
        linux-vdso.so.1 (0x00007ffc8d7f9000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f391c7da000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f391c5d6000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f391c3b7000)
        libsgx_enclave_common.so.1 => /usr/lib/x86_64-linux-gnu/libsgx_enclave_common.so.1 (0x00007f391c1b1000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f391bdc0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f391cca5000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f391ba37000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f391b699000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f391b481000)
```

Windows:
```
C:\code\openenclave\build\install\bin>dumpbin /dependents oesign.exe
Microsoft (R) COFF/PE Dumper Version 14.23.28107.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file oesign.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    WS2_32.dll
    bcrypt.dll
    CRYPT32.dll
    api-ms-win-core-synch-l1-2-0.dll
    sgx_enclave_common.dll
    KERNEL32.dll
    VCRUNTIME140D.dll
    ucrtbased.dll
```

**Comment by radhikaj** [comment]
> This issue is different from #2264, which wants to take out dependency on sgx_enclave_common and other intel libraries, but not including sgx_dcap_ql.dll.
> 
> In 0.7, we already took out the dependency on sgx_dcap_ql.dll for oesign. I just ran oesign built from 0.7 on a SGX1 machine (without FLC), and it is fine. The dependency walker also shows there is dependency on sgx_enclave_common but not sgx_dcap_ql.dll for 0.7 oesign.
> 
> Maybe we introduced the dependency back mistakenly lately?

@jxyang:
On Windows:
When building with HAS_QUOTE_PROVIDER=OFF, there is no dependency on sgx_dcap_ql.dll. I suspect this is what you tried. This is true for v0.7.0 and v0.8.0.

When using the Nuget Package on Windows(I have not verified what happends on Linux), oesign has a dependency on sgx_dcap_ql.dl. This is true for 0.7.0 and 0.8.0.

This is the output I see for the oesign in the 0.7.0NuGet Package:
Under windbg: 0:000> bm oesign!sgx_qe*
breakpoint 1 redefined
  1: 00007ff7`6033c418 @!"oesign!sgx_qe_get_quote"
breakpoint 2 redefined
  2: 00007ff7`6033c412 @!"oesign!sgx_qe_get_quote_size"
breakpoint 3 redefined
  3: 00007ff7`6033c40c @!"oesign!sgx_qe_get_target_info

Also see 
![image](https://user-images.githubusercontent.com/6453577/74391935-732ff500-4dba-11ea-96f6-7d59f992b4b9.png)


My suspicion is that these APIs are not called, but not being optimized out. See issue https://github.com/openenclave/openenclave/issues/2546 I filed as a follow up.

**Comment by dthaler** [comment]
Question: why is SGX required on the signing machine?  Is it impossible to sign a binary to run on SGX, from a machine without SGX?

**Comment by achamayou** [comment]
@dthaler I’m also really interested in the answer to that question, our CI/CD pipeline could be quite a bit simpler/cheaper if it wasn’t for this restriction.

**Comment by jxyang** [comment]
@dthaler We need the SGX hardware to do the measurement, and then we put the MRENCLAVE inside oeinfo of the elf image.

**Comment by dthaler** [comment]
@jxyang That's what I don't get.  If every SGX CPU can compute the same measurement, then why can't the MRENCLAVE calculation be done in software?
