### ISSUE TITLE
Crash due to missing locks around enclave->bindings

### ISSUE THREAD

**Issue by mikbras** [openenclave/openenclave#2569]
A multi-threaded test encountered the following crash.

```
2020-02-15T16:53:13.731807Z [(H)ERROR] tid(0x7fa56f7fe700) | tcs=0x81260000
 [/root/openenclave/host/sgx/enclavemanager.c:oe_query_enclave_instance:199]
 ./run: line 1: 19776 Aborted                 (core dumped)
 ```

This due to missing locks here and in other places that should protect these fields:

```
oe_enclave_t.bindings
oe_enclave_t.num_bindings
```

**Comment by mikbras** [comment]
Fixed by PR #2570

**Comment by jhand2** [comment]
Can you give more details on which test was failing and under what circumstances?

**Comment by jhand2** [comment]
We should consider adding better testing to stress test our thread-safety

**Comment by achamayou** [comment]
@radhikaj can we please raise the priority of this item and get the fix merged?

It's a safety issue in multi-threaded applications, there is no user workaround at this time, it shouldn't take a month to make it to master.

**Comment by jhand2** [comment]
It takes a month when the PR author doesn't bother to respond to feedback
