### ISSUE TITLE
oe_get_evidence() flags parameter does not apply to some attestation formats

### ISSUE THREAD

**Issue by yentsanglee** [openenclave/openenclave#2571]
The second parameter of oe_get_evidence() defined in [plugin.h](https://github.com/openenclave/openenclave/blob/master/include/openenclave/attestation/plugin.h) is used to indicate if the evidence is for local or remote attestation. It may not apply to some attestation formats. For example, setting evidence_format to SGX EPID and flags to LOCAL is invalid.

oe_result_t oe_get_evidence(
    const oe_uuid_t* evidence_format_uuid,
    uint32_t flags,
    const oe_claim_t* custom_claims,
    size_t custom_claims_length,
    const void* opt_params,
    size_t opt_params_size,
    uint8_t** evidence_buffer,
    size_t* evidence_buffer_size,
    uint8_t** endorsements_buffer,
    size_t* endorsements_buffer_size);

The suggestion is to combine 'evidence_format_uuid' and 'flags' parameters. For example, remove 'flags' and define these evidence formats:
- OE_SGX_LOCAL_ATTESTATION_UUID
- OE_SGX_ECDSA_P256_ATTESTATION_UUID
- OE_SGX_EPID_ATTESTATION_UUID

**Comment by jhand2** [comment]
Can look into `oe_get_report()` to see how in the past it has been handled to version APIs.

@CodeMonkeyLeet to provide more details

**Comment by CodeMonkeyLeet** [comment]
For examples on how to version and deprecate a public API, see:
1. Introduce signature breaking APIs: https://github.com/openenclave/openenclave/commit/e5e7f0dddaa6d9759f838515d00f0064df177935
    - Because we're pre-v1.0 of the SDK, we're okay with switching the default macro mapping to the new implementation by default in the same step.
2. Blocking old APIs: https://github.com/openenclave/openenclave/commit/b799790f35f575bb7f359fb91348f81b2a433652

**Comment by shnwc** [comment]
Is this PR fixed by PR #2579 ?

**Comment by jhand2** [comment]
@shnwc, yes this is addressed in that PR

**Comment by dthaler** [comment]
Now fixed
