### ISSUE TITLE
Helper function to parse oe_endorsements_t

### ISSUE THREAD

**Issue by jazzybluesea** [openenclave/openenclave#2583]
**Problem**
Attestation endorsements returned by _oe_get_evidence()_ is an opaque structure.  For users who want to parse and access the endorsement fields, it would be nice to have a function that parses the fields in the buffer and returns an array of pointers pointing to the different fields.  This helper function would apply to all attestation plug-ins given that the format of the endorsement buffer is the same across plug-ins.  See _oe_endorsements_t_.

**Function prototype**
```
oe_result_t oe_parse_endorsements( 
  uint8_t* endorsement_buffer,              // Input raw buffer with the endorsement fields
  size_t endorsement_buffer_size,           // Input raw buffer size
  uint8_t* endorsement_fields_array,        // Input/output.  Array of uint8_t*
  size_t  endorsement_fields_array_size,    // Size of array of uint8_t*
  size_t* endorsement_fields_actual_size);  // Actual number of fields set in array of uint8_t*
```

**Comment by jhand2** [comment]
Do we document/require that the format of this structure be the same for all plugins? If we want to provide functions to work with the structure then it needs to be a defined contract.

**Comment by jazzybluesea** [comment]
Good point, we will have to clearly document this requirement for plug-in writers.  The struct _oe_endorsements_t_ is very generic and should accommodate all plug-ins.

**Comment by jhand2** [comment]
If the structure needs to follow a certain format, should it be an opaque buffer, or should we just actually define the structure and make that the out param of `oe_get_evidence`?

@yentsanglee expressed an interest in changing the signature of oe_get_evidence anyway, so if we have to deprecate an API I want to make sure we get it right this time around.

**Comment by jazzybluesea** [comment]
@jhand2 I think there is something in the middle here.  Keeping it opaque gives the user the option to choose their own format without having to force the user to user the standard one.  In that case, the user will have to use their own parser.

**Comment by jhand2** [comment]
If we don't want to lock people into a format I don't feel good about exposing public APIs that only work some of the time/with some plugins.

If the structure contract is just between the plugin and the remote party then OE shouldn't expose APIs to do operations on the structure.

**Comment by yentsanglee** [comment]
The plugin was designed the way that oe_get_evidence() returns evidence and endorsements. Both become input of oe_verify_evidence(). To the application, the data structure are opaque. Only plugin attester and verifier know the data structure. I agree with @jhand2 - I don't think we should expose public APIs to operate on the structure.

**Comment by radhikaj** [comment]
Based on triage, this does not belong in the OE SDK repo and should reside with the plugins. 
OE SDK can have a sample plugin(no-op plugin), that does not do anything specific SGX plugin->we want to be able to run ci/cd and ensure that the plugin APIs work.
