### ISSUE TITLE
Refactor core EDL to allow inclusion of smaller subsets of functionality

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2585]
Currently all the OE-defined ECalls/OCalls are in 3 edl files:
* tee.edl
* sgx.edl
* syscall.edl

These should be refactored to allow an enclave to just import discrete chunks of functionality. For example, the socket feature can be split out from syscall.edl into a separate socket.edl file that would only be imported by applications which wish to use sockets.

**Comment by radhikaj** [comment]
@mikbras says refactor into network and filesystem.
@dthaler : Anything that is common can be in a separate edl file that is imported by network and filesystem

**Comment by jhand2** [comment]
First round of refactoring in https://github.com/openenclave/openenclave/pull/2683

**Comment by jhand2** [comment]
syscall.edl refactored in https://github.com/openenclave/openenclave/pull/2685

**Comment by jhand2** [comment]
Last pieces implemented by https://github.com/openenclave/openenclave/pull/2784
