### ISSUE TITLE
Support zig-zag ocalls: enclave1-ecall -> ocall1 -> enclave2 ecall -> ocall2

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#2590]
With #2551, a context parameter is passed to ecalls. The context parameter contains a buffer that the ecall can use to allocate ocall parameters. This provides significant performance benefits as well as allows all ocalls to be implemented in EDL (maintainability and security).

Currently, the buffer is allocated in host's thread-local memory:
https://github.com/openenclave/openenclave/blob/89dba4c34e47e02383828c093c29ec35ef021f04/host/sgx/enter.c#L73

This is very efficient. However in the following call pattern:
   `enclave1-ecall -> ocall1 -> enclave2 ecall -> ocall2`

would result in ocall2 and ocall1 using the same buffer which would lead to incorrect results.

We need an efficient fix to handle this scenario.

**Comment by anakrish** [comment]
@jhand2 @nonpolarity Can either of you take this on?

**Comment by jhand2** [comment]
Good catch. I might have some time to look into this but I have a couple other things I need to work on first. @nonpolarity if you have free time you can take it, otherwise I can pick this up once I have some time.

**Comment by radhikaj** [comment]
@anakrish Since this is a regression, please fix that for v0.9. This is an SGX only issue right now.
