### ISSUE TITLE
oehostapp and oehost are potentially redundant

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2595]
tl;dr We should remove either oehost or oehostapp cmake targets and just recommend one

Note, this would require a deprecation warning in v0.9 release

From @CodeMonkeyLeet in #2593:

> we currently expect everyone to link against oehostapp given the sample usage anyway, and so we ostensibly already recommend -rdynamic to be the default use case. We still make oehost available, presumably to provide an option without -rdynamic (and prior to this change, without noexecstack).
>
> Do you think providing a library that doesn't pull in -rdynamic in CMake by default is valuable? My understanding of -rdynamic is that it pulls in all symbols which is useful for backtracing and dynamic library load/link scenarios and is the preferable default. I assume this expands the size of the resulting binary; are there other potentially undesirable effects? Assuming we only have the -rdynamic default, is there an easy way to override that in a user's build? (e.g. I couldn't find a no-dynamic option).
>
> @jhand2 Yes, it would be a breaking change to remove one or the other library, but it's one of those things that's better to change sooner rather than later, and we would still want to mark deprecation in this release, then eliminate in the next one.

**Comment by radhikaj** [comment]
We will deprecate in v0.9 and will have only one of these in the next release.

**Comment by radhikaj** [comment]
@dthaler is using oehost.

**Comment by nonpolarity** [comment]
@CodeMonkeyLeet @anakrish Thanks for the discussion in #2593 . 
It seems now this issue depends on how to deal with the option "-rdynamic".  The pro is that with this option the dynsym can help to locate while dynamic loading. The con is that the extra size of object file, and potential performance loss to load the object.
Please add any opinions.

**Comment by radhikaj** [comment]
-rdynamic - If a dev uses oehost.lib and creates a dynamic library. Then the onus is on the developer to set -rdynamic. For v0.10, we will use oehost without -rdynamic.
