### ISSUE TITLE
Support as much of libc as is possible/secure/stable

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2598]
There are some libc functions that are not supported today in OE. Opening this issue to track overarching libc support.

* [X] Math function support is added by https://github.com/openenclave/openenclave/pull/2552
* [x] stdlib support is added by https://github.com/openenclave/openenclave/pull/2559

Up to date support in master can be found at https://github.com/openenclave/openenclave/blob/master/docs/LibcSupport.md

**Comment by radhikaj** [comment]
Thanks @jhand2 for finishing this.
