### ISSUE TITLE
[WEBSITE] Add "macOS" or remove "all software platforms"

### ISSUE THREAD

**Issue by lazaridiscom** [openenclave/openenclave#2610]
Visiting the website

https://openenclave.io/sdk/

the section "Core Tenents" mentions:

> Multi-platform
> Design with all software platforms, Windows and Linux, in mind

This needs to be corrected, either:
* Add macOS support
* Correct "all software platforms"

I usually write within projects "you can't ignore one of the major 3 platforms, which is Windows".

Well, now I write "you can't ignore one of the major 3 platforms, which is macOS"

**Comment by achamayou** [comment]
@lazaridiscom Intel does not release an SGX driver for macOS, so Windows and Linux are currently "all software platforms" on which you can use SGX hardware.

There is also no release of macOS targeting ARM, with or without OP-TEE.

It isn't effectively possible for the OpenEnclave SDK to target macOS or other platforms that do not support enclave hardware, so I think the statement is reasonable as it stands.

**Comment by lazaridiscom** [comment]
> so I think the statement is reasonable as it stands.

only if you provide the additional information, something like:

=> Design with all **SGX/enclave supported** software platforms, Windows and Linux, in mind

You need to add this info, otherwise it reads like MS is ignoring macOS existence.

**Comment by lazaridiscom** [comment]
@radhikaj , this Is technically still open.

**Comment by dthaler** [comment]
I agree this should still be open, and I agree with the filer's point.

**Comment by dthaler** [comment]
I just found Radhika's PR #5 and would be ok with either that or my PR #6 which I submitted before seeing Radhika's.

**Comment by radhikaj** [comment]
Merged Dave's PR.

**Comment by lazaridiscom** [comment]
@dthaler , the initial version of https://github.com/openenclave/openenclave-site/pull/5 was fine.

the corrected 5 and your https://github.com/openenclave/openenclave-site/pull/6 are not fine.

So my "nit" still stands:

"you can't ignore one of the major 3 platforms, which is macOS"

My comment  https://github.com/openenclave/openenclave-site/pull/5#issuecomment-592750722 is still actual, and this issue here is from my, (an external observers) view still open.

**Comment by lazaridiscom** [comment]
## Dual-Platform

Design with Windows and Linux in mind

**Comment by dthaler** [comment]
I believe the page accurately reflects the current state of the code.   This is an open source project which welcomes contributions from the community.  If someone contributes work on MacOS, that would be great!  Until then, I don't think the page is inaccurate in stating that it is currently designed for Windows and Linux.

**Comment by lazaridiscom** [comment]
## Multi-Platform (in 2020)

* Windows
* Linux

Source: @dthaler, Microsoft, The Openenclave Project

Resting my case.
