### ISSUE TITLE
CI: Enable Windows SGX Simulation mode testing

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#2614]
PR #2600 enables SGX Simulation Mode on Windows.
The CI needs to be updated to lock this down.

**Comment by radhikaj** [comment]
If the community can get this done, we can have this work scheduled for v0.9. Otherwise, we will move it to backlog.

**Comment by BRMcLaren** [comment]
@radhikaj I was waiting on a build, got around to it. Merging now
