### ISSUE TITLE
[COMPLAINT] DCO Requirement is Discriminating

### ISSUE THREAD

**Issue by ghost** [openenclave/openenclave#2615]
## Situation

https://github.com/openenclave/openenclave/blob/master/docs/Contributing.md#developer-certificate-of-origin

I understand that this is something dictated by the linux-foundation, which shows once more that "linux" serves only freedom "as defined by the linux-foundation".

Personally, I do not want to have my name and email within each commit. I am fine to (digitally) sign a CLA, even an NDA (in commercial projects), but I don't want my email in each commit.

I recently left the Hyperledger project, because of the terrible organization of the linux-foundation, incl. its DCO requirement. 

Commit-histories polluted with "signed-off-by" nonsense - I mean, how can one focus on the essence?

And it seems that the linux-foundation ignores the procedures of the rest of the industry (like e.g. SAP with it's nice https://cla-assistant.io/).

## Discrimination

**A) Privacy:** I don't want my name and email within each commit.

**B) Noise:** I become highly distracted by (technically) non-relevant information

How can I still contribute on code-level to this project?

**Comment by jhand2** [comment]
As a Linux Foundation project, we are following Linux Foundation guidance in using DCO. Any complaints or recommendations should be addressed in the appropriate forum with the Linux Foundation
