### ISSUE TITLE
How to write data to a secure file like Intel SGX SDK?

### ISSUE THREAD

**Issue by sword03** [openenclave/openenclave#2616]
Intel SGX SDK provides an api "sgx_fopen_auto_key" to write data to secure file. How could I make it in Open Enclave?

**Comment by jhand2** [comment]
Currently OE only provides a normal/insecure filesystem. It provides cryptographic functions via mbedtls to allow to to encrypt data prior to writing it over an insecure channel.

**Comment by sword03** [comment]
> Currently OE only provides a normal/insecure filesystem. It provides cryptographic functions via mbedtls to allow to to encrypt data prior to writing it over an insecure channel.

That's right. Data must be encrypted before writing to insecure file as follows:
https://github.com/openenclave/openenclave/tree/master/samples/data-sealing
