### ISSUE TITLE
Windows prereqs script fails with new Azure DCAP NuGet 

### ISSUE THREAD

**Issue by HernanGatta** [openenclave/openenclave#2623]
Three days ago, the Azure DCAP NuGet package was updated to version `1.2.0` from `0.0.3`.

The internal structure of the package no longer matches what the Windows prereqs script expects. Thus, the script fails.

[Line 641](https://github.com/openenclave/openenclave/blob/master/scripts/install-windows-prereqs.ps1#L641) in the script references `Azure.DCAP.Windows\script` to invoke `InstallAzureDCAP.ps1`, but the script is now under `Azure.DCAP.Windows\tools` in the NuGet package.

Curiously, even if the prereqs script specifies version `0.0.3` of the Azure DCAP NuGet package by downloading it first and setting a local package source, `nuget` still fetches `1.2.0`.

Additionally, the installation script inside the package (`InstallAzureDCAP.ps1`) was not updated to reflect the change in the package's directory layout, and thus fails even if the prereqs script is updated.

Said script attempts to copy `dll\dcap_quoteprov.dll` to a user-provided installation path, but the DLL is now under `build\native` in the package.

**Comment by radhikaj** [comment]
The script should be updated to use the right path. Please treat this as high priority

**Comment by BRMcLaren** [comment]
@radhikaj Does this mean the fix is to upgrade to 1.2?

@oprinmarius @ionutbalutoiu @paulcallen 

This issue has further reaching implications, and it's breaking the ability to rebuild the infrastructure when packer errors out trying to build the images. We need to look into this ASAP as blocking dependency changes and possible security fixes is an issue.

**Comment by HernanGatta** [comment]
@BRMcLaren: FWIW, I worked around this for the moment with `-Version 0.0.3` on [line 634](https://github.com/openenclave/openenclave/blob/master/scripts/install-windows-prereqs.ps1#L634).
