### ISSUE TITLE
Upgrade DCAP client to 1.2

### ISSUE THREAD

**Issue by BRMcLaren** [openenclave/openenclave#2627]
OE is currently using a 0.03 version of the DCAP client, with 1.2 out we should upgrade the CI and scripts to use the latest version.

**Comment by yentsanglee** [comment]
Azure DCAP client 1.2 adds collateral v2 supports. It's supposed to be compatible with OE SDK attestation which is still consuming collateral v1. However, the backward compatibility has never been thoroughly tested.

**Comment by radhikaj** [comment]
@paulcallen @BRMcLaren Please investigate this for v0.9.
