### ISSUE TITLE
[WEBSITE] Reopen #2610

### ISSUE THREAD

**Issue by lazaridiscom** [openenclave/openenclave#2638]
I file an issue, maintainers close, reopen, again close - whilst ignoring the essence of the issue.

#2610

I insist: 

"multi-platform" contains macOS. If not, then you need to clarify.

i gave a wording example. one dev adopted it, two others felt the need to continue ignoring macOS existence (and mine btw., but that's not the main problem).

**Comment by jhand2** [comment]
Open source software development is an inherently cooperative process. It is not enough to believe that your way is the right way, you must convince someone else that it is the right way.

I have heard your concern and I understand you have an opinion, but I don’t agree with the solution and so far nobody else has agreed with it either. I am happy that you want to contribute and I hope you continue to do so, but you should know that this is simply part of the process.

To address this specific issue, it is my opinion (shared by other commenters and contributors) that the documentation clearly states which operating systems the OE SDK supports. I’ll leave this issue open for now for others to weigh in.

**Comment by lazaridiscom** [comment]
> Open source software development is an inherently cooperative process. It is not enough to believe that your way is the right way, you must convince someone else that it is the right way.

Please spare this kind of talk for some juniors or internals.

>and so far nobody else has agreed with it either.

At least stop spreading misinformation.  My suggestion was adopted, until you intervened

https://github.com/openenclave/openenclave/issues/2610#issuecomment-594272005

>I understand you have an opinion

nah, you don't understand, thats the problem.

it is not my opinion, but a fact, but i'll not state it again.

> I’ll leave this issue open for now for others to weigh in.

i don't care about this issue here, i care that you realize your rudeness, and reopen the issue in question, which is #2610.

listening to external observers prevents you from making insider errors. opinion? or again a simple fact?

**Comment by andschwa** [comment]
Hi @lazaridiscom, as a member of Open Enclave's Community Governance Committee, I need to inform you that we have found your language and tone to be in violation of our stated [Code of Conduct](https://github.com/openenclave/openenclave/blob/master/docs/CodeOfConduct.md). Specifically, the above comment (among other interactions you have thus far made) is unwelcoming, insulting, and overall inappropriate for this community. This is an official warning to adhere to our Code of Conduct, and any further violations will result in escalated action, including but not limited to being banned from this project.

We would like to encourage all individuals to be able to participate in our community. To that end, our top priority is to create a positive environment. We encourage everyone to be respectful and use welcoming and inclusive language. We hope that you will realize the necessity of this, and would be happy to continue working with you if you can adjust your interactions appropriately.

Thank you,

Andy Schwartzmeyer on behalf of the Open Enclave Community Governance Committee

**Comment by lazaridiscom** [comment]
## Essence
"See, no CoC protects an freethinking-individual against mainstream masses, they stick always together and hide behind their (misinterpretd, by majority vote) CoCs."
source: https://github.com/confidential-computing/governance/issues/14#issuecomment-595817732

## The "CoC-Nanny" Intervenes
> and any further violations will result in escalated action, including but not limited to being banned from this project.

"but not limited", i think that is the mot interesting point:

**What else, beyond banning me, will you do?** 


> I need to inform you that we have found your language and tone to be in violation of our stated Code of Conduct. 

I need to inform you that you  people (the "we", the accusers-judges-executioners in one entity) have lost contact to reality.

**My "language and tone" is nothing special, and is part of my individual style of expression, especially when I am in a condition of "super-flow" and exposed to any form of inconsistency.**

**I will neither change my language, nor my tone or style. Both, language and tone, are perfectly valid, given the circumstances. I will remain myself, and will repel this attack to my individuality.**

## Counter

I found your processes, tone and language: discriminating, rude, unprofessional. It lacks focusing on the issues at hand (technical, terminology).

## The CoC-Fascism

Be aware that I have at this point no way to defend myself, as the construct "CoC and its application", is a one-way governance construct. One can easily label this as "CoC-Fascism" (so, now, you geniuses, did i just call you "fascists", or is this (... fill this in ...)

## Microsoft

It really looked like Microsoft is changing, and I really believe this sympathetic new CEO does well. But then, Open-Source has become less and less about freedom, even entities like Linux-Foundation behave like IT-fascists.

## Note to Readers 

Remember what this is all about. Essentially, a **Microsoft/Linux** governed project redefines "Multi-Platform" to be "Windows and Linux", ignoring 'macOS'.

I insist here, so Microsoft does not "loose face" (I don't care about Linux/Linux Foundation, they are damaged to no repair anyways).

Giving up: https://github.com/openenclave/openenclave/issues/2610#issuecomment-596048628

.

**Comment by lazaridiscom** [comment]
Please feel free to close this issue.

**Comment by andschwa** [comment]
On behalf of the Open Enclave Community Governance Committee, since the user @lazaridiscom violated our Code of Conduct after a formal warning and clearly stated refusal to abide by said Code of Conduct, the user has now been banned until further notice.
