### ISSUE TITLE
C++ functions missing in OE SDK

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#2646]
Intel SGX-SDK provides these missing functions and OE can consider adding them.
1.	cinttypes 
•	SGX SDK supports imaxabs() and imaxdiv(). OE does not.
2.	cmath 
•	OE does not support: acosh(), asinh(), fmal(), lgamma(), lgammaf(), sinh(), sinhl(), tgamma()
3.	functional 
•	The header exists in OE, but the OE documentation says it is not supported.
4.	tuple 
•	OE doc says there are known issues with tuple.apply (but doesn’t say what they are)
5.	utility 
•	OE doc says “as_const” is not supported. SGX SDK supports this in Linux when compiler used is C++17

**Comment by mingweishih** [comment]
Item 1, 3, 4, and 5 should be resolved by #2735. Will investigate the item 2 in another PR.

**Comment by mingweishih** [comment]
Most of the items are resolved in #2735. The remaining part are specific math functions as mentioned in #2639.
