### ISSUE TITLE
SGX verifier plugin shall verify the integrity of the serialized custom claims before extraction

### ISSUE THREAD

**Issue by shnwc** [openenclave/openenclave#2658]
In SGX verifier plugin code file common/sgx/verifier.c :

 Upon successful verification of the SGX report by oe_verify_quote_with_sgx_endorsements(), the _verify_evidence() function shall retrieve the hash value held in the report_data field (as defined in the oe_report_t structure), and use it to verify the integrity of the serialized claims. This verification shall be done before deserializing and extracting the claims.

**Comment by radhikaj** [comment]
@shnwc Is this a suggestion for a design? Please clarify so I can label appropriately.

**Comment by shnwc** [comment]
@radhikaj This is a bug in the code that needs to be fixed

**Comment by yentsanglee** [comment]
This is a bug in the built-in verifier. Will fix.

**Comment by yentsanglee** [comment]
Please assign to qiucwang.
