### ISSUE TITLE
Open Enclave users trust that SGX quote parsing is fuzz tested and secure

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#266]
`oe_verify_report` handling for remote attestation reports (SGX quotes) introduces a non-trivial amount of parsing code into the OE runtime. This includes:

* Logic to interpret Intel's binary SGX quote format and validate signatures over it
* Wrapper for mbedtls/openSSL ASN methods to parse custom Intel SGX PCK certificate extensions
* Minimal JSON parser for Intel's TCBInfo and QEIdentity blobs

Per security best-practices, we should run the quote handling code under fuzz testing to increase our confidence that the parsing logic is robust and secure.

**Comment by vishnumohan1991** [comment]
applications have been committed under branch parserapp@266

**Comment by johnkord** [comment]
There's no more additional work for v0.5.
