### ISSUE TITLE
Documentation: Link for downloading Intel DCP Library is broken

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#2665]
In https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsManualSGX1Prereqs.md, the link  in the following line is broken

> Firstly we download the Intel SGX DCAP self-extracting executable from [here](http://registrationcenter-download.intel.com/akdlm/irc_nas/16014/Intel%20SGX%20DCAP%20for%20Windows%20v1.4.100.4.exe).

**Comment by mingweishih** [comment]
We should fix the link based on #2664

**Comment by radhikaj** [comment]
#2684 fixed this
