### ISSUE TITLE
Use EDL to generate headers structures that are used in EDL

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2666]
# Current Behavior

Currently many of the structures passed as arguments in EDL functions are defined in C header and included into EDL. For example `oe_asymmetric_key_params_t` is used in `common/tee.edl` by including the bits/types.h header:

https://github.com/openenclave/openenclave/blob/99410b10b4782d33e76819bc681e651e96cd9739/common/tee.edl#L17

These structures are known as "foreign structures" as they are not defined in EDL.

# The problem

The problem with using foreign structures is that they cannot benefit from [EDL deep copy](https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/full_edl_serialization.md). On SGX, using foreign structures can pose security issues, since the enclave will be reading host memory. For trustzone, since the enclave and host to not share an address space, passing pointers that are not deep copied can cause crashes and other undefined behavior since the enclave cannot dereference host memory.

# Requirements
* Structures used as arguments in EDL functions can be annotated for EDL deep copy
* Structures passed as arguments in EDL can also be used by the enclave C code.

# Nice to have
* Enclave developers can somehow use C structures in their EDL
    * This could be defining a structure in EDL and then mapping it to a corresponding C structure with generated code to convert between the two.

**Comment by radhikaj** [comment]
Recommend: add guidance to developers once you have a solution.

**Comment by jhand2** [comment]
Some ideas I've come up with that may or may not work:
* Define all structures to be used by EDL files as EDL structs. Use edger8r to generate C headers
* Annotate C structures (via comments or macros) in a way that edger8r understands so it can do deep copy.
* Defining the same structure in C and EDL. Then provide a way to map them and autogenerate code to convert between the two. This would mean that the function the developer calls would take the C struct as a parameter, but under the hood the edger8r code would use the EDL-defined structure to do serialization.
