### ISSUE TITLE
The `install_lvi_mitigation_bindir` should install the wrappers for clang, clang-8, and clang-9

### ISSUE THREAD

**Issue by mingweishih** [openenclave/openenclave#2669]
#2651 supports using Make to build samples with clang, clang-8, or clang-9 (previously, only clang-7 available). Therefore, the `install_lvi_mitigation_bindir` script, which installs the compiler wrappers for supporting Load Value Injection(SGX) mitigation, should also add those clang wrappers to support this modification properly.

**Comment by anakrish** [comment]
Also, `install_lvi_mitigation_bindir` does not seem to handle '~' correctly.

**Comment by mingweishih** [comment]
Thanks @anakrish. I'll make a PR to address both issues.

**Comment by radhikaj** [comment]
Put this in v.10

**Comment by radhikaj** [comment]
Expand LVI
