### ISSUE TITLE
fedora cmake rules broken for ENABLE_REFMAN=on

### ISSUE THREAD

**Issue by yakman2020** [openenclave/openenclave#2681]
When building source on fedora 31 (and, I presume any redhat based distro, rhel, centos) the build rules for building doxygen do not identify dot correctly, then force themselves into trying to use  LaTeX, which reveals a cmake syntax error:

-- Found Doxygen: /usr/bin/doxygen (found version "1.8.15") found components:  doxygen dot 
CMake Error at build/CMakeDoxygenDefaults.cmake:471 (set):
  Syntax error in cmake code at

    /space/home/brcamp/Projects/openenclave/build/CMakeDoxygenDefaults.cmake:471

  when parsing string

    \makeindex

  Invalid character escape '\m'.
Call Stack (most recent call first):
  /usr/cmake-3.13.1-Linux-x86_64/share/cmake-3.13/Modules/FindDoxygen.cmake:958 (include)
  docs/refman/CMakeLists.txt:41 (doxygen_add_docs)

Workaround: 
cmake -DENABLE_REFMAN=OFF on fedora, rhel, centos.

**Comment by jhand2** [comment]
I use fedora 31 at home and am unable to repro this. Note it is a non-SGX machine and I'm running cmake 3.16 (rather than 3.13)

**Comment by radhikaj** [comment]
Closing since this does not repro with newer cmake.
