### ISSUE TITLE
EC Private Key PEM read/write APIs

### ISSUE THREAD

**Issue by bodzhang** [openenclave/openenclave#2696]
In [include/openenclave/internal/crypto/ec.h](https://github.com/openenclave/openenclave/blob/master/include/openenclave/internal/crypto/ec.h):
oe_ec_private_key_write_pem(const oe_ec_private_key_t* private_key, uint8_t* pem_data, size_t* pem_size);

In [include/openenclave/internal/ec.h](https://github.com/openenclave/openenclave/blob/master/include/openenclave/internal/ec.h):
oe_result_t oe_ec_private_key_read_pem(oe_ec_private_key_t* private_key,const uint8_t* pem_data, size_t pem_size);

These two APIs seem to indicate the pem format private key is not protected. Without the protection such as how similar OpenSSL APIs using password to protect the private key in pem file, the private key would be exposed if the pem format data leaves the TEE.

Is the intended use of the two APIs for pem format data exchange between functions within the TEE environment only?

**Comment by jhand2** [comment]
> Is the intended use of the two APIs for pem format data exchange between functions within the TEE environment only?

Yes these functions are for internal enclave use only (the headers aren't installed with the SDK) and the private key is not exposed outside the enclave.
