### ISSUE TITLE
how to build oeedger8r ？

### ISSUE THREAD

**Issue by hixuu** [openenclave/openenclave#2704]
how to build oeedger8r separately ?without esy

**Comment by jhand2** [comment]
We used to build oeedger8r with the native ocaml build tools, but switched to esy because it worked better for building on both Windows and Linux.

Is there a specific reason you cannot use esy?

**Comment by hixuu** [comment]
yes, I meet a problem when installing esy. T.T
or is there any binary avaliable for Linux os ?

`> esy-solve-cudf@0.1.10 postinstall /usr/local/lib/node_modules/esy/node_modules/esy-solve-cudf
> node ./postinstall.js


/usr/local/lib/node_modules/esy/node_modules/esy-solve-cudf/postinstall.js:7
const install = (filename) => {
                            ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
`

**Comment by anakrish** [comment]
@hixuu 

To use the OE SDK, you need not necessarily build it from the scratch.
You can use prebuilt libraries and binaries (oeedger8r,oegdb, oesign etc) by installing the latest packages from here: https://github.com/openenclave/openenclave/releases . 

We can also help you with issues regarding building the OE SDK.
What is the version of nodejs installed in the system?

**Comment by hixuu** [comment]
thank you for your reply. 
my nodejs version is v0.10.25.
I want to setup environment for OPTEE SDK. but it's seems there are some dependencies on SGX.
hmm, does the prebuilt  binaries works with OPTEE ?

**Comment by anakrish** [comment]
@HernanGatta, @dthaler  Can you follow up with @hixuu about setting up OE for OPTEE SDK?

**Comment by dthaler** [comment]
See https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/OP-TEE/Introduction.md

**Comment by dthaler** [comment]
Also issue #2720 tracks ongoing investigation about prebuilt binaries

**Comment by radhikaj** [comment]
@hixuu  Does the above information answer your question?

**Comment by HernanGatta** [comment]
Just to add some details, the SDK currently doesn't ship binary packages for OP-TEE. The reason, as briefly outlined in the issue that Dave linked to, is that, depending on the board that you choose to use, you may build OP-TEE with different configuration parameters. This, in turn, affects the Dev Kit that OP-TEE generates, which the SDK consumes during its build.

There are still discussions to be had as to how to best work this problem, but for the moment it is necessary to build the SDK from source when using it to work with OP-TEE.

If you are running into issues building the SDK on your system, I would recommend that you use a container to do it in. That way, you'll have a clean environment to start off with, and if something goes wrong, you can start again without modifying your system.

LXD containers work great for this. For example, this is what I do for my own workflow:

```bash
# Run this one command once to map the container's user to your own
echo root:$UID:1 | sudo tee -a /etc/subuid /etc/subgid 

# Container name
CONTAINER=oesdk

# Create a container with an Ubuntu 18.04 image
lxc init ubuntu:18.04 $CONTAINER

# Mount your home directory inside the container
lxc config set $CONTAINER raw.idmap 'both 1000 1000'
lxc config device add $CONTAINER homedir disk source=$HOME path=$HOME

# Set the container's AppArmor profile to unconfined (allows mount/bind)
lxc config set $CONTAINER raw.lxc "lxc.apparmor.profile=unconfined"

# Start the container
lxc start $CONTAINER

# Get a Bash shell in the container
lxc exec $CONTAINER -- su ubuntu

# Follow the SDK guide you were previously using
# Run the commands to install Ansible and to get
# get the SDK's dependencies, all in the container

# To exit from the container, just quit the shell
exit
```

If you make a mistake or something goes wrong, you can `lxc delete $CONTAINER` and start again.

**Comment by mingweishih** [comment]
Now the oeedger8r is switched to C++ implementation. I'm closing this issue. Feel free to reopen if necessary.
