### ISSUE TITLE
Remove requirement for stub ecall in EDL files

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2713]
Currently oeedger8r requires EDL for an enclave to have at least one public ecall. This requirement seems unnecessary, there is no reason that an enclave must define an ecall.

In particular, removing this requirement would allow for an EDL file containing only structs/enums to be used to generate header files.

**Comment by dthaler** [comment]
Agree, I would love to see that requirement removed, as I've had to have dummy ecalls for years (going back to when just using the Intel SGX SDK) for exactly this reason.  I always found it annoying to have to add unused APIs just to make edger8r happy.

**Comment by anakrish** [comment]
If I am not mistaken, Intel SDK initializes the enclave (e.g calling global constructors) when the first ecall is made, where as in OE SDK the initialization happens as part of enclave creation.

It would be good to talk to Intel to see if we can relax this restriction in edl.

**Comment by radhikaj** [comment]
@jhand2 please update the issue.

**Comment by radhikaj** [comment]
@mwshan request you follow up on @anakrish's question above.

**Comment by MWShan** [comment]
The Intel SDK (actually the untrusted run-time system) makes a specific call into the enclave to perform initialization.  This is not an explicitly defined ECall in the EDL.  This call will return with the results of the initialization; thus, you would need an explicit ECall to get back into the enclave.

Does the OE SDK allow the thread to remain within the enclave on an implicit initialization ECall?  

Maybe we could define an EDL directive which overrides the requirement for an ECall.

@jbdelcuv - do you see any reason why we need an ECall?

**Comment by jbdelcuv** [comment]
The Intel SGX SDK initializes the enclave as part of enclave creation. We use a reserved ECALL identifier (-1) for that purpose. Global constructors are executed when the first (ISV) ECALL is made.
The Edger8r expects an enclave EDL file to have at least a public ECALL function. An enclave without an ECALL isn't very useful. :)
However, I do agree that we can lift such restriction for library EDL files, i.e. EDL files that are used to generate header files only (using the --header-only option) or are meant to get imported into enclave EDL files.

**Comment by jhand2** [comment]
> However, I do agree that we can lift such restriction for library EDL files, i.e. EDL files that are used to generate header files only (using the --header-only option) or are meant to get imported into enclave EDL files.

Just to clarify, I mis-spoke previously. When passed the --header-only option, edger8r does relax this restriction.

**Comment by anakrish** [comment]
> > However, I do agree that we can lift such restriction for library EDL files, i.e. EDL files that are used to generate header files only (using the --header-only option) or are meant to get imported into enclave EDL files.
> 
> Just to clarify, I mis-spoke previously. When passed the --header-only option, edger8r does relax this restriction.

This seems like a non issue then. Feel free to reopen otherwise.
