### ISSUE TITLE
Outdated buildandsign doc

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#2714]
GettingStartedDocs\buildandsign.md looks to be outdated.
* There is no mention of OE_SET_ENCLAVE_OPTEE, only SGX.
* The only discussion of .conf parameters is SGX-specific, without explaining why.

**Comment by CodeMonkeyLeet** [comment]
Removed from SIG-Arch, will track the arch issue discussions in the future with #2844, this issue will track fixing up the documentation.
