### ISSUE TITLE
Switchless sample unexpectedly has multiple values of NumTCS

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#2715]
https://github.com/openenclave/openenclave/blob/master/samples/switchless/enclave/enc.c line 39 sets NumTCS to 2.
https://github.com/openenclave/openenclave/blob/master/samples/switchless/enclave/switchless.conf line 8 sets NumTCS to 1.

It's unclear why the sample uses both a .conf file and a OE_SET_ENCLAVE_SGX() macro, let alone why they have different values. It's also unclear which one takes precedence, which overlaps with issue #2714

**Comment by radhikaj** [comment]
The recommendation right now is to use the configuration file for SGX only samples.

**Comment by dthaler** [comment]
PR #2636 addresses part of this issue but making both locations have the same value of NumTCS=2.
A future PR will address the issue of having both the macro and the .conf file, as well as adding comments explaining why the number 2 was chosen (Anand explained: "The sample already has 1 tcs. And now to handle switchless calls we need one worker, making the total enclave theads to two.")
