### ISSUE TITLE
Nuget Package Upload Warning

### ISSUE THREAD

**Issue by BRMcLaren** [openenclave/openenclave#2716]
When uploading packages, we receive the following warning:

"The <licenseUrl> element is deprecated. Consider using the <license> element instead."

More information can be found at: https://aka.ms/deprecateLicenseUrl

**Comment by jhand2** [comment]
Just to clarify, is this specifically for the licenseUrl, or are we using other deprecated fields as well?

**Comment by BRMcLaren** [comment]
@jhand2  Just the license URL, this was the only deprecated URL noticed.

This is not critical, assigning to myself.

**Comment by BRMcLaren** [comment]
Closing as "won't do"
