### ISSUE TITLE
OE SDK installed through APT having PLATFORM ERROR with DCAP v1.4

### ISSUE THREAD

**Issue by praenubilus** [openenclave/openenclave#2718]
VM: ACCVM on Azure
OS: Ubuntu 18.04 
Problem Description: Recently we have Installed Open Enclave from apt source following the steps from the [official doc](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md) in an ACCVM. The intel SGX DCAP Driver we have is version 1.4. There is no compiling error for the application. But when we run the application, the OESDK will complain for a PLATFORM error. Details can be seen from the following screenshot. It seems DCAP 1.5 will fix the problem.

![Screenshot from 2020-03-20 16-10-56](https://user-images.githubusercontent.com/547418/77212716-78711580-6ac5-11ea-921c-038b7f3aa630.png)

**Comment by jxyang** [comment]
Just to add two more data points. 1) when we created the acc vm, we checked "install oe sdk" option. That seems causing the 1.4 dcap driver to be installed. 2) when using the contributor installation guide, i.e., building oe sdk from source, the driver is updated to 1.5. And there is no platform error.

It seems something in the contributor installation scripts are missing in the package installation scripts.

**Comment by anakrish** [comment]
@soccerGB Is the "install oe sdk" option still recommended? 

@jxyang @praenubilus Was OE SDK installed using "apt install" or via "install oe sdk" option?

**Comment by soccerGB** [comment]
Could you check to see if you have Azure DCAP client installed on your system? 

if not, you can find latest version  in https://github.com/microsoft/Azure-DCAP-Client/releases.

**Comment by praenubilus** [comment]
> @soccerGB Is the "install oe sdk" option still recommended?
> 
> @jxyang @praenubilus Was OE SDK installed using "apt install" or via "install oe sdk" option?

@anakrish The install OE SDK is still the default option for ACC template. The OE SK is installed using APT install

**Comment by praenubilus** [comment]
> Could you check to see if you have Azure DCAP client installed on your system?
> 
> if not, you can find latest version in https://github.com/microsoft/Azure-DCAP-Client/releases.

Is there a difference between Intel DCAP or Azure DCAP? If yes, how can I check/tell the difference?

**Comment by soccerGB** [comment]
You can run the following command to find out which version of Azure DCAP client you have,

 dpkg --list | grep az-dcap-client
ii  az-dcap-client 1.1                            amd64        Intel(R) SGX DCAP plugin for Azure Integration

The current OE SDK does not support Intel DCAP client yet.

**Comment by radhikaj** [comment]
@soccerGB Please update this issue.

**Comment by yentsanglee** [comment]
No consistent repro but likely a local cert caching permission issue in az-dcap-client due to recent driver privilege update in DCAP QL. Suggestions are to fix in az-dcap-client:
1. Make local cert cache shared by all users.
2. For sgx_ql_get_quote_config() to return success if cert is retrieved but local caching fails.

**Comment by radhikaj** [comment]
@praenubilus  please take a look at the suggestions and let us know if you are unblocked.

**Comment by jazzybluesea** [comment]
I believe I ran into this issue.  If you list of the files under ~/.az-dcap-client, if you will see a cache file owned by root.  The way I worked around it was to remove cache files.  I believe the cache owned by root was created when I did an upgrade.

**Comment by jxyang** [comment]
I just want to understand why the contributor installation flow could update a pre-installed SGX dcap driver but the apt installation flow couldn't.

**Comment by jhand2** [comment]
Closing this issue. Please reopen if you have a repro
