### ISSUE TITLE
Remove dependency on Azure DCAP libraries when unnecessary for SGX

### ISSUE THREAD

**Issue by HernanGatta** [openenclave/openenclave#2728]
It would be good to ensure that in documents targeted at users that install the SDK from binary packages for SGX which mandate the installation of the Azure DCAP libraries, that step be conditioned on:

1. Is the step for simulation mode?
2. Should the Intel DCAP client be used instead?

Two examples of this are the pages pointed to to [install the SDK on Ubuntu for simulation mode](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Simulation.md), for [16.04](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md) and [18.04](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md). These pages have the user install the Azure DCAP libraries even if the user expects to use simulation mode only.

This is tangentially related to issue [2177](https://github.com/openenclave/openenclave/issues/2177).

**Comment by radhikaj** [comment]
Looking into delay loading sgx dlls.

**Comment by radhikaj** [comment]
https://github.com/openenclave/openenclave/pull/2882

**Comment by radhikaj** [comment]
Fixed in #3162 and 3155#
