### ISSUE TITLE
Add OESDK mailing lists to documentation

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#2742]
There are two relevant email lists today, neither of which is mentioned in any document in the repo:
oesdk@lists.confidentialcomputing.io
oesdkcgc@lists.confidentialcomputing.io 

I believe the oesdkcgc list should at least be referenced at Committers.md and
the oesdk list would be good to mention right in the main README file.

**Comment by jhand2** [comment]
Currently only members of the GCG can send mail to the oesdkcgc mailing list. Do you think that is the correct behavior?

For the oesdk mailing list I agree we should publish it in the README

**Comment by dthaler** [comment]
> Currently only members of the GCG can send mail to the oesdkcgc mailing list. Do you think that is the correct behavior?

My opinion: no.  I think anyone should be able to send email to it, e.g., to report a code of conduct issue or whatever else.

**Comment by dthaler** [comment]
Between PR #2814 and PR #2744 this is now done.
