### ISSUE TITLE
OpenEnclave-libcxx-test Failures

### ISSUE THREAD

**Issue by BRMcLaren** [openenclave/openenclave#2783]
Libcxx ACC1604 gcc Debug
Libcxx ACC1604 gcc RelWithDebInfo
Libcxx ACC1604 gcc Release

Are repeatedly [failing](https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/OpenEnclave-libcxx-tests/detail/OpenEnclave-libcxx-tests/52/pipeline).

There error in question seems to be 

```
At global scope:

cc1plus: warning: unrecognized command line option ‘-Wno-unused-local-typedef’

tests/libcxx/enc/CMakeFiles/libcxxtest-std_utilities_variant_variant.variant_variant.swap_swap.pass_enc.dir/build.make:70: recipe for target 'tests/libcxx/enc/CMakeFiles/libcxxtest-std_utilities_variant_variant.variant_variant.swap_swap.pass_enc.dir/main.cpp.o' failed

make[2]: *** [tests/libcxx/enc/CMakeFiles/libcxxtest-std_utilities_variant_variant.variant_variant.swap_swap.pass_enc.dir/main.cpp.o] Error 1

CMakeFiles/Makefile2:16220: recipe for target 'tests/libcxx/enc/CMakeFiles/libcxxtest-std_utilities_variant_variant.variant_variant.swap_swap.pass_enc.dir/all' failed

make[1]: *** [tests/libcxx/enc/CMakeFiles/libcxxtest-std_utilities_variant_variant.variant_variant.swap_swap.pass_enc.dir/all] Error 2

Makefile:162: recipe for target 'all' failed

make: *** [all] Error 2

script returned exit code 2
```

**Comment by jhand2** [comment]
Why is it using GCC 5? https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/OpenEnclave-libcxx-tests/runs/52/nodes/19/steps/128/log/?start=0

```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
```

**Comment by ionutbalutoiu** [comment]
> Why is it using GCC 5? https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/OpenEnclave-libcxx-tests/runs/52/nodes/19/steps/128/log/?start=0
> 
> ```
> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> ```
> 
> The 18.04 build uses gcc 7. I would say gcc 5 support is comfortably out of scope

The default GCC version on Ubuntu 16.04 is `5.4.0`. And we still have CI running with Ubuntu 16.04 testing stages.

Please see my https://github.com/openenclave/openenclave/issues/1516#issuecomment-482602896 about moving from GCC `5.4.0` on Ubuntu 16.04.

As far as I recall, we wanted to test with compilers from default repositories on all the platforms that we support. On Ubuntu 16.04, we have only GCC 5.4.0 as previously investigated by me.

If we decide to bump GCC on Ubuntu 16.04 via a third party PPA (as suggested by me in the linked comment), we can do that.

**Comment by jhand2** [comment]
Oh ok, I didn't realize the default in Ubuntu 16.04 was still so old. In that case I think we should continue to support the default compilers for all distros we support.

The problem here is just that @mingweishih added some new C++17 tests and GCC 5 doesn't support C++17. Assigning this to @mingweishih to mitigate

**Comment by mingweishih** [comment]
Side note to this issue: supporting ubuntu 16.04 should then cause a conflict if we want to use c++17 by default (#2770).

**Comment by jhand2** [comment]
> Side note to this issue: supporting ubuntu 16.04 should then cause a conflict if we want to use c++17 by default (#2770).

Is there a particular reason we need to support C++17 by default? Or was it just a nice-to-have?

**Comment by mingweishih** [comment]
I think it's just nice-to-have.
