### ISSUE TITLE
Optimize collateral memcpy and serialization

### ISSUE THREAD

**Issue by yufjiang** [openenclave/openenclave#2792]
Regarding the PR https://github.com/openenclave/openenclave/pull/2506, Sergio suggested two optimization opportunities. 

Quote his words below:
1.  "Would it be possible to just return and use the sgx_ql_qve_collateral_t returned from the DCAP client instead of copying the data into our oe_get_sgx_quote_verification_collateral_args_t structure? This would shave off some time." 

2. "When the caller does not pass in the endorsements/collaterals in oe_verify_report(), we currently fetch the serialized collaterals and then use the serialized collaterals for verification. One optimization, given that there is so much data to copy, is to NOT create the serialized collaterals in this specific scenario and just use the collaterals straight from the DCAP client. In the scenario when the caller passes in collaterals, we would need to convert the serializable object to something like this struct (reverse of create_sgx_endorsements())."

Create this issue to track the work on these two optimization opportunities.

#2283 Covers the caching of the SGX collaterals by the DCAP client.

**Comment by yufjiang** [comment]
During triage, feel free to assign this issue to me. Thanks!

**Comment by yentsanglee** [comment]
The major bottleneck is on collateral caching which was fixed in az-dcap-client [PR 105](https://github.com/microsoft/Azure-DCAP-Client/pull/105) and multiple ocall which was fixed in PR 2969. The perf improved by this issue is trivial. Closing the issue.
