### ISSUE TITLE
Merge Enforcement Alternatives

### ISSUE THREAD

**Issue by BRMcLaren** [openenclave/openenclave#2798]
I would like to begin the discussion to move away from Bors and explore alternatives. Bors has been great for the OpenEnclave project but there are some limitations that we would like to find solutions to, primarily scalability.

Please discuss in this thread, recommending alternatives and any pros/cons that are known and we can look into them and come up with a proposal. Ease of use, scalability, and automation configuration in regards to pull requests and community engagement would be the ideal scenario.

**Current Suggestions:**
[Bors](https://bors.tech/)
[Prow](https://github.com/kubernetes/test-infra/tree/master/prow)

**Deficiencies to address:**

Non-parallelized testing
Singular pipeline configuration
Confusing

**Ideal Requirements:**

- Required Status Check validation
- Optional Status Check validation (ex. E2E status check)
- Notification System to allow contributors to alert a Committer to run CI testing, similar to 'Bors try' today
- Some sort of queue system to allow Contributors a testing ETA
- manage who can sign off pull requests
- manage who can kick off automation or which automation on pull request
- Support multiple pipelines across different companies
- Maybe multi-phase testing where some pipelines are only kicked off if others pass first. (Smoke testing versus longer integration testing etc)
- manage how many sign-off on request is required
- ability to delegate "approver" and "reviewer" permissions separately
- ability to control permissions on a per-directory basis
- CI plugin extensibility for external contributions of test runs, with permissions managed by an OE team
- integration with GitHub tags

**Assumptions**

Assume a system such as the below exists, while it doesn't today I believe that to be what we are working towards.

![image](https://user-images.githubusercontent.com/54328827/78714253-6a4a3400-78d0-11ea-8b7c-7488af10f68b.png)

**Comment by mingweishih** [comment]
One suggestion from @AevaOnline was [prow](https://github.com/kubernetes/test-infra/tree/master/prow). But I think we need more information such as the comparison against bors.

**Comment by BRMcLaren** [comment]
@mingweishih Thanks for bringing this up! Edited the top level to include a list of current and potential alternatives.

I agree that a comparison would be helpful, maybe in the sense of a matrix to understand the relative tooling weak points and strengths.

**Comment by douglasmaciver** [comment]
As we begin comparative analysis, it would helpful if someone could list the requirements. Also, an enumeration of Bors deficiencies would help. Neither of these lists need be fancy or exhaustive.

**Comment by BRMcLaren** [comment]
@douglasmaciver , a great point. How about starting with an "Ideal Requirements list", and then we can some comparison at how these tools stack up against each other?

**Comment by paulcallen** [comment]
Few suggestions of requirements
* manage who can sign off pull requests
* manage who can kick off automation or which automation on pull request
* Support multiple pipelines across different companies
* Maybe multi-phase testing where some pipelines are only kicked off if others pass first
* manage how many sign-off on request is required

**Comment by AevaOnline** [comment]
@BRMcLaren , thanks for kicking off this discussion!

I'd like to upvote all the items Paul mentioned above, and add a few suggestions coming out of the governance discussions:
* ability to delegate "approver" and "reviewer" permissions separately
* ability to control permissions on a per-directory basis

Coming from our goal to enable plugins in the project codebase: 
* CI plugin extensibility for external contributions of test runs, with permissions managed by an OE team

And one more nice-to-have, stemming from my experience in larger projects:
* integration with GitHub tags
  * for example, if the bot could automatically apply tags such as `tag:failing-tests` or `tag:ready-to-merge`, this might help speed up the review process by enabling filtered dashboards for reviewers
  * combining this with plugin extensibility, we could have trusted 3rd-party CI systems that also control tags such as `tag:passing-sgx` or `tag:failing-optee` to help further track the quality of patches with a distributed CI/CD system

**Comment by jhand2** [comment]
Suggestion to add a project board for testing issues if SIG-Testing would like to use that.

**Comment by radhikaj** [comment]
I have  created https://github.com/openenclave/openenclave/projects/15

**Comment by dthaler** [comment]
Another project I was a maintainer of used Travis-CI but I see that on yet another project (that I have not been a part of) is considering replacing travis-ci with prow: https://github.com/kubeflow/tf-operator/issues/382

**Comment by douglasmaciver** [comment]
Aeva introduced me to a couple of contacts within Microsoft who have direct experience with Prow.

**Comment by BRMcLaren** [comment]
I've implemented everyone's asks over here: https://github.com/openenclave/test-infra/

If any further asks exist, please write them there. Thanks @AevaOnline  for the pointers!
