### ISSUE TITLE
snmalloc depends on symbols in libcxx

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2802]
cc @achamayou 

When I compile OE with -DUSE_SNMALLOC=ON with clang-9, snmalloc appears to depend on `__cxa_guard_acquire` and `__cxa_guard_release` from libcxx. This leads to linker errors for enclaves which are not linked with libcxx. I am currently unable to test this with a different compiler to see if this issue is compiler-specific.

Has anyone else seen this/can anyone repro with a different compiler?

**Comment by jhand2** [comment]
Confirmed also happens with gcc 9

**Comment by jhand2** [comment]
Additional context @anakrish pointed me to a comment on the original snmalloc PR from @mjp41

>> Does snmalloc use thread-local variables? If so, it might make sense to use a thread-local variable to hold to to the thread's allocator instead of adding a member to td_t.
>
> To do this, would include more C++ features, so would be harder to support inside oecore. For the current implementation for OE has no dependency on a C++ library at runtime. This was the main reason for modifying td_t. Outside the enclave, we have used C++ thread_static variables, but this requires runtime links to
> __cxa_thread_atexit
> __cxa_guard_acquire
>  __cxa_guard_release
>
>This is not something you probably want to support in oecore.

**Comment by anakrish** [comment]
@jhand2 Thanks for creating this. Fixing this will allow us to consider using `snmalloc` as potential default allocator.

It might make sense to create an issue in the snmalloc repo:
https://github.com/microsoft/snmalloc
I created couple of issues there and they got addressed pretty quickly.

**Comment by jhand2** [comment]
Ok I can open an issue on the snmalloc repo. I do want to understand what exactly is causing the usage. First, I can't find anything in C++ called `thread_static`. Does this mean `static thread_local` instead?

**Comment by anakrish** [comment]
I think these are the culprits:
https://github.com/microsoft/snmalloc/blob/74657d9dbc776a54f78b77896a9955ebce5c8076/src/ds/helpers.h#L24-L26

The compiler is required to make the construction of these static variables thread-safe.
```c
      static std::atomic_flag flag;
      static std::atomic<bool> initialised;
      static Object obj;
```

**Comment by anakrish** [comment]
@jhand2 `thread_static` must have been a typo.

Yes, thread-local variables won't generate _cxa_guards.

**Comment by mjp41** [comment]
I don't believe you should see `_cxa_guard` with the way `snmalloc` is configured to build inside OE. The only static with a non-trivial destructor shouldn't be compiled on OE.

Could you let me know where in the disassembly the _cxa_guards appear?  Is this a Debug or Release build?  I think there is a .o file for the allocator that gets linked in.  Could send me that?

Thread static is a typo.  We have some "thread safe statics" and some "thread_local" variables. I sometimes get confused ;-)

**Comment by mjp41** [comment]
@achamayou can you remember what the .o file is called.

Is this on a Linux SGX build, or another platform?

**Comment by achamayou** [comment]
@mjp oeallocator

**Comment by achamayou** [comment]
@jhand2 I haven’t seen that with clang-8 and the Open Enclave test cases, which I don’t believe link libc++. I can look at this a bit later today, it’s definitely not expected.

**Comment by achamayou** [comment]
I was wrong, I'd been using clang-7, the compiler selection logic is different in openenclave:

```
amchamay@amchamay2:/data/src/openenclave/test$ cmake -GNinja -DUSE_SNMALLOC=ON -L ..
-- The C compiler identification is Clang 7.1.0
-- The CXX compiler identification is Clang 7.1.0
...
amchamay@amchamay2:/data/src/openenclave/build$ nm -C ./enclave/core/CMakeFiles/oeallocator.dir/sgx/snmalloc/snmalloc_wrapper.cpp.o | grep -c cxa
0
```

With clang-8:

```
amchamay@amchamay2:/data/src/openenclave/build$ cmake -GNinja -DUSE_SNMALLOC=ON ..
-- The C compiler identification is Clang 8.0.1
-- The CXX compiler identification is Clang 8.0.1
...
CMake Warning at cmake/compiler_settings.cmake:8 (message):
  Open Enclave officially supports Clang 7 only, but your Clang version
  (8.0.1) is older or newer than that.  Build problems may occur.
Call Stack (most recent call first):
  CMakeLists.txt:175 (include)
...
amchamay@amchamay2:/data/src/openenclave/build$ nm -C ./enclave/core/CMakeFiles/oeallocator.dir/sgx/snmalloc/snmalloc_wrapper.cpp.o | grep -c cxa
0
```

**Comment by achamayou** [comment]
```
amchamay@amchamay2:/data/src/openenclave/build$ cmake -GNinja -DUSE_SNMALLOC=ON ..
-- The C compiler identification is Clang 9.0.0
-- The CXX compiler identification is Clang 9.0.0
...
CMake Warning at cmake/compiler_settings.cmake:8 (message):
  Open Enclave officially supports Clang 7 only, but your Clang version
  (9.0.0) is older or newer than that.  Build problems may occur.
Call Stack (most recent call first):
  CMakeLists.txt:175 (include)
...
amchamay@amchamay2:/data/src/openenclave/build$ nm -C ./enclave/core/CMakeFiles/oeallocator.dir/sgx/snmalloc/snmalloc_wrapper.cpp.o | grep -c cxa
0
```

@jhand2 how do you hit those errors? I'm on Ubuntu 18.04, building OE master 5193551120051c63091a2331ac04ab276947a173

**Comment by jhand2** [comment]
The message you pasted is just a warning and is expected. We print it because we don't have any CI to test clang > 7. I don't see any actual failures. in this snippet.

**Comment by achamayou** [comment]
@jhand2 sure, I just included it along with the identification lines to make it clear the runs are with 8 and 9 :)

I also don't see any failures, which is my point, so that's why I was asking how you got those linking errors. Is it a Windows build? A different branch?

**Comment by jhand2** [comment]
@achamayou I'll get back to you when I have a little more time to look into this. My main concern was to make sure we didn't do anything that blocks people from using snmalloc who want to use it.

If none of you are blocked I can address this with a little less urgency (but I'll still try to figure out what's going on :smile:)

**Comment by anakrish** [comment]
@achamayou With latest openenclave master (actually my fork which is up to date with upstream),
I can trigger the issue if using  ggc-8.

```bash
export CC=gcc-8
export CXX=g++-8
cmake -DHAS_QUOTE_PROVIDER=off -DUSE_SNMALLOC=on ..
cd tests/echo/enc
make -j 16
...
[100%] Linking CXX executable echo_enc
/usr/bin/ld: ../../../output/lib/openenclave/enclave/liboecore.a(snmalloc_wrapper.cpp.o): in function `snmalloc::Singleton<snmalloc::MemoryProviderStateMixin<snmalloc::PALPlainMixin<snmalloc::PALOpenEnclave> >*, &snmalloc::MemoryProviderStateMixin<snmalloc::PALPlainMixin<snmalloc::PALOpenEnclave> >::make>::get(bool*)':
/home/anakrish/work/fork1/enclave/core/sgx/snmalloc/../../../../3rdparty/snmalloc/src/override/../mem/../ds/helpers.h:24: undefined reference to `__cxa_guard_acquire'
/usr/bin/ld: /home/anakrish/work/fork1/enclave/core/sgx/snmalloc/../../../../3rdparty/snmalloc/src/override/../mem/../ds/helpers.h:24: undefined reference to `__cxa_guard_release'
/usr/bin/ld: /home/anakrish/work/fork1/enclave/core/sgx/snmalloc/../../../../3rdparty/snmalloc/src/override/../mem/../ds/helpers.h:25: undefined reference to `__cxa_guard_acquire'
/usr/bin/ld: /home/anakrish/work/fork1/enclave/core/sgx/snmalloc/../../../../3rdparty/snmalloc/src/override/../mem/../ds/helpers.h:25: undefined reference to `__cxa_guard_release'
/usr/bin/ld: ../../../output/lib/openenclave/enclave/liboecore.a(snmalloc_wrapper.cpp.o): in function `snmalloc::Singleton<snmalloc::AllocPool<snmalloc::MemoryProviderStateMixin<snmalloc::PALPlainMixin<snmalloc::PALOpenEnclave> > >*, &snmalloc::AllocPool<snmalloc::MemoryProviderStateMixin<snmalloc::PALPlainMixin<snmalloc::PALOpenEnclave> > >::make>::get(bool*)':
/home/anakrish/work/fork1/enclave/core/sgx/snmalloc/../../../../3rdparty/snmalloc/src/override/../mem/../ds/helpers.h:24: undefined reference to `__cxa_guard_acquire'
/usr/bin/ld: /home/anakrish/work/fork1/enclave/core/sgx/snmalloc/../../../../3rdparty/snmalloc/src/override/../mem/../ds/helpers.h:24: undefined reference to `__cxa_guard_release'
/usr/bin/ld: /home/anakrish/work/fork1/enclave/core/sgx/snmalloc/../../../../3rdparty/snmalloc/src/override/../mem/../ds/helpers.h:25: undefined reference to `__cxa_guard_acquire'
/usr/bin/ld: /home/anakrish/work/fork1/enclave/core/sgx/snmalloc/../../../../3rdparty/snmalloc/src/override/../mem/../ds/helpers.h:25: undefined reference to `__cxa_guard_release'
/usr/bin/ld: ../../../output/lib/openenclave/enclave/liboecore.a(snmalloc_wrapper.cpp.o): in function `std::atomic<snmalloc::ABA<snmalloc::Allocator<snmalloc::MemoryProviderStateMixin<snmalloc::PALPlainMixin<snmalloc::PALOpenEnclave> >, snmalloc::DefaultChunkMap<snmalloc::GlobalPagemapTemplate<snmalloc::Pagemap<20ul, unsigned char, (unsigned char)0> > >, true, &snmalloc::lazy_replacement>, (snmalloc::Construction)0>::Linked>::compare_exchange_weak(snmalloc::ABA<snmalloc::Allocator<snmalloc::MemoryProviderStateMixin<snmalloc::PALPlainMixin<snmalloc::PALOpenEnclave> >, snmalloc::DefaultChunkMap<snmalloc::GlobalPagemapTemplate<snmalloc::Pagemap<20ul, unsigned char, (unsigned char)0> > >, true, &snmalloc::lazy_replacement>, (snmalloc::Construction)0>::Linked&, snmalloc::ABA<snmalloc::Allocator<snmalloc::MemoryProviderStateMixin<snmalloc::PALPlainMixin<snmalloc::PALOpenEnclave> >, snmalloc::DefaultChunkMap<snmalloc::GlobalPagemapTemplate<snmalloc::Pagemap<20ul, unsigned char, (unsigned char)0> > >, true, &snmalloc::lazy_replacement>, (snmalloc::Construction)0>::Linked, std::memory_order, std::memory_order)':
/usr/include/c++/8/atomic:288: undefined reference to `__atomic_compare_exchange_16'
/usr/bin/ld: ../../../output/lib/openenclave/enclave/liboecore.a(snmalloc_wrapper.cpp.o): in function `std::atomic<snmalloc::ABA<snmalloc::Largeslab, (snmalloc::Construction)1>::Linked>::compare_exchange_weak(snmalloc::ABA<snmalloc::Largeslab, (snmalloc::Construction)1>::Linked&, snmalloc::ABA<snmalloc::Largeslab, (snmalloc::Construction)1>::Linked, std::memory_order, std::memory_order)':
/usr/include/c++/8/atomic:288: undefined reference to `__atomic_compare_exchange_16'
```

**Comment by anakrish** [comment]
One interesting in the above log is that `snmalloc` seems to be compiled with system headers and not the C++ headers provided by oe. Is that expected?

**Comment by anakrish** [comment]
@jhand2 @mingweishih 
The log says `[100%] Linking CXX executable echo_enc` which is quite confusing since echo_enc does not need C++. Can you please take a look since it was changed recently.

**Comment by mjp41** [comment]
I duplicated the issue looking at some non-OE code using gcc-8.  I believe the PR on snmalloc [#167](https://github.com/microsoft/snmalloc/pull/167) should fix this, but if someone could test as I don't have the full OE setup working.

**Comment by achamayou** [comment]
No luck reproducing with any of the clangs, but gcc-8 does it. @mjp trying your patch now.

**Comment by achamayou** [comment]
@jhand2 I believe this is fixed by #2831, can you confirm on your side?

Separately from that, there is a problem with snmalloc using the wrong set of libc and libcxx headers when building: https://github.com/openenclave/openenclave/pull/2831#issuecomment-612444414

That does not cause a build break at the moment, but it's still something I'm going to look at fixing shortly.

**Comment by jhand2** [comment]
I will test #2831 today or tomorrow

**Comment by jhand2** [comment]
Finally got around to testing this an everything looks good. Thanks!
