### ISSUE TITLE
Jenkins GitHub multi-status checks

### ISSUE THREAD

**Issue by BRMcLaren** [openenclave/openenclave#2805]
I want to preface this by giving credit to the writer @ionutbalutoiu, also that overall it would be good if we can frame a discussion around the _process_ , validation, etc as opposed to specific tooling. For tooling suggestions, please keep the discussion centered [here](https://github.com/openenclave/openenclave/issues/2798 )

**Overview**
![image](https://user-images.githubusercontent.com/54328827/78726079-eef37d00-78e5-11ea-81f1-15dcdb88d222.png)

This proposal presents a distributed Jenkins CI/CD system with separate GitHub status checks for every testing level/pipeline. The testing levels are triggered on new pull requests by Open Enclave admins or white-listed contributors.

**Requirments**
When a new pull request is submitted to the upstream Open Enclave repository, an admin or white-listed contributor can trigger testing levels via GitHub comments, this can be thought of as multiple pipelines.

![image](https://user-images.githubusercontent.com/54328827/78726101-fb77d580-78e5-11ea-8551-339c4a55205f.png)

Also, besides triggering testing levels individually, one can trigger all the testing levels on merge.

![image](https://user-images.githubusercontent.com/54328827/78726119-07fc2e00-78e6-11ea-9554-8a46d049dff0.png)

If a new contributor submits a pull request, a CI bot will leave a comment asking for an admin to trigger the CI:

![image](https://user-images.githubusercontent.com/54328827/78726139-16e2e080-78e6-11ea-999c-7774fd95a351.png)

An admin can trigger the CI using above instructions, or they can white-list the contributor, and let them trigger the CI themself.

![image](https://user-images.githubusercontent.com/54328827/78726143-1cd8c180-78e6-11ea-944f-f2981218cb6f.png)

Thus, merging into master won't be allowed even if you are an admin

![image](https://user-images.githubusercontent.com/54328827/78726148-23673900-78e6-11ea-8007-26c73f59184e.png)

unless all the GitHub checks pass:

![image](https://user-images.githubusercontent.com/54328827/78726157-27935680-78e6-11ea-81e9-a30d561c7d70.png)

In reality, this will be gated be tooling outlined [here](https://github.com/openenclave/openenclave/issues/2798)

**Benefits of this system:**

Easy onboarding of additional pipelines
Scalability
Multi-tiered testing
Every Pipeline admin maintains control over their systems, allowing flexibility in implementation assuming matching SLA.

**Downsides**

Complexity increase

Let's discuss and come up with an agreed-upon solution down below.

**Comment by jhand2** [comment]
@AevaOnline Could you take a look at this and give any opinions you have on this proposal?

Maybe we should talk about this in SIG-testing meeting this week.

**Comment by AevaOnline** [comment]
This UX looks like a great improvement, and it raises a couple questions to discuss further in the ways it differs from what I've seen elsewhere:

1. the example of an "add to whitelist" (*) command raises the question, how is the access control list (ACL) managed in a transparent, discoverable, and auditable way? These three qualities are important for building community trust in a distributed open source project.

In this proposal, it appears that unilateral changes to the ACL are possible, and it appears to be stored outside of the repo (and thus only visible to folks with CI admin access). If there is a separate view, eg. in the CI system, to the current ACL list, how are changes tracked? if someone needs to do the equivalent of "git blame" for an ACL change, how will that be performed?

By comparison, what if the ACL was itself stored in a text file directly in the repo? Changes to the ACL would be peer-reviewed (not unilateral), discoverable (anyone can look at the file), and auditable (you can see exactly when, in the history, the ACL changed).

2. "merging only allowed after tests pass"

This proposal appears to still require humans to perform the merge, and isn't clear on how ACLs interact with the "merge" button. As far as I know, GitHub is not able to enforce granular ACLs, so this suggests that lots of people still have merge access to the project. Could you clarify the plan here?

For example, how would this system prevent someone who should be granted merge access for, say, an API change, from also merging a change to somewhere else, say, SGX code, for which they should not have access?

3. "merging into master won't be allowed even if you are an admin" 

Will there be _anyone_ who has the ability to overrule the status check? This is necessary in a few edge cases, eg. if the CI system trips over something and a patch has to be pushed in to get things going again. In an ideal system this wouldn't be necessary, but the world isn't perfect and I've seen this come up in many projects. 

AIUI, this is something that Github project admins (or owners?) should still have the ability to do, and we would want to keep that list _very_ small (like, 3 - 5 people).


(*) as an aside, I would also advocate for the use of the words "allowlist" and "denylist", or more generally "access control lists"

**Comment by BRMcLaren** [comment]
>the example of an "add to whitelist" (*) command raises the question, how is the access control list (ACL) managed in a transparent, discoverable, and auditable way? These three qualities are important for building community trust in a distributed open source project.

We went another direction, using Owners files and allowing any collaborator in the organization to submit trusted PR's. Anyone outside of the org, we have given everyone the ability within the org to whitelist their PR's. This is auditable, and the reviewers/approvers can be seen in any repo.

>As far as I know, GitHub is not able to enforce granular ACLs, so this suggests that lots of people still have merge access to the project. Could you clarify the plan here? For example, how would this system prevent someone who should be granted merge access for, say, an API change, from also merging a change to somewhere else, say, SGX code, for which they should not have access?

Yes. This was an interesting learning curve. We implemented Prow for granular access control. The merge button can only be interacted with via automated, the Owners lists dictate who can approve changes, this is handled in granularity via subdirectory leaves.

>Will there be anyone who has the ability to overrule the status check? This is necessary in a few edge cases, eg. if the CI system trips over something and a patch has to be pushed in to get things going again. In an ideal system, this wouldn't be necessary, but the world isn't perfect and I've seen this come up in many projects.

Repo admins have the ability to /override a status check.

> In an ideal system, this wouldn't be necessary, but the world isn't perfect and I've seen this come up in many projects.

Yup. Completely agree. Bors has taught us this.

> AIUI, this is something that Github project admins (or owners?) should still have the ability to do, and we would want to keep that list very small (like, 3 - 5 people).

Yup.


I'm also closing this issue, it was discussed 2 months ago within SIG Testing and later split out into SIG CI. If anyone wants to continue the conversation, please head over to the https://github.com/openenclave/test-infra project.
