### ISSUE TITLE
Document/propose deprecation process for public APIs pre-v1.0

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2813]
There is currently an accepted process for deprecating public APIs but the mechanism is not well documented. Write up a document on how to properly deprecate/replace a public API in OE.

This issue/documentation will not apply after the OE v1.0 release.

**Comment by radhikaj** [comment]
@jhand2, this appears to be related to #2567

**Comment by jhand2** [comment]
Closing as dup of #2567
