### ISSUE TITLE
A few ocalls used by oecore cannot be opted out of

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2818]
In particular, the following edl files have ocalls which are always linked into oecore and cannot be opted out of:

* sgx/attestation.edl
* sgx/cpu.edl
* sgx/debug.edl
* sgx/switchless.edl
* logging.edl

**Comment by mingweishih** [comment]
With #3023, #3151 and #3203, now only sgx/attestation.edl, sgx/cpu.edl cannot be opt-out.
The opt-out of the sgx/cpu.edl is tracked by #3025.
Regarding sgx/attestation.edl, I'd like to get feedback to see whether it makes sense to be opt-out. More specifically, do we need to support an enclave without the attestation support?

cc @CodeMonkeyLeet @jhand2 @yentsanglee @radhikaj @anakrish

**Comment by dthaler** [comment]
I think it should be supported, but it's not high priority.   Other libOS approaches like Enarx don't support attestation by the app (the deployment mechanism does the attestation), so I don't think it's a blocker in general.

**Comment by mingweishih** [comment]
Close given #3214 is merged.
