### ISSUE TITLE
Ubuntu OE SDK 0.8.2 remote_attestation and attested_tls samples fail with latest Intel SGX SW Updates

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#2828]
This issue happens on both Ubuntu 1604 and Ubuntu 1804.

When OE SDK 0.8.2 or earlier is installed along side Intel SGX Linux 2.9.1 and Intel DCAP 1.6.100.2, the remote_attestation sample and the attested_tls sample segfault.
This happens only if you are using package config.

To work around the problem if you are using the SDK, in the openenclave SDK install path, under share/pkgconfig, change the *.pc files to remove -lsgx_urts
As an example, you would need to change Libs in share/pkgconfig/oehost.pc as below:
Libs: -rdynamic -Wl,-z,noexecstack -L${libdir}/openenclave/host -loehost -ldl -lpthread -lsgx_enclave_common -lsgx_dcap_ql

If you are building the SDK from source and installing it, you would need PR #2825.

Note: there is a preexiting issue that was found when the samples were built with make followed by cmake. Please find more information here: #2829.

**Comment by jhand2** [comment]
Fixed in master
