### ISSUE TITLE
Allow simple preprocessor directives in  EDL

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2833]
I mostly want to gauge if people think this is a good idea or not. Feel give reasons we shouldn't do this.

We could allow simple C preprocessor directives in EDL. In particular, I'm thinking `#ifdef` and `#ifndef`. This would also mean adding an option (such as `--define`) to oeedger8r. I mostly think this is useful for features which are only used on a single TEE. For example:

```
// myapp.edl
#ifdef PLATFORM_SGX
    from "switchless.edl" import *;
#endif
```

This is not currently possible. If your application wanted to use an SGX-specific feature only when on SGX, you would need a different EDL file for each TEE you want your app to run on.

**Comment by dthaler** [comment]
I would love to see this, it was painful to use EDLs when we first started because of this lack of capability.

**Comment by jhand2** [comment]
I see a couple ways to do this:
1. Re purpose the ocaml C preprocessor code into a library: https://github.com/ocaml-community/cppo
2. Invoke the C preprocessor via command-line

2 is probably easier but 1 may be easier in terms of dependency management.

@anakrish do you have an opinion of this?

**Comment by jhand2** [comment]
@anakrish I have started implementing the 2nd option in oeedger8r-cpp, should have a PR ready soon. On Linux it will use the cpp cmdline tool, and on Windows it will use cl.exe

Do you have any concerns with this approach or do you think this is a fine way to handle this?

**Comment by anakrish** [comment]
Thanks for getting a head start on this.
I don't see any concern. We just need to define the preprocessor capabilities.

Note: Intel edger8r does use the C compiler as an edl preprocessor:
https://github.com/intel/linux-sgx/blob/fdc9b33ee173a5e7743f20a2a9cb1dd8db114dca/sdk/edger8r/linux/Preprocessor.ml#L58
```ocaml
let command = sprintf "gcc -x c -E -P \"%s\" 2>/dev/null" full_path in
```
However, this results in incorrect locations for error messages, for which I created an issue:
https://github.com/intel/linux-sgx/issues/319

Essentially, we need to change the lexer to process the `#line` directives emitted by the preprocessor to preserve the original line numbers.

**Comment by jhand2** [comment]
Support for this is added in https://github.com/openenclave/oeedger8r-cpp/pull/9

When this PR is merged and oeedger8r-cpp is made the default this issue will be resolved

**Comment by mingweishih** [comment]
This is supported in the current master branch of [oeedger8r-cpp](https://github.com/openenclave/oeedger8r-cpp). We can close this issue once updating the submodule.

**Comment by radhikaj** [comment]
Hooray! Thanks @mingweishih
