### ISSUE TITLE
Use native ocaml compiler instead of esy where available

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#2835]
It a platform already has a version of ocaml that is sufficient to compile edger8r, use that instead of building ocaml from source via esy.
Currently
- esy does not seem to build out of the box on RHEL
- The default version of ocaml for ubuntu 18.04 and 16.04 is enough to compile edger8r
- esy requires administrator prompt on windows to create symlinks

**Comment by radhikaj** [comment]
@andschwa  Can you please comment on what the problems were which led you to adopt esy.

**Comment by anakrish** [comment]
This is superceded by the move to C++ edger8r.
https://github.com/openenclave/openenclave/pull/3082
