### ISSUE TITLE
Samples seem to be taking a long time to run

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2838]
On #2820 the samples took too long on a couple stages and timed out: https://oe-jenkins-dev.westeurope.cloudapp.azure.com/job/Bors/job/staging/243/display/redirect

Anecdotally I have noticed that the samples take a very long time to run when I am doing local testing.

We should look into this and see if there is a way we can (a) reduce the take they take or (b) run them individually as different tests in ctest.

**Comment by mingweishih** [comment]
On Linux, what the test currently does is
- Build each sample with cmake and run
- Build each sample with make and run

On Windows, only using cmake as make is not supported.

**Comment by jhand2** [comment]
On windows it uses cmake/ninja. But I don't know if the build is what's taking a long time or if it's a particular sample.

**Comment by jhand2** [comment]
Samples timed out again on the same PR: https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/244/pipeline

Based on the content of the PR I this the issue is separate from the PR

**Comment by dthaler** [comment]
I was just going to file an issue and found this one already filed, thanks!

Same problem hit by PR #2830.   I'd recommend that the samples test gets split into one test per sample, not one that tries to cover all possible samples.  I expect the number of samples to keep growing, and it's far more scalable to have the number of tests grow than it is to have the size of a test keep growing.

In the meantime, is there an easy way to increase the timeout of the samples test?

**Comment by jhand2** [comment]
It looks like the sample timeout issue may have been due to some network issue. This morning all CI builds are passing again. So at least for now I don't think we need to increase the timeout as long as CI keeps chugging along.

But I still agree one test per sample is the right thing to do so leaving this issue open.

**Comment by dthaler** [comment]
PR #2861 also seems to contain a relevant fix

**Comment by radhikaj** [comment]
Looking at the logs:  It is most certainly
1) Only on Windows Server 2016
2) The attested tls sample.
I am not sure what causes this.

 Build files have been written to: C:/Users/oeadmin/workspace/Bors_staging/build/X64-Debug/samples/attested_tls

191: Error: could not load cache

191: -- Samples test 'attested_tls' with CMake running...

191: [1/31] Generating tls_server_t.h, tls_server_t.c, tls_server_args.h

191: Generating edge routines for the Open Enclave SDK.

191: Success.

191: [2/31] Generating tls_client_u.h, tls_client_u.c, tls_client_args.h

191: Generating edge routines for the Open Enclave SDK.

191: Success.

191: [3/31] Generating tls_server_u.h, tls_server_u.c, tls_server_args.h

191: Generating edge routines for the Open Enclave SDK.

191: Success.

191: [4/31] Building CXX object server\enc\CMakeFiles\tls_server_enc.dir\cert_verifier.cpp.obj

191: [5/31] Building C object server\enc\CMakeFiles\tls_server_enc.dir\tls_server_t.c.obj

191: [6/31] Building CXX object server\enc\CMakeFiles\tls_server_enc.dir\server.cpp.obj

191: [7/31] Building CXX object server\enc\CMakeFiles\tls_server_enc.dir\ecalls.cpp.obj

191: [8/31] Building CXX object server\enc\CMakeFiles\tls_server_enc.dir\__\__\common\utility.cpp.obj

191: [9/31] Building C object client\host\CMakeFiles\tls_client_host.dir\tls_client_u.c.obj

191: [10/31] Building CXX object server\host\CMakeFiles\tls_server_host.dir\host.cpp.obj

191: [11/31] Building CXX object client\host\CMakeFiles\tls_client_host.dir\host.cpp.obj

191: C:\Users\oeadmin\workspace\Bors_staging\build\X64-Debug\openenclave\share\openenclave\samples\attested_tls\client\host\host.cpp(70): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data

191: C:\Users\oeadmin\workspace\Bors_staging\build\X64-Debug\openenclave\share\openenclave\samples\attested_tls\client\host\host.cpp(87): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data

191: [12/31] Building C object server\host\CMakeFiles\tls_server_host.dir\tls_server_u.c.obj

191: [13/31] Building CXX object server\enc\CMakeFiles\tls_server_enc.dir\identity_verifier.cpp.obj

191: [14/31] Linking CXX executable server\enc\tls_server_enc

191: [15/31] Linking CXX executable server\host\tls_server_host.exe

191: [16/31] Linking CXX executable client\host\tls_client_host.exe

191: [17/31] Generating tls_server_enc.signed, tls_server_enc_mrenclave.h

191: Created C:/Users/oeadmin/workspace/Bors_staging/build/X64-Debug/samples/attested_tls/server/enc/tls_server_enc.signed

191: [18/31] Generating tls_client_t.h, tls_client_t.c, tls_client_args.h

191: Generating edge routines for the Open Enclave SDK.

191: Success.

191: [19/31] Building CXX object client\enc\CMakeFiles\tls_client_enc.dir\ecalls.cpp.obj

191: [20/31] Building CXX object client\enc\CMakeFiles\tls_client_enc.dir\client.cpp.obj

191: [21/31] Building CXX object non_enc_client\CMakeFiles\tls_non_enc_client.dir\verify_signer_openssl.cpp.obj

191: C:\Users\oeadmin\workspace\Bors_staging\build\X64-Debug\openenclave\share\openenclave\samples\attested_tls\non_enc_client\verify_signer_openssl.cpp(87): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data

191: [22/31] Building CXX object client\enc\CMakeFiles\tls_client_enc.dir\cert_verifier.cpp.obj

191: [23/31] Building CXX object client\enc\CMakeFiles\tls_client_enc.dir\__\__\common\utility.cpp.obj

191: [24/31] Building C object client\enc\CMakeFiles\tls_client_enc.dir\tls_client_t.c.obj

191: [25/31] Building CXX object client\enc\CMakeFiles\tls_client_enc.dir\identity_verifier.cpp.obj

191: [26/31] Building CXX object non_enc_client\CMakeFiles\tls_non_enc_client.dir\client.cpp.obj

191: C:\Users\oeadmin\workspace\Bors_staging\build\X64-Debug\openenclave\share\openenclave\samples\attested_tls\non_enc_client\client.cpp(45): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data

191: C:\Users\oeadmin\workspace\Bors_staging\build\X64-Debug\openenclave\share\openenclave\samples\attested_tls\non_enc_client\client.cpp(51): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data

191: C:\Users\oeadmin\workspace\Bors_staging\build\X64-Debug\openenclave\share\openenclave\samples\attested_tls\non_enc_client\client.cpp(116): warning C4477: 'printf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t'

191: C:\Users\oeadmin\workspace\Bors_staging\build\X64-Debug\openenclave\share\openenclave\samples\attested_tls\non_enc_client\client.cpp(116): note: consider using '%zu' in the format string

191: C:\Users\oeadmin\workspace\Bors_staging\build\X64-Debug\openenclave\share\openenclave\samples\attested_tls\non_enc_client\client.cpp(188): warning C4244: '=': conversion from 'SOCKET' to 'int', possible loss of data

191: [27/31] Building CXX object non_enc_client\CMakeFiles\tls_non_enc_client.dir\verify_callback.cpp.obj

191: C:\Users\oeadmin\workspace\Bors_staging\build\X64-Debug\openenclave\share\openenclave\samples\attested_tls\non_enc_client\verify_callback.cpp(163): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

191: C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h(208): note: see declaration of 'fopen'

191: [28/31] Linking CXX executable client\enc\tls_client_enc

191: [29/31] Generating tls_client_enc.signed

191: Created C:/Users/oeadmin/workspace/Bors_staging/build/X64-Debug/samples/attested_tls/client/enc/tls_client_enc.signed

191: [30/31] Linking CXX executable non_enc_client\tls_non_enc_client.exe

191/191 Test #191: samples ...............................................................................................................................***Timeout 480.00 sec

**Comment by jhand2** [comment]
Does it always fail on that step (linking)?

The attested_tls sample is just the last sample so it’s likely a coincidence that it always fails on that one.

**Comment by radhikaj** [comment]
It is not the last sample run. To compare it with the Windows Server 2019 release logs https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/277/pipeline/45
Switchless sample runs last

oeadmin@accws19d1f6180 C:\oe\open-enclave\openenclave\share\openenclave\samples\remote_attestation\build>(

cd C:\oe\open-enclave\openenclave\share\openenclave\samples\"switchless"  

 mkdir build  

 cd build  

 cmake .. -G Ninja -DNUGET_PACKAGE_PATH=C:\oe_prereqs -DLVI_MITIGATION=ControlFlow   || exit /b 0  

 ninja   || exit /b 0  

 ninja run   || exit /b 0 

) 

-- The C compiler identification is MSVC 19.16.27038.0

-- The CXX compiler identification is MSVC 19.16.27038.0

-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe

-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe

-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Looking for pthread.h

-- Looking for pthread.h - not found

-- Found Threads: TRUE  

VERBOSE-- Looking for sgx_enclave_common library - found

VERBOSE-- Looking for sgx_dcap_ql library - found

-- Performing Test OE_SPECTRE_MITIGATION_C_FLAGS_SUPPORTED

-- Performing Test OE_SPECTRE_MITIGATION_C_FLAGS_SUPPORTED - Failed

-- Performing Test OE_SPECTRE_MITIGATION_CXX_FLAGS_SUPPORTED

-- Performing Test OE_SPECTRE_MITIGATION_CXX_FLAGS_SUPPORTED - Failed

-- Configuring done

-- Generating done

CMake Warning:

  Manually-specified variables were not used by the project:



    LVI_MITIGATION





-- Build files have been written to: C:/oe/open-enclave/openenclave/share/openenclave/samples/switchless/build

[1/12] Generating oedebugrt.dll

[2/12] Generating oedebugrt.pdb

[3/12] Generating switchless_t.h, switchless_t.c, switchless_args.h

Generating edge routines for the Open Enclave SDK.

Success.

[4/12] Generating switchless_u.h, switchless_u.c, switchless_args.h

Generating edge routines for the Open Enclave SDK.

Success.

[5/12] Building C object enclave\CMakeFiles\enclave.dir\enc.c.obj

[6/12] Building C object host\CMakeFiles\switchless_host.dir\switchless_u.c.obj

[7/12] Building C object enclave\CMakeFiles\enclave.dir\switchless_t.c.obj

[8/12] Building C object host\CMakeFiles\switchless_host.dir\host.c.obj

..\host\host.c(28): warning C4133: 'function': incompatible types - from 'double *' to 'LARGE_INTEGER *'

..\host\host.c(51): warning C4090: 'function': different 'const' qualifiers

..\host\host.c(75): warning C4133: 'function': incompatible types - from 'double *' to 'LARGE_INTEGER *'

[9/12] Linking C executable enclave\enclave

[10/12] Linking C executable host\switchless_host.exe

[11/12] Generating private.pem, public.pem

Generating RSA private key, 3072 bit long modulus (2 primes)

.........................++++*.........................................................................++++

....................................++++*.....................................................................................................................................++++

e is 3 (0x03)

writing RSA key

[12/12] Generating enclave/enclave.signed

Created C:/oe/open-enclave/openenclave/share/openenclave/samples/switchless/build/enclave/enclave.signed

[1/1] cmd.exe /C "cd /D C:\oe\open-enclave\openenclave\share\openenclave\samples\switchless\build && C:\oe\open-enclave\openenclave\share\openenclave\samples\switchless\build\host\switchless_host.exe C:/oe/open-enclave/openenclave/share/openenclave/samples/switchless/build/enclave/enclave.signed"

1000000 host_increment_switchless() calls: 1000000 + 1000000 = 2000000. Time spent: 823 ms

1000000 host_increment_regular() calls: 1000000 + 1000000 = 2000000. Time spent: 4689 ms

1000000 enclave_decrement_switchless() calls: 1000000 - 1000000 = 0. Time spent: 1343 ms

1000000 enclave_decrement_regular() calls: 1000000 - 1000000 = 0. Time spent: 12983 ms

**Comment by jhand2** [comment]
@radhikaj it does actually look like every time it hangs during linking. And because it’s the LVI build I wonder if the LVI changes for the Windows compiler toolchain introduced a very specific bug that’s only hit in the attested_tls sample?

**Comment by mingweishih** [comment]
> @radhikaj it does actually look like every time it hangs during linking. And because it’s the LVI build I wonder if the LVI changes for the Windows compiler toolchain introduced a very specific bug that’s only hit in the attested_tls sample?

attested_tls sample is not compiled with LVI mitigation (only the helloworld sample does).

**Comment by jhand2** [comment]
good point. It just seems weird that it always fails during linking and it only happens on the LVI builds. But I can't repro locally so I can't isolate which part is actually taking so long.

**Comment by mingweishih** [comment]
> To compare it with the Windows Server 2019 release logs https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/Bors/detail/staging/277/pipeline/45
> Switchless sample runs last See log below
> 
> ## On Windows Server 2016 attested tls sample runs last. Which is weird.
> oeadmin@accws19d1f6180 C:\oe\open-enclave\openenclave\share\openenclave\samples\remote_attestation\build>(
> 
> cd C:\oe\open-enclave\openenclave\share\openenclave\samples"switchless"
> 
> mkdir build
> 
> cd build
> 
> cmake .. -G Ninja -DNUGET_PACKAGE_PATH=C:\oe_prereqs -DLVI_MITIGATION=ControlFlow || exit /b 0
> 
> ninja || exit /b 0
> 
> ninja run || exit /b 0
> 
> )
> 
> -- The C compiler identification is MSVC 19.16.27038.0
> 
> -- The CXX compiler identification is MSVC 19.16.27038.0
> 
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
> 
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
> 
> -- Detecting C compiler ABI info
> 
> -- Detecting C compiler ABI info - done
> 
> -- Detecting C compile features
> 
> -- Detecting C compile features - done
> 
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
> 
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
> 
> -- Detecting CXX compiler ABI info
> 
> -- Detecting CXX compiler ABI info - done
> 
> -- Detecting CXX compile features
> 
> -- Detecting CXX compile features - done
> 
> -- Looking for pthread.h
> 
> -- Looking for pthread.h - not found
> 
> -- Found Threads: TRUE
> 
> VERBOSE-- Looking for sgx_enclave_common library - found
> 
> VERBOSE-- Looking for sgx_dcap_ql library - found
> 
> -- Performing Test OE_SPECTRE_MITIGATION_C_FLAGS_SUPPORTED
> 
> -- Performing Test OE_SPECTRE_MITIGATION_C_FLAGS_SUPPORTED - Failed
> 
> -- Performing Test OE_SPECTRE_MITIGATION_CXX_FLAGS_SUPPORTED
> 
> -- Performing Test OE_SPECTRE_MITIGATION_CXX_FLAGS_SUPPORTED - Failed
> 
> -- Configuring done
> 
> -- Generating done
> 
> CMake Warning:
> 
> Manually-specified variables were not used by the project:
> 
> ```
> LVI_MITIGATION
> ```
> 
> -- Build files have been written to: C:/oe/open-enclave/openenclave/share/openenclave/samples/switchless/build
> 
> [1/12] Generating oedebugrt.dll
> 
> [2/12] Generating oedebugrt.pdb
> 
> [3/12] Generating switchless_t.h, switchless_t.c, switchless_args.h
> 
> Generating edge routines for the Open Enclave SDK.
> 
> Success.
> 
> [4/12] Generating switchless_u.h, switchless_u.c, switchless_args.h
> 
> Generating edge routines for the Open Enclave SDK.
> 
> Success.
> 
> [5/12] Building C object enclave\CMakeFiles\enclave.dir\enc.c.obj
> 
> [6/12] Building C object host\CMakeFiles\switchless_host.dir\switchless_u.c.obj
> 
> [7/12] Building C object enclave\CMakeFiles\enclave.dir\switchless_t.c.obj
> 
> [8/12] Building C object host\CMakeFiles\switchless_host.dir\host.c.obj
> 
> ..\host\host.c(28): warning C4133: 'function': incompatible types - from 'double *' to 'LARGE_INTEGER *'
> 
> ..\host\host.c(51): warning C4090: 'function': different 'const' qualifiers
> 
> ..\host\host.c(75): warning C4133: 'function': incompatible types - from 'double *' to 'LARGE_INTEGER *'
> 
> [9/12] Linking C executable enclave\enclave
> 
> [10/12] Linking C executable host\switchless_host.exe
> 
> [11/12] Generating private.pem, public.pem
> 
> Generating RSA private key, 3072 bit long modulus (2 primes)
> 
> .........................++++*.........................................................................++++
> 
> ....................................++++*.....................................................................................................................................++++
> 
> e is 3 (0x03)
> 
> writing RSA key
> 
> [12/12] Generating enclave/enclave.signed
> 
> Created C:/oe/open-enclave/openenclave/share/openenclave/samples/switchless/build/enclave/enclave.signed
> 
> [1/1] cmd.exe /C "cd /D C:\oe\open-enclave\openenclave\share\openenclave\samples\switchless\build && C:\oe\open-enclave\openenclave\share\openenclave\samples\switchless\build\host\switchless_host.exe C:/oe/open-enclave/openenclave/share/openenclave/samples/switchless/build/enclave/enclave.signed"
> 
> 1000000 host_increment_switchless() calls: 1000000 + 1000000 = 2000000. Time spent: 823 ms
> 
> 1000000 host_increment_regular() calls: 1000000 + 1000000 = 2000000. Time spent: 4689 ms
> 
> 1000000 enclave_decrement_switchless() calls: 1000000 - 1000000 = 0. Time spent: 1343 ms
> 
> 1000000 enclave_decrement_regular() calls: 1000000 - 1000000 = 0. Time spent: 12983 ms

On Windows 2019, the sample test has been finished already. There is an additional sample test (this log refers to) after the ctest for testing the package. If you scroll up a bit, you should be able see the log for ctest.

**Comment by jhand2** [comment]
https://github.com/openenclave/openenclave/pull/2703 increases the timeout to 30 min which does appear to solve the problem temporarily. We will keep investigating to figure out the problem so we can reduce the timeout.
