### ISSUE TITLE
Document instructions for manually installing Intel SGX drivers on WS2019

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#2840]
Given the new support for WS2019 planned for the upcoming v0.9 release, should we also document instructions for contributors/SDK users to manually install/upgrade the Intel SGX drivers on WS2019?

The question came up in the context of users who explicitly do not enable Windows Update on their VMs, and whether there was an alternative for them to get started on a clean WS2019 VM image or upgrade an older version of the PSW drivers/components without enabling Windows Update. 

This requires investigation because unlike the WS2016 Intel SGX PSW, Intel does not release an executable installer for WS2019 and only the collection of .inf and component binaries under the `PSW_INF_RS3_and_above` folder of their self-extracting Intel SGX PSW for Windows package.

This requirement also likely applies to Windows 10 client > 1709 users.

**Comment by MWShan** [comment]
Intel provides information on how to configure WS2016 and WS2019 in this document: [https://download.01.org/intel-sgx/latest/dcap-latest/windows/docs/Intel_SGX_DCAP_Windows_SW_Installation_Guide.pdf](url)

**Comment by radhikaj** [comment]
Duping this to 2267
