### ISSUE TITLE
Issue installing OE SDK on WS2016

### ISSUE THREAD

**Issue by gupta-ak** [openenclave/openenclave#2842]
In this [document](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md), the link to ["Intel Data Center Attestation Primitives (DCAP) Libraries v1.5](http://registrationcenter-download.intel.com/akdlm/irc_nas/16474/Intel%20SGX%20DCAP%20for%20Windows%20v1.5.100.2.exe) doesn't work for me. I'm getting a 404/blank screen when trying to install it. It looks like there is a v1.6 version now.

The work around I did was to install the newest version of the [Intel SGX SDK](https://software.intel.com/en-us/sgx/sdk) and then install the DCAP library from there.

**Comment by jhand2** [comment]
For the Windows releases whenever a new package is released the link for the old package becomes invalid. So the fix here is to update the documentation with the new v1.6 link.

We are working with intel for a more permanent solution to avoid invalidation links to older packages.

**Comment by jhand2** [comment]
@larrywxyz's PR https://github.com/openenclave/openenclave/pull/2832 updates this link so assigning to him
