### ISSUE TITLE
helloworld build error in open-enclave.0.8.2.nupkg

### ISSUE THREAD

**Issue by scofinan** [openenclave/openenclave#2849]
Test environment:
HW: SKL
SW: Windows Server 2016

How to reproduce:
1. Followed this wiki to install prerequisites:
https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Windows.md
SGX PSW: Intel(R)_SGX_Windows_x64_PSW_2.7.100.2.exe
SGX SDK: open-enclave.0.8.2.nupkg
oe is installed in C:\openenclave
2. Followed this wiki to build oe sdk sample helloworld:
https://github.com/openenclave/openenclave/blob/master/samples/README_Windows.md
$set CMAKE_PREFIX_PATH=C:\openenclave\open-enclave\openenclave\lib\openenclave\cmake
$cd C:\openenclave\open-enclave\openenclave\share\openenclave\samples\helloworld
$mkdir build
$cd build
$$cmake .. -G Ninja -DNUGET_PACKAGE_PATH=C:\oe_prereqs

Error message is as below:
C:\openenclave\open-enclave\openenclave\share\openenclave\samples\helloworld\build>cmake .. -G Ninja -DNUGET_PACKAGE_PATH=C:\oe_prereqs
-- The C compiler identification is MSVC 19.25.28612.0
-- The CXX compiler identification is MSVC 19.25.28612.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:15 (find_package):
  Could not find a configuration file for package "OpenEnclave" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    C:/openenclave/open-enclave/openenclave/lib/openenclave/cmake/openenclave-config.cmake, version: 0.8.2 (64bit)

-- Configuring incomplete, errors occurred!
See also "C:/openenclave/open-enclave/openenclave/share/openenclave/samples/helloworld/build/CMakeFiles/CMakeOutput.log".

**Comment by anakrish** [comment]
@scofinan Can you make sure if you are using x64 Native Prompt?

The error log shows that the x86 compiler is being picked up
`Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe`

**Comment by scofinan** [comment]
> @scofinan Can you make sure if you are using x64 Native Tools Prompt?
> 
> The error log shows that the x86 compiler is being picked up
> `Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.25.28610/bin/Hostx86/x86/cl.exe`

Thanks, anakrish,

This is my fault that I used x86 Native Tools Prompt, after I changed to x64, this error disappeared.

But I met another error like this:
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
CMake Error at C:/openenclave/open-enclave/openenclave/lib/openenclave/cmake/openenclave-config.cmake:116 (message):
  -- Looking for sgx_enclave_common library - not found
Call Stack (most recent call first):
  CMakeLists.txt:15 (find_package)

I checked that SGX PSW is working well, don't know if there needs other installation or setting?

**Comment by mingweishih** [comment]
> sgx_enclave_common

Can you check if the C:\oe_prereqs\EnclaveCommonAPI\lib/native\x64-Release exist?

**Comment by scofinan** [comment]
> > sgx_enclave_common
> 
> Can you check if the C:\oe_prereqs\EnclaveCommonAPI\lib/native\x64-Release exist?

This error happened during OE SDK installation, so after this error happened, C:\oe_prereqs didn't have any files, since the installation failed.

**Comment by scofinan** [comment]
Could anyone tell where sgx_enclave_common library is? It seems the key error of this bug.

**Comment by anakrish** [comment]
@scofinan Enclave Common API can be obtained following this: https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md

Can you tell me which version of Windows you are using? Win Server 2016 or Win 10?

**Comment by anakrish** [comment]
@scofinan Rereading your comments, you are on Win Server 2016.
Can you confirm if you have executed
```cmd
nuget.exe install EnclaveCommonAPI -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs
```
This is one of the last instructions in https://github.com/openenclave/openenclave/blob/master/samples/README_Windows.md

@mingweishih Can you confirm if the above command is correct for the latest PSW?

**Comment by mingweishih** [comment]
@anakrish Confirmed it works.

@scofinan can you try following the instruction: https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md#intel-data-center-attestation-primitives-dcap-libraries-v16

The below is the part of instruction that installs the sgx_enclave_command library. However, I'd recommend to follow the full instructions in the documentation in case there are other things missing.

- Download and run the .exe from [here](http://registrationcenter-download.intel.com/akdlm/irc_nas/16620/Intel%20SGX%20DCAP%20for%20Windows%20v1.6.100.2.exe)
- Extract the files to `C:\`
- Run the following command from powershell
`nuget.exe install EnclaveCommonAPI -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs`

**Comment by scofinan** [comment]
> @scofinan Enclave Common API can be obtained following this: https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md
> 
> Can you tell me which version of Windows you are using? Win Server 2016 or Win 10?

I tried both on Windows Server 2016 & 2019, the issues are same.

**Comment by scofinan** [comment]
> @scofinan Rereading your comments, you are on Win Server 2016.
> Can you confirm if you have executed
> 
> ```batchfile
> nuget.exe install EnclaveCommonAPI -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs
> ```
> 
> This is one of the last instructions in https://github.com/openenclave/openenclave/blob/master/samples/README_Windows.md
> 
> @mingweishih Can you confirm if the above command is correct for the latest PSW?

hi, anakrish, 

I installed PSW from this link:
https://github.com/openenclave/openenclave - Windows with SGX hardware - SGX1 with Flexible Launch Control (FLC) Prerequisites:
**C:\Intel SGX PSW for Windows v2.7.101.2\PSW_EXE_RS2_and_before\Intel(R)_SGX_Windows_x64_PSW_2.7.101.2.exe"**

and installed SDK from this link:
https://github.com/openenclave/openenclave - Windows with SGX hardware - Download and install the Open Enclave SDK NuGet Package:
**nuget.exe install open-enclave -Source C:\openenclave_nuget -OutputDirectory C:\oe -ExcludeVersion**

About your provided command, where can I find it in https://github.com/openenclave/openenclave?
nuget.exe install EnclaveCommonAPI -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs

**Comment by scofinan** [comment]
> @anakrish Confirmed it works.
> 
> @scofinan can you try following the instruction: https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md#intel-data-center-attestation-primitives-dcap-libraries-v16
> 
> The below is the part of instruction that installs the sgx_enclave_command library. However, I'd recommend to follow the full instructions in the documentation in case there are other things missing.
> 
> * Download and run the .exe from [here](http://registrationcenter-download.intel.com/akdlm/irc_nas/16620/Intel%20SGX%20DCAP%20for%20Windows%20v1.6.100.2.exe)
> * Extract the files to `C:\`
> * Run the following command from powershell
>   `nuget.exe install EnclaveCommonAPI -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs`

hi, mingweishih,

In https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md#intel-data-center-attestation-primitives-dcap-libraries-v16 -  Azure DCAP client for Windows [optional]
This part is optional, why user need to install DCAP? Actually, installing PSW and Nuget is enough, right?

**Comment by scofinan** [comment]
> @anakrish Confirmed it works.
> 
> @scofinan can you try following the instruction: https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md#intel-data-center-attestation-primitives-dcap-libraries-v16
> 
> The below is the part of instruction that installs the sgx_enclave_command library. However, I'd recommend to follow the full instructions in the documentation in case there are other things missing.
> 
> * Download and run the .exe from [here](http://registrationcenter-download.intel.com/akdlm/irc_nas/16620/Intel%20SGX%20DCAP%20for%20Windows%20v1.6.100.2.exe)
> * Extract the files to `C:\`
> * Run the following command from powershell
>   `nuget.exe install EnclaveCommonAPI -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs`

hi, @mingweishih 
It still had errors when run **cmake .. -G Ninja -DNUGET_PACKAGE_PATH=C:\oe_prereqs** to build helloworld.

Re-list my test status:
OS: Windows Server 2016
PSW: C:\Intel SGX PSW for Windows v2.7.101.2\PSW_EXE_RS2_and_before\Intel(R)_SGX_Windows_x64_PSW_2.7.101.2.exe"
SDK: .\nuget.exe install open-enclave -Source C:\openenclave_nuget -OutputDirectory C:\oe -ExcludeVersion
DCAP: .\nuget.exe install EnclaveCommonAPI -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs
**(And why we need to install DCAP? What's the use of it? All OE wiki pages don't show it is a mandatory option...)**

Could you please use a new and clear test environment to do a double check? Suppose your test environment has some previous versions which may affect the new version installation.
[build_error_of_helloworld.txt](https://github.com/openenclave/openenclave/files/4526668/build_error_of_helloworld.txt)

**Comment by mingweishih** [comment]
> > @anakrish Confirmed it works.
> > @scofinan can you try following the instruction: https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md#intel-data-center-attestation-primitives-dcap-libraries-v16
> > The below is the part of instruction that installs the sgx_enclave_command library. However, I'd recommend to follow the full instructions in the documentation in case there are other things missing.
> > 
> > * Download and run the .exe from [here](http://registrationcenter-download.intel.com/akdlm/irc_nas/16620/Intel%20SGX%20DCAP%20for%20Windows%20v1.6.100.2.exe)
> > * Extract the files to `C:\`
> > * Run the following command from powershell
> >   `nuget.exe install EnclaveCommonAPI -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs`
> 
> hi, @mingweishih
> It still had errors when run **cmake .. -G Ninja -DNUGET_PACKAGE_PATH=C:\oe_prereqs** to build helloworld.
> 
> Re-list my test status:
> OS: Windows Server 2016
> PSW: **C:\Intel SGX PSW for Windows v2.7.101.2\PSW_EXE_RS2_and_before\Intel(R)_SGX_Windows_x64_PSW_2.7.101.2.exe"**
> SDK: **.\nuget.exe install open-enclave -Source C:\openenclave_nuget -OutputDirectory C:\oe -ExcludeVersion**
> DCAP: **.\nuget.exe install EnclaveCommonAPI -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs**
> **(And why we need to install DCAP? What's the use of it? All OE wiki pages don't show it is a mandatory option...)**
> 
> Could you please use a new and clear test environment to do a double check? Suppose your test environment has some previous versions which may affect the new version installation.
> [build_error_of_helloworld.txt](https://github.com/openenclave/openenclave/files/4526668/build_error_of_helloworld.txt)

Hi @scofinan,

Thanks again for your reporting. I've tried to reproduce the steps in a newly created win server 2016. I can confirm that currently Intel DCAP are required to build and run the helloworld sample. I've updated the documentation in #2942.

Also, starting from v0.9, only Intel DCAP nuget package should be required during the build time. The issue of removing the runtime dependency of Intel DCAP driver is tracked in #2941.

**Comment by jhand2** [comment]
Specifically, you will also need to run `nuget.exe install DCAP_Components -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs`

**Comment by scofinan** [comment]
> Specifically, you will also need to run `nuget.exe install DCAP_Components -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs`

hi, @jhand2 @mingweishih 

OE wikis are a little confused for me, could you please help check if following steps right that I abstract from those OE wikis? It still had errors. :(

(In PowerShell)
install PSW:
$ C:\Intel SGX PSW for Windows v2.7.101.2\PSW_EXE_RS2_and_before\Intel(R)_SGX_Windows_x64_PSW_2.7.101.2.exe"

install DCAP
$ .\nuget.exe install EnclaveCommonAPI -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs
$ .\nuget.exe install DCAP_Components -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs

install SDK
$ .\nuget.exe install open-enclave -pre -Source C:\openenclave_nuget -OutputDirectory C:\openenclave -ExcludeVersion

(In 64 Native Tools Command Prompt for VS2017 or 2019)

$ set CMAKE_PREFIX_PATH=C:\openenclave\open-enclave\openenclave\lib\openenclave\cmake
$ mkdir build
$ cd build
$ cmake .. -G Ninja -DNUGET_PACKAGE_PATH=C:\oe_prereqs
$ ninja

[error.txt](https://github.com/openenclave/openenclave/files/4534568/error.txt)

**Comment by scofinan** [comment]
> Specifically, you will also need to run `nuget.exe install DCAP_Components -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs`

I installed open-enclave.0.9.0.nupkg and got following picture's result:
<img width="777" alt="error_open-enclave 0 9 0 nupkg" src="https://user-images.githubusercontent.com/44156386/80344799-bdddeb00-889a-11ea-8296-da9326c31696.png">

How is **sgx_dcap_ql.dll** installed? And which package includes it?
What I have installed are:
**Intel(R)_SGX_Windows_x64_PSW_2.7.101.2.exe
Intel SGX DCAP for Windows v1.6.100.2.exe
open-enclave.0.9.0.nupkg**

Are there any other mandatory packages to install?

**Comment by mingweishih** [comment]
> > Specifically, you will also need to run `nuget.exe install DCAP_Components -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs`
> 
> I installed open-enclave.0.9.0.nupkg and got following picture's result:
> <img alt="error_open-enclave 0 9 0 nupkg" width="777" src="https://user-images.githubusercontent.com/44156386/80344799-bdddeb00-889a-11ea-8296-da9326c31696.png">
> 
> How is **sgx_dcap_ql.dll** installed? And which package includes it?
> 
> What I have installed are:
> **Intel(R)_SGX_Windows_x64_PSW_2.7.101.2.exe Intel SGX DCAP for Windows v1.6.100.2.exe open-enclave.0.9.0.nupkg**
> 
> Are there any other mandatory packages to install?
> 
> Attach all output messages:
> [error message.txt](https://github.com/openenclave/openenclave/files/4538101/error.message.txt)

It should be part of DCAP drivers. Please check the steps 1-3 in the [here](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md#intel-data-center-attestation-primitives-dcap-libraries-v16)

**Comment by scofinan** [comment]
> > > Specifically, you will also need to run `nuget.exe install DCAP_Components -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs`
> > 
> > 
> > I installed open-enclave.0.9.0.nupkg and got following picture's result:
> > <img alt="error_open-enclave 0 9 0 nupkg" width="777" src="https://user-images.githubusercontent.com/44156386/80344799-bdddeb00-889a-11ea-8296-da9326c31696.png">
> > How is **sgx_dcap_ql.dll** installed? And which package includes it?
> > What I have installed are:
> > **Intel(R)_SGX_Windows_x64_PSW_2.7.101.2.exe Intel SGX DCAP for Windows v1.6.100.2.exe open-enclave.0.9.0.nupkg**
> > Are there any other mandatory packages to install?
> > Attach all output messages:
> > [error message.txt](https://github.com/openenclave/openenclave/files/4538101/error.message.txt)
> 
> It should be part of DCAP drivers. Please check the steps 1-3 in the [here](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md#intel-data-center-attestation-primitives-dcap-libraries-v16)

hi， @mingweishih 

I am so confused that there are 2 packages in https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md#intel-data-center-attestation-primitives-dcap-libraries-v16

$ nuget.exe install Microsoft.Azure.DCAP -ExcludeVersion -Version 1.3.0 -OutputDirectory C:\oe_prereqs
This command uses **microsoft.azure.dcap.1.3.0.nupkg**

$ nuget.exe install DCAP_Components -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs
$ nuget.exe install EnclaveCommonAPI -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs
These 2 commands uses **Intel SGX DCAP for Windows v1.6.100.2.exe**

Are those 2 packages same? I tried them meanwhile but they cannot coexist.

And when I run 
$ devcon.exe install LC_driver\drivers\b361e4d8-bc01-43fc-b8a6-8d101e659ed1\sgx_base_dev.inf root\SgxLCDevice
$ devcon.exe install DCAP_INF\drivers\226fdf07-49d3-46aa-a0ce-f21b6d4a05cf\sgx_dcap_dev.inf root\SgxLCDevice_DCAP
Will fail, what the probable causes?

**Comment by scofinan** [comment]
Could any one pick up a clear environment and go through the installation process?
I think current wikis have many nests and a little hard for new users, it costs so much time...
Thank you very much!

**Comment by mingweishih** [comment]
> Could any one pick up a blank environment and go through the installation process, then create a clear wiki just for installation?
> I think current wikis have many nests and not clear enough, it is a little hard for new users and costs so much time...
> Thank you very much!

Hi @scofinan,

I've already gone through the process on a newly created win 2016 machine last Friday. Please find my steps based on the [doc](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Windows.md) as 
follows. Please double check if there is any steps you're missing.

- Install Microsoft Visual Studio Build Tools 2019
- Install Git for Windows 64-bit
  - Make sure `C:\Program Files\Git\bin` and `C:\Program Files\Git\mingw64\bin` are added to the environment variable PATH (if not, manually add them)
- Add Clang
  - Make sure `C:\Program Files\LLVM\bin` is added to PATH
Next, follow the instruction [here](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md)
- Install Intel Platform Software for Windows (PSW) v2.7 
- Skip Azure DCAP client for Windows 
- Install Intel Data Center Attestation Primitives (DCAP) Libraries v1.6
  - Follow step 1 - 3 to install the driver (*.dll)
    - For `devcon.exe` in step 3, add `C:\Program Files (x86)\Windows Kits\10\tools\x64` to the PATH
    - Also, the paths to the `*.inf` may be different from the documentation. Manually check the path and use the correct ones, see the examples below.
![image](https://user-images.githubusercontent.com/58993167/80512941-2678a680-8933-11ea-8782-911201b12fcd.png)
![image (1)](https://user-images.githubusercontent.com/58993167/80512951-2aa4c400-8933-11ea-88b5-047569cb811c.png)
  - Follow step 4 to install the .lib files
    - Download the `nuget.exe` binary and follow the instruction
- Going back to [docs](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Windows.md#download-and-install-the-open-enclave-sdk-nuget-package), install the openenclave via nuget.
 - I used package v0.8.2 as it's what you initially tried to use.
- Follow [here](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Windows_using_oe_sdk.md) to build and run the helloworld.
  - Be sure to use x64 prompt from vs
  - The path to `set CMAKE_PREFIX_PATH=C:\openenclave\lib\openenclave\cmake` should be `set CMAKE_PREFIX_PATH=C:\oe\open-enclave\openenclave\lib\openenclave\cmake`

**Comment by scofinan** [comment]
> > Could any one pick up a blank environment and go through the installation process, then create a clear wiki just for installation?
> > I think current wikis have many nests and not clear enough, it is a little hard for new users and costs so much time...
> > Thank you very much!
> 
> Hi @scofinan,
> 
> I've already gone through the process on a newly created win 2016 machine last Friday. Please find my steps based on the [doc](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Windows.md) as
> follows. Please double check if there is any steps you're missing.
> 
> * Install Microsoft Visual Studio Build Tools 2019
> * Install Git for Windows 64-bit
>   
>   * Make sure `C:\Program Files\Git\bin` and `C:\Program Files\Git\mingw64\bin` are added to the environment variable PATH (if not, manually add them)
> * Add Clang
>   
>   * Make sure `C:\Program Files\LLVM\bin` is added to PATH
>     Next, follow the instruction [here](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md)
> * Install Intel Platform Software for Windows (PSW) v2.7
> * Skip Azure DCAP client for Windows
> * Install Intel Data Center Attestation Primitives (DCAP) Libraries v1.6
>   
>   * Follow step 1 - 3 to install the driver (*.dll)
>     
>     * For `devcon.exe` in step 3, add `C:\Program Files (x86)\Windows Kits\10\tools\x64` to the PATH
>     * Also, the paths to the `*.inf` may be different from the documentation. Manually check the path and use the correct ones, see the examples below.
>       ![image](https://user-images.githubusercontent.com/58993167/80512941-2678a680-8933-11ea-8782-911201b12fcd.png)
>       ![image (1)](https://user-images.githubusercontent.com/58993167/80512951-2aa4c400-8933-11ea-88b5-047569cb811c.png)
>   * Follow step 4 to install the .lib files
>     
>     * Download the `nuget.exe` binary and follow the instruction
> * Going back to [docs](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Windows.md#download-and-install-the-open-enclave-sdk-nuget-package), install the openenclave via nuget.
>   
>   * I used package v0.8.2 as it's what you initially tried to use.
> * Follow [here](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Windows_using_oe_sdk.md) to build and run the helloworld.
>   
>   * Be sure to use x64 prompt from vs
>   * The path to `set CMAKE_PREFIX_PATH=C:\openenclave\lib\openenclave\cmake` should be `set CMAKE_PREFIX_PATH=C:\oe\open-enclave\openenclave\lib\openenclave\cmake`

hi, @mingweishih 

Thanks for the detailed steps, but I still met the error as before:

C:\openenclave\share\openenclave\samples\helloworld\build>cmake .. -G Ninja -DNUGET_PACKAGE_PATH=C:\openenclave
-- The C compiler identification is MSVC 19.25.28614.0
-- The CXX compiler identification is MSVC 19.25.28614.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
CMake Error at C:/oe/open-enclave/openenclave/lib/openenclave/cmake/openenclave-config.cmake:116 (message):
  -- **Looking for sgx_enclave_common library - not found**
Call Stack (most recent call first):
  CMakeLists.txt:15 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/openenclave/share/openenclave/samples/helloworld/build/CMakeFiles/CMakeOutput.log".
See also "C:/openenclave/share/openenclave/samples/helloworld/build/CMakeFiles/CMakeError.log".

Is **sgx_enclave_common** library not in Intel(R)_SGX_Windows_x64_PSW_2.7.101.2.exe?
When I install following 2, this error will disappear:
nuget.exe install DCAP_Components -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs
nuget.exe install EnclaveCommonAPI -ExcludeVersion -Source "C:\Intel SGX DCAP for Windows v1.6.100.2\nuget" -OutputDirectory c:\oe_prereqs
But your steps don't include these 2 commands.

[CMakeError.log](https://github.com/openenclave/openenclave/files/4550275/CMakeError.log)
[CMakeOutput.log](https://github.com/openenclave/openenclave/files/4550277/CMakeOutput.log)

**Comment by mingweishih** [comment]
> > > Could any one pick up a blank environment and go through the installation process, then create a clear wiki just for installation?
> > > I think current wikis have many nests and not clear enough, it is a little hard for new users and costs so much time...
> > > Thank you very much!
> > 
> > 
> > Hi @scofinan,
> > I've already gone through the process on a newly created win 2016 machine last Friday. Please find my steps based on the [doc](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Windows.md) as
> > follows. Please double check if there is any steps you're missing.
> > 
> > * Install Microsoft Visual Studio Build Tools 2019
> > * Install Git for Windows 64-bit
> >   
> >   * Make sure `C:\Program Files\Git\bin` and `C:\Program Files\Git\mingw64\bin` are added to the environment variable PATH (if not, manually add them)
> > * Add Clang
> >   
> >   * Make sure `C:\Program Files\LLVM\bin` is added to PATH
> >     Next, follow the instruction [here](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsManualSGX1FLCDCAPPrereqs.md)
> > * Install Intel Platform Software for Windows (PSW) v2.7
> > * Skip Azure DCAP client for Windows
> > * Install Intel Data Center Attestation Primitives (DCAP) Libraries v1.6
> >   
> >   * Follow step 1 - 3 to install the driver (*.dll)
> >     
> >     * For `devcon.exe` in step 3, add `C:\Program Files (x86)\Windows Kits\10\tools\x64` to the PATH
> >     * Also, the paths to the `*.inf` may be different from the documentation. Manually check the path and use the correct ones, see the examples below.
> >       ![image](https://user-images.githubusercontent.com/58993167/80512941-2678a680-8933-11ea-8782-911201b12fcd.png)
> >       ![image (1)](https://user-images.githubusercontent.com/58993167/80512951-2aa4c400-8933-11ea-88b5-047569cb811c.png)
> >   * Follow step 4 to install the .lib files
> >     
> >     * Download the `nuget.exe` binary and follow the instruction
> > * Going back to [docs](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Windows.md#download-and-install-the-open-enclave-sdk-nuget-package), install the openenclave via nuget.
> >   
> >   * I used package v0.8.2 as it's what you initially tried to use.
> > * Follow [here](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Windows_using_oe_sdk.md) to build and run the helloworld.
> >   
> >   * Be sure to use x64 prompt from vs
> >   * The path to `set CMAKE_PREFIX_PATH=C:\openenclave\lib\openenclave\cmake` should be `set CMAKE_PREFIX_PATH=C:\oe\open-enclave\openenclave\lib\openenclave\cmake`
> 
> hi, @mingweishih
> 
> By following the detailed steps, it now works for me, really appreciate your support! :)

Glad that it finally worked out! Thanks so much to you, too!
