### ISSUE TITLE
Need to update URLs for Intel Linux drivers in the setup scripts

### ISSUE THREAD

**Issue by jinghe-INTC** [openenclave/openenclave#2850]
Since Intel has released new SGX and DCAP drivers for Linux, it needs to update the URLs of Intel drivers in the Ansible scripts:
openenclave/scripts/ansible/roles/linux/intel/vars/ubuntu/xenial.yml
openenclave/scripts/ansible/roles/linux/intel/vars/ubuntu/bionic.yml
Otherwise there will be execution problems with the latest Intel DCAP/SGX packages installed by APT.

The latest drivers from Intel are at:
https://download.01.org/intel-sgx/sgx-dcap/1.6/linux/distro/ubuntuServer16.04/sgx_linux_x64_driver_1.32.bin
https://download.01.org/intel-sgx/sgx-dcap/1.6/linux/distro/ubuntuServer18.04/sgx_linux_x64_driver_1.32.bin
https://download.01.org/intel-sgx/sgx-linux/2.9/distro/ubuntu16.04-server/sgx_linux_x64_driver_2.6.0_95eaa6f.bin
https://download.01.org/intel-sgx/sgx-linux/2.9/distro/ubuntu18.04-server/sgx_linux_x64_driver_2.6.0_95eaa6f.bin

**Comment by jhand2** [comment]
While I agree that we should update, I have seen no problems with the 2.9/1.6 Intel packages and the v1.22 dcap driver.

What problems do you expect to see?

**Comment by jinghe-INTC** [comment]
We set up a new system with the script last week,  and there were problems executing most of the ctest cases.

**Comment by radhikaj** [comment]
Also https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md and https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_16.04.md need to specify the latest intel driver versions.

**Comment by jhand2** [comment]
By the way we shouldn't update these docs until a new version of the driver is release. Without https://github.com/intel/SGXDataCenterAttestationPrimitives/pull/96, the driver fails to load on many types of machines (ACC VMs and most likely bare metal)
