### ISSUE TITLE
On Windows errno is not set as expected. This is exposed by a new test added in PR #2746

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#2858]
Please see https://github.com/openenclave/openenclave/pull/2746.

OE enclave does not set errno for strtol on windows.  We would expect  strtol to set errno inside enclaves.

**Comment by anakrish** [comment]
Closing this since changing `long` to `int64_t` has fixed Windows failures.

**Comment by radhikaj** [comment]
Thanks much @anakrish
