### ISSUE TITLE
Add BUILD_TESTS as CMake build option

### ISSUE THREAD

**Issue by letmaik** [openenclave/openenclave#2894]
It would be nice if one could disable building of the tests.

**Comment by radhikaj** [comment]
Is there an issue with how long samples take to build? What would the value of this option be for the end user?

**Comment by letmaik** [comment]
Not sampls, but tests. They take quite a while to build. I'm building OE as part of CI jobs and every second counts :) I'm currently patching the CMake script to not build the tests, but obviously that's bad. Every project I know of has build flags to omit building samples and/or tests. I think OE should have that too.

**Comment by jhand2** [comment]
Opened a PR https://github.com/openenclave/openenclave/pull/2897
