### ISSUE TITLE
Request for a message logging plug-in model for OE SDK

### ISSUE THREAD

**Issue by soccerGB** [openenclave/openenclave#2895]
Currently, the OE SDK internal logging support is tightly coupled with OE SDK implementation. it only outputs to console or thelog file specified through environment variable. Surely, each enclave application could redirect the console output to other destination via piping but it's not very flexible. 
Also, the logging is only enabled when for debug version of an enclave. It does not provide any help when it comes to investigating any production oe sdk application, which is a unsolved support issue. 

Is it possible to provide a logging plug-in model so that all applications on the same platform can benefit. For example, a cloud provider could provide such a logging plug-in to service its customers' oe applications and collect diagnostic data (with customer's approval)  for better customer support. 
The user of the plug-in should have control of the message output (level, fre/chk....)

**Comment by jhand2** [comment]
I think this issue is more clear in what it is asking for than https://github.com/openenclave/openenclave/issues/1046. Can we close the other issue in favor of this one?

In general I agree this this is  valuable thing to have.

**Comment by jhand2** [comment]
This would also mean moving the console logging mechanism to an optional plugin which is great as it makes the untrusted logging ocalls optional (they are unfortunately currently mandatory).

**Comment by achamayou** [comment]
Some applications will have their own mechanism for communication between enclave and host, and will want the log messages to use that/piggy back on existing traffic (we are in that situation), so something that would be beneficial is a logging mechanism that clearly separates message generation from their delivery, and allows user-provided delivery.

**Comment by anakrish** [comment]
@achamayou How are you working around this current limitation of the tight coupling between the message generation and message logging?
Today, all the enclave side logging is done via a single `oe_log_ocall` function. Are you providing your own implementation for this function?

**Comment by CodeMonkeyLeet** [comment]
Per [SIG-arch meeting](https://hackmd.io/KOeBDVlyQpOC-OqqHYvs0A?both#12-May-2020), keeping this on the backlog while investigating the priority and intended use case for this feature request.

**Comment by achamayou** [comment]
@anakrish we don't, OE logging happens via ocalls, which isn't ideal. If we had a clean way to route it over our communication mechanism (which we use for our logs and other purposes), it would be much better.

Is replacing oe_log_ocall a supported way of handling in-enclave OE logging for user apps?

**Comment by anakrish** [comment]
Thanks for the inputs @soccerGB @achamayou 
Created issue #3073 to focus on the need to provide a way to capture internal logs.

**Comment by anakrish** [comment]
I'm closing this in favor of #3073
