### ISSUE TITLE
Our gcc tests in CI use clang

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2930]
See log for this GCC build `ACC1604 gcc Debug LVI`: https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/rest/organizations/jenkins/pipelines/pipelines/pipelines/Azure-Linux/runs/148/nodes/30/steps/223/log/?start=0

```
-- The C compiler identification is Clang 7.1.0
-- The CXX compiler identification is Clang 7.1.0
-- The ASM compiler identification is Clang
-- Found assembler: /usr/local/lvi-mitigation/bin/clang-7
-- Check for working C compiler: /usr/local/lvi-mitigation/bin/clang-7
-- Check for working C compiler: /usr/local/lvi-mitigation/bin/clang-7 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/lvi-mitigation/bin/clang++-7
-- Check for working CXX compiler: /usr/local/lvi-mitigation/bin/clang++-7 -- works
```

The builds for all GCC linux builds I've looked at look to be the same.

**Comment by jhand2** [comment]
After looking at https://github.com/openenclave/openenclave-ci/blob/master/src/jenkins/common/Openenclave.groovy setting the environment variables CC and CXX should work. I don't know why it isn't working.

**Comment by mingweishih** [comment]
This is because of building with LVI mitigation, which suppresses the logic of detecting compilers in normal ways. Please assign this issue to me.
