### ISSUE TITLE
Translate quote3_error_t codes to human error messages

### ISSUE THREAD

**Issue by letmaik** [openenclave/openenclave#2945]
OE calls `sgx_qe_get_target_info` (and friends) but when an error happens then it only dumps OE_PLATFORM_ERROR together with "quote3_error_t=0x...". The error codes are listed at https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/quote_wrapper/common/inc/sgx_ql_lib_common.h. It would be good if the code is translated by OE into an understandable message.

**Comment by yentsanglee** [comment]
quote3_error_t values are defined by Intel. Our translation in OE may get out of sync if Intel modifies them.

**Comment by letmaik** [comment]
In that case I suggest to collaborate with Intel so that they come up with a `strerror` equivalent.

**Comment by jhand2** [comment]
Feel free to open an issue on the intel/linux-sgx repo. Thanks!

**Comment by radhikaj** [comment]
@yentsanglee Please open an issue in the Intel DCAP repo.

**Comment by yentsanglee** [comment]
Links to https://github.com/intel/SGXDataCenterAttestationPrimitives/issues/102

**Comment by yentsanglee** [comment]
I think the least we can do is to show the link to the header file at the error message - https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/quote_wrapper/common/inc/sgx_ql_lib_common.h
