### ISSUE TITLE
Add sample using endorsements in oe_verify_remote_report

### ISSUE THREAD

**Issue by letmaik** [openenclave/openenclave#2946]
The existing "hostverify" sample doesn't use the `endorsement` argument in `oe_verify_remote_report`.

**Comment by jhand2** [comment]
@ryanhsu19 do you think this is something that could be added to the existing sample?

**Comment by yentsanglee** [comment]
oecert generates report as well as endorsement file (*.col). Host verify sample can read the endorsement file as an argument in oe_verify_remote_report().

**Comment by letmaik** [comment]
What's the progress here? `oe_verify_remote_report` is not even part of the API docs because `host_verify.h` is missing https://openenclave.io/apidocs/v0.9/files.html.

**Comment by letmaik** [comment]
I tried to figure it out myself without much success. I need to call `oe_get_sgx_endorsements` which is not part of the public API.
