### ISSUE TITLE
Make oecert TEE-agile

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#2948]
Issue #2898 proposes to publish the oecert tool, which is currently SGX-specific.
This issue is to track making oecert not be SGX-only, but be applicable to multiple types of TEEs,
such as by using plugins of some sort.

Issue #2903 tracks general guidance around plugins.

**Comment by yentsanglee** [comment]
oecert has been replaced by oeutil which can generated evidence of various format. It's not SGX specific anymore.
