### ISSUE TITLE
install-windows-prereqs.ps1 should work on WS2019 with SGX1FLC option

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#2960]
Install-DCAP-dependencies still needs to be updated to be able to manually install the drivers over the existing ones via devcon; Install-DCAP-dependencies for WS2019 is just broken. (i.e. make SGX1FLC option just work on WS2019 instead of requiring SGX1FLC-nodriver option.)
See PR##2911 for manual instructions on updating drivers on WS2019.

**Comment by BRMcLaren** [comment]
Closing as resolved, fixed in #3525. @rs-- if I missed anything, please re-open as that wasn't the main focus of that PR.
