### ISSUE TITLE
Enable SGX endorsements retrieval and parsing

### ISSUE THREAD

**Issue by yentsanglee** [openenclave/openenclave#2976]
Endorsements help external verifier or relying party to perform additional validation. There are functions to retrieve attestation endorsements from oe_report_t. The functions are defined in openenclave\common\sgx\endorsements.h but it has not been made public. Also need sample code to demonstrate how endorsements can be retrieved and parsed.

**Comment by radhikaj** [comment]
Need to decide how to expose SGX specific APIs.

**Comment by yentsanglee** [comment]
I think this is for legacy SGX support. In the new plugin model, verifier knows how to parse endorsements.

**Comment by yentsanglee** [comment]
Similar to PR #2986, endorsements.h goes to include/openenclave/attestation/sgx.

**Comment by yentsanglee** [comment]
No longer needed.

**Comment by qiucwang** [comment]
SGX endorsements will be retrieved in claims from `oe_verify_evidence()`. Multiple SGX specific claims will be added to reflect that:
#define OE_CLAIM_SGX_TCB_INFO "tcb_info"
#define OE_CLAIM_SGX_TCB_ISSUER_CHAIN "tcb_issuer_chain"
#define OE_CLAIM_SGX_QE_ID_INFO "qe_id_info"
#define OE_CLAIM_SGX_QE_ID_ISSUER_CHAIN "qe_id_issuer_chain"
#define OE_CLAIM_SGX_PCK_CRL "pck_crl"
#define OE_CLAIM_SGX_ROOT_CA_CRL "root_ca_crl"
#define OE_CLAIM_SGX_CRL_ISSUER_CHAIN "crl_issuer_chain"
#define OE_SGX_CLAIMS_COUNT 7
