### ISSUE TITLE
No .cmake-format file

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#2989]
The script in `scripts/format-cmake` references a .cmake-format config file, however I don't see such a file checked in. Was that file accidentally omitted?

When I run `format-cmake`, it doesn't seem to follow the rules run on the existing files

cc @dthaler

**Comment by jhand2** [comment]
For example, when I run cmake-format on my machine, it prefers

```
if(NOT HAVE_GETOPT_LONG)
```

But the changes in #2893 prefer to add a space

```
if (NOT HAVE_GETOPT_LONG)
```

**Comment by dthaler** [comment]
ack, you're right.  PR #2990 generated.

**Comment by jhand2** [comment]
Fixed by  #2990
