### ISSUE TITLE
oe_verify_evidence should accept SGX quotes as input

### ISSUE THREAD

**Issue by LarryOsterman** [openenclave/openenclave#2999]
Currently oe_verify_evidence can only work with the output of oe_generate_evidence, which means it cannot be used to validate SGX collateral. oe_verify_evidence should be changed to accept collateral from known TEEs instead of must oe_generate_evidence.

**Comment by yentsanglee** [comment]
Currently
- oe_verify_evidence() verifies evidence from oe_get_evidence()
- oe_verify_report() verifies report from oe_get_report()

It helps if the legacy format from oe_get_report() and the new format from oe_get_evidence() can be unified and oe_verify_evidence(), which is the promoted API, can verify both formats.

**Comment by CodeMonkeyLeet** [comment]
@LarryOsterman, to clarify the requirement, are you asking for:
- a migration path between the `oe_get_report()` and `oe_get_evidence()` APIs, or
- `oe_verify_evidence()` to be able to handle raw TEE evidence not conforming to the data contract specified by the attestation plugin model?
    - For example, in the case of SGX, the desire is for `oe_verify_evidence()` to process a raw SGX quote produced by the Intel SGX SDK.

**Comment by LarryOsterman** [comment]
I have two possible inputs to my service:

- An OpenEnclave report from an SGX enclave.

- An SGX quote generated by an Intel SGX quoting enclave

I would like to have access to the claims returned by oe_verify_evidence, specifically the claims which include the state of the quote and the validity lifetime of the quote.

In order to do that, there needs to be a mechanism where either (a) oe_verify_evidence can accept either an OpenEnclave report or an SgX quote (there is a trivial transformation between those two, so it doesn't matter which of the two it is) or (b) some other function that can accept an OpenEnclave report or sgx function which returns the information currently returned by oe_verify_evidence.

That API doesn't need to be oe_verify_evidence, I just need the information that oe_verify_evidence returns.

**Comment by dthaler** [comment]
PR #2959 tracks requirements, and I believe it already covers all of Larry's requirements listed here.
It also describes proposal abstract APIs without dictating what the actual concrete APIs look like.

**Comment by yentsanglee** [comment]
For backward compatibility, it will be great if oe_verify_evidence() or new verifying API can also verify the reports generated by oe_get_report().

**Comment by radhikaj** [comment]
Bring up in sig-attestation. @radhikaj  to add to agenda

**Comment by yentsanglee** [comment]
Resolved by PR #3441 and other PRs.
