### ISSUE TITLE
Consider moving to recent versions of clang/LLVM

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#3001]
OE SDK currently is tested with clang-7 both on Windows and Linux.
For SGX, compiling with clang provides ability to incorporate mitigations (e.g: -mspeculative-load-hardening). The current release of LLVM is 10; there have been other mitigations that are now available since clang-7.

Do we have a plan/timeline for moving to newer versions of LLV/clang?

**Comment by jhand2** [comment]
This issue was opened a while ago to standardize around clang-8: https://github.com/openenclave/openenclave/issues/2476

Either clang 8 or 9 would be fine with me. We clang 7-9 all currently work I think, so its just a matter of changing the version used in CI right?

**Comment by jhand2** [comment]
Btw I think our RHEL build uses clang 8 by default already.

**Comment by anakrish** [comment]
@jhand2 Additionally we need to
- Avoid hard-coded references to clang-7 in our docs 
- Avoid hard-coding clang-7 in samples
- Avoid hard-coding clang-7 in scripts (ansible, install-prereqs)

**Comment by radhikaj** [comment]
@mingweishih : Samples- hardcoding of clang-7 has now been removed.

**Comment by radhikaj** [comment]
Scripts: should find appropriate version if it exists, otherwise picks a min version.

**Comment by radhikaj** [comment]
Do #2476 first.

**Comment by radhikaj** [comment]
we currently use clang-8 and are moving to clang-10.
