### ISSUE TITLE
How to build OE unit tests on Ubuntu 18.04

### ISSUE THREAD

**Issue by scofinan** [openenclave/openenclave#3005]
SW: Ubuntu 18.04, OE latest version
HW: SKL

According to https://github.com/openenclave/openenclave/tree/master/tests,
To run all tests Open Enclave tests, type the following commands to build and run the tests from the corresponding CMake output folder:
build$ make
build$ ctest

Questions: Where does user execute those commands? If in openenclave/tests, where does build/ exist? And how to generate it?

**Comment by jhand2** [comment]
The tests are built as part of the SDK. In short:

```
# Start from root directory of repo
$ mkdir build
$ cd build
$ cmake ..
$ make
$ ctest
```

You can find more complete instructions in the docs for building the SDK from source.

**Comment by scofinan** [comment]
> The tests are built as part of the SDK. Assuming proper dependencies are installed, in short:
> 
> ```
> # Start from root directory of repo
> $ mkdir build
> $ cd build
> $ cmake ..
> $ make
> $ ctest
> ```
> 
> You can find more complete instructions in the docs for building the SDK from source.

hello, @jhand2 

Thanks for the support, yes I have tried your steps before reported this issue, also met some errors as below:
...
-- Valgrind not found
-- Looking for crypto library - found
-- Looking for dl library - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
ENABLE_FULL_LIBCXX_TESTS not set - building some libcxx tests
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")
CMake Error at tools/oeedger8r/CMakeLists.txt:11 (message):
  Please check your esy installation

-- Configuring incomplete, errors occurred!
See also "/home/sgx/Desktop/oe/openenclave/build/CMakeFiles/CMakeOutput.log".
See also "/home/sgx/Desktop/oe/openenclave/build/CMakeFiles/CMakeError.log".

Attach the logs:
[CMakeError.log](https://github.com/openenclave/openenclave/files/4602864/CMakeError.log)
[CMakeOutput.log](https://github.com/openenclave/openenclave/files/4602865/CMakeOutput.log)


BTW, I follow this wiki to enable OE SDK on Ubuntu 18.04, are there any other web pages need to follow?
https://github.com/openenclave/openenclave/blob/v0.9.x/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md

**Comment by nonpolarity** [comment]
@scofinan "Please check your esy installation" means esy is not ready on your system. After https://github.com/openenclave/openenclave/blob/v0.9.x/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md you probably need https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1GettingStarted.md or https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1FLCGettingStarted.md to install all the prerequisites, which include esy.

**Comment by scofinan** [comment]
> @scofinan "Please check your esy installation" means esy is not ready on your system. After https://github.com/openenclave/openenclave/blob/v0.9.x/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md you probably need https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1GettingStarted.md or https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1FLCGettingStarted.md to install all the prerequisites, which include esy.

hi, @nonpolarity 
Thanks for the support, When I run 
$ansible-playbook scripts/ansible/oe-contributors-setup-sgx1.yml

Here is the error message:
TASK [linux/openenclave : Install all the Open Enclave prerequisites APT packages for development] ****
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update apt cache."}

NO MORE HOSTS LEFT ************************************************************************************
        to retry, use: --limit @/home/sgx/Desktop/oe/openenclave/scripts/ansible/oe-contributors-setup-sgx1.retry

PLAY RECAP ********************************************************************************************
localhost                  : ok=10   changed=0    unreachable=0    failed=1

My host has set up proxy due to network requirement, so does it need to set proxy of ansible and how to set it if needed? Or any other settings?

**Comment by nonpolarity** [comment]
@scofinan Yes I think the error is related to network issue. I have no much experience about ansible proxy, maybe you can try the reference here https://stackoverflow.com/questions/53591531/dynamicly-set-http-proxy-in-an-ansible-playbook.

**Comment by scofinan** [comment]
> @scofinan Yes I think the error is related to network issue. I have no much experience about ansible proxy, maybe you can try the reference here https://stackoverflow.com/questions/53591531/dynamicly-set-http-proxy-in-an-ansible-playbook.

@nonpolarity 
Thanks a lot for the support.

I found that some 3rd parties downloaded very slowly and I annotated them, then the unit test build process would be normal. Maybe it was caused by different network status. I will close this issue.

**Comment by ChrisVoile** [comment]
After cmake, is it normal for Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed?
