### ISSUE TITLE
install-windows-prereqs.ps1 can fail trying to set sgx_lc_msr regkey on WS2019

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#3010]
The install-windows-prereqs.ps1 script can fail with the error:

> Cannot find path 'HKLM:\SYSTEM\CurrentControlSet\Services\sgx_lc_msr\Parameters' because it does not exist.

This is because it always tries to set the sgx_lc_msr regkey assuming that the user may be using the `SGX1FLC-NoDriver` setting, but still wants the enable the default installed FLC driver. However, if the device is not SGX enabled or there WU has failed to setup the sgx_lc_msr regkey before the script is run, there's no regkey to create the value under.

As an independent fix, the script should:
- only attempt to write the regkey if both `($LaunchConfiguration -eq "SGX1FLC-NoDriver") -and (${OS_VERSION} -eq "WinServer2019")`
- probe the presence of the regkey and create it if not found.

This can also be addressed as part of fixing #2960: If the `SGX1FLC` option just works for WS2019 by always upgrading from local packages, then the script should only set the regkey in that scenario, and not try to set it in the `SGX1FLC-NoDriver` configuration.

**Comment by BRMcLaren** [comment]
@CodeMonkeyLeet I fixed this as part of #2960 , closing now. If we see a resurgence please re-open,
