### ISSUE TITLE
Sample project remote_attestation failed in execution on a SGX FLC platform

### ISSUE THREAD

**Issue by jinghe-INTC** [openenclave/openenclave#3011]
There is a problem in running sample project remote_attestation on a SGX FLC platform with Ubuntu 18.04.
Intel SGX/DCAP driver, PSW were installed, and  /etc/sgx_default_qcnl.conf has been modified, pointing to a valid SGX PCCS server.  

What else do I need to do to make this sample work properly on the FLC platform?

**I have removed the log from this post since it was not the right one for this issue. Please ignore it if you have the copy.**

**Comment by jhand2** [comment]
Need more information

* What version of OE
* What version of PSW
* What version of DCAP libs
* What version of SGX driver

The failure happens during loading so I don't think it's necessarily related to attestation

**Comment by jsun39** [comment]
I
Enclave: ***/home/sgxtest/git/openenclave/samples/remote_attestation/common/attestation.cpp(59): generate_remote_report succeeded.
Enclave: ***/home/sgxtest/git/openenclave/samples/remote_attestation/common/dispatcher.cpp(133): get_remote_report_with_pubkey succeeded
Host: 1st enclave's public key:
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAohMkqv0ccUXBEkwfWc/H
vo0WF2QVKqbexLTD7K+Q+u9bkBmLv0xS/moQ9KGiFJpyMJclu61K5BDeIgbqqZ0S
fg0h8aFD5EUsxX9Q9cv5kDa4a4fkYLnI6MHyFOpXt+elrgaYAEq9cuEruUAtoSpU
f1BGIhF+OfFbpWkZnR02MGrZA09DOXYSVO4SoOzk8eHxxsB1ftEh+PzSUacfRuf4
miQe88jSlofiPXdJyaCcCcuTCC0cT12m9eybG9xKrAgmRFvH5f0yXMHmTp8j4fav
QyDplNsjiwFLyYcXf3+QeKj6ROoPkbe5joJkk7+td/rQ0AwiG8CJvLyyGFQcbFOC
zQIDAQAB
-----END PUBLIC KEY-----
Host: requesting 2nd enclave to attest 1st enclave's the remote report and the public key
2020-05-11T15:06:42.434607Z [(E)ERROR] tid(0x7f9a9a362740) | enclave_b.signed::OE_INVALID_PARAMETER [/home/sgxtest/git/openenclave/enclave/crypto/cert.c:oe_cert_chain_read_pem:742]
2020-05-11T15:06:42.434749Z [(E)ERROR] tid(0x7f9a9a362740) | enclave_b.signed::OE_INVALID_PARAMETER [/home/sgxtest/git/openenclave/common/sgx/quote.c:oe_get_quote_cert_chain_internal:401]
2020-05-11T15:06:42.434890Z [(E)ERROR] tid(0x7f9a9a362740) | enclave_b.signed:Failed to get certificate chain from quote. OE_INVALID_PARAMETER (oe_result_t=OE_INVALID_PARAMETER) [/home/sgxtest/git/openenclave/common/sgx/endorsements.c:oe_get_sgx_endorsements:370]
2020-05-11T15:06:42.435050Z [(E)ERROR] tid(0x7f9a9a362740) | enclave_b.signed::OE_INVALID_PARAMETER [/home/sgxtest/git/openenclave/enclave/crypto/cert.c:oe_cert_free:711]
2020-05-11T15:06:42.435180Z [(E)ERROR] tid(0x7f9a9a362740) | enclave_b.signed::OE_INVALID_PARAMETER [/home/sgxtest/git/openenclave/enclave/crypto/cert.c:oe_cert_free:711]
2020-05-11T15:06:42.435315Z [(E)ERROR] tid(0x7f9a9a362740) | enclave_b.signed::OE_INVALID_PARAMETER [/home/sgxtest/git/openenclave/enclave/crypto/cert.c:oe_cert_chain_free:781]
2020-05-11T15:06:42.435467Z [(E)ERROR] tid(0x7f9a9a362740) | enclave_b.signed:Failed to get SGX endorsements. OE_INVALID_PARAMETER (oe_result_t=OE_INVALID_PARAMETER) [/home/sgxtest/git/openenclave/common/sgx/quote.c:oe_verify_sgx_quote:453]
2020-05-11T15:06:42.435599Z [(E)ERROR] tid(0x7f9a9a362740) | enclave_b.signed::OE_INVALID_PARAMETER [/home/sgxtest/git/openenclave/enclave/sgx/report.c:oe_verify_report:70]
Enclave: ***/home/sgxtest/git/openenclave/samples/remote_attestation/common/attestation.cpp(102): oe_verify_report failed (OE_INVALID_PARAMETER).

Enclave: ***/home/sgxtest/git/openenclave/samples/remote_attestation/common/dispatcher.cpp(175): verify_report_and_set_pubkey failed.
Host: verify_report_and_set_pubkey failed. OE_OKHost: Terminating enclaves
Enclave: ***/home/sgxtest/git/openenclave/samples/remote_attestation/common/crypto.cpp(90): mbedtls cleaned up.
Host: Enclave successfully terminated.
Enclave: ***/home/sgxtest/git/openenclave/samples/remote_attestation/common/crypto.cpp(90): mbedtls cleaned up.
Host: Enclave successfully terminated.
Host:  failed

**Comment by jsun39** [comment]
I think Jing posted the wrong log, please see the above log info.

**Comment by jinghe-INTC** [comment]
Thanks. And see the version information below:
OE: v0.9.0
PSW: SGX 2.9.1 Linux
DCAP libs: DCAP 1.6 
SGX driver: sgx-1.32

**Comment by jhand2** [comment]
@yentsanglee could you or someone on your team take a look at this?

**Comment by radhikaj** [comment]
Please use https://github.com/openenclave/openenclave/issues/3011#issuecomment-626515817 as the log you would investigate.

**Comment by radhikaj** [comment]
@jinghe-INTC Can you please update the first log you added in the original description of the issue? It appears to be unrelated to attestation.

**Comment by yentsanglee** [comment]
@jinghe-INTC did you run the sample on an Azure VM? Can you please set log level to INFO and re-run the sample?

export OE_LOG_LEVEL="INFO"

**Comment by jinghe-INTC** [comment]
Here's the execution log on Azure VM (Ubuntu 16.04):
[remote_attestation.azure.log](https://github.com/openenclave/openenclave/files/4613059/remote_attestation.azure.log)

**Comment by jsun39** [comment]
I have tried to execute: export OE_LOG_LEVEL="INFO", the log information didn't change. So I guess that this log level setting is not available to non-Azure VM environment.  If my guess is wrong, please let me know how to change the log level on non-Azure VM environment.

**Comment by radhikaj** [comment]
> Here's the execution log on Azure VM (Ubuntu 16.04):
> [remote_attestation.azure.log](https://github.com/openenclave/openenclave/files/4613059/remote_attestation.azure.log)

@jinghe-INTC From the log it looks like the remote attestation sample passed
 [/home/azureuser/openenclave-master/common/sgx/qeidentity.c:oe_validate_qe_identity:87]
Enclave: ***/home/azureuser/remote_attestation/common/attestation.cpp(163): remote attestation succeeded.
Enclave: ***/home/azureuser/remote_attestation/common/dispatcher.cpp(179): verify_report_and_set_pubkey succeeded.
Host: Remote attestation Succeeded
Host: Terminating enclaves
Enclave: ***/home/azureuser/remote_attestation/common/crypto.cpp(90): mbedtls cleaned up.
Host: Enclave successfully terminated.
Enclave: ***/home/azureuser/remote_attestation/common/crypto.cpp(90): mbedtls cleaned up.
Host: Enclave successfully terminated.
Host:  succeeded

**Comment by jinghe-INTC** [comment]
Yes. It always passes on Azure VM but not on SGX FLC physical platform. 
Is there any way to print this kind of verbose information on non-Azure platform? Thanks.

**Comment by yentsanglee** [comment]
We have recently enabled attestation on non-Azure platform but it requires some setup.
@yufjiang can you please help?

**Comment by yufjiang** [comment]
Hi @jinghe-INTC have you tried to follow the instructions in this document. See if it can help you out.
https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/NonAccMachineSGXLinuxGettingStarted.md

**Comment by jinghe-INTC** [comment]
After carefully  setting up the PCCS service, the sample passed.

> $ host/remote_attestation_host enclave_a/enclave_a.signed enclave_b/enclave_b.signed
Host: Creating two enclaves
Host: Enclave library enclave_a/enclave_a.signed
...
Enclave: ***/home/sgx1911/git/openenclave/samples/remote_attestation/common/dispatcher.cpp(179): verify_report_and_set_pubkey succeeded.
Host: Remote attestation Succeeded
Host: Terminating enclaves
Enclave: ***/home/sgx1911/git/openenclave/samples/remote_attestation/common/crypto.cpp(90): mbedtls cleaned up.
Host: Enclave successfully terminated.
Enclave: ***/home/sgx1911/git/openenclave/samples/remote_attestation/common/crypto.cpp(90): mbedtls cleaned up.
Host: Enclave successfully terminated.
Host:  succeeded
