### ISSUE TITLE
install-windows-prereqs.ps1: Installation of Python adds partial path to system path

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#3043]
Running `./scripts/install-windows-prereqs.ps1 -InstallPath C:/oe_prereqs -LaunchConfiguration SGX1FLC -DCAPClientType Azure1` causes `C:\Program Files\python-3.7.4\Scr` to be added to system path.

Additionally it raises the following warnings, which indicates that the `install-windows-prereqs.ps1` may be corrupting the PATH.

SUCCESS: Specified value was saved.
[2020-05-17T17:17:45.3769286+00:00] Start-ExecuteWithRetry attempt 0
  **WARNING: The script wheel.exe is installed in '**C:\Program Files\python-3.7.4\Scripts**' which is not on PATH.**
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**WARNING: **The data being saved is truncated to 1024 characters**.**
[2020-05-17T17:17:56.3939980+00:00] Start-ExecuteWithRetry terminated
Collecting pip<19.2
  Using cached https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/2c/c5/0d38afb961f83e0d51f319f7dc166195ebabc1ea3cb20a10a77f500f7156/setuptools-46.4.0-py3-none-any.whl
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/8c/23/848298cccf8e40f5bbb59009b32848a4c38f4e7f3364297ab3c3e2e2cd14/wheel-0.34.2-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-19.1.1 setuptools-46.4.0 wheel-0.34.2

SUCCESS: Specified value was saved.
[2020-05-17T17:17:56.4096225+00:00] Start-ExecuteWithRetry attempt 0
**WARNING: **You are using pip version 19.1.1, however version 20.1 is available**.**
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
[2020-05-17T17:17:58.0943130+00:00] Start-ExecuteWithRetry terminated
Collecting cmake_format
  Using cached https://files.pythonhosted.org/packages/63/00/cc2609916eb0ddb636619350e2bdf8b96e509ca65a44860bd11f6287e143/cmake_format-0.6.10-py3-none-any.whl
Collecting six>=1.13.0 (from cmake_format)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Installing collected packages: six, cmake-format
Successfully installed cmake-format-0.6.10 six-1.14.0
```

**Comment by BRMcLaren** [comment]
@anakrish I fixed this months ago and forgot to close this out. Can you verify if this is still a problem and if not, let's close it out?

**Comment by BRMcLaren** [comment]
accidentally closed

**Comment by radhikaj** [comment]
@anakrish I think this is fixed. Can you reopen if you find an issue?
