### ISSUE TITLE
Use syscall to set fs/gs in simulation mode

### ISSUE THREAD

**Issue by mikbras** [openenclave/openenclave#3048]
Rather than emulating the WRFSBASE/WRGSBASE instructions, it would be best to use a syscall.

**Comment by jhand2** [comment]
Exception handling does not currently work in simulation mode, so OE is not emulating the instructions in this case.

**Comment by radhikaj** [comment]
This is addressed in Jordan's branch. @jhand2: Please add commit-id here. Closing this as of now since it is not a problem and has been fixed.

**Comment by jhand2** [comment]
Fixed here https://github.com/openenclave/openenclave/commit/2d92ced21169b0fa9628d60216ac8922f913bc37
