### ISSUE TITLE
__oe_get_enclave_size() does not reflect the ELRANGE

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#3056]
As observed in PR #3007:

- `_calculate_enclave_size()` in the enclave creation/measurement codepath produces 2 values:
    - `enclave_end`, the total size of the enclave loaded during enclave creation, including the enclave image and all the data pages such as the heap, stacks and TCS pages.
    - `enclave_size`, the size of the enclave as recorded by the SECS, which must be a power of 2 for SGX. This is the `enclave_end` value rounded up to the next power of 2, and reflects the ELRANGE of the enclave. 
- `oe_sgx_build_enclave()` calls `oe_sgx_create_enclave()` with `enclave_size` which sets that value in the SECS for the enclave. 
- `oe_sgx_build_enclave()` calls `patch()` on the enclave image with calculated `enclave_end` as the `image_info.enclave_size` global value before loading it into the enclave.
- After the enclave is initialized, the enclave internally can call `__oe_get_enclave_size()`, which returns the global `image_info.enclave_size` that was patched, but this value is potentially smaller than the size of the enclave as seen by SGX (which is the power of 2 `enclave_size` value).

This has some ambiguous semantics in the enclave, since `__oe_get_enclave_size()` is used by the bounds checks `oe_is_within_enclave()` and `oe_is_outside_enclave()`, which seem like they should reflect the SGX enclave boundary as determined by the enclave SECS rather than the limit of the pages initially provisioned in to the enclave. Its only other use seems to be in a vestigial helper function `oe_get_num_pages()` for a diagnostic code path for tests/ecall that is never built.

This may have more bearing once OE SDK supports SGX2, as there will likely be a need to figure out the end of the currently allocated pages in the enclave virtual address range for EDMM. At that point, we will need to track two separate variables: one for the currently allocated limit (`enclave_end`, which should be renamed, and likely be made mutable) and the actual size of the enclave (`enclave_size`). We should probably fix the semantics of the `__oe_get_enclave_size()` in the meantime though, by having `oe_sgx_build_enclave()` patch the image with `enclave_size` rather than `enclave_end`.

**Comment by radhikaj** [comment]
Intel SDK is using the actual enclave size (ELRANGE)
