### ISSUE TITLE
SGX: LVI mitigation tool limitation when processing assembly source with .byte code

### ISSUE THREAD

**Issue by bodzhang** [openenclave/openenclave#3068]
The GNU Assembler and Python script based solution to parse assembly code and insert LFENCE or replacing RET/Indirect-branch instructions were adopted in Intel SGX SDK project and [Open Enclave project ](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/AdvancedBuildInfo.md#lvi-mitigation) to mitigate the [LVI issue](https://software.intel.com/security-software-guidance/insights/deep-dive-load-value-injection).

The GNU Assembler and the Python script search for relevant instruction mnemonic, for example, instructions reading from memory, or RET instruction, and perform the required insertion or replacement. This implementation is not able to handle .byte code instructions in the assembly code. I believe the GNU Assembler and the Python script will output a warning if it encounters .byte code. 

Though it should be an uncommon practice to write assembly source code using .byte code, and compilers typically won't generate assembly output with .byte code, some assembly source code does use .byte code. One prominent example is OpenSSL project. OpenSSL contains assembly implementation for certain crypto algorithm, to leverage specific CPU instructions for security or performance reason. OpenSSL source tree contains perl scripts that the build process uses to generate assembly code. The output assembly code contains .byte code for certain instructions. My guess is that the perl scripts were developed before those instructions were widely supported by the assemblers. So the developer(s) chose to use .byte code instead of mnemonic.

Due to the limitation of the GNU Assembler and the Python script implementation, the Intel [SGXSSL project](https://github.com/intel/intel-sgx-ssl) chose to [manually insert mitigation around .byte code the tool can't handle](https://github.com/intel/intel-sgx-ssl/blob/master/openssl_source/Linux/README.md). For example, in [aesni-x86_64.s](https://github.com/intel/intel-sgx-ssl/blob/master/openssl_source/Linux/aesni-x86_64.s), at [line 1847](https://github.com/intel/intel-sgx-ssl/blob/67e01f1ecc47d89e3ef6a73b0959ba5a6e61e27c/openssl_source/Linux/aesni-x86_64.s#L1847), the .byte code is [AESENCLAST](https://www.felixcloutier.com/x86/aesenclast) instruction with memory load. A LFENCE instruction was inserted after it.

The ongoing effort of supporting OpenSSL crypto in OE SDK as described in the [design doc](https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/enclave_openssl_support.md) needs to keep the LVI mitigation tool limitation in mind.

**Comment by radhikaj** [comment]
As soon as we have support for Open SSL, the openssl code will not be LVI instrumented.

**Comment by mingweishih** [comment]
[Here](https://github.com/intel/intel-sgx-ssl/tree/master/openssl_source/Linux) lists the set of assembly code rewritten by Intel.

**Comment by anakrish** [comment]
Is it not possible to amend the python script to inset the lfences manually after each .byte code?
For example the following code would print the locations of each .byte within a .S file, assuming pygments python library has been installed via pip.

```python
asm_code = open('aesni-x86_64.s').read()
from pygments.lexers import GasLexer
lexer = GasLexer()
tokens = lexer.get_tokens_unprocessed(asm_code)
for t in tokens:
    if t[2].startswith('.byte'):
        print(t)
```

Is there more to it than inserting an lfence after every .byte gas mneumonic?
