### ISSUE TITLE
Missing dependency for the latest Intel SGX deb package

### ISSUE THREAD

**Issue by devansh1305** [openenclave/openenclave#3079]
So I am trying this command:
`sudo dpkg -i libsgx-enclave-common_2.6.100.51363-bionic1_amd64.deb` 

this is the output i get:
```
(Reading database ... 280706 files and directories currently installed.)
Preparing to unpack libsgx-enclave-common_2.6.100.51363-bionic1_amd64.deb ...
Unpacking libsgx-enclave-common (2.6.100.51363-bionic1) over (2.6.100.51363-bionic1) ...
dpkg: dependency problems prevent configuration of libsgx-enclave-common:
 libsgx-enclave-common depends on libprotobuf10; however:
  Package libprotobuf10 is not installed.

dpkg: error processing package libsgx-enclave-common (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.31-0ubuntu9) ...
Errors were encountered while processing:
 libsgx-enclave-common
```

Any idea whats the problem?

PS: I am on:
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
```

**Comment by jhand2** [comment]
dpkg will not install dependent libraries. The package was still installed, it just wasn't configured. To fix it up you can run `sudo apt install -f`

Please note that the Open Enclave SDK is not officially supported on Ubuntu 20.04. There may be things that don't work as expected.

**Comment by devansh1305** [comment]
Still get the same error. I guess I will have to roll back to 18.04

**Comment by jhand2** [comment]
One likely issue is that the package you're installing is for bionic (18.04) and will likely not work on a different system.

**Comment by devansh1305** [comment]
> One likely issue is that the package you're installing is for bionic (18.04) and will likely not work on a different system.

Is there a difference between ubuntu 18.04 LTS and bionic?

**Comment by jhand2** [comment]
bionic is the codename for 18.04

**Comment by jhand2** [comment]
xenial == 16.04
bionic == 18.04
focal == 20.04

**Comment by devansh1305** [comment]
oh ok
