### ISSUE TITLE
API exposing the amounts of available and used memory in-enclave

### ISSUE THREAD

**Issue by achamayou** [openenclave/openenclave#3097]
Opening this as an issue to discuss first whether it should be its own design proposal, or should be done as an amendment to the Pluggable allocators Design Spec written by @anakrish.

I've raised this a couple of times before:
- https://github.com/openenclave/openenclave/issues/2023#issuecomment-571150418
- https://github.com/openenclave/openenclave/pull/2722#pullrequestreview-378993738

Running a service inside an enclave today means setting a fixed heap size for each node at startup via the oesign config (*). Operating that service safely and efficiently requires monitoring how much of that total memory is currently used or available, at least roughly, in particular:

1. is memory usage near capacity?
2. is it considerably under?
3. is it steadily heading towards capacity?

For the operator to see this, service nodes must expose it, and for the nodes to expose it, they must be able to obtain it. Although it is not the only option, I believe OpenEnclave should have an API exposing these values because:

1. It has access to, and knowledge of the enclave configuration
2. It has access to the allocator, which it abstracts away from the user

It may be that certain enclave or allocator configurations do not allow exposing meaningful values for these metrics, in which case the API should make it explicit they could not be obtained.

(*) with SGXv1 anyway, but that's what's commercially available in the cloud today.

As a very rough first draft, I would suggest something like:

```
struct oe_memory_stats
{
  size_t total_bytes;
  size_t used_bytes;
};

oe_result_t oe_get_memory_stats(oe_memory_stats * stats);
```

**Comment by achamayou** [comment]
@anakrish not very accurate, a rough amount is enough to answer the following questions:

> is memory usage near capacity?
> is it considerably under?
> is it steadily heading towards capacity?

I've discussed this with @mjp41, who thinks that it should be relatively easy to have that number for snmalloc, so long as the precision is 1Mb, which for the purposes of running SGX-based services in a cloud setting is accurate enough. He also suggested having a high watermark value, which corresponds to the amount the allocator has grabbed, but not necessarily handed off entirely.

For our purposes, we'd be equally happy with a stats object that we have to cast to the right type, knowing the allocator we use, or a tagged union. In general though, it seems like it should be possible to provide a useful approximation across most if not all allocators? Perhaps it's a case of going with the former at first, and eventually doing the latter.

**Comment by mjp41** [comment]
So for snmalloc, we use memory in chunks (for OE this is 1MiB), I can easily provide the following two counts

* Reserved - How many chunks of address space we have reserved for running the allocators. (High water mark)
* Active - How many chunks are currently active. 

The first is the amount required to provision the enclave, the other can be used to track the system health.  You can use this to correlate spikes that push up the high-water mark.

Both of these can be tracked accurately, and efficiently.  Both numbers will be well above the amount of active calls to `malloc`.  E.g. a single allocation 1byte allocation, will give 1MiB in use.  But at a reasonable service scale, should be an accurate approximation to the used memory.

**Comment by anakrish** [comment]
> In general though, it seems like it should be possible to provide a useful approximation across most if not all allocators
@achamayou Can you confirm if it is indeed the case? For example, I don't see equivalent APIs in 
tcmalloc, mimalloc.

Also, it is not clear how the proposed API maps to dlmalloc's mallinfo:
https://github.com/openenclave/openenclave/blob/444c574a18643104e1d67d3210b9e98c413bfa5d/3rdparty/dlmalloc/dlmalloc/malloc.h#L83-L94

How can an allocator declare its accuracy?

**Comment by achamayou** [comment]
@anakrish mimalloc has very extensive stats, see https://github.com/microsoft/mimalloc#using-the-library, https://github.com/microsoft/mimalloc/blob/master/doc/mimalloc-doc.h#L301 and https://github.com/microsoft/mimalloc/blob/master/src/stats.c

tcmalloc does too: https://github.com/google/tcmalloc/blob/master/tcmalloc/stats.h#L87

There's obviously no single unified API for this, since the stats are highly implementation dependent. But they all can give a useful sense of how much memory the allocator is using in total, and how much it has handed out, roughly. The answer does not need to be perfect, by the time it is returned to the user, it is outdated anyway!

It's still perfectly good for answering the questions any sensible service operator will ask themselves:

> is memory usage near capacity?
> is it considerably under?
> is it steadily heading towards capacity?

I don't know what you mean by how does an allocator declare its accuracy, or why it should do so for this use case. For the limited purpose of service monitoring and capacity planning, it makes no difference if the precision is 1Mb, 1Kb, or any other amount so long as it's a small value compared to the total amount of memory used by the service.

If an allocator truly cannot give a sense of these basic metrics, it can:

1. return an error via oe_get_memory_stats()
2. safely be ignored by the vast majority of service operators, who do not think that random enclave aborts caused by memory exhaustion is a sensible capacity planning mechanism.

I haven't looked at the dlmalloc stats in detail, since it just isn't a realistic choice for multi-threaded applications. I suspect `usmblks` and `uordblks` are good matches for total and used, but we should check.

It may be useful to return an opaque pointer to the stats for application developers who want to fine tune the memory behaviour of their service. That's a separate issue however. A service operator will likely neither care nor have a choice of which memory allocator gets used (indeed the enclave may be built by a 3rd party), but will still need to provision resources for it to run sustainably.

**Comment by achamayou** [comment]
> Yes. Based on my current thinking, since stats are quite implementation dependent, it does seem like something that the OE SDK ought not to try to funnel via single interface.
> 
> Currently, OE SDK does support plugging in a custom allocator. Therefore the user can interact with the rich stats API that an allocator provides, directly. Say you want to investigate some kind of suspected performance issue with allocations within the enclave, the user will likely be served best by using the rich stats API that the specific allocator provides.

This line of thinking seems to be applied inconsistently in the OE SDK. Attestation for example is wrapped into a single generic interface, despite there being only a single implementation of it today (and indeed for the foreseeable future).

Users cannot get the total heap size of the enclave from their allocator, only Open Enclave has that information. Can that at least be made available?

> In that case, realistically one would expect the enclave author (3rd party) so provide the enclave user with an API to query the stats.

As pointed out, at least one element of those stats cannot easily be provided through code. This is extremely common functionality that will need to be duplicated in virtually every application (definitely every service), when it could be trivially done centrally at the SDK level. This is not mutually exclusive with exposing an opaque handle to the details for users who want more.

There is clearly *some* level of acceptance that the SDK should be useful out of the box, since you do ship a libc, a libcxx (neither of which are pluggable), a un-namespaced mbedtls (users can only supply their own with complicated and undocumented hacks) etc. Why not aim for sensible defaults consistently, and try to make it possible for application developers to get something working on the only hardware you support without having to re-invent the wheel in every app?

**Comment by achamayou** [comment]
Done in #3484
