### ISSUE TITLE
SGX: Testing: child_process_destroy test occassionally fails in CI

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#3099]
https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/608/pipeline

**Comment by anakrish** [comment]
CC @yanxue-intel

**Comment by anakrish** [comment]
https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/615/pipeline/72

220/224 Test #220: tests/child_process_destroy ...........................................................................................................Child aborted***Exception:   0.41 sec

Test failed: ../tests/child_process/host/host.cpp(114): main child_status == 0

**Comment by yanxue-intel** [comment]
@jinghe-INTC Can you take a look?

**Comment by radhikaj** [comment]
Let's disable this test and re-enable later since this is blocking PRs as of now.

**Comment by jinghe-INTC** [comment]
Is there anyway to reproduce the problem manually? How to setup an environment of "ACC1804 gcc Debug LVI e2e" which seems to be the only platform with the problem?

**Comment by anakrish** [comment]
@mingweishih Can you help with setting up an "ACC 1804 gcc Debug LVI" environment?
Yes, it does seem that in both the links, it is similar kind of environment that has the problem.

@BRMcLaren Is there some way to grep the CI logs to indeed confirm that issue does indeed only happen on the above mentioned platform?
