### ISSUE TITLE
Testing:  Sporadic failures in E2E tests

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#3101]
Some instances:
https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/609/pipeline

```bash
TASK [linux/openenclave : Install all the Open Enclave prerequisites YUM packages for development] *** 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to synchronize cache for repo 'epel'", "rc": 1, "results": []}
```

https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/570/pipeline
```bash
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to download packages: Curl error (28): Timeout was reached for https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=x86_64&infra=$infra&content=$contentdir [Connection timed out after 30000 milliseconds]", "results": []}
```
https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/603/pipeline
```bash
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?"], "stdout": "", "stdout_lines": []
```

**Comment by CodeMonkeyLeet** [comment]
Still seeing the YUM repo timeout issue: 
https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/708/pipeline

```
TASK [linux/intel : Install the Intel libsgx package dependencies] *************

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to download packages: Curl error (28): Timeout was reached for https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=x86_64&infra=$infra&content=$contentdir [Connection timed out after 30001 milliseconds]", "results": []}
```

**Comment by anakrish** [comment]
@CodeMonkeyLeet @BRMcLaren @rs-- 

Do we need e2e tests for every PR or can it just be a nightly job? The reason I ask is that the number of  PRs that have an effect on the e2e scripts are minimal compared to the PRs that are unrelated to e2e scripts. 

I'd guess that e2e tests might add quite a bit of time to each CI run while not adding significantly more value than if they were run at a nightly basis.

**Comment by rs--** [comment]
@anakrish I'm okay with the idea of running e2e nightly builds.

If, and when does the nightly build catch an issue with the install scripts, what would be the proposed process of getting a fixed pushed through? Would we have to investigate who caused the issue, and assign a ticket to them?

**Comment by anakrish** [comment]
@rs-- 
Those are very good questions. I'd expect that if a genuine failure is detected, then an email to the team with the list of commits that went in since the last successful run, would be sufficient.
Note: these are my suggestions that I'd like to see a discussion on; not yet a confirmed plan of action.

There are some precedents
- LVI tests
- full C++ testsuite

And some anticipated testing
- stress tests

These might need the same course of action when failures are detected.

**Comment by CodeMonkeyLeet** [comment]
> Do we need e2e tests for every PR or can it just be a nightly job?

@anakrish What do you mean by "e2e tests" in this discussion? Do you mean simply not running all configurations in this case (e.g. RHEL)? Or not running setup? I think we have the freedom to scope the PR runs as it best suits our needs but I'm unclear on what the proposal is.

**Comment by anakrish** [comment]
The discussion in this PR https://github.com/openenclave/openenclave/pull/3053 describes what end-to-end means - essentially install prereqs on a fresh system, then build and test the OE SDK.

My proposal is that there is not much value in running/testing install prereqs for each PR. We are observing sporadic failures in prereqs installation in PRs that have nothing to do with the changes in a PR.

Since we are already running e2e tests on every PR, can someone point me to the original proposal/discussion for this decision?

**Comment by anakrish** [comment]
Saw another instance now: https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/730/pipeline

RHEL/YUM seems to be the problematic platform.

**Comment by CodeMonkeyLeet** [comment]
Another one at https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/732/pipeline

@rs-- The Curl timeout to the YUM repository seems to be the most commonly hit one and it doesn't appear to be addressed by the previous workaround. Specifically, there are two declarations of the task  `intel_sgx_package_dependencies` and one has the retry guard (in sgx-packages-install.yml) but not the other (in sgx-driver-requirements.yml) ... can you verify that the workaround covers the cases that are actually getting hit? I suspect it's the latter since there's no retries in the logs.

**Comment by anakrish** [comment]
Another one: 
https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/738/pipeline

**Comment by anakrish** [comment]
Same symptom as @CodeMonkeyLeet mentioned:
TASK [linux/intel : Install the Intel libsgx package dependencies] *************

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to download packages: Curl error (28): Timeout was reached for https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=x86_64&infra=$infra&content=$contentdir [Connection timed out after 30000 milliseconds]", "results": []}

**Comment by dthaler** [comment]
PR #2985 hit this too
https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/686/pipeline

**Comment by anakrish** [comment]
This occurred again:
https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/766/pipeline/49

**Comment by anakrish** [comment]
It happened again on the same PR: 
https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/767/pipeline/

**Comment by anakrish** [comment]
I am closing this. In the past 5 days, I have not seen this happen again.
