### ISSUE TITLE
SGX: Add support for SIGSEGV handling to OE

### ISSUE THREAD

**Issue by jhand2** [openenclave/openenclave#3118]
Currently for SGX, OE can handle SIGILL inside an enclave, but cannot handle SIGSEGV.

A preliminary implementation can be found here: https://github.com/openenclave/openenclave/commit/bb24836609e61877b412b63eb70e4ff7bd64eadd

This needs to be cleaned up to be merged into master

**Comment by radhikaj** [comment]
@jhand2  Please add more details to this issue.

**Comment by anakrish** [comment]
> Currently for SGX, OE can handle SIGILL inside an enclave, but cannot handle SIGSEGV.

Correction: OE SDK  handles SIGILL only for the CPUID instruction. It does not handle SIGILLs due to all the other invalid instructions that may happen within the enclave.

**Comment by jhand2** [comment]
I'm talking about what a registered vectored exception handler can handle, not what OE handles by default. A user can register vectored exception handler to handle arbitrary SIGILL exceptions today. But not arbitrary SIGSEGV.

I also don't know what the discussion around page faults was yesterday. Are page faults in SGX raised as SIGSEGV?

**Comment by CodeMonkeyLeet** [comment]
@jhand2 The question that was raised yesterday during triage was around why it was interesting for the enclave to try and handle SIGSEGV. Unhandled page faults lead to segfaults and that will happen in SGX since there is no native mechanism for demand paging. SGX with EDMM provides a mechanism to set a MISCSELECT bit such that page fault information is captured inside the enclave on AEX, so that it can be called back into to handle the fault. This functionality does not exist in basic SGX1, which is why Mark & I were curious what other reason there could be for an enclave to provide support for handling SIGSEGV.

**Comment by jhand2** [comment]
@CodeMonkeyLeet I see. The goal is to provide full support for POSIX signal handling APIs. You could argue whether handling SIGSEGV in an application is a good idea or not, but for a libos to offer that functionality it would be required. Am I missing something?

**Comment by MWShan** [comment]
I would be very cautious about the enclave doing any exception processing based solely on input from the host (untrusted).  It is difficult to say how the enclave may be manipulated by the host.  The host can interrupt the enclave and then call the enclave to try to get it to process a host provided fault.

**Comment by bodzhang** [comment]
Intel's Icelake CPU (10nm Gen 10 Core) supports delivering #PG and #GP exception info securely inside the enclave. The feature is enumerated in CPUID(EAX=12H, ECX=0).EBX.bit0. If the CPU supports this feature (CPUID(EAX=12H, ECX=0).EBX.bit0=1), with SW opt-in (SECS.MISCSELECT.bit0=1), the CPU delivers #PG and #GP exception info in SSA. 

The current OE SDK implementation does not support SW opt-in to enable this feature. The signing tool sets SIGSTRUCT.MISCSELECT=0, and SIGSTRUCT.MISCMASK=0xffffffff, which means the enclave load must set SECS.MISCSELECT=0. The enclave loader does not enumerate CPU' support on this feature either.

On SGX CPUs supporting #PG and #GP exception info in SSA, page fault exception info can be analyzed inside the enclave in a trusted manner.

**Comment by anakrish** [comment]
@bodzhang Would the faulting address also be available within the enclave?
Currently, exception context is accessed via `sgx_ssa_gpr_t` structure: https://github.com/openenclave/openenclave/blob/300a5b649d648ae539c7b8053bd35f24b327cd25/include/openenclave/bits/sgx/sgxtypes.h#L334-L360

Where would the faulting address be stored?

**Comment by bodzhang** [comment]
@anakrish , `sgx_exit_info` contains the #PF error code or #GP error code. For #PF, `sgx-exit_info` also contains the memory address that the faulting instruction is attempting to access (CR2 value when #PG happens).

@radhikaj , is there a different issue tracking the request to support SIGSEGV based on SGX2.0 #PF/#GP handling?
