### ISSUE TITLE
Decide the approach to deal with the code differences of third-party dependencies

### ISSUE THREAD

**Issue by mingweishih** [openenclave/openenclave#3120]
This issue is the follow-up issue of #2984.  In addition to the consensus of using submodules for third-party dependencies, the goal of the issue is extending the discussion on the approach of dealing with code differences (non-upstreamed) in those dependencies. More specifically, the potential directions have been scoped down to the following two options.

- Option 1
  - Create a fork of upstreamed repo (e.g., `openenclave/mbedtls`)
  - Apply the code differences
  - Have the submodule point to the patched fork.
- Option 2
  - Maintain the patches in the OE repo
  - Have the submodule point to the upstreamed repo
  - Apply the patches during the config/build time.

Other related discussions
- #1902
- The [thread](https://github.com/openenclave/openenclave/pull/1820/files/f387980d1b8b55619bf7574f897148d78154bde8#diff-8903239df476d7401cf9e76af0252622) in #1820

**Comment by CodeMonkeyLeet** [comment]
Per [SIG-Arch meeting](https://hackmd.io/KOeBDVlyQpOC-OqqHYvs0A?view#11-Aug-2020):
* Consensus is that changes that can be upstreamed should use Option 1.
   * This fork would be maintained under the OE SDK project.
   * If we maintain a fork for holding changes while upstreaming, we should be clear the fork is not intended for consumption as a standalone (i.e. we are not forking the original project).
* Any changes that we are not willing or able to upstream should reside in the OE SDK repo.
   * This is not a prescription to use patches (option 2), and could involve alternative source file inclusions, different configuration settings and introducing abstraction layers.
* A basic heuristic is:
   1. Can OE SDK consume a clone of the project with no changes to the 3rd party sources? If so, take a submodule dependency directly.
   2. If a change needs to be made, is the change something that is valuable to upstream into the 3rd party project (e.g. bug fixes, feature extension) and are we willing to do the work to upstream it? If so, fork the repo under OE SDK project and start the upstreaming process.
