### ISSUE TITLE
Build without libsgx-enclave-common-dev on non-SGX machines for simulation only

### ISSUE THREAD

**Issue by letmaik** [openenclave/openenclave#3127]
I'm trying to follow the scenario of point 3 in https://github.com/openenclave/openenclave/tree/master/scripts/ansible#open-enclave-deployment-options-via-ansible. This doesn't install any SGX libraries. However, trying to build OE (with `-DHAS_QUOTE_PROVIDER=OFF`) fails with "Intel SGX EnclaveCommonAPI library not found, aborting!". `libsgx-enclave-common-dev` shouldn't be needed for simulation mode.

My concrete use case is to get [LGTM](https://lgtm.com) code analysis working for an OE project. The service requires to build the code but doesn't allow to install apt dependencies from non-official channels. This is why I can't install the Intel SGX libraries (not that it would make sense anyway).

Earlier discussion: https://github.com/openenclave/openenclave/issues/2252.

**Comment by jhand2** [comment]
Simulation mode is a runtime configuration, not build-time. As such, libsgx-enclave-common-dev is absolutely needed for simulation mode.

I do see value in adding a configuration that allows you to build OE for simulation mode only, but it's a non-trivial amount of work.

**Comment by letmaik** [comment]
I see, could you roughly outline what would have to change in OE?

**Comment by anakrish** [comment]
@letmaik I'd like to understand your multiple usecases a bit better.

PR #2882 "Dynamically load Intel SGX Enclave Common shared library" was an attempt to  use dynamic loading of sgx-enclave-common so that there is no hard-dependency on intel libraries for simulation mode. Some users have wanted to be able to run OE in AMD machines, and pre sgx intel machines.
In that PR, you commented: 
https://github.com/openenclave/openenclave/pull/2882#issuecomment-620688353
> Is there a way to opt-out of this? dlopen`ing dependencies makes life harder if you want to analyze dependencies automatically (e.g. for auditing) and also if you want to bundle dependencies automatically into a package.

It seems like you'd want a hard-dependency between oe libraries and intel libraries, while also be able to install oe without libsgx-enclave-common-dev.
I think your requirements might be a bit more nuanced; can you shed some light?

**Comment by anakrish** [comment]
@jhand2 
> s such, libsgx-enclave-common-dev is absolutely needed for simulation mode.

I'm not sure I understand the rationale for this. Simulation mode ought to work on non-intel machines. So why would libsgx-enclave-common-dev be absolutely needed for simulation mode?

**Comment by jhand2** [comment]
> I'm not sure I understand the rationale for this. Simulation mode ought to work on non-intel machines. So why would libsgx-enclave-common-dev be absolutely needed for simulation mode?

As a build-time dependency (I know that's up for debate in #2882 but the current build does require it).

I would advocate for a build-time flag to allow for building OE for simulation mode only and would have no build-time dependency on any TEE libraries. I see that is pretty non-controversial.

**Comment by anakrish** [comment]
I see what you mean now. Currently the build system requires lib-sgx-enclave-common as a hard dependency; but it need not be.

**Comment by anakrish** [comment]
@letmaik My previous response was for Jordan. 
Can you clarify your requirements? It seems you want ldd to show a hard-dependency on intel libraries, yet want to install and run OE SDK in a machine without intel libraries.

**Comment by letmaik** [comment]
@anakrish I had a look at your PR again. I forgot it also removes the build-time dependency to the Intel libraries which is what I'm asking for here. Being able to ldd dependencies is a nice-to-have for me but not a blocker, and I understand the advantages of the PR (having a single application build  without requiring Intel libraries on non-SGX machines). The main reason for being able to ldd is that it makes it easier to create a self-contained application bundle that includes all its dependencies (by patching rpaths), but yes, it's an edge case that isn't important here. I'm fine with getting the PR merged after figuring out the Debian packaging situation (see last comment).

**Comment by anakrish** [comment]
Thanks for the clarification @letmaik. 
I have brought up the general issue of simulation-mode & sgx dependencies for discussion in SigArch: 
https://zoom.us/j/95309871627?pwd=K1RmbmZtUUowNFhRbWFZRVN4R2VmUT09

https://hackmd.io/@aeva/oesdk-sig-arch
