### ISSUE TITLE
Use of OE_BUILD_ENCLAVE in headers

### ISSUE THREAD

**Issue by wintersteiger** [openenclave/openenclave#3130]
This is the only occurrence of the macro `OE_BUILD_ENCLAVE` in the public (installed) header files: https://github.com/openenclave/openenclave/blob/4cc53259c32f2c1a1bd321d85b37049c9fed7efd/include/openenclave/attestation/attester.h#L15

This means that all client code also needs to define this macro if they want to use an attester (plugin). Are there plans to make this the default behavior and to use this macro in other places, or is this an unintended "leak" of internals?

**Comment by radhikaj** [comment]
OE_BUILD_ENCLAVE  is internal and should not be in a public header file. Just remove it.

**Comment by radhikaj** [comment]
Use  _OE_ENCLAVE_H

**Comment by shnwc** [comment]
_OE_ENCLAVE_H does not work, since this header file does not depend on <openenclave/enclave.h> to be included. Will change to print error message when _OE_HOST_H is defined.
