### ISSUE TITLE
Application will Crash (OE_PLATFORM_ERROR) w/ feature/sgx-lkl-support branch

### ISSUE THREAD

**Issue by praenubilus** [openenclave/openenclave#3133]
OESDK: we build OESDK from feature/sgx-lkl-support branch with flag `-DWITH_EEID=on -DCOMPILE_SYSTEM_EDL=ON`, to be more specific, below is the cmake string we used:
```bash
mkdir build && cd build && cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="/opt/openenclave-sgxlkl-support" -DWITH_EEID=on -DCOMPILE_SYSTEM_EDL=ON ..
```
VM Tested:
Standard DC8_v2 (8 vcpus, 32 GiB memory), East US, Ubuntu 18.04 Gen2
Standard DC4s_v2 (4 vcpus, 16 GiB memory), East US, Ubuntu 18.04 Gen2
Symptom:
After build and install the OESDK, when running application with this version of OESDK, the application will crash with following platform error:
![Screenshot from 2020-06-15 16-35-00](https://user-images.githubusercontent.com/547418/84718173-de3a3580-af2c-11ea-9b92-ab19b2e50f76.png)
We tested this on an existing VM created at the end of April. The VM comes with an sgx driver 1.22, even update it to latest driver(1.33), the problem is still there.
We also tested on a new created VM, having the same problem.

This problem has been tested and reproduced for the last three SHA1 commits:
_055b1f0651fbac7bb9ab030b9c3984469597d65d_
_7d9c8e060327a0ff087497b1e84fe57f92f1c978_
_25b31864dcb8ed80d9c1c857bdb1cf15c3393027_

**Comment by anakrish** [comment]
CC @jhand2 @CodeMonkeyLeet

**Comment by jhand2** [comment]
Can you share an application I can run (a test or sample in the repo) where this repros? I am unable to repro this issue.

**Comment by jhand2** [comment]
@praenubilus I rebased with master and am unable to repro this. Could you get the latest from the branch and try again?

```
git checkout feature/sgx-lkl-support
git fetch origin
git reset --hard origin/feature/sgx-lkl-support
```

**Comment by praenubilus** [comment]
@jhand2 , with the latest rebased one, the platform error goes away. Another minor issue, I still received the error prompt: 
```bash
Azure Quote Provider: libdcap_quoteprov.so [ERROR]: Could not retreive environment variable for 'AZDCAP_DEBUG_LOG_LEVEL'
```
This also happens in master branch. Should I be concerned about it?

**Comment by praenubilus** [comment]
@jhand2 , with the latest rebased one, the platform error goes away. Another issue I have, I still received the error prompt: 
```bash
Azure Quote Provider: libdcap_quoteprov.so [ERROR]: Could not retreive environment variable for 'AZDCAP_DEBUG_LOG_LEVEL'
```
This also happens in master branch. Should I be concerned about it?

**Comment by jhand2** [comment]
@praenubilus Can you open a different issue for that? That is probably something we need to bubble up to the Azure DCAP client developers.

So can this issue be closed?

**Comment by praenubilus** [comment]
Yes, the problem solved. I will close the issue and create another issue.
