### ISSUE TITLE
SGX certificate extension parsing on Icelake platform fails

### ISSUE THREAD

**Issue by yentsanglee** [openenclave/openenclave#3134]
Remote attestation fails on Icelake platform from parsing SGX certificate extension. Error OE_INVALID_SGX_CERTIFICATE_EXTENSIONS in function ParseSGXExtensions() in 
openenclave\common\sgx\sgxcertextensions.c.

Current code in ParseSGXExtensions() only parses up to extension OPT_CACHED_KEYS_OID (1.2.840.113741.1.13.1.7) while more optional extension OIDs (up to 1.2.840.113741.1.13.1.7.3) are defined in [SGX Spec](https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/Intel_SGX_PCK_Certificate_CRL_Spec-1.4.pdf).

**Comment by anakrish** [comment]
@yentsanglee Do those optional extensions only apply to Icelake or do they apply to pre-Icelake systems as well?

**Comment by yentsanglee** [comment]
> @yentsanglee Do those optional extensions only apply to Icelake or do they apply to pre-Icelake systems as well?

According to the spec, the optional extensions apply to pre-icelake systems but Intel PCCS just never specified them.

**Comment by yentsanglee** [comment]
Wrong pull request. This issue has not been resolved.
