### ISSUE TITLE
OESDK: Enclaves cannot access host memory by default

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#3141]
This is a follow up to a discussion in SIG-TEsting where the differences in the behavior of OE SDK and Intel SDK were discussed.

Capturing differences here to continue discussion:
In both SDKs, the host cannot access enclave memory
In Intel SDK, the enclave SDK can access host memory
In OE SDK, edger8r generated code assumes that the enclave cannot access host memory since the generated code must work on OPTEE too where the enclave indeed cannot access host memory.

Unmodified intel generated code:
sgx_status_t sb_xor(sgx_enclave_id_t eid, unsigned long long* retval, unsigned long long* array, size_t count)
{
                sgx_status_t status;
                ms_sb_xor_t ms;
                ms.ms_count = count;
                ms.ms_array = array;
                status = sgx_ecall(eid, 5, &ocall_table_Enclave, &ms);
                if (status == SGX_SUCCESS && retval) *retval = ms.ms_retval;
                return status;
}
 
OE generated code (only listed relevant code):
oe_result_t sb_xor(
    oe_enclave_t* enclave,
    unsigned long long* _retval,
    unsigned long long* array,
    size_t count)
{
 
…
 
    /* Allocate marshalling buffer. */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);
    _buffer = (uint8_t*)oe_malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL)
    {
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }
    
    …
    
    /* Copy args structure (now filled) to input buffer. */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));
 
    /* Call enclave function. */
    if ((_result = oe_call_enclave_function(
             enclave,
             helloworld_fcn_id_sb_xor,
             _input_buffer,
             _input_buffer_size,
             _output_buffer,
             _output_buffer_size,
             &_output_bytes_written)) != OE_OK)
        goto done;
 
    …
    
    /* No pointers to restore for deep copy. */
    OE_READ_IN_OUT_PARAM(array, (size_t)(((size_t)_args.count * sizeof(unsigned long long)))); // perform memcpy
 
    …
 
    return _result;
}

**Comment by anakrish** [comment]
Thanks for writing this up Radhika.
Consider rephrasing this
> In OE SDK, the enclave cannot access host memory

to 

> In OE SDK,  edger8r generated code assumes that the enclave cannot access host memory since the generated code must work on OPTEE too where the enclave indeed cannot access host memory.

**Comment by ShundaZhang** [comment]
sgx_status_t sb_xor(sgx_enclave_id_t eid, unsigned long long* retval, unsigned long long* array, size_t count)
{
sgx_status_t status;
ms_sb_xor_t ms;
ms.ms_count = count;
ms.ms_array = array;
status = sgx_ecall(eid, 5, &ocall_table_Enclave, &ms);
if (status == SGX_SUCCESS && retval) *retval = ms.ms_retval;
return status;
}
The unmodified intel generated code here is from the un-trusted part of the generated code. intel generated code has another part in trusted part and will build with enclave code together. In that part of code, we create buffer, similar as OE code listed by radhikaj.

We also create a internal buffer in edger8r code and copy the outside buffer into internal buffer and then continue to manipulate the data in internal buffer. Similar as what OE is doing.

And actually SGX hardware doesn't provide the protection against enclave accessing host memory.
So I am afraid even the edger8r generated code should not assume that the enclave cannot access host memory for SGX.

**Comment by ShundaZhang** [comment]
We have discussed a similar topic in https://github.com/openenclave/oeedger8r-cpp/issues/28. And got the conclusion that it is not a security issue, because OE and Intel SDK are different in marshaling data, and the copy we are discussing locates in un-trusted code while copy of SGX Edger8r locates in trusted code.

**Comment by anakrish** [comment]
Closing this since this not a security issue.
However we need to continue to scrutinize edger8r and generated code since it operates at critical security boundary.
