### ISSUE TITLE
SGX: Ghost OCalls/System Calls Opt In: Separate libraries for system edls

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#3154]
In order to use a system library that makes ocalls, has ecalls, in Intel SDK the user must
- import the system edl 
- link a system library into the enclave and the host.

E.g: to use switchless calling, the user must import switchless.edl:
https://github.com/intel/linux-sgx/blob/0e71c227ada2174c6dd7557e424815a3f953564a/SampleCode/Switchless/Enclave/Enclave.edl#L36
```c
from "sgx_tswitchless.edl" import *;
```

and link lsgx_tswitchless.a into the enclave
https://github.com/intel/linux-sgx/blob/0e71c227ada2174c6dd7557e424815a3f953564a/SampleCode/Switchless/Makefile#L154
```bash
	-Wl,--whole-archive  -lsgx_tswitchless -l$(Trts_Library_Name) -Wl,--no-whole-archive \
```

and link sgx_uswitchless.a into the host:
https://github.com/intel/linux-sgx/blob/0e71c227ada2174c6dd7557e424815a3f953564a/SampleCode/Switchless/Makefile#L104
```c
                  -Wl,--whole-archive  -lsgx_uswitchless -Wl,--no-whole-archive \
```

The approved design for [Explicit Enclave Opt-in to System OCalls](https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/system_ocall_opt_in.md) does not address whether OE SDK should also require the user to explicitly explicitly link against libraries that accompany the system edls.

It is not clear if this was discussed and resolved or was never discussed.

One one hand not having the user link libraries reduces the burden on the user. The linker will anyways only pull in what is needed. (Note: We use -ffunction-section compiler option and gc-sections linker option).

On the other hand, requiring the user to link in a library explicitly makes it clear that the functionality in a library is being imported. Additionally it allows using --whole-archive to for include initializers in a library that the linker may otherwise not import.

**Comment by anakrish** [comment]
CC: @mingweishih @jhand2 @CodeMonkeyLeet @radhikaj 

It would be good to discuss this issue, in case it was not already addressed, since it will have an impact on the user experience, possibly across TEEs.

**Comment by anakrish** [comment]
We discussed this in Sig-Arch and the consensus was that OE SDK will not refactor code out into separate libraries for switchless, printing, file system etc other than the separation than the libraries that currently exist.

**Comment by CodeMonkeyLeet** [comment]
Closing this issue as resolved during the SIG-Arch meeting.
