### ISSUE TITLE
Unable to separate oehost target while building host-verify package

### ISSUE THREAD

**Issue by ryanhsu19** [openenclave/openenclave#3160]
With only namespace `openenclave-targets` used to build both OE and host-verify packages, it is impossible to separate `openenclave::oehost` from all the necessary targets 

 - `openenclave::oehostverify`
 - `openenclave::host_verify`
 - `openenclave::oe_includes`

used by host-verify package; therefore,

 1. We are unable to build the host-verify sample without removing anything related to `openenclave::oehost` in the `openenclave-targets*.cmake` files installed by the host-verify package.

 2. We are unable to integrate this into CI/CD, which is related to #2519.

As for the structure of the minimal host-verify package, please refer to my original comment in #3123:

 - https://github.com/openenclave/openenclave/pull/3123#issuecomment-646300983_

**Comment by radhikaj** [comment]
@ryanhsu19 Please add impact of this issue to the description.

**Comment by ryanhsu19** [comment]
@radhikaj Just added the impact of this issue. Hopefully this will clarify the issue.
