### ISSUE TITLE
FLC/Non-FLC in one build?

### ISSUE THREAD

**Issue by letmaik** [openenclave/openenclave#3178]
OE has `HAS_QUOTE_PROVIDER=ON|OFF` as build-time option. Since the Intel SGX libraries are now all dlopen'd I was wondering whether it makes sense to allow building a single OE variant that works across all SGX variants (currently FLC/non-FLC) with appropriate runtime introspection.

**Comment by radhikaj** [comment]
This would be resolved if HAS_QUOTE_PROVIDE is deleted as an option.

**Comment by anakrish** [comment]
I looked at this. We are quite close to being able to build OE on a non FLC machine and use it in an FLC machine (ie FLC/Non-FLC in one build).
In addition to removing HAS_QUOTE_PROVIDER, we need to 
- remove dependency on Intel SGX headers in host/sgx/quote.c
- Remove LING_SGX_DCAP_QL
- Figure out whether the platform has dcap and selectively enable tests.

This looks quite possible to do v0.11

**Comment by anakrish** [comment]
This is fixed by the PRs currently checked in as part of #3272.
