### ISSUE TITLE
Add sample that gets quote and endorsements within an enclave using the C API

### ISSUE THREAD

**Issue by letmaik** [openenclave/openenclave#3196]
This is a follow-up on https://github.com/openenclave/openenclave/issues/2946. 

The `hostverify` sample uses the `oecert` tool to generate the quote and endorsements, however I need to do the same using the C API inside the enclave.

**Comment by yentsanglee** [comment]
Local/remote attestation samples call oe_get_report() to get local/remote report. We are working on finalizing oe_get_evidence() which returns evidence/report/quote and endorsements.

@letmaik letmaik, what is the the purpose or urgency of this issue?

**Comment by letmaik** [comment]
@yentsanglee I need to build clients that don't have a dependency on Azure DCAP Client. For that, I need working endorsement support.

**Comment by yentsanglee** [comment]
@letmaik you can call oe_get_evidence() with a pointer to `endorsements_buffer`.
