### ISSUE TITLE
Ensure that oeedger8r generated names are conformant to Developer Guidelines

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#3210]
oeedger8r generates names using older naming convention. e.g: `__oe_ecalls_table`.
This issue is to keep track of the task of changing the emitted names to be conformant to [Developer Guidelines](https://github.com/openenclave/openenclave/blob/master/docs/Community/DevelopmentGuide.md)

**Comment by anakrish** [comment]
Most of the SDK naming conformance is being done in #3208

**Comment by mingweishih** [comment]
Will be addressed by https://github.com/openenclave/oeedger8r-cpp/pull/66
