### ISSUE TITLE
Attestation endorsements should not be wrapped in oe_attestation_header_t

### ISSUE THREAD

**Issue by yentsanglee** [openenclave/openenclave#3241]
Attestation endorsements format is proprietary to each evidence format but at public level API oe_verify_evidence() it should be a clear buffer.

Attention - openenclave/common/attest_plugin.c:oe_verify_evidence()

**Comment by wintersteiger** [comment]
I use such wrapped endorsements in the EEID plugins, which most likely would have to be updated (which I'm happy to do as long as I know about it). I didn't think the additional header wrapping was a problem, is that mainly a size/performance consideration?

**Comment by yentsanglee** [comment]
Turned out it was there since plugin model started. Closing the issue.
