### ISSUE TITLE
Fragment test

### ISSUE THREAD

**Issue by achamayou** [openenclave/openenclave#3262]
In relation to #3256 I've been looking at the memory fragment test, because it makes use of dlmallinfo(), which is dlmalloc-specific.

It defines __get_heap_size as dlmallinfo().keepcost: https://github.com/openenclave/openenclave/blob/master/tests/memory/enc/fragment.c#L34

That's:

>   keepcost:  the maximum number of bytes that could ideally be released
>                back to system via malloc_trim. ("ideally" means that
>                it ignores page restrictions etc.)

>   malloc_trim(size_t pad);
> 
>   If possible, gives memory back to the system (via negative arguments
>   to sbrk) if there is unused memory at the `high' end of the malloc
>   pool or in unused MMAP segments. You can call this after freeing
>   large blocks of memory to potentially reduce the system-level memory
>   requirements of a program. However, it cannot guarantee to reduce
>   memory. Under some allocation patterns, some large free blocks of
>   memory will be locked between two used chunks, so they cannot be
>   given back to the system.

So that's memory held by the allocator that isn't actively in use, and could conceivably be released. It's neither the whole available space for the heap, nor the actual heap size held by the allocator or handed out.

The test does use it as if it was though, eg. https://github.com/openenclave/openenclave/blob/master/tests/memory/enc/fragment.c#L107

So I think there are two questions:

1. Should the test be modified to use fordblks/uordblks instead?
2. Should there be at least an internal API exposing the total/in-use amounts, which this test can target, and which effectively becomes part of the pluggable allocator API?

**Comment by CodeMonkeyLeet** [comment]
I'll also note that tests/bigmalloc has a similar issue where it cannot run with snmalloc because it assumes an `sbrk()` based allocator to infer remaining heap size. It may be worth thinking about a standardized `oe_allocator_mallinfo` contract with pluggable allocators to be able to standardize these tests.

**Comment by achamayou** [comment]
Yes, good point. There has been some prior discussion about this, although in the context of exposing this to users instead https://github.com/openenclave/openenclave/issues/3097. May I propose an `oe_allocator_mallinfo`, to be exposed internally to tests only? Is the best way to do that a separate design document, or a PR against the existing pluggable allocator design document?
