### ISSUE TITLE
Regression of custom claims in evidence based attestation

### ISSUE THREAD

**Issue by jxyang** [openenclave/openenclave#3264]
I was able to create a list of custom claims, each with its own name, data, and size, and pass them to `oe_get_evidence`, and the generated evidence would include these custom claims. On the verifier side, `oe_verifiy_evidence` would extract the claims, each with its own name / data / size.  The feature allowed me to implement attested TLS with "public key" as a custom claim.

With PR #3198, all the flexibility is gone. I can only have one custom claims, and the name has to be "custom_claims". And there is no way I can pass the length of the custom claim in the evidence. So the verifier has to obtain the length of the custom claim somewhere to validate it.

Can someone explain to me why do we take the great effort to make custom claims much less flexible and potentially have much worse user experience?

**Comment by jxyang** [comment]
@yentsanglee

**Comment by anakrish** [comment]
CC: @CodeMonkeyLeet @dthaler since this is a question about API design.

**Comment by jxyang** [comment]
Note this blocks PR #3161, the first practical user scenario of custom claims.

**Comment by shnwc** [comment]
@jxyang With the change in PR #3198, the API takes in the custom claims as a flat buffer. There is no restriction in how the application software (the caller) structures its set of custom claims held in the buffer.

The team agreed that this allows the API to give the most flexibility. As more and more custom claims use cases are supported that require some structures, helper functions can be added to support processing these structures.

The replaced design where custom claims are presented as a list of name / value string pairs is restrictive, not flexible enough meet the requirements described in PR #2959.

**Comment by dthaler** [comment]
To add to what Shanwei said, oe_claim_t includes the size, so the full flat buffer has a known length.   The app can use whatever format it wants within that buffer (e.g., any standard format or custom format).

**Comment by jxyang** [comment]
It seems to me by forcing plugin writers to implement their own serialization routines, we allow the buffer to be either big endian or little endian. Is there any other flexibility we gained? If that's case, why not add another parameter indicating the endianness?

**Comment by dthaler** [comment]
> It seems to me by forcing plugin writers to implement their own serialization routines, we allow the buffer to be either big endian or little endian. Is there any other flexibility we gained? If that's case, why not add another parameter indicating the endianness?

My opinion: Endianness only matters for multi-byte integers, and the things you serialize might not include any such things.   Also, any particular format already has an inherent endianness associated with it or it won't interoperate, so I don't think an additional parameter is needed.

**Comment by shnwc** [comment]
> It seems to me by forcing plugin writers to implement their own serialization routines, we allow the buffer to be either big endian or little endian. Is there any other flexibility we gained? If that's case, why not add another parameter indicating the endianness?
@jxyang `oe_get_evidence()` takes in custom claims held in a flat byte array, and plugins don't do any serialization. It's the application developers' responsibility to put any format in the array. As discussed in [comment](https://github.com/openenclave/openenclave/issues/3264#issuecomment-659557138), if there are enough shared format requirement, helper functions can be added to the API.

**Comment by jxyang** [comment]
@shnwc If it's expected the application has to serialize/deserialize custom claims, that's certainly not reflected in https://github.com/openenclave/openenclave/blob/05d109a5706fe4c439f64cd68ffee6e2430b9542/tests/attestation_plugin/plugin/tests.c#L712

Here the test is cutting corner by passing the `custom_claims_size` directly from the attester to the verifier. And do a flat comparison without deserialization.

My point is: if you have written the tests the way you expect from plugin users, you'd have realized #3198 was missing something.

**Comment by shnwc** [comment]
@jxyang 

> openenclave/tests/attestation_plugin/plugin/tests.c

My understanding is that this is unit test that exercises the attestation plugin APIs, and not intended to be sample code showing how application code uses the APIs. In this unit test code, we know `oe_get_evidence()` and `oe_verify_evidence()` run in the same program. So I don't see anything missing here. Let me know if you still see something missing.

On the other hand, we are aware that there is more work to address endianness (issue #3047) and to update sample applications to use the plugin API (issue #2975).

**Comment by jxyang** [comment]
@shnwc There is little value in generating evidence and then consume it in the same enclave. Attestation is inherently across enclaves. If you have written the test with two enclaves, you'd realized the serialization functions you removed are actually needed.

**Comment by yentsanglee** [comment]
Helper functions to serialize/de-serialize will be added per issue #3303.
