### ISSUE TITLE
safecrt test build failure on Ubuntu 18.04

### ISSUE THREAD

**Issue by hyjiang** [openenclave/openenclave#3275]
I am following https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1FLCGettingStarted.md to build openenclave on ubuntu 18.04 + SGX FLC enabled NUC.

But I always came across below build failure.
Rev: db8a9dc14bafe48703895ede7c99c29384128cf3  master

Scanning dependencies of target safecrt_host
[  4%] Building CXX object tests/safecrt/host/CMakeFiles/safecrt_host.dir/__/common/test.cpp.o
[  4%] Building CXX object tests/safecrt/host/CMakeFiles/safecrt_host.dir/host.cpp.o
[  4%] Building C object tests/safecrt/host/CMakeFiles/safecrt_host.dir/safecrt_u.c.o
/home/sgx/github/openenclave/build/tests/safecrt/host/safecrt_u.c:27:14: error: unknown type name 'oe_ecall_info_t'; did you mean
      'oe_ocall_func_t'?
static const oe_ecall_info_t __safecrt_ecall_info_table[] =
             ^~~~~~~~~~~~~~~
             oe_ocall_func_t
/home/sgx/github/openenclave/include/openenclave/host.h:81:16: note: 'oe_ocall_func_t' declared here
typedef void (*oe_ocall_func_t)(
               ^
/home/sgx/github/openenclave/build/tests/safecrt/host/safecrt_u.c:29:7: error: incompatible pointer types initializing 'const oe_ocall_func_t'
      (aka 'void (*const)(const unsigned char *, unsigned long, unsigned char *, unsigned long, unsigned long *)') with an expression of type
      'char [18]' [-Werror,-Wincompatible-pointer-types]
    { "enc_test_memcpy_s" },
      ^~~~~~~~~~~~~~~~~~~
/home/sgx/github/openenclave/build/tests/safecrt/host/safecrt_u.c:29:5: error: braces around scalar initializer [-Werror,-Wbraced-scalar-init]
    { "enc_test_memcpy_s" },
    ^~~~~~~~~~~~~~~~~~~~~~~
/home/sgx/github/openenclave/build/tests/safecrt/host/safecrt_u.c:30:7: error: incompatible pointer types initializing 'const oe_ocall_func_t'
      (aka 'void (*const)(const unsigned char *, unsigned long, unsigned char *, unsigned long, unsigned long *)') with an expression of type
      'char [19]' [-Werror,-Wincompatible-pointer-types]
    { "enc_test_memmove_s" },
      ^~~~~~~~~~~~~~~~~~~~
/home/sgx/github/openenclave/build/tests/safecrt/host/safecrt_u.c:30:5: error: braces around scalar initializer [-Werror,-Wbraced-scalar-init]
    { "enc_test_memmove_s" },
    ^~~~~~~~~~~~~~~~~~~~~~~~
/home/sgx/github/openenclave/build/tests/safecrt/host/safecrt_u.c:31:7: error: incompatible pointer types initializing 'const oe_ocall_func_t'
      (aka 'void (*const)(const unsigned char *, unsigned long, unsigned char *, unsigned long, unsigned long *)') with an expression of type
      'char [19]' [-Werror,-Wincompatible-pointer-types]
    { "enc_test_strncpy_s" },
.......

Not sure whether it's an env issue.

**Comment by mingweishih** [comment]
Have you update the git submodule (e.g., `git submodule update --init --recursive`)?

**Comment by hyjiang** [comment]
Thanks @mingweishih , this command resolve my build issue.
I am using `git submodule update --init --remote` instead of `--recursive`.

I will close this issue.
