### ISSUE TITLE
Request for the CA to be configurable to support running in different envs & HW at different maturity levels

### ISSUE THREAD

**Issue by yanxue-intel** [openenclave/openenclave#3284]
CA's name and root key's value in the production platform are different from those in the pre-production plaform, but OE only hardcode those with production value.

Is OE attestation planned to support the pre-production platform?

**Comment by anakrish** [comment]
CC: @yentsanglee @soccerGB

**Comment by radhikaj** [comment]
By pre-production platform, do you mean IceLake? Please let us know.

**Comment by yanxue-intel** [comment]
IceLake Server

**Comment by AevaOnline** [comment]
It seems to me that attestation should not use hard-coded CAs or keys, period. Is this not the case?

Could OE contain an extensible list, prepopulated with good defaults, that can be changed at build time (and thereby ingest data from environment variables in the build process)?

**Comment by soccerGB** [comment]
Non-production certs are not secure, thus it;s not trustworthy. It should be treated as trusted only in the development, which could be done via customized code provided by whoever needs it.

**Comment by ShundaZhang** [comment]
Our purpose is to improve the Remote Attestation verification code, to support verifying the quote by a different CA. The developers may use some pre-production CPUs in their development environment, the major difference from production environment in RA verification is the CA.

**Comment by ShundaZhang** [comment]
> It seems to me that attestation should not use hard-coded CAs or keys, period. Is this not the case?
> 
> Could OE contain an extensible list, prepopulated with good defaults, that can be changed at build time (and thereby ingest data from environment variables in the build process)?

Our purpose is to improve the Remote Attestation verification code, to support verifying the quote by a different CA. The developers may use some pre-production CPUs in their development environment, the major difference from production environment in RA verification is the CA.

**Comment by yanxue-intel** [comment]
fix in [https://github.com/openenclave/openenclave/pull/3336](url)

**Comment by dthaler** [comment]
@yanxue-intel This process looks insecure, since how do they know the correct key is on the page and an attacker hasn't snuck in a change to the markdown file, or the HTML rendering of it?    Is this only for debugging and should never be used in actual deployment?   Assuming so, is there a large warning somewhere?
