### ISSUE TITLE
LVI mitigation binary distribution

### ISSUE THREAD

**Issue by eddyashton** [openenclave/openenclave#3286]
Anybody who wants to benefit from LVI mitigations will need to both link with the LVI mitigated configurations of OE libraries, and build their own enclave code with LVI mitigations. To do the latter, they should be using the same toolchain and options. Currently they need to obtain this toolchain by running the `install_lvi_mitigation_bindir` script locally.

Why is this installed by a script? Is there a reason this binary directory is not simply included in the release package, to build complete enclaves with the `-lvi-cfg.a`s?

**Comment by mingweishih** [comment]
The main reason is really that the LVI mitigation is not supported by upstream compiler toolchain (both gcc and clang) yet.  As a workaround, the installed binaries include two parts:

- Wrapper of the compilers installed in this system -- if we shipped the wrappers, we have to hard-code the path to the compiler.
- Intel's assembler and linker -- again, we're still waiting the support LVI mitigation becomes upstream. Before that happens, we need to pull those binaries from the intel site.

**Comment by radhikaj** [comment]
CLosing issue. Please reopen if there are further questions.
