### ISSUE TITLE
Add attestation custom claims serializing/de-serializing helper functions

### ISSUE THREAD

**Issue by yentsanglee** [openenclave/openenclave#3303]
Per request and comments in issue #3264, helper functions to serialize and de-serialize array of oe_claim_t are needed.

The buffer from serialized oe_claim_t array can then be used to convey custom claims between attester and verifier. I.e.:

Attester:
- claims of name/value pairs --(serialize)--> plain buffer --(oe_get_evidence)--> evidence with custom claims

Verifier
- evidence with custom claims --(oe_verify_evidence)--> plain buffer OE_CLAIM_CUSTOM_CLAIMS --(de-serialize)--> claims of name/value pairs

**Comment by shnwc** [comment]
LGTM.
