### ISSUE TITLE
PSW version used by LVI

### ISSUE THREAD

**Issue by eddyashton** [openenclave/openenclave#3307]
The `install_lvi_mitigation_bindir` script [installs version 2.9](https://github.com/openenclave/openenclave/blob/4bf2dca44b92a962c932f9277d6e488acdd13592/scripts/lvi-mitigation/install_lvi_mitigation_bindir#L58) of the Intel LVI mitigation tools. As far as I can tell, these tool versions are the same as the Intel PSW/SDK versions (they are downloaded from the same [versioned sources](https://download.01.org/intel-sgx/sgx-linux/)). The 0.10 release of Open Enclave claims it is tested against PSW v2.10, but it appears the LVI-mitigated binaries in the release will still have been built with PSW v2.9 LVI mitigation tools.

Is this the case?
Do you know what the implications are? Are there likely to be any version incompatibilities if we use v2.10 for everything else, but v2.9 of the LVI mitigation tools?
Can we ensure this script remains up-to-date in future?

I notice that the `as.ld.objdump` file has increased in size from [3.8MiB](https://download.01.org/intel-sgx/sgx-linux/2.9/) to [35.6Mib](https://download.01.org/intel-sgx/sgx-linux/2.10/), suggesting the mitigation logic is significantly more complex in v2.10, so OE is potentially missing important mitigations? Of course this is just conjecture since I don't know what's in these customised `as`/`ld` binaries - perhaps someone from Intel can shed more light on this?

**Comment by anakrish** [comment]
CC: @mingweishih

**Comment by mingweishih** [comment]
Thanks for bringing this up. I'll double check with Intel if we need to switch to use the latest toolchain.

Just from my opinion, I would not expect there will be much difference in these two versions. The size difference is more likely due to the tool are built with different compilation flags (e.g.,  `-g`).

**Comment by eddyashton** [comment]
Another question on the LVI binaries:

I was looking to do some basic validation that LVI mitigations had been applied, by comparing the `.a` and `-lvi-cfg.a` binaries, expecting that the latter is similar but with a large number of additional lfences. However, it appears the `-lvi-cfg.a` versions are consistently smaller than their unmitigated counterparts? Can you explain why that is?

```$ ls -l --block-size K /opt/openenclave/lib/openenclave/enclave/
total 50348K
-rw-r--r-- 1 root root  1897K Jul 21 08:57 libmbedcrypto-lvi-cfg.a
-rw-r--r-- 1 root root  2383K Jul 21 08:58 libmbedcrypto.a
-rw-r--r-- 1 root root   576K Jul 21 08:57 libmbedtls-lvi-cfg.a
-rw-r--r-- 1 root root   761K Jul 21 08:59 libmbedtls.a
-rw-r--r-- 1 root root   325K Jul 21 08:57 libmbedx509-lvi-cfg.a
-rw-r--r-- 1 root root   410K Jul 21 08:58 libmbedx509.a
-rw-r--r-- 1 root root   956K Jul 21 08:56 liboecore-lvi-cfg.a
-rw-r--r-- 1 root root  1111K Jul 21 08:57 liboecore.a
-rw-r--r-- 1 root root   437K Jul 21 08:57 liboecryptombed-lvi-cfg.a
-rw-r--r-- 1 root root   550K Jul 21 08:59 liboecryptombed.a
-rw-r--r-- 1 root root  1033K Jul 21 08:57 liboeenclave-lvi-cfg.a
-rw-r--r-- 1 root root  1332K Jul 21 08:59 liboeenclave.a
-rw-r--r-- 1 root root    76K Jul 21 09:09 liboehostepoll-lvi-cfg.a
-rw-r--r-- 1 root root    98K Jul 21 09:09 liboehostepoll.a
-rw-r--r-- 1 root root   141K Jul 21 09:09 liboehostfs-lvi-cfg.a
-rw-r--r-- 1 root root   178K Jul 21 09:09 liboehostfs.a
-rw-r--r-- 1 root root    25K Jul 21 08:59 liboehostresolver-lvi-cfg.a
-rw-r--r-- 1 root root    30K Jul 21 08:59 liboehostresolver.a
-rw-r--r-- 1 root root   121K Jul 21 08:59 liboehostsock-lvi-cfg.a
-rw-r--r-- 1 root root   155K Jul 21 08:59 liboehostsock.a
-rw-r--r-- 1 root root  4950K Jul 21 08:57 liboelibc-lvi-cfg.a
-rw-r--r-- 1 root root  5369K Jul 21 08:58 liboelibc.a
-rw-r--r-- 1 root root  9833K Jul 21 09:00 liboelibcxx-lvi-cfg.a
-rw-r--r-- 1 root root 13853K Jul 21 09:01 liboelibcxx.a
-rw-r--r-- 1 root root  1204K Jul 21 08:59 liboesnmalloc-lvi-cfg.a
-rw-r--r-- 1 root root  1204K Jul 21 08:59 liboesnmalloc.a
-rw-r--r-- 1 root root   573K Jul 21 08:56 liboesyscall-lvi-cfg.a
-rw-r--r-- 1 root root   715K Jul 21 08:57 liboesyscall.a
```

The only exception is `oesnmalloc`, which is identical in both versions - has this somehow not been built with LVI mitigations enabled?

Related: Tried to run `objdump -D <file> | grep lfence | wc -l` as a crude count to compare mitigated/non-mitigated libraries (this works for my downstream LVI-mitigated binaries). However this doesn't work on the OE `-lvi-cfg.a` binaries, since it looks like the binaries are in some unexpected format:

```
objdump: output/lib/openenclave/enclave/liboeenclave-lvi-cfg.a(attest_plugin.c.o): unable to initialize decompress status for section .debug_str
objdump: attest_plugin.c.o: File format not recognized
...
```

Any idea why the customised `ld` and `as` aren't producing a parseable format?

**Comment by mingweishih** [comment]
> Another question on the LVI binaries:
> 
> I was looking to do some basic validation that LVI mitigations had been applied, by comparing the `.a` and `-lvi-cfg.a` binaries, expecting that the latter is similar but with a large number of additional lfences. However, it appears the `-lvi-cfg.a` versions are consistently smaller than their unmitigated counterparts? Can you explain why that is?
> 
> ```
> total 50348K
> -rw-r--r-- 1 root root  1897K Jul 21 08:57 libmbedcrypto-lvi-cfg.a
> -rw-r--r-- 1 root root  2383K Jul 21 08:58 libmbedcrypto.a
> -rw-r--r-- 1 root root   576K Jul 21 08:57 libmbedtls-lvi-cfg.a
> -rw-r--r-- 1 root root   761K Jul 21 08:59 libmbedtls.a
> -rw-r--r-- 1 root root   325K Jul 21 08:57 libmbedx509-lvi-cfg.a
> -rw-r--r-- 1 root root   410K Jul 21 08:58 libmbedx509.a
> -rw-r--r-- 1 root root   956K Jul 21 08:56 liboecore-lvi-cfg.a
> -rw-r--r-- 1 root root  1111K Jul 21 08:57 liboecore.a
> -rw-r--r-- 1 root root   437K Jul 21 08:57 liboecryptombed-lvi-cfg.a
> -rw-r--r-- 1 root root   550K Jul 21 08:59 liboecryptombed.a
> -rw-r--r-- 1 root root  1033K Jul 21 08:57 liboeenclave-lvi-cfg.a
> -rw-r--r-- 1 root root  1332K Jul 21 08:59 liboeenclave.a
> -rw-r--r-- 1 root root    76K Jul 21 09:09 liboehostepoll-lvi-cfg.a
> -rw-r--r-- 1 root root    98K Jul 21 09:09 liboehostepoll.a
> -rw-r--r-- 1 root root   141K Jul 21 09:09 liboehostfs-lvi-cfg.a
> -rw-r--r-- 1 root root   178K Jul 21 09:09 liboehostfs.a
> -rw-r--r-- 1 root root    25K Jul 21 08:59 liboehostresolver-lvi-cfg.a
> -rw-r--r-- 1 root root    30K Jul 21 08:59 liboehostresolver.a
> -rw-r--r-- 1 root root   121K Jul 21 08:59 liboehostsock-lvi-cfg.a
> -rw-r--r-- 1 root root   155K Jul 21 08:59 liboehostsock.a
> -rw-r--r-- 1 root root  4950K Jul 21 08:57 liboelibc-lvi-cfg.a
> -rw-r--r-- 1 root root  5369K Jul 21 08:58 liboelibc.a
> -rw-r--r-- 1 root root  9833K Jul 21 09:00 liboelibcxx-lvi-cfg.a
> -rw-r--r-- 1 root root 13853K Jul 21 09:01 liboelibcxx.a
> -rw-r--r-- 1 root root  1204K Jul 21 08:59 liboesnmalloc-lvi-cfg.a
> -rw-r--r-- 1 root root  1204K Jul 21 08:59 liboesnmalloc.a
> -rw-r--r-- 1 root root   573K Jul 21 08:56 liboesyscall-lvi-cfg.a
> -rw-r--r-- 1 root root   715K Jul 21 08:57 liboesyscall.a
> ```
> 
> The only exception is `oesnmalloc`, which is identical in both versions - has this somehow not been built with LVI mitigations enabled?
> 
> EDIT: Originally had a question about `why doesn't objdump work` here, but I've just found that the Intel archive with `ld` and `as` also contains an `objdump` which is able to parse the `-lvi-cfg.a` variants, so I can compare:
> 
> ```
> $ /tmp/external/toolset/objdump -d /opt/openenclave/lib/openenclave/enclave/liboeenclave.a | grep -c lfence
> 0
> $ /tmp/external/toolset/objdump -d /opt/openenclave/lib/openenclave/enclave/liboeenclave-lvi-cfg.a | grep -c lfence
> 115
> ```
> 
> So it _does_ look mitigated, just smaller because some strings have been stripped?

The size difference is due to we are using different versions of assembler & linker to built regular and lvi-mitigated libraries;
i.e., the lvi toolchain from intel is based on the latest version (2.32) of binutils while the regular OE build is using the version (2.30 on ubuntu 18.04) from the ubuntu distribution.

After some investigation, you are right, these is some build problem with snmalloc that lvi mitigation is not correctly applied. I'll file an issue for that. Thanks!

**Comment by mingweishih** [comment]
Update: I found the size difference is mainly due that Intel includes the toolchain for each of the following Linux distributions:
`centos8.1  fedora31  fedora32  nix  rhel8.0  rhel8.1  rhel8.2  sles15.2  ubuntu18.04  ubuntu20.04`
