### ISSUE TITLE
EnclaveCommonAPI and DCAP nuget packages need to be removed from install_prereqs

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#3311]
All SGX dlls are available in system 32 and are dynamically loaded.
The corresponding nuget packages are no longer needed to build the SDK.
The installation of these nuget packages can be removed from install_prereqs scripts.

**Comment by BRMcLaren** [comment]
@anakrish I am not sure this is true.

How do we build in a container without these packages?

**Comment by BRMcLaren** [comment]
I was also under the impression that 2016 did not come with the sgx dlls preloaded.

**Comment by anakrish** [comment]
@BRMcLaren For building the SDK, we don't need the sgx header files and .sgx lib files. For running the SDK, we need the sgx dlls.
My understanding is that the SGX nuget packages only contain the header files and lib files.
In Win 2016, do you know where the SGX DLLs come from?

**Comment by BRMcLaren** [comment]
Probably https://github.com/BRMcLaren/openenclave/blob/UpdateIntelLinks/scripts/install-windows-prereqs.ps1#L403.

OK, so that gets us past building.
But if we do this change, how do we run in a container?

**Comment by anakrish** [comment]
Removing  the nuget  shouldn't have any effect on running since the DLLs don't come from nuget.

**Comment by BRMcLaren** [comment]
Regardless, I don't think this should be assigned to me or @rs-- . It isn't CI related and doesn't improve the system. A better approach would be flushing out the package manager suggestion here https://github.com/openenclave/openenclave/issues/3000 as opposed to continuing to add effort into this script.

It's not something we can commit to and will hurt our efforts to move towards containerization, so unassigning.

**Comment by anakrish** [comment]
Sure sounds good. When we get around to package manager solution, we just need to remember to not put in the effort to install these nuget packages.

**Comment by anakrish** [comment]
@radhikaj I'm closing this since we don't want to invest more in the install prereqs scripts.

**Comment by BRMcLaren** [comment]
@anakrish Might I suggest adding this to your package manager requirements?

I suspect for containers that need to run the sdk we need this while just the build steps and onhost 2019 we do not.
