### ISSUE TITLE
hostverify library: Cannot use oe_verify_attestation_certificate_with_evidence

### ISSUE THREAD

**Issue by letmaik** [openenclave/openenclave#3312]
This is with current `master`:
```
../openenclave/lib/openenclave/host/liboehostverify.a(verifier.c.o): In function `_verify_report':
.../common/sgx/verifier.c:742: undefined reference to `oe_verify_report_internal'
```
Looks like some sources are missing in the archive.

**Comment by yentsanglee** [comment]
Since there are 2 OIDs to identify the extension, oe_verify_attestation_certificate_with_evidence() should be deprecated.

**Comment by radhikaj** [comment]
@letmaik  Is this blocking your app/scenario? What are the repro steps.  @yentsanglee , can you please follow up.

**Comment by letmaik** [comment]
No, for now I can just link to `oehost`, but it should be resolved anyway.
