### ISSUE TITLE
Cannot parse MAA CA certificate with quote

### ISSUE THREAD

**Issue by letmaik** [openenclave/openenclave#3313]
I'm trying to use `oe_verify_attestation_certificate` / `oe_verify_attestation_certificate_with_evidence` to verify the CA certificates from MAA.

Here is an example DER-encoded MAA cert: [cert_0.der.zip](https://github.com/openenclave/openenclave/files/4972207/cert_0.der.zip). This can also be obtained from the [public endpoint](https://shareduks.uks.attest.azure.net/.well-known/openid-configuration).
For convenience, here is the extracted quote from the `1.2.840.113556.10.1.1` extension: [cert_0.quote.zip](https://github.com/openenclave/openenclave/files/4972282/cert_0.quote.zip).

My observations so far are:
- `oe_verify_attestation_certificate*` does not support raw SGX quotes, but the MAA cert uses those currently.
- The MAA cert stores the quote under `1.2.840.113556.10.1.1`.
  - `oe_verify_attestation_certificate` expects `1.2.840.113556.10.1.1`.
  - `oe_verify_attestation_certificate_with_evidence` expects `1.2.840.113556.10.1.2`.
- Patching OE to use `1.2.840.113556.10.1.1` with `oe_verify_attestation_certificate_with_evidence` and forcing the raw SGX quote plugin fails with "Parse error after parsing SGX signature" at `../common/sgx/quote.c:_parse_quote:113`.

Some questions:
1. Does it make sense in principle to try to use `oe_verify_attestation_certificate_with_evidence` for this purpose?
2. Why are there two OIDs? Which one should be used by MAA?
3. Why is the quote parsing failing? Is it not a standard raw SGX quote after all?

**Comment by anakrish** [comment]
CC: @yentsanglee @shnwc

**Comment by gkostal** [comment]
It's a known issue that currently MAA and the OE SDK don't treat OID 1.2.840.113556.10.1.1 equivalently.  Discussions are underway to achieve consistency here.  At the moment, MAA generates an Intel SGX quote while the OE SDK expects an OE SGX quote.

**Comment by yentsanglee** [comment]
Like @gkostal mentioned, the OID was used for different purpose by MAA and discussions are underway. From OE SDK's point of view, I am more concerned about having 2 functions to verify certificates.

Will add to agenda in SIG-attestation meeting.

**Comment by radhikaj** [comment]
@yentsanglee , can we sort this out with @gkostal. 
We need to track this in the Changelog as a breaking change and communicate it.

**Comment by yentsanglee** [comment]
Certificate generated from MAA has different format. MAA will change their OID to something other than `1.2.840.113556.10.1.1`.

In OE, `1.2.840.113556.10.1.1` is for report generated by oe_get_report().
`1.2.840.113556.10.1.2` is for evidence generated by oe_get_evidence() with format id embedded.

`oe_verify_attestation_certificate_with_evidence` should be deprecated because `oe_verify_attestation_certificate` can be used to verify both extensions (Issue #3338).

**Comment by letmaik** [comment]
@yentsanglee Does that mean OE will not support validating MAA certificates?

**Comment by letmaik** [comment]
@anakrish @yentsanglee @radhikaj Could you re-open this issue? I don't think this is resolved yet. We need to be able to verify MAA certs without re-implementing all of OE's existing validation code.

**Comment by ad-l** [comment]
> Certificate generated from MAA has different format. MAA will change their OID to something other than `1.2.840.113556.10.1.1`.
> 
> In OE, `1.2.840.113556.10.1.1` is for report generated by oe_get_report().
> `1.2.840.113556.10.1.2` is for evidence generated by oe_get_evidence() with format id embedded.
> 
> `oe_verify_attestation_certificate_with_evidence` should be deprecated because `oe_verify_attestation_certificate` can be used to verify both extensions (Issue #3338).

@gkostal that resolution doesn't make much sense - if MAA defines a separate OID to embed non-OE quotes, how are users expected to verify the MAA certificate? What about the evidence/endorsements/collaterals? Intel doesn't define a standard serialization for those. We would prefer that MAA certificates that embed quotes can be verified with `oe_verify_attestation_certificate`

**Comment by yentsanglee** [comment]
There was an agreement for MAA to use **1.3.6.1.4.1.311.105.3** going forward but OE SDK has to be extended to recognize the MAA OID.

**Comment by gkostal** [comment]
> We would prefer that MAA certificates that embed quotes can be verified with `oe_verify_attestation_certificate`

@ad-l , MAA was recently changed to use `oe_generate_attestation_certificate` to generate its signing certificate.  This change is now live in PROD, so `oe_verify_attestation_certificate` should work for you.

**Comment by letmaik** [comment]
@gkostal Thanks! I verified it and it works. I'm assuming the following is obsolete:
> There was an agreement for MAA to use 1.3.6.1.4.1.311.105.3 going forward but OE SDK has to be extended to recognize the MAA OID.

**Comment by yentsanglee** [comment]
Closing the issue as MAA has changed to use OE SDK to generate certificate.
