### ISSUE TITLE
Default SGX SIGSTRUCT ATTRIBUTEMASK allows the loader to enable MPX inside the enclave

### ISSUE THREAD

**Issue by bodzhang** [openenclave/openenclave#3316]
The [default SGX SIGSTRUCT ATTRIBUTEMASK](https://github.com/openenclave/openenclave/blob/05d109a5706fe4c439f64cd68ffee6e2430b9542/include/openenclave/bits/sgx/sgxtypes.h#L139) used by the signing tool allows the untrusted (outside of SGX enclave TCB) enclave loader to enable MPX (Intel [SDM](https://software.intel.com/content/www/us/en/develop/articles/intel-sdm.html#combined) chapter 17) inside the enclave.

To securely use MPX inside the enclave, the enclave developer must carefully design how the MPX Bound Directory and Bound Table are allocated and accessed. OE SDK does not provide any framework or library to accomplish that. If a developer unintentionally include MPX instructions in the enclave without the proper design (for example, by linking with a library compiled to use MPX features), and allows the untrusted loader to enable MPX inside the enclave, a malicious OS/loader might be able to set Bound Directory and/or Bound Table to overlap with enclave memory and trick the MPX instruction executed inside the Enclave to unintentionally overwrite Enclave code/data. Further analysis is required to understand whether this type of attack is realistic.

It's safer to set the SIGSTRUCT.ATTRIBUTEMASK default to disable MPX inside the enclave and require the enclave developers to explicitly override the default if they ant to support MPX inside the enclave.

**Comment by anakrish** [comment]
CC: @mingweishih @CodeMonkeyLeet

**Comment by CodeMonkeyLeet** [comment]
To clarify, my understanding is that the `SIGSTRUCT.ATTRIBUTEMASK` doesn't block a feature, it simply causes the appropriate ATTRIBUTE bits to be measured into the enclave identity. Indirectly, this will prevent an unexpected setting of the attribute by the loader that is not set in the original enclave signature.

The enclave entry functions effectively break the MPX feature today, and it's highly unlikely you're going to stumble across an MPX-enabled static library redistributable to use in an enclave. Given that GCC has deprecated support for MPX, I'm less concerned about MPX specifically, and think of this more as a defense-in-depth suggestion: It's simple enough to change the default mask to align with the Intel SGX SDK, where it looks like not just the MPX bit is masked, but all XFRM bits other than the AVX ones.

**Comment by radhikaj** [comment]
@MWShan will post further details on how this is done in Intel SGX SDK. Thanks!
