### ISSUE TITLE
Discussion of Future CI Improvments/Decoupling

### ISSUE THREAD

**Issue by BRMcLaren** [openenclave/openenclave#3323]
In SIG testing we discussed the future of the organization's CI and decoupling it from the sdk. This issue is to serve as a continuation of the discussion between companies and to allow others to contribute with feature requests, etc to establish a baseline. Below is a list of things we are currently looking into understanding if there is anything else, please bring it up and we will look into it. I will break off the topics as they become too large to be contained in a single issue.

 1. Automation
    * Prow
        * Pros/Cons
    	* Workload balancer for CI instances
    	* MVP
 	* Automated labelling
        * Owners for code repos/trees
        * Labelling for trusted code to build
        * Might need more than 1 "test all command"
    * Other options from prow?
        * Manual, many pull request validations
	* another merge bot for distributed ci
    * Backend
        * Post Submit server rebuilds
        * How to manage containers and versioning for organization
	* Infrastructure as code
		* Onboarding other repos
		* Self Service
		* Gate Keeper of the above
    * Anything else we want to accomplish via automation that is not testing
    * How to enable Developers of the SDK outside of CI, what can we do, what would people like to see
	* Containerized Dev environments
		* How can we get people to use it?
		* How can we make this public?
    * Testing
	* Testing Matrix, for or against?
	* Containerization vs host, do we need/want both?
		* Do we still need SGX1 Machines?
		* What about things that are not easily supported Rhel 8 containers etc
	* Status Contexts
		* If a job fails and logs are not available, does this gate the PR?
	* How to align the developer and CI contribution experience
	* CI "Limbo"
    * Where to document all this?
	* Onboarding of other repos
	* [Altered PR process](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#code-review-using-owners-files)
    * Chatops
	* labels
	* closing/opening PR's
	* alerting of code owners
	* retrying tests etc.
 2. Decoupling build infrastracture
 	* Test-infra
        * CI Images versus Dev Images
		* CI images support of non standard dependency installation?
        * Dependency changes, where do they belong how do we handle
 3. Metrics
	* Monitoring of CCC, Azure, Intel instances
		* How do we monitor Intel Instances?
		* Prometheus is being looked at for Azure and CCC, no decision to be made yet.
	* Grafana
	* Code Coverage
 4. [Security] (https://github.com/openenclave/openenclave/issues/3325)

 5. Roll out strategy
	* Phase 1, dogfooding
	* Phase 2, oeedgr8r
	* Phase 3, onboard another external ci (CCC split)
        * Phase 4, openenclave repo
        * Phase 5, Intel Inboarding

For context, I have taken all the recommended actions from https://github.com/openenclave/openenclave/issues/2798 and https://github.com/openenclave/openenclave/issues/2805 along with many others and built out a prototype (to be donated) https://github.com/BRMcLaren/test-infra which we are starting to work on production-izing.

If there are questions around something above, please comment below and we can expand on the pieces people are interested in.

**Comment by MWShan** [comment]
@sfblackl - please review

**Comment by radhikaj** [comment]
Also see #2798

**Comment by BRMcLaren** [comment]
Prow is still in development at the [test-infra](https://github.com/openenclave/test-infra) project. Let's move this conversation there.

**Comment by BRMcLaren** [comment]
https://github.com/openenclave/test-infra/issues/266
