### ISSUE TITLE
host_verify CLI should make use of the new attestation API

### ISSUE THREAD

**Issue by jumaffre** [openenclave/openenclave#3333]
The `host_verify` CLI shipped with OE (sources: https://github.com/openenclave/openenclave/tree/master/samples/host_verify) currently uses the `oe_verify_remote_report` API, which I believe is incompatible with the new attestation API (i.e. `oe_get_evidence`, etc.). In other words, a quote generated with `oe_get_evidence` cannot be verified successfully with `oe_verify_remote_report`. 

Am I right in thinking that `host_verify` should be using the new attestation API?

As CCF is aiming to use the new attestation API to be able to cache the quote endorsements, the described `host_verify` limitation is blocking us to take on board these changes (we rely on `host_verify` for clients to verify CCF nodes' quotes) 

This might be implemented as part of #3276 and might also be linked to #3312 

Let me know what you guys think. I am happy to contribute some changes to the CLI myself.

**Comment by mingweishih** [comment]
cc @yentsanglee

**Comment by yentsanglee** [comment]
We are gradually convert attestation samples from oe_report to oe_evidence API set.

**Comment by yentsanglee** [comment]
Tasks
1. oe_verify_evidence() must be include in host_verify.h
2. host_verify must call oe_verify_evidence(OE_FORMAT_UUID_SGX_ECDSA_P256_REPORT, ...) to verify evidence
