### ISSUE TITLE
Switch shellcheck url to github releases page

### ISSUE THREAD

**Issue by jianlia** [openenclave/openenclave#3345]
Switchcheck URL need to be updated per  https://github.com/koalaman/shellcheck/issues/1871

The following error is hit during autmation

https://github.com/openenclave/openenclave/blob/d3909bf8f75ec787ce75f0efc28449f069efa3f6/scripts/install-windows-prereqs.ps1#L19

Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----         8/5/2020  12:08 AM                packages                                                              
Downloading: https://shellcheck.storage.googleapis.com/shellcheck-v0.7.0.zip
[2020-08-05T00:08:07.1950948+00:00] Start-ExecuteWithRetry attempt 0
[2020-08-05T00:08:07.3824007+00:00] Start-ExecuteWithRetry RetryMessage: Failed to download https://shellcheck.storage.googleapis.com/shellcheck-v0.7.0.zip. Retrying
...
[2020-08-05T00:08:37.8214688+00:00] Start-ExecuteWithRetry attempt 10
[2020-08-05T00:08:37.8527284+00:00] Start-ExecuteWithRetry exception thrown

**Comment by anakrish** [comment]
@BRMcLaren What is the right url to use for Windows?

**Comment by BRMcLaren** [comment]
@anakrish https://github.com/BRMcLaren/openenclave/blob/master/scripts/ansible/oe-windows-acc-setup.yml#L23 would be the one stashed.

Let me take care of this, testing now.
