### ISSUE TITLE
source code package tag 0.10.0 issue: cmake error in git submodule init oeedger8r-cpp

### ISSUE THREAD

**Issue by johnvenn** [openenclave/openenclave#3346]
this is a test with source code package in 0.10.0 :https://github.com/openenclave/openenclave/releases/tag/v0.10.0

download openenclave-0.10.0.tar.gz, extract it, and running the build process, there is an error in "mkdir build && cmake .. "

CMake Error at cmake/utilities.cmake:9 (message):
  Submodule oeedger8r-cpp is empty.  You can initialize the submodule now
  with 'git submodule update --recursive --init', or during 'git clone' by
  passing '--recursive'.
 

then I use the command to init oeedger8r-cpp submodule, there was an error:
fatal: not a git repository (or any of the parent directories): .git

is this a temporary problem?

**Comment by anakrish** [comment]
@radhikaj Due to use of various submodules, I don't think it is possible to build SDK from published sources. I remember that we'd discussed this in the past, though I don't remember whether we decided to bundle the submodule sources as well.

**Comment by johnvenn** [comment]
> @radhikaj Due to use of various submodules, I don't think it is possible to build SDK from published sources. I remember that we'd discussed this in the past, though I don't remember whether we decided to bundle the submodule sources as well.

so, is that just for backup? 

because we would checkout the tag to build the released source.

**Comment by anakrish** [comment]
@mingweishih found out the following issue https://github.community/t/create-release-that-contains-submodule/1329

Giithub creates the Source Code.zip artifact when a release is created and it does not package the code for submodules.
Once it is fixed upstream, this issue will be solved.

**Comment by johnvenn** [comment]
> @mingweishih found out the following issue https://github.community/t/create-release-that-contains-submodule/1329
> 
> Giithub creates the Source Code.zip artifact when a release is created and it does not package the code for submodules.
> Once it is fixed upstream, this issue will be solved.

ok, thanks for the reply. I thought people should have reported this issue previously. it seems it's not project specific. I'll close this issue.
