### ISSUE TITLE
Avoid compact form of xstate

### ISSUE THREAD

**Issue by jxyang** [openenclave/openenclave#3350]
OE assumes the compact form of xstate is always supported. This is true for machines with sgx capability, but not true for all intel CPUs. Since running the simulation mode could happen on non-sgx machines, we should avoid using the compact form to allow maximum compatibility.

https://github.com/openenclave/openenclave/blob/eb1f65bd181212d8c22afaec7050319b55ffe5de/enclave/core/sgx/asmdefs.c#L40

**Comment by jxyang** [comment]
This issue currently blocks sgx-lkl feature branch from syncing with the latest OE master.

**Comment by anakrish** [comment]
From the same discussion, we cannot assume that xsave instruction is available. If it is not available, we'd need to use fxrstor.

**Comment by CodeMonkeyLeet** [comment]
@anakrish Can you file a separate issue for the check for OS XSAVE enablement? It's a more involved fix that where I think we should also evaluate if the sections of the code using FXRSTOR/FXSAVE should not also be consolidated to use the dynamic detection for XSAVE/XRSTOR support.
