### ISSUE TITLE
Remove hard dependency on XRSTOR in OE SDK

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#3360]
OE SDK code currently assumes that support for XSAVE/XRSTOR is always available when using SGX enclaves. This can potentially cause runtime fails in other scenarios such as simulation mode, as seen with the related issue #3350 around assuming support for compacted representation of XSAVE data (XCOMP_BV[63]). 

The enclave side code should check that support for XSAVE/XRSTOR is supported at runtime, and fallback to the use of FXSAVE/FXRSTOR if not. As part of this work, we should also evaluation consolidating the codepaths which only use FXSAVE/FXRSTOR today to use the dynamic detection.

**Comment by anakrish** [comment]
@bodzhang Can an enclave securely detect at runtime if `xrstor` is available?

**Comment by bodzhang** [comment]
@anakrish, enclave code can check whether XSAVE is enabled through `REPORT.Attributes.XFRM`.
