### ISSUE TITLE
Enquiry: mktime results to this log : 2020-08-11T04:38:00.000000Z [(E)ERROR] tid(0x4624) | tgse.elf.signed:path=/etc/localtime oe_errno=2 [C:\Users\Administrator\OE\Packaging\SDK\syscall\mount.c oe_mount_resolve:119]

### ISSUE THREAD

**Issue by JeromeCustodio** [openenclave/openenclave#3372]
May i know what this error means? Is there any recommendation on how to get the current time?
Is there any recommendation on how to convert struct tm to time_t?

I am using Open Enclave MS Visual Studio 2019 Extension version: 0.7.29

https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/visualstudio_dev.md

Thank you

**Comment by radhikaj** [comment]
mktime is not supported.
The list of APIs are listed here:https://github.com/openenclave/openenclave/blob/master/docs/LibcSupport.md

**Comment by radhikaj** [comment]
If mktime is locale specific, is there another POSIX API that can be used?

**Comment by radhikaj** [comment]
@JeromeCustodio  Can you please reopen if you dont have an alternative and this is blocking you?
