### ISSUE TITLE
OE checks whether a size_t variable is negative

### ISSUE THREAD

**Issue by jxyang** [openenclave/openenclave#3377]
On this [line](https://github.com/openenclave/openenclave/blob/80309da445e768d05031b14ef0e33997662a7769/enclave/crypto/cert.c#L1180), we are checking if a size_t variable `bytes_written` is <= 0.  So even if the function `mbedtls_x509write_crt_der` returns a negative number to indicate error, we will never detect it.

We are lucky that `mbedtls_x509write_crt_der` never failed until today when I tried to generate an EEID based certificate and that triggered `MBEDTLS_ERR_ASN1_BUF_TOO_SMALL`.

**Comment by anakrish** [comment]
An interesting questions is why the compiler did not complain that `<=  0` does not make sense for a `size_t` variable.

**Comment by jxyang** [comment]
It probably will actual complain if the expression is `< 0`. There is a `1/INT_MAX` change `==0` could catch an error.

**Comment by radhikaj** [comment]
size_t is the wrong type since mbedtls_x509write_crt_der can return a negative value on failure. 
Follow up on Anand's question.
