### ISSUE TITLE
`OE_MAX_CERT_SIZE` is too small for EEID report

### ISSUE THREAD

**Issue by jxyang** [openenclave/openenclave#3378]
`OE_MAX_CERT_SIZE` is 8192, which should be enough for most cases. But with EEID plugin, we are creating a huge data blob that exceeds the limit. As my debugger shows, the data blob is 18671 bytes for an sample sgx-lkl application. We need to increase the size limit.

**Comment by anakrish** [comment]
@jxyang Do you need to encode the entire data blob in the cert ? Can you instead just encode the hash of the data blob?

**Comment by jxyang** [comment]
@anakrish If we do that, we need to accompany an EEID data blob with the cerificate. I think most internet protocols consider certificate to be a self-contained credential.

**Comment by jxyang** [comment]
If we are fine with the `config_id` approach in https://github.com/bodzhang/openenclave/blob/EEIDDesignChange/docs/DesignDocs/ExtendedEnclaveInitializationData_V2.md, and give up the idea of having a fine-grained verification on the EEID data blob,  we probably can get away with just the hash value in the certificate. I don't have preference on which way to go.

**Comment by anakrish** [comment]
@jxyang I like the idea of certs being self contained.

**Comment by anakrish** [comment]
CC: @yentsanglee @wintersteiger @CodeMonkeyLeet @bodzhang

**Comment by CodeMonkeyLeet** [comment]
My expectation is that the EEIDv2 design will supersede the existing implementation, so the certificate size shouldn't be necessary if this can wait until those changes take effect. 

If we do want to bump the maximum size of the cert, I would suggest that instead of just bumping up the constant, the attested TLS certificate generation codepath returns the size of buffer needed and the caller has a fallback to dynamically allocate a larger buffer to call the function again.

**Comment by yentsanglee** [comment]
I agree with @CodeMonkeyLeet that the max cert size is specified by the caller, probably with a suggested value. If we set the maximum size to a big value just for exceptional cases, we are wasting memory.

**Comment by wintersteiger** [comment]
I agree, this should definitely be variable-size. The new EEID design will indeed allow us to record just the config_id, but the design isn't finalized yet, so it might take a bit more time for this to become available.

**Comment by jxyang** [comment]
@bodzhang

**Comment by yentsanglee** [comment]
Deep in the call stack if mbedtls certificate generation can return size needed if allocation is not enough, that will be ideal.

**Comment by yentsanglee** [comment]
@jxyang, can this wait until EEID is available?

**Comment by jxyang** [comment]
We need a fix to unblock the PR to sgx-lkl, which is needed by customers.

Increasing the limit would be easiest and quickest path to resolve the issue. This constant is used only in `generate_x509_self_signed_certificate` to allocate a local buffer, and the buffer is reclaimed in the same function. There is no much harm to increase the size limit IMO.

**Comment by CodeMonkeyLeet** [comment]
@yentsanglee Took a look at the mbedtls code for `mbedtls_x509write_crt_der` and confirmed that it will not return the required size in the event of `MBEDTLS_ERR_ASN1_BUF_TOO_SMALL` It only writes until it runs out of buffer space and does not precalculate the required buffer size.

**Comment by yentsanglee** [comment]
> We need a fix to unblock the PR to sgx-lkl, which is needed by customers.
> 
> Increasing the limit would be easiest and quickest path to resolve the issue. This constant is used only in `generate_x509_self_signed_certificate` to allocate a local buffer, and the buffer is reclaimed in the same function. There is no much harm to increase the size limit IMO.

The local buffer `cert_buf` is given to `output_cert` on success and is not reclaimed.

Can we calculate the max size in generate_x509_self_signed_certificate() based on the input parameters (oid_size, strlen(subject_name), private_key_buf_size, public_key_buf_size, and remote_report_buf_size)?
