### ISSUE TITLE
Simplify SGX attestation UUIDs

### ISSUE THREAD

**Issue by yentsanglee** [openenclave/openenclave#3379]
Feedback from @LarryOsterman - Our verifier accepts SGX evidence type. Among all SGX attestation UUIDs defined in OE SDK, not sure which one to pick.

Current SGX types:
    * OE_FORMAT_UUID_SGX_ECDSA_P256
    * OE_FORMAT_UUID_SGX_ECDSA_P256_REPORT
    * OE_FORMAT_UUID_SGX_ECDSA_P256_QUOTE
    * OE_FORMAT_UUID_SGX_ECDSA_P384
    * OE_FORMAT_UUID_SGX_EPID_LINKABLE
    * OE_FORMAT_UUID_SGX_EPID_UNLINKABLE

**Comment by shnwc** [comment]
I’d assume @LarryOsterman's quotes are all in ECDSA-p256 format. DCAP only generates this type of quotes. ECDSA-Pp384 quote generation is not supported yet. EPID quote can only be generated by another library such as quote-ex, and before generating an EPID quote, a platform needs to be configured to join and EPID group.

To verify an ECDSA-p256 quotes, application software can call oe_verify_evidence() with format_id set to OE_FORMAT_UUID_SGX_ECDSA_P256_QUOTE.

**Comment by LarryOsterman** [comment]
@shnwc How would I as a user of the API know which quote format I have? There are 6 different options, and to the best of my knowledge, the only way of determining which of the options is the correct one to use is to parse the evidence to determine what the format of the evidence is. But the whole point of this API is that I shouldn't have to parse the evidence.

If it is possible for the attestation API to distinguish between various options by looking at the evidence, then it should not be presented to the user as a choice. All it does is to introduce a failure point for the customer AND it becomes what the Windows team calls a "call generator" - in other words, an issue which is highly likely to cause the customer to request support.

It's probably safe to know that the caller knows that this evidence came from an SGX enclave (SGX). It's also probably safe to know that the caller knows that the evidence is of the form of an SGX Quote or an SGX Report. That reduces the set of 6 options to 4 (I'm not 100% sure what an SGX_EPID is - if it's an expression of a type 2 or 3 quote validation data, then that's another option that a caller shouldn't have to know.

However it is NOT reasonable to require the caller to know which encryption algorithm was used to sign the attestation evidence. That is a parameter which is not under the control of the caller, and thus they should not be required to know it.

**Comment by yentsanglee** [comment]
@shnwc, as part of the issue resolution, please also provide Doxygen-style comments in [evidence.h](https://github.com/openenclave/openenclave/blob/master/include/openenclave/attestation/sgx/evidence.h) for each UUID. The comments will be included in generating [Open Enclave SDK API Reference](https://openenclave.io/apidocs/v0.10/) where OE developers refer to. It's fair to also specify

1.  Legit `flags` for each UUID when calling oe_get_evidence()
2.  Allowable custom_claims_size
3.  Other UUID specific limitations

**Comment by LarryOsterman** [comment]
Oh, and one other thought piling onto my original thought: If at some point in the future, someone decides to change the quoting enclave to use RSA to sign a quote, is it really appropriate to require that clients know about this change and update their code to reflect the change?

**Comment by shnwc** [comment]
Based on the comments here and the discussion in this weeek's SIG-attestation meeting, one proposal to fix this issue is to replace existing `OE_FORMAT_UUID_SGX_ECDSA_P256_REPORT` and  `OE_FORMAT_UUID_SGX_ECDSA_P256_QUOTE` with two new IDs, for evidence verification:
* `OE_FORMAT_UUID_SGX_REPORT`
  * Verifies OE reports generated by `oe_get_report()`, for both SGX local and remote attestation
* `OE_FORMAT_UUID_SGX_QUOTE`
  * Verifies all SGX quotes generated by the DCAP library
  * Currently only ECDSA-p256 quotes can be verified
  * In the future, verification of quotes with other algorithms could be added, without the need of new UUIDs.

I'll create a PR to update the design document [Attestation_API_Proposal.md](https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/Attestation_API_Proposal.md), and another PR for the implementation.

**Comment by LarryOsterman** [comment]
To confirm: You do not plan on validating Intel SGX reports (there's a nomenclature challenge here - Intel calls the local construct a report and the remote construct a quote, OE calls both of these a report).

**Comment by shnwc** [comment]
> To confirm: You do not plan on validating Intel SGX reports (there's a nomenclature challenge here - Intel calls the local construct a report and the remote construct a quote, OE calls both of these a report).

Correct, there is no plan for `oe_verify_evidence()` to verify raw SGX reports. There is no API in OE SDK or the DCAP library to generate raw SGX reports either.

**Comment by shnwc** [comment]
I've just created PR #3402 to fix this issue. Please review.
