### ISSUE TITLE
Security issues, code pages are readable by who takes control of the OS

### ISSUE THREAD

**Issue by VincenzoGallicchio** [openenclave/openenclave#3399]
Hi everyone,
I'm new to this framework and in general to the subject but I know that the TEE is supposed to protect data executed within the enclave from compromised OSes.
Now, since the code is freely accessible in the folder of the project how do we manage privacy protection?
Specifically, I'm writing an app that seals some passwords into protected memory, but password are readable in my files, so would be the keys if i wanted to encrypt them first
Hope I've been clear
Thanks

**Comment by mingweishih** [comment]
What you describe is correct---"protect data executed within the enclave" really means that its a runtime protection (i.e., data-in-use protection). This also implies that TEE is not for protecting the privacy of the source code, but for the runtime data generated by the code. For example, you can write an application that generates a random key. In this case, this key is protected by TEE against the compromised OSes. TEE also ensures the integrity of the code loaded into the enclave via remote attestation.

To be secure in your scenario, you need to combine not only the "data-in-use" protection (offered by TEE) but also "data-in-transit" (e.g., encrypted network channel) and "data-in-rest" (encrypted disk/files). For example, you can remotely attest the enclave, establish a encrypted channel, and then send the key to the enclave via the channel. After that, you can have enclave write the encrypted file into the memory, and use the key to decrypt the data.

**Comment by radhikaj** [comment]
#3387 will track PCL. Closing this since the questions are answered.
