### ISSUE TITLE
CI/CD: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (129084 != 128880)

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#3405]
Occasionally, when the metadata in mirrors are updated, apt will fail in VMs.
The failure will have the following message:

> Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (129084 != 128880). Mirror sync in progress?

Here is an example: https://oe-jenkins-dev.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Linux/detail/Azure-Linux/1249/pipeline

The recommendation from the relevant team that handles apt repos is to wait for 5 minutes and then retry.
|

**Comment by BRMcLaren** [comment]
Closing, unsure why it was not done automatically. Took suggested approach and did the retry 5x with 1 min sleep: https://github.com/openenclave/openenclave/blob/master/.jenkins/pipelines/Azure/Linux/Jenkinsfile#L73
