### ISSUE TITLE
oeedger-cpp ignores (w)string conflicts with out,user_check,count,size

### ISSUE THREAD

**Issue by yanxue-intel** [openenclave/openenclave#3431]
my.edl
```
enclave {
    trusted {
        public int ecall([string, out] char *s);
        public int ecall([string, user_check] char *s);
        public int ecall([string, in, count=10] char *s);
        public int ecall([string, in, size=10] char *s);
    };
};
```

old version(OCAML) oeedger can check out those invalid syntax, but oeedger-cpp will ignore.

**Comment by anakrish** [comment]
This is not a blocker. It is just extra error checking. Therefore we have put it in backlog. Will get to this in v0.11 if time permits.

**Comment by mingweishih** [comment]
These checks have been implemented in the current `oeedger8r`.
