### ISSUE TITLE
RSA key generation failure with OE OpenSSL

### ISSUE THREAD

**Issue by lzha101** [openenclave/openenclave#3449]
OE OpenSSL is an experimental feature currently. Tried below code snippets inside enclave built with OE OpenSSL + OE SDK. Seems it always fails at `RSA_generate_key_ex()`. 

```
bool test_rsa_key_gen()
{
    bool ret = false;
    RSA* rsa_ctx = NULL;
    BIGNUM* bn_e = NULL;
    BIGNUM* tmp_bn_e = NULL;
    do
    {
        rsa_ctx = RSA_new();
        if (rsa_ctx == NULL) {
                break;
        }
        unsigned int e[1];
        e[0] = RSA_F4;
        unsigned char *p_e = (unsigned char *)e;
        tmp_bn_e = BN_new();
        bn_e = BN_lebin2bn(p_e, 4, tmp_bn_e);

        if (RSA_generate_key_ex(rsa_ctx, 384 * 8, bn_e, NULL) != 1) {
                break;
        }
        ret = true;
    }while(0);
    if(rsa_ctx)
        RSA_free(rsa_ctx);
    if(tmp_bn_e)
        BN_clear_free(tmp_bn_e);
    return ret;
}
```
But the same code logic executes successfully in untrusted app with system OpenSSL ( v1.1.1). 
I also verified the code snippets inside enclave with SGXSSL + Intel SGX SDK:  The RSA key could be generated successfully as well.

Guess the ported OE OpenSSL has some RSA related bug.

**Comment by CodeMonkeyLeet** [comment]
@mingweishih I suspect this is because the rdrand engine is not registered by default; can you work with @lzha101 on the expected usage of the current implementation?

**Comment by mingweishih** [comment]
Currently it's required to register the rdrand engine to use OpebSSL RAND APIs in OE, please see https://github.com/openenclave/openenclave/blob/master/docs/OpenSSLSupport.md#how-to-use-rand-apis for more details.

**Comment by lzha101** [comment]
Thanks for your clarification. So currently each API which requires to access random needs to register the rdrand engine first.  
SGXSSL uses an exception handler to handle the case `rdtsc` instruction not supported in SGX1. Do you plan to do this as well, like what you did for `cpuid`?  Then it doesn't require users to change anything to adopt the OE OpenSSL.  And it seems more generic. Currently OpenSSL could use rdrand engine to workaround this. But not sure if later we will have other modules requesting `rdtsc`.

**Comment by mingweishih** [comment]
We do consider that option (i.e., handling `rdtsc` via exception handler). However, we didn't support it mainly for security and performance reasons. More specifically, `rdtsc` with exception handler cannot be considered as secure source. In addition, the default OpenSSL (assuming v1.1.1) RAND seed/reseed that use `rdtsc` involve in multiple context switches (including invocation of the `rdtsc` itself and several ocalls to obtain time/pid), which are fairly expensive. It would be good to see the rationale (other than compatibility) behind why SGXSSL decides to support `rdtsc` via exception handler.

Given those reasons, we feel using rdrand engine is more suitable for the sgx enclaves. We're also considering improving the user experience of rdrand engine opt-in before moving the OpenSSL out of experimental feature.

**Comment by radhikaj** [comment]
@lzha101 , @mingweishih  has a workaround described in  https://github.com/openenclave/openenclave/blob/master/docs/OpenSSLSupport.md#how-to-use-rand-apis
Based on the discussion in SIG-Testing, I am moving this to backlog.

**Comment by mingweishih** [comment]
This shouldn't be an issue anymore. Closing for now.
