### ISSUE TITLE
host_verify CLI should display some quote information

### ISSUE THREAD

**Issue by jumaffre** [openenclave/openenclave#3455]
The `host_verify` CLI shipped with `openenclave` is very useful for clients to verify the quote of an enclave server they are connecting to. In CCF, we rely on this utility [in this way](https://microsoft.github.io/CCF/master/users/verify_quote.html).

However, it is important for a client to verify not only that the quote is valid, but also that the version of the code (`mrenclave`) is trusted. Similarly, verifying`mrsigner` and the `report_data` would be useful for further verification.

I believe that the best way to do this is for `host_verify` to print `mrenclave`, `mrsigner` and `report_data` after the quote verification has been successful. That way, a client can perform further checks afterwards.

**Comment by yentsanglee** [comment]
We are planning on moving to oe_verify_evidence() soon. Will print associated claims for mrsigner, mrenclave, and report_data.

**Comment by achamayou** [comment]
@yentsanglee that's great to hear, thank you.

**Comment by yentsanglee** [comment]
Assigning to @jumaffre as he is also fixing #3276

**Comment by yentsanglee** [comment]
@jumaffre please mark as "In progress" in the Project SIG-Attestation if you have started working on this.
