### ISSUE TITLE
Multiple potential null pointer derefs in hostcalls.c

### ISSUE THREAD

**Issue by douglasmaciver** [openenclave/openenclave#3456]
There are two potential null pointer derefs.

Here with td:
https://github.com/openenclave/openenclave/blob/8e8c5cb91fdfef859bd20a8b996110cf5910616d/enclave/core/sgx/hostcalls.c#L13-L16

And here with ecall_context:
https://github.com/openenclave/openenclave/blob/8e8c5cb91fdfef859bd20a8b996110cf5910616d/enclave/core/sgx/hostcalls.c#L66-L72

**Comment by radhikaj** [comment]
@douglasmaciver Is there a generic way to detect all the missing nullptr checks? Is there some tooling we could use?

**Comment by radhikaj** [comment]
Intel SDK uses Clockwork to track such patterns. @douglasmaciver will follow up with a tool/analysis to find more locations for this.

**Comment by radhikaj** [comment]
@dthaler suggests annotations. How would they be enforced?
