### ISSUE TITLE
eeid::deserialize_element(): improper bounds checking leads to integer underflow and buffer overread

### ISSUE THREAD

**Issue by douglasmaciver** [openenclave/openenclave#3473]
While the calling context for `deserialize_element()'s` upstream function `oe_deserialize_eeid()` is not known, clearly this parsing function is not coded for unexpected input, malicious or not.  The `while` loop does not check for exhaustion of the remaining buffer.

https://github.com/openenclave/openenclave/blob/a85420361cbd37f3e503c65954341bcd25d0251a/common/sgx/eeid.c#L87-L102

**Comment by wintersteiger** [comment]
Thanks for reporting this issue! These functions are not used anymore, they have been replaced by the ntoh/hton functions further down in the file. Removed in #3535.
