### ISSUE TITLE
C11 and asm

### ISSUE THREAD

**Issue by wintersteiger** [openenclave/openenclave#3474]
The cmake scripts set the C standard to C11 ([here](https://github.com/openenclave/openenclave/blob/1ffb22341d1d48f994e42a79ddcfe54b0e47f467/cmake/compiler_settings.cmake#L19))

However, on Linux it adds `-std=gnu11` instead of `-std=c11`, which allows GNU extensions like the `asm` keyword, while on Windows it adds `-std:c11`, which does not.

Versions: 
Linux: cmake 3.18.2, with clang-7 or gcc 7.5)
Windows: cmake 3.18.2, MSVC 19.27.29111.0, clang 7.0.1 (via `scripts/clangw`)

All three compilers reject the following program if C11 is enabled.

    int main() {
        asm volatile("pause");
        return 0;
    }

Thus, if I translate `-std:c11` to `-std=c11` in the `clangw` script, many enclave source files won't build as clangw rejects the input as `asm` is not legal C11. I builds successfully if I just drop `-std:c11` in `clangw`.

Is the intention that all OE code should be C11, or is that overly conservative and it's fine to drop `-std:c11` on Windows? I'm not sure, but I think `__asm` and `__asm__` are legal C11, so should we change all occurrences thereof? 

CC @CodeMonkeyLeet @jhand2

**Comment by jhand2** [comment]
cc @anakrish as well

In general we rely on a bunch of GNU extensions (specifically function/variable attributes) inside the enclave, so for enclave code I think it's fine to just always use gnu11.

But I'm a little confused. On the host the following code is currently used for all platforms:
```
        asm volatile("fxsave %[fx_state] \n\t" // Save floating point state.
                     "pushfq \n\t"             // Save flags.
                     "enclu \n\t"
                     "popfq \n\t"               // Restore flags.
                     "fxrstor %[fx_state] \n\t" // Restore floating point state.
                     : OE_ENCLU_REGISTERS
                     : [fx_state] "m"(fx_state)OE_FRAME_POINTER
                     : OE_ENCLU_CLOBBERED_REGISTERS);
```

If `asm volatile` is a gnu extension, why does this work on Windows?

**Comment by anakrish** [comment]
@jhand2 We compile host/sgx/enter.c using clang on Windows. Doing so allows us to avoid having to hand implement the host side enter/exit in asm, which was quite difficult to get right.

**Comment by anakrish** [comment]
@wintersteiger Mapping the msvc `-std:c11` flag to `-std=gnu11` appears to be the right thing to do.

**Comment by CodeMonkeyLeet** [comment]
@wintersteiger Thanks for the investigation and explanation! I agree that using the `-std=gnu11` flag in the clangw script is probably the cheapest fix here that makes sense.

**Comment by wintersteiger** [comment]
Great! I agree, `-std=gnu11` is the best solution.
