### ISSUE TITLE
New DCAP release broke CI ansible scripts

### ISSUE THREAD

**Issue by BRMcLaren** [openenclave/openenclave#3477]
With Intel's new DCAP release a change was noticed in the packaging and 
`/usr/lib/x86_64-linux-gnu/libsgx_dcap_quoteverify.so` is no longer installed.

This causes issues with the CI scripts as part of the validation checks we check the file paths. This package needs to be added to the scripts as a quick fix, the long term fix being to version the PSW/DCAP libraries to ensure this does not happen again.

**Comment by CyanDevs** [comment]
libsgx_dcap_quoteverify is now provided by the libsgx-dcap-quote-verify-dev now and should be added to https://github.com/openenclave/openenclave/blob/f1bc20839bcbd673edb2ecc80d2942914d1aecd9/scripts/ansible/roles/linux/intel/vars/ubuntu/main.yml#L14

**Comment by anakrish** [comment]
Should we instead assert that /usr/lib/x86_64-linux-gnu/libsgx_dcap_quoteverify.**so1** is present?
From what I understand, dev packages are not expected to be installed on production environments.
They just provide a symbolic link to the acutal shared library.
