### ISSUE TITLE
Why is pthread_spin_trylock() not provided?

### ISSUE THREAD

**Issue by eddyashton** [openenclave/openenclave#3483]
Open Enclave provides partial support for standard POSIX/LibC functions. The current support is listed [here](https://github.com/openenclave/openenclave/blob/master/docs/LibcSupport.md). This list does not include `pthread_spin_trylock()`. All other `pthread_spin_` functions _are_ supported, as far as I can tell only `trylock` is missing

Why is this? Is there a technical reason why `trylock` is not supportable? Or is this an accidental omission?

From a quick read of the code it looks like the `oe_spin_lock` implementation could be `oe_spin_trylock` with only slight modification, and this could be wrapped/exposed as `pthread_spin_trylock` in the same manner as the other `pthread_spin_` functions.

**Comment by anakrish** [comment]
This is likely an accidental omission.
