### ISSUE TITLE
Name of libsgx_quote_ex.dll

### ISSUE THREAD

**Issue by wintersteiger** [openenclave/openenclave#3490]
I'm wondering whether `libsgx_quote_ex.dll` ([here](https://github.com/openenclave/openenclave/blob/52ec4e58ec0d41468d4d60fc34ca53addef8c3ef/host/sgx/windows/sgxquoteexloader.c#L13)) had its name changed to `sgx_quote_ex.dll`. After installing everything (I think) on a fresh Windows 10 ACC VM, I find `sgx_quote_ex.dll` in `C:\Windows\SysWOW64` (and the Intel DCAP package), but I have no `libsgx_quote_ex.dll` anywhere.

**Comment by anakrish** [comment]
Since, by convention, shared libraries on Windows don't have the `lib` prefix, this seems like a latent typo/bug.
