### ISSUE TITLE
Gratuitous differences in local vs remote attestation samples

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#3495]
Doing a diff between the two (e.g., "windiff local_attestation remote_attestation") shows a bunch of gratuitous differences (having nothing to do with local vs remote), including a couple that look like errors. 

Here's a few illustrative examples:

* Local sample frees claims at end of attestation.cpp and remote sample does not.
* Local sample makes duplicate calls to mbedtls_pk_rsa(), but remote sample does not.
* enclave_b/cmakelists.txt has duplicate copyright headers in local sample, but not in remote sample.
* Local sample has trace output in attestation.cpp that is missing from the remote sample

To address all these issues, and prevent more occurrences, I recommend combining these two samples into one sample, with command-line options saying whether to use local or remote.

**Comment by yentsanglee** [comment]
It was agreed on in SIG-Attestation meeting to combine remote and local attestation samples as enclave-to-enclave attestation sample.
