### ISSUE TITLE
do we need to add --search-path in example command of oeedger8r in helloworld sample README.md?

### ISSUE THREAD

**Issue by johnvenn** [openenclave/openenclave#3501]
I found in sample helloworld README.md, there is a sample command line of using oeedger8r tool to generate files for host and enclave, but no search-path following oedger8r command:
cd host  //should add this command?
oeedger8r ../helloworld_sample.edl --untrusted // no --search-path?

cd enclave //should add this command?
oeedger8r ../helloworld_sample.edl --trusted //no --search-path?

**Comment by radhikaj** [comment]
This is being addressed in #3527
