### ISSUE TITLE
a question: how is the hex value in _oe_enclave_setting_type calculated?

### ISSUE THREAD

**Issue by johnvenn** [openenclave/openenclave#3506]
Just a question in include/openenclave/host.h, oe_enclave_setting_type defined here:

typedef enum _oe_enclave_setting_type
{
    OE_ENCLAVE_SETTING_CONTEXT_SWITCHLESS = 0xdc73a628,
#ifdef OE_WITH_EXPERIMENTAL_EEID
    OE_EXTENDED_ENCLAVE_INITIALIZATION_DATA = 0x976a8f66,
#endif
} oe_enclave_setting_type_t;

but how those hex values caculated for "eeid" and "switchless" feature. 

If I want to add another feature by this setting type, how could I get the new hex value? 

There is no document pointing out this.

**Comment by johnvenn** [comment]
anyone who can answer my question?

**Comment by anakrish** [comment]
I could be wrong, but I think it is just a random hex string generated via `uuidgen` command on linux.

**Comment by radhikaj** [comment]
@dthaler would like to review whether using a random number here is a good idea or not.

**Comment by radhikaj** [comment]
The answer is that this is just a random hex string.

**Comment by johnvenn** [comment]
ok, thanks a lot.
