### ISSUE TITLE
 tls_e2e test hangs on RHEL

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#3508]
We have noticed that the tls_e2e  test hangs every often on RHEL. We are temporarily disabling it while we investigate them.

**Comment by dthaler** [comment]
@radhikaj PR #3507 looks to be about tests, whereas title of this issue says sample.  Please clarify if this is about testing or about sample code.

**Comment by radhikaj** [comment]
@dthaler, thanks. I updated it to say sample.

**Comment by dthaler** [comment]
> @dthaler, thanks. I updated it to say sample.

What did you update.  The title of this issue says sample.  The description of this issue says test.  The PR says test.

**Comment by mingweishih** [comment]
> > @dthaler, thanks. I updated it to say sample.
> 
> What did you update. The title of this issue says sample. The description of this issue says test. The PR says test.

@radhikaj only changed the label. I just changed the title as well.
