### ISSUE TITLE
oeedger8r should be modified to warn when an EDL specification cannot be fully serialized

### ISSUE THREAD

**Issue by douglasmaciver** [openenclave/openenclave#3513]
This is a request that openenclave implements the proposal linked below.

There have been several cases where projects may have avoided edge security issues if there had been warnings as proposed in this specification:
[docs/DesignDocs/full_edl_serialization.md](https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/full_edl_serialization.md)

>Although EDL provides sufficient mechanisms for performing full serialization, the generator does not currently enforce these mechanisms. By default, the generator produces edge routines that implicitly copy untrusted memory references into the enclave. This results in potential security flaws and non-portable code.
>
>To overcome these problems, the generator can be modified to warn when an EDL specification cannot be fully serialized.

**Comment by radhikaj** [comment]
@manojrupireddy Please investigate if we get warnings or not currently.
