### ISSUE TITLE
Heap page flags

### ISSUE THREAD

**Issue by wintersteiger** [openenclave/openenclave#3518]
Some applications (like SGX-LKL) require the executable flag on heap pages. The flags are currently hard-coded ([here](https://github.com/openenclave/openenclave/blob/03e07014e80d4894aee58d41216eeaa6d321a11d/host/sgx/create.c#L123)) which means that they can't be changed without modifying Open Enclave itself. (SGX-LKL does that [here](https://github.com/openenclave/openenclave/blob/2d24c56ed5432cab4c38d15e2728d772bc9cd391/host/sgx/create.c#L124).)

Since the page flags are measured ([here](https://github.com/openenclave/openenclave/blob/03e07014e80d4894aee58d41216eeaa6d321a11d/host/sgx/sgxmeasure.c#L92)), this means that such applications lose the ability to create and verify quotes from unmodified OE applications. Similarly, measurements created by such applications, can't be verified by an unmodified OE. 

I think we need to add this as an option in some way, perhaps by simply saving the required flags in `.oeinfo`.

**Comment by radhikaj** [comment]
There is an  intersection with EDMM and memory management model - See https://github.com/openenclave/openenclave/pull/3639
