### ISSUE TITLE
OE submodule

### ISSUE THREAD

**Issue by wintersteiger** [openenclave/openenclave#3519]
Which version/branch of OE are we currently using? It looks like `feature/sgx-lkl-support` doesn't have everything it needs for user-space isolation:

    obj/sgxlkl/enclave_init.o: In function `_enter_user_space':
    /data/cwinter/sgx-lkl/src/enclave/enclave_init.c:119: undefined reference to `__oe_get_isolated_image_entry_point'
    /data/cwinter/sgx-lkl/src/enclave/enclave_init.c:130: undefined reference to `__oe_get_isolated_image_base'

@mikbras could you take a look at this and coordinate with @jhand2 to get everything into one branch? Thanks!

**Comment by radhikaj** [comment]
@wintersteiger, Is the question here which branch of OE is SGX-LKL using? If this is not related to oe master, can we close this here and track it elsewhere?

**Comment by wintersteiger** [comment]
SGX-LKL uses the `feature/sgx-lkl-support` branch, but something's gone wrong there recently, because SGX-LKL doesn't build (link) with that branch anymore and we're in some sort of in-between state with updates to `feature/sgx-lkl-support` blocked by https://github.com/lsds/sgx-lkl-musl/pull/38.
