### ISSUE TITLE
Open Enclave Repository Guidelines

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#3521]
Currently [OE](https://github.com/openenclave) has a number of repos:
* openenclave: SDK for developing enclaves
* openenclave-build: Reproducible & secure build resources for Open Enclave
* oeedger8r-cpp: An implementation of oeedger8r in C++
* openenclave-mbedtls: Open Enclave copy of mbedtls for inclusion as submodule in SDK.
* openenclave-site: Website for Open Enclave SDK, please file issues at the main repo.
* openenclave-ci
* gperftools: Main gperftools repository (forked from gperftools/gperftools)
* public-talks: Common area for sharing community content
* openenclave-curl: libcurl build files to enable use in Open Enclave applications
* openenclave-template: This is a template repo with a license and code of conduct.

plus two more listed as "private".   However, there is no currently documented process for creating or removing such repos.  Furthermore, some of the existing repos do not use the same license.  For example, while most use MIT, gperftools (being a fork of gperftools/gperftools) uses BSD-3-Clause, and public-talks uses Apache.   

The [Open Enclave Technical Charter](https://github.com/openenclave/openenclave/blob/master/TECHNICAL_CHARTER.md) states that the MIT License is the default, but that:

> The TSC may approve the use of an alternative license or licenses for inbound or outbound contributions on an exception basis. To request an exception, please describe the contribution, the alternative open source license(s), and the justification for using an alternative open source license for the Project. License exceptions must be approved by a two-thirds vote of the entire TSC.

I don't believe the CGC ever explicitly discussed the license issue for public-talks, which just illustrates that we need to better document the process by which repos are approved.   Similarly, forking of other repos for purposes of creating upstream patches (e.g., gperftools) is another area where licenses may vary.

Besides license, other questions for new repos include:
a) should github issues be filed in the new repo, or in the main openenclave repo?
b) should issues in the new repo be discussed in the master openenclave triage meeting, or in some separate process?
c) should one or more of the existing SIGs (e.g., SIG-Architecture, SIG-Testing) oversee relevant aspects of the new repo, or not?
d) will the repo be public or private, and if private, why?

An example of a  writeup of repo guidelines is the [Kubernetes Repository Guidelines](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md).

**Comment by AevaOnline** [comment]
This was an "oops" on my part, when creating the openenclave/publictalks repo. 

As far as the process itself, I would suggest that openenclave/openenclave docs/Community be forked into openenclave/community and the governance votes be handled through changes in that repo.
