### ISSUE TITLE
[Bug] Windows PSW/DCAP Dependency Incompatibility with Windows Update on Windows 2019

### ISSUE THREAD

**Issue by BRMcLaren** [openenclave/openenclave#3523]
When launching Windows 2019 vm's a common practice is for Windows Update to run before a user is able to tunnel into the VM. Yesterday this was the output configuration of Windows Update

Intel DCAP v1.8.x
Intel PSW v2.7.x

Which is not compatible versions whereas the current dcap and psw need to be aligned in this case 1.8 and 2.9, otherwise compatibility issues will be seen. Our installation scripts for Windows only update the DCAP components and rely on Windows Update for the PSW, this leaves and edge case. We need to update the installation scripts to allow the user to do one of two things, either update to a compatible version (latest, usually) or allow users to not install any DCAP or PSW dependencies.

We should also add a document that outlines what that compatibility matrix is if it is not already done (I have not seen one).

**Comment by radhikaj** [comment]
We will use this issue to track script problems and @BRMcLaren  will open another issue (tracked as External) to track the issue when mismatched PSW and DCAP are installed by WU.

**Comment by BRMcLaren** [comment]
@radhikaj  we have been stable for 2 weeks after the fixes here: https://github.com/openenclave/openenclave/pull/3525

Closing as resolved, we have an external issue for the upstream windows update issues: https://github.com/openenclave/openenclave/issues/3532
