### ISSUE TITLE
Ctest failed but samples work - SGX1 mode

### ISSUE THREAD

**Issue by mofanv** [openenclave/openenclave#3536]
Hi,

I followed [SGX1GettingStarted.md](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1GettingStarted.md) to set up. The project built very well, but there are some tests failed in `ctest` as follows.

```
96% tests passed, 10 tests failed out of 282

Total Test time (real) = 444.54 sec

The following tests did not run:
	 73 - tests/bigmalloc (Skipped)
	228 - tests/report_attestation_without_enclave (Skipped)

The following tests FAILED:
	 62 - tests/tls_e2e (Child aborted)
	 69 - tests/attestation_cert_api (Failed)
	 71 - tests/attestation_plugin_cert (Failed)
	 80 - tests/debug-signed (Failed)
	 81 - tests/nodebug-signed (Failed)
	227 - tests/report (Failed)
	241 - tests/fs (Child aborted)
	277 - tests/child_process_ecall (Child aborted)
	278 - tests/child_process_destroy (Child aborted)
	279 - tests/child_process_create (Child aborted)
Errors while running CTest

```

However, all `samples` (such as hello_world, etc) for SGX1 still work, and tests on them all passed. I wonder what results in these errors? are these failed tests essential? or do I need to pass them as well even though I am already able to run samples.
Thanks!
Fan

**Comment by mingweishih** [comment]
Can you provide more information of your dev environment (e.g., local machine or Azure ACC VM, version of Intel SGX / DCAP Driver, etc.)

**Comment by mingweishih** [comment]
Closing the issue for now. Feel free to reopen is any follow-up needed.
