### ISSUE TITLE
Unnecessary CMAKE_PREFIX_PATH in openenclaverc

### ISSUE THREAD

**Issue by binxing** [openenclave/openenclave#3543]
`CMAKE_PREFIX_PATH` env var is supposed to contain a colon separated list of paths for cmake functions (such as `find_package`) to search for external modules. `share/openenclave/openenclaverc` however overwrites (rather than appending to) `CMAKE_PREFIX_PATH`, which potentially disables other external modules and would be problematic should an enclave depend on more external modules than just `OpenEnclave`. In fact, `CMAKE_PREFIX_PATH` is unnecessary as long as /*path/to/OpenEnclave_InstallDir*/bin is listed in `PATH`. Shall we remove it from `openenclaverc`? Or did I miss anything?

**Comment by mingweishih** [comment]
CMAKE_PREFIX_PATH is required by LVI mitigation so it can't be removed. Also, I recalled that there is a problem with appending paths to CMAKE_PREFIX_PATH with openenclaverc.

Is there specific reasons you want to modify/remove the use of it?

**Comment by binxing** [comment]
Hi @mingweishih,

It's just a potential problem for now, as `OpenEnclave` is the only package used by any enclave. But I'm worried the problem will become realistic some day, when there's need to import multiple cmake modules by an enclave. Moreover, I think it a bit ugly to **overwrite** `CMAKE_PREFIX_PATH`, which is supposed to be **appended** to instead.

IMHO, an easy and viable fix could be to symlink `openenclave` to `openenclave-lvi-mitigation` under /*path/to/OpenEnclave_InstallDir*/lib directory, as shown below. It works well in my environment. If you agree, I can provide a patch.

```
$ tree -d /opt/openenclave/lib/
/opt/openenclave/lib/
├── openenclave
│   ├── cmake
│   ├── debugger
│   │   └── gdb-sgx-plugin
│   ├── enclave
│   └── host
└── openenclave-lvi-mitigation -> openenclave
```

Btw, I have a question regarding LVI tool chain, which may be a bit off-topic. I notice the script lvi_mitigation_bin/invoke_compiler uses the flag `-link-lvi-mitigation` to dispatch clang to either its original or the lvi-mitigated version. As far as I know, the lvi-mitigated version is a superset of the original. Then why not always use the lvi-mitigated clang?

**Comment by mingweishih** [comment]
> Hi @mingweishih,
> 
> It's just a potential problem for now, as `OpenEnclave` is the only package used by any enclave. But I'm worried the problem will become realistic some day, when there's need to import multiple cmake modules by an enclave. Moreover, I think it a bit ugly to **overwrite** `CMAKE_PREFIX_PATH`, which is supposed to be **appended** to instead.
> 
> IMHO, an easy and viable fix could be to symlink `openenclave` to `openenclave-lvi-mitigation` under /_path/to/OpenEnclave_InstallDir_/lib directory, as shown below. It works well in my environment. If you agree, I can provide a patch.
> 
> ```
> $ tree -d /opt/openenclave/lib/
> /opt/openenclave/lib/
> ├── openenclave
> │   ├── cmake
> │   ├── debugger
> │   │   └── gdb-sgx-plugin
> │   ├── enclave
> │   └── host
> └── openenclave-lvi-mitigation -> openenclave
> ```
> 

I had a PR to fix this (#3554). Thanks for reporting this.

> Btw, I have a question regarding LVI tool chain, which may be a bit off-topic. I notice the script lvi_mitigation_bin/invoke_compiler uses the flag `-link-lvi-mitigation` to dispatch clang to either its original or the lvi-mitigated version. As far as I know, the lvi-mitigated version is a superset of the original. Then why not always use the lvi-mitigated clang?

If you're talking about only the if branch, then it's correct that we can use either the original compiler or our wrapper (the lvi-mitigated version you refer to). For the else branch, we're doing a trick of modifying the PATH when invoking the compiler (i.e., excluding /usr/bin from the PATH) so that the compiler will not be able to find the default `as` and `ld`. Therefore, we need to keep both branches.

**Comment by binxing** [comment]
My dev env may be different but what I observed was that, if `clang-7` was prefixed with an explicit path, it'd search for `as` and `ld` in the prefix before searching $PATH.

Here's my test:

Create a very simple `clang-test.cpp`.
```C++
#include <stdio.h>

int main(int, char **argv)
{
    printf("%s\n", argv[0]);
    return 0;
}
```

Then compile it using the original `clang-7`. As expected, it fails.
```
$ which clang-7 
/usr/bin/clang-7
$ clang-7 -fno-integrated-as -Wa,-mlfence-before-ret=not -O3 clang-test.cpp -o clang-test
/usr/bin/as: unrecognized option '-mlfence-before-ret=not'
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
```

Then symlink `clang-7` to the current directory and try again. As expected, it fails again.
```
$ ln -sv /usr/bin/clang-7 
'./clang-7' -> '/usr/bin/clang-7'
$ tree .
.
├── clang-7 -> /usr/bin/clang-7
└── clang-test.cpp
$ ./clang-7 -fno-integrated-as -Wa,-mlfence-before-ret=not -O3 clang-test.cpp -o clang-test
/usr/bin/as: unrecognized option '-mlfence-before-ret=not'
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
```

But with symlinks to `as` and `ld` in the mitigation tool chain, it succeeds.
```
$ ln -t . -svr ~/lvi_mitigation_bin/as ~/lvi_mitigation_bin/ld 
'./as' -> '../lvi_mitigation_bin/as'
'./ld' -> '../lvi_mitigation_bin/ld'
$ which as ld
/usr/bin/as
/usr/bin/ld
$ ./clang-7 -fno-integrated-as -Wa,-mlfence-before-ret=not -O3 clang-test.cpp -o clang-test
$ objdump -Cd clang-test|grep lfence
  401144:	0f ae e8             	lfence 
```

Finally, try plain `clang-7` again and confirm that it fails as expected, even with lvi-mitigated `as` and `ld` in the current directory.
```
$ tree .
.
├── as -> ../lvi_mitigation_bin/as
├── clang-7 -> /usr/bin/clang-7
├── clang-test
├── clang-test.cpp
└── ld -> ../lvi_mitigation_bin/ld
$ clang-7 -fno-integrated-as -Wa,-mlfence-before-ret=not -O3 clang-test.cpp -o clang-test
/usr/bin/as: unrecognized option '-mlfence-before-ret=not'
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
```

So I conclude that the `else` branch and the `$PATH` override are **unnecessary** in my dev env.

**Comment by mingweishih** [comment]
> My dev env may be different but what I observed was that, if `clang-7` was prefixed with an explicit path, it'd search for `as` and `ld` in the prefix before searching $PATH.
> 
> Here's my test:
> 
> Create a very simple `clang-test.cpp`.
> 
> ```c++
> #include <stdio.h>
> 
> int main(int, char **argv)
> {
>     printf("%s\n", argv[0]);
>     return 0;
> }
> ```
> 
> Then compile it using the original `clang-7`. As expected, it fails.
> 
> ```
> $ which clang-7 
> /usr/bin/clang-7
> $ clang-7 -fno-integrated-as -Wa,-mlfence-before-ret=not -O3 clang-test.cpp -o clang-test
> /usr/bin/as: unrecognized option '-mlfence-before-ret=not'
> clang: error: assembler command failed with exit code 1 (use -v to see invocation)
> ```
> 
> Then symlink `clang-7` to the current directory and try again. As expected, it fails again.
> 
> ```
> $ ln -sv /usr/bin/clang-7 
> './clang-7' -> '/usr/bin/clang-7'
> $ tree .
> .
> ├── clang-7 -> /usr/bin/clang-7
> └── clang-test.cpp
> $ ./clang-7 -fno-integrated-as -Wa,-mlfence-before-ret=not -O3 clang-test.cpp -o clang-test
> /usr/bin/as: unrecognized option '-mlfence-before-ret=not'
> clang: error: assembler command failed with exit code 1 (use -v to see invocation)
> ```
> 
> But with symlinks to `as` and `ld` in the mitigation tool chain, it succeeds.
> 
> ```
> $ ln -t . -svr ~/lvi_mitigation_bin/as ~/lvi_mitigation_bin/ld 
> './as' -> '../lvi_mitigation_bin/as'
> './ld' -> '../lvi_mitigation_bin/ld'
> $ which as ld
> /usr/bin/as
> /usr/bin/ld
> $ ./clang-7 -fno-integrated-as -Wa,-mlfence-before-ret=not -O3 clang-test.cpp -o clang-test
> $ objdump -Cd clang-test|grep lfence
>   401144:	0f ae e8             	lfence 
> ```
> 
> Finally, try plain `clang-7` again and confirm that it fails as expected, even with lvi-mitigated `as` and `ld` in the current directory.
> 
> ```
> $ tree .
> .
> ├── as -> ../lvi_mitigation_bin/as
> ├── clang-7 -> /usr/bin/clang-7
> ├── clang-test
> ├── clang-test.cpp
> └── ld -> ../lvi_mitigation_bin/ld
> $ clang-7 -fno-integrated-as -Wa,-mlfence-before-ret=not -O3 clang-test.cpp -o clang-test
> /usr/bin/as: unrecognized option '-mlfence-before-ret=not'
> clang: error: assembler command failed with exit code 1 (use -v to see invocation)
> ```
> 
> So I conclude that the `else` branch and the `$PATH` override are **unnecessary** in my dev env.

That PATH override is mainly to also cover the case of gcc, which has different behavior with clang as you described. That is, gcc will search whatever in the PATH for ld and as instead of the directory of where gcc binary is invoked.

**Comment by binxing** [comment]
Thanks for the explanation. But the current script (`call_compiler`) won't work on Ubuntu 20.x or RedHat distros as `/bin` is simply a symbolic link to `/usr/bin` on those OS's.

IIUC, it's OK to always use LVI-mitigated `as` and `ld` regardless LVI options are present on command line or not. Then the following script will work in all cases.

```
$ cat lvi_mitigation_bin/compiler.sh 
#!/usr/bin/env bash

readonly wrapper_name=$(basename $0)
readonly wrapper_dir=$(dirname $0)
readonly compiler_dirs=( $(dirname $(which -a $0 ${wrapper_name}) | uniq) )

if [[ -L ${wrapper_dir}/${wrapper_name}_symlink ]]; then
    exec ${wrapper_dir}/${wrapper_name}_symlink "$@"
elif [[ -z "${compiler_dirs[1]}" ]]; then
    echo error: \'${wrapper_name}\' not found in \$PATH, nor does a symlink exist in ${wrapper_dir}
    exit 1
else
    PATH=${wrapper_dir}:$PATH exec ${compiler_dirs[1]}/${wrapper_name} "$@"
fi
```

LVI-mitigated `gcc`/`g++` and `clang-7`/`clang++-7` will then be just symbolic links to the above script, as shown below.

```
$ tree lvi_mitigation_bin/
lvi_mitigation_bin/
├── as
├── clang-7 -> compiler.sh
├── clang++-7 -> compiler.sh
├── clang-7_symlink -> /usr/bin/clang-7
├── clang++-7_symlink -> /usr/bin/clang++-7
├── compiler.sh
├── g++ -> compiler.sh
├── gcc -> compiler.sh
└── ld
```

**Comment by mingweishih** [comment]
> Thanks for the explanation. But the current script (`call_compiler`) won't work on Ubuntu 20.x or RedHat distros as `/bin` is simply a symbolic link to `/usr/bin` on those OS's.
> 
> IIUC, it's OK to always use LVI-mitigated `as` and `ld` regardless LVI options are present on command line or not. Then the following script will work in all cases.
> 
> ```
> $ cat lvi_mitigation_bin/compiler.sh 
> #!/usr/bin/env bash
> 
> readonly wrapper_name=$(basename $0)
> readonly wrapper_dir=$(dirname $0)
> readonly compiler_dirs=( $(dirname $(which -a $0 ${wrapper_name}) | uniq) )
> 
> if [[ -L ${wrapper_dir}/${wrapper_name}_symlink ]]; then
>     exec ${wrapper_dir}/${wrapper_name}_symlink "$@"
> elif [[ -z "${compiler_dirs[1]}" ]]; then
>     echo error: \'${wrapper_name}\' not found in \$PATH, nor does a symlink exist in ${wrapper_dir}
>     exit 1
> else
>     PATH=${wrapper_dir}:$PATH exec ${compiler_dirs[1]}/${wrapper_name} "$@"
> fi
> ```
> 
> LVI-mitigated `gcc`/`g++` and `clang-7`/`clang++-7` will then be just symbolic links to the above script, as shown below.
> 
> ```
> $ tree lvi_mitigation_bin/
> lvi_mitigation_bin/
> ├── as
> ├── clang-7 -> compiler.sh
> ├── clang++-7 -> compiler.sh
> ├── clang-7_symlink -> /usr/bin/clang-7
> ├── clang++-7_symlink -> /usr/bin/clang++-7
> ├── compiler.sh
> ├── g++ -> compiler.sh
> ├── gcc -> compiler.sh
> └── ld
> ```

Given that the thread so far is a bit off-topic now, I've created #3568 to track the issue.
