### ISSUE TITLE
Deprecate support for gcc while building OE SDK from source

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#3555]
1) Our developer docs state that developers should use clang while building from source
2) clang provides spectre mitigations while gcc(On Ubuntu 1604) does not. 

What deprecation would mean
1) We remove CI support for building the SDK with gcc from source
2) Update docs to say that we only recommend building with clang while building the SDK from source.

From Sig-arch this morning
1. We will issue a notice of deprecation for gcc support in v0.11 but stop supporting it after v0.12.
2. In the docs, we will clarify that we recommend building with clang with the spectre mitigations. We will not prevent developers from building with a compiler of their choice.
3. After v0.12, we will remove support from CI
4. We should revisit what version of clang we can support. See issue: https://github.com/openenclave/openenclave/issues/2476, added to SIG-Arch agenda

Please note:
Samples are built and tested against gcc and Clang today and this will remain so even after v0.12. Developers can continue to use the compiler of their choice while building applications.

**Comment by mingweishih** [comment]
Note that this issue only affects x86 build. For OP-TEE on the aarch64, we still support aarch64 gcc toolchain.
