### ISSUE TITLE
Socket within Enclave. 

### ISSUE THREAD

**Issue by nico95v** [openenclave/openenclave#3563]
Hello to all,
I took the helloworld example and I'm trying to create a socket communication with an external program written in Python. I run this in simulation mode. The main problem is that the creation of the socket in the enclave is not successful. Is it possible to communicate with a socket inside the enclave? Also, how can I import the openssl library and use it inside the enclave?
Thank you.

**Comment by jhand2** [comment]
Hey, a few answers and a few questions :smile:

1. Yes it is possible to use a socket connection, but it requires you to import socket.edl and link liboesyscall
2. What is the error you get when trying to use sockets?
3. Work is underway to support openssl, but today we only support mbedtls
4. To see a usage of sockets inside the enclave, take a look at `tests/syscall/socket/enc/enc.c`. Also check out the CMakeLists.txt and edl file for that enclave
5. To see a usage of mbedtls, see `tests/tls_e2e`

**Comment by radhikaj** [comment]
@nico95v Do the answers above resolve your issue?

**Comment by radhikaj** [comment]
Hi, I am closing this issue. Please reopen if you see that this is unresolved.
