### ISSUE TITLE
Bug in collateral extraction?

### ISSUE THREAD

**Issue by wintersteiger** [openenclave/openenclave#3566]
The code following the call to `oe_get_quote_verification_collateral_ocall` [here](https://github.com/openenclave/openenclave/blob/98b71a493cbbadda84c72187e9b5a59a3a1d7dec/enclave/sgx/collateralinfo.c#L195) expects that all out-sizes have been filled in correctly if it returns `OE_BUFFER_TOO_SMALL`. That OCALL however, returns after the first element that doesn't fit into the buffer ([here](https://github.com/openenclave/openenclave/blob/36c0303cf92ff206f270ac89d7b3cd721d83fa76/host/sgx/ocalls/ocalls.c#L179)) and it won't initialize the remaining out-sizes.

That code has been there for months though, is there some hard-to-see detail that I'm missing? I think that either `oe_get_quote_verification_collateral_ocall` should produce all of the sizes the first time around, or `oe_get_sgx_quote_verification_collateral` needs to `continue;` the loop after each call to `oe_realloc`.

**Comment by yentsanglee** [comment]
The required sizes probably never exceed the default sizes so the problem never surfaced. In any case, this issue needs to be fixed.

**Comment by radhikaj** [comment]
This is a double call pattern, look into whether this is a way around this.
