### ISSUE TITLE
_get_attester_plugins: second ocall - should check output buffer size instead of ignoring it.

### ISSUE THREAD

**Issue by shnwc** [openenclave/openenclave#3569]
Follow up on issue #3500 and PR #3564 .

As @douglasmaciver [commented](https://github.com/openenclave/openenclave/pull/3564#pullrequestreview-492007388):

> While this change addresses the security concern, it does pose a functional incorrectness if the second call to oe_get_supported_attester_format_ids_ocall returns fewer format_ids than the first reported. ...

In case this happens, the list of plugins returned by `_get_attester_plugins()` in `enclave/sgx/attester.c` would countain plugins that have random format IDs.

A better fix is check the output buffer size by the second call to `oe_get_supported_attester_format_ids_ocall()`, to ensure it is no larger than the input buffer size. This fix will address the security concern, and be functionally correct.

**Comment by douglasmaciver** [comment]
@shnwc Kudos for taking the initiative to make this better. While you are working on this, you might look at how the system handles changes to the plugins set, or if that's even possible.

**Comment by radhikaj** [comment]
From triage - avoid double call patterns. Look into if there is a way around it here.

**Comment by radhikaj** [comment]
Shan-wei will look into the short term solution.

**Comment by shnwc** [comment]
> @shnwc Kudos for taking the initiative to make this better. While you are working on this, you might look at how the system handles changes to the plugins set, or if that's even possible.

With the current implementation, it's not possible for an attester application to discover changes in plugins set and re-register them after it calls `oe_attester_initialize()`, except restarting. But if a plugin can no longer function properly (e.g. if it requires a background service like AESM, but the service is no longer accessible), the plugin will return proper error code.

**Comment by shnwc** [comment]
Closed by PR #3570
