### ISSUE TITLE
OP-TEE OS C++ support on OE SDK

### ISSUE THREAD

**Issue by flothia** [openenclave/openenclave#3584]
Hi all,

I was wondering if there was no mistake about the SDK preview support for the C/C++ feature on OP-TEE OS (https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/OP-TEE/Introduction.md -> Supported Features/3.)
On the official documentation of OP-TEE OS (https://optee.readthedocs.io/en/latest/faq/faq.html#q-can-i-use-c-libraries-in-op-tee), it is indicated that C++ libraries are currently not supported.
Is the OP-TEE OS support on OE SDK includes dedicated bindings for the C++ support ?

Thanks in advance.

**Comment by HernanGatta** [comment]
Hello Flo,

The SDK does indeed provide preview support for C++ on OP-TEE.

A few notes:

1. OP-TEE has recently gained [experimental support for C++](https://github.com/OP-TEE/optee_os/pull/3693), though the SDK does not yet take advantage of it;
2. Support for C++ exceptions in the SDK is not complete, and while exception handlers will likely execute, you might observe unwarranted modifications to the stack during unwinding, possible crashing the enclave;
3. Seeing as OP-TEE enclaves are forcibly single-threaded and non-reentrant [1], usage of C++ features that assume concurrency support might deadlock.

[1] Single-threaded meaning that an enclave may execute on a single core at a time, and non-reentrant meaning that you cannot perform an ECALL from an OCALL. These are limitations imposed by OP-TEE itself, though there's been talk of improving that situation on the OP-TEE side.

Hope that helps!

**Comment by dthaler** [comment]
@flothia Does this answer the question?  Can the issue be closed or is there something left to track?
