### ISSUE TITLE
Misleading OE_BUFFER_TOO_SMALL error messages

### ISSUE THREAD

**Issue by yentsanglee** [openenclave/openenclave#3585]
There are many benign OE_BUFFER_TOO_SMALL errors in traces from functions which return required buffer size. Such functions are typically called twice - first time to get required size; second time to retrieve data with allocated buffer. The first call unnecessarily prints OE_BUFFER_TOO_SMALL error messages that can be misleading when root causing issue from log.

Example:
```c++
    r = oe_get_crl_distribution_points(..., NULL, &buffer_size);
    if (r == OE_BUFFER_TOO_SMALL)
    {
        uint8_t* buffer = (uint8_t*)malloc(buffer_size);
        oe_get_crl_distribution_points(..., buffer, &buffer_size);
```

**Comment by radhikaj** [comment]
Action: Dont log anything if you pass in a null buffer into these functions.
