### ISSUE TITLE
Unexpected compilation errors caused by OpenSSL unsupported.h

### ISSUE THREAD

**Issue by mingweishih** [openenclave/openenclave#3587]
Currently we put OpenSSL APIs (across multiple headers) that we want to disable in the same header, `unsupported.h`.  The  `unsupported.h` explicitly includes the corresponding OpenSSL headers as follows to enforce the inclusion order.

```
#include <openssl/crypto.h>
#include <openssl/ssl.h>
#include <openssl/x509_vfy.h>
```

In addition, we enforce the these OpenSSL headers to include `unsupported.h` so that we can correctly trigger the compilation errors when users try to use any of the disabled APIs. However, the inclusion of multiple headers could cause unexpected compilation errors. See the following example:

If an application (indirectly or directly) includes `evp.h` before any of above three headers, then the following error will be triggered.

```
In file included from /home/ssh_office/workspace/oe-ms2/common/crypto/openssl/hmac.c:7:
In file included from /home/ssh_office/workspace/oe-ms2/build/output/include/openenclave/openssl/hmac.h:15:
In file included from /home/ssh_office/workspace/oe-ms2/build/output/include/openenclave/openssl/evp.h:16:
In file included from /home/ssh_office/workspace/oe-ms2/build/output/include/openenclave/openssl/bio.h:20:
In file included from /home/ssh_office/workspace/oe-ms2/build/output/include/openenclave/openssl/crypto.h:446:
In file included from /home/ssh_office/workspace/oe-ms2/build/output/include/openenclave/openssl/unsupported.h:29:
In file included from /home/ssh_office/workspace/oe-ms2/build/output/include/openenclave/openssl/ssl.h:25:
/home/ssh_office/workspace/oe-ms2/build/output/include/openenclave/openssl/pem.h:234:19: error: unknown type name 'EVP_CIPHER_INFO'; did you mean
      'EVP_CIPHER_CTX'?
int PEM_do_header(EVP_CIPHER_INFO *cipher, unsigned char *data, long *len,
                  ^~~~~~~~~~~~~~~
                  EVP_CIPHER_CTX
```

The reason for this is that `ssl.h` depends on some type definitions in `evp.h`. However, the `unsupported.h` forces the inclusion of `ssl.h` before the point of those type definition in the `evp.h`.

**Comment by CodeMonkeyLeet** [comment]
Copying the elaboration of the issue from #3588:

> Changes look fine, but I'm unclear on the explanation of the repro in #3587:
> 
> * unsupported.h is not included in evp.h
> * evp.h is included before ssl.h by the app for the repro
> * ssl.h depends on definitions in evp.h
> * unsupported.h is appended to the end of ssl.h
> * unsupported.h includes crypto.h, ssl.h and x509_vfy.h
> 
> How does that lead to the assertion:
> 
> > unsupported.h forces the inclusion of ssl.h before the point of those type definition in the evp.h

The problem is that

evp.h
```
line 16 # include <openssl/bio.h>
...

line 396 typedef struct evp_cipher_info_st {
line 397    const EVP_CIPHER *cipher;
line 398    unsigned char iv[EVP_MAX_IV_LENGTH];
line 399} EVP_CIPHER_INFO;
```

Before reaching line 396, the inclusion of bio.h in line 16 will indirectly force the inclusion of ssl.h (bio.h -> crypto.h -> unsupported.h > ssl.h). This is where the error occurs.
