### ISSUE TITLE
Confirm and check that the parameter `claims` in API `oe_verify_evidence()` is optional

### ISSUE THREAD

**Issue by shnwc** [openenclave/openenclave#3594]
In `include/openenclave/attestation/verifier.h`, the `claims` parameter in API `oe_verify_evidence()` is not documented as optional, but the implementation of this API in `common/attest_plugin.c` allows this parameter to be NULL. On the other hand, `_verify_evidence()` in `common/sgx/verifier.c` requires its `claims` parameter to be non-NULL.

Need to clarify doxygen documentation and update implementation to support the `claims` parameter in API `oe_verify_evidence()`as optional, and to skip calling `oe_sgx_extract_claims()` when this parameter is NULL.

This issue was brought up in this [comment thread](https://github.com/openenclave/openenclave/pull/3499#discussion_r494672966).

**Comment by radhikaj** [comment]
This is a code and documentation issue.
