### ISSUE TITLE
samples\attestation is still tested in ctest case "samples", even when DCAP libraries not installed on Windows

### ISSUE THREAD

**Issue by jinghe-INTC** [openenclave/openenclave#3595]
During OE Windows setup, I chose not to install DCAP driver by running:
`./scripts/install-windows-prereqs.ps1 -InstallPath C:/oe_prereqs -LaunchConfiguration SGX1 -DCAPClientType None
`

However later in ctest, case "samples" always failed. I looked into the detail, and found the sample project `attestation` had an execution failure. Although at the beginning of the samples' test,  it did say: 
```
System does not have DCAP libraries.  Attestation based samples will NOT be
  tested.
```

I am wondering if case `attestation` in 
https://github.com/openenclave/openenclave/blob/7201ae4aa35fb9ba644fdace465dd9b810e13f0f/samples/test-samples.cmake#L65
can be moved to 
https://github.com/openenclave/openenclave/blob/7201ae4aa35fb9ba644fdace465dd9b810e13f0f/samples/test-samples.cmake#L70

**Comment by radhikaj** [comment]
For v0.12, please move attestation test to line 70 as suggested.
