### ISSUE TITLE
oeedger8r - Prow Integration

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#3601]
As part of SIG-Testing a decision was made to begin the prow roll out on the oeedger8r-cpp repo. We are beginning integration now, please be aware of any nuances and if an issue is noticed please comment here. It will be a little rocky to start so we are starting with ubuntu 1604 and 1804 containerization to start.

Filed by @BRMcLaren  https://github.com/openenclave/oeedger8r-cpp/issues/42

**Comment by BRMcLaren** [comment]
Completed! Prow is live on oeedgr8r for the past few weeks
