### ISSUE TITLE
oeedger8r - Add comments to sources explaining details where needed

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#3606]
The code has been written with readability in mind, and to mirror its corresponding python implementation. Currently though there are no code comments; the inner workings should be quite easy to figure out since the EDL language is not that complex.

That being said, adding comments judiciously would help with maintenance.

Filed by @anakrish : https://github.com/openenclave/oeedger8r-cpp/issues/2

**Comment by radhikaj** [comment]
Ongoing code documentation improvements.

**Comment by dthaler** [comment]
@radhikaj Why was this issue closed?   I'd expect either a PR merged, or a comment explaining why something is closed with no PR.
