### ISSUE TITLE
Clang-8 incompatabilities

### ISSUE THREAD

**Issue by BRMcLaren** [openenclave/openenclave#3615]
After adding all the backend changes to be able to use clang-8 in the CI the following problems appear.

Linux: https://oe-jenkins-tf.westeurope.cloudapp.azure.com/job/pipelines/job/Azure-Linux/252/

` 75/280 Test  #75: tests/cppException ....................................................................................................................Child aborted***Exception:   0.18 sec
=== This program is used to test basic cpp exception functionalities.
=== TestCppException() 
char type exception tests passed.
integer type exception tests passed.
string type exception tests passed.
string reference type exception tests passed.
user defined class type exception tests passed.
user defined class reference type exception tests passed.
user defined class type exception test passed.
user defined class reference type exception test passed.
user defined class type exception test passed.
Ellipsis exception catch tests passed.
Re-throw and throw new exception in the catch clause tests passed.
catch clause in the outermost block tests passed.
Find the matching catch clause through call stack tests passed
StackUnwind local unwind test passed.
StackUnwind global unwind test passed.
StackUnwind local unwind second test passed.
StackUnwind global unwind second test passed.
StackUnwind unwind test passed.
FunctionTryBlock exception test passed.
Cpp exception tests passed!
=== passed regular cpp exception tests.
=== TestUnhandledException(0)  
This test will crash the enclave.
2020-09-29T20:12:25+0000.765056Z [(H)ERROR] tid(0x7f8e722ab740) | :OE_ENCLAVE_ABORTING [../host/calls.c:_call_enclave_function_impl:56]
=== passed unhandled cpp exception tests (0).
=== TestUnhandledException(1)  
This test will crash the enclave.
        Start  76: tests/crypto_crls_cert_chains
`

This seems to be only when the build configuration is 'RelWithDebInfo'.

However, Windows fails to build entirely in `Release` mode

Windows: https://oe-jenkins-tf.westeurope.cloudapp.azure.com/job/pipelines/job/Azure-Windows/274/

`[2809/4286] Building C object libc\CMakeFiles\oelibc.dir\__\3rdparty\musl\musl\src\search\tsearch.c.obj
[2810/4286] Building C object libc\CMakeFiles\oelibc.dir\__\3rdparty\musl\musl\src\search\twalk.c.obj
FAILED: libc/CMakeFiles/oelibc.dir/__/3rdparty/musl/musl/src/search/twalk.c.obj 
"C:/Program Files/Git/bin/bash.exe" "C:/Users/oeadmin/workspace/pipelines/Azure-Windows/scripts/clangw" "-DOE_API_VERSION=2 -DOE_BUILD_ENCLAVE -D_XOPEN_SOURCE=700 -I3rdparty\musl\musl\src\include -I3rdparty\musl\musl\src\internal -I3rdparty\musl\musl\arch\x86_64 -I..\..\include -Ioutput\include -Ioutput\include\openenclave\libc /DWIN32 /D_WINDOWS /wd4566 /wd4200 /MD /O2 /Ob2 /DNDEBUG   /WX /W3 -Wall -Werror -Wpointer-arith -Wconversion -Wextra -Wno-missing-field-initializers -fno-strict-aliasing -mxsave -fno-builtin-malloc -fno-builtin-calloc -fno-builtin -mllvm -x86-speculative-load-hardening -fno-builtin-memcpy -fno-builtin-memset -ffreestanding -mrdrnd -Wno-missing-braces -Wno-parentheses -Wno-unknown-pragmas -Wno-conversion -Wno-unused-parameter -Wno-sign-compare -Wno-dangling-else -Wno-ignored-attributes -Wno-logical-op-parentheses -Wno-string-plus-int -Wno-typedef-redefinition -Wno-unneeded-internal-declaration -m64 -fPIE -nostdinc -fstack-protector-strong -fvisibility=hidden -fno-omit-frame-pointer -ffunction-sections -fdata-sections -ftls-model=local-exec /showIncludes -o libc\CMakeFiles\oelibc.dir\__\3rdparty\musl\musl\src\search\twalk.c.obj -c ..\..\3rdparty\musl\musl\src\search\twalk.c"
fatal error: error in backend: Undefined temporary symbol
[2811/4286] Building C object libc\CMakeFiles\oelibc.dir\__\3rdparty\musl\musl\src\stat\fstat.c.obj
[2812/4286] Building C object libc\CMakeFiles\oelibc.dir\__\3rdparty\musl\musl\src\stdio\asprintf.c.obj
[2813/4286] Building C object libc\CMakeFiles\oelibc.dir\__\3rdparty\musl\musl\src\stdio\dprintf.c.obj
[2814/4286] Building C object libc\CMakeFiles\oelibc.dir\__\3rdparty\musl\musl\src\stdio\clearerr.c.obj
[2815/4286] Building C object libc\CMakeFiles\oelibc.dir\__\3rdparty\musl\musl\src\stdio\fclose.c.obj
ninja: build stopped: subcommand failed.
script returned exit code 1`

Additionally Code Coverage is only compatible with clang-7 at this time.

**Comment by anakrish** [comment]
We have run into the second problem (twalk.c not compiling) before, maybe in RHEL.

**Comment by anakrish** [comment]
https://github.com/openenclave/openenclave/issues/2556

**Comment by BRMcLaren** [comment]
@anakrish reading past comments, I believe the solution is this? https://github.com/openenclave/openenclave-ci/pull/23/files

I will run it through another end to end, see if this solves it.

**Comment by BRMcLaren** [comment]
@anakrish This [fix](https://github.com/openenclave/openenclave/blob/master/libc/CMakeLists.txt#L869) was merged in as the original solution. I also passed in the -o0 flag in the above PR, and tested against that but the result seems the same: 

```
FAILED: libc/CMakeFiles/oelibc.dir/__/3rdparty/musl/musl/src/search/twalk.c.obj 

"C:/Program Files/Git/bin/bash.exe" "C:/Users/oeadmin/workspace/pipelines/Azure-Windows/scripts/clangw" "-DOE_API_VERSION=2 -DOE_BUILD_ENCLAVE -D_XOPEN_SOURCE=700 -I3rdparty\musl\musl\src\include -I3rdparty\musl\musl\src\internal -I3rdparty\musl\musl\arch\x86_64 -I..\..\include -Ioutput\include -Ioutput\include\openenclave\libc /DWIN32 /D_WINDOWS /wd4566 /wd4200 /MD /O2 /Ob2 /DNDEBUG   /WX /W3 -Wall -Werror -Wpointer-arith -Wconversion -Wextra -Wno-missing-field-initializers -fno-strict-aliasing -mxsave -fno-builtin-malloc -fno-builtin-calloc -fno-builtin -mllvm -x86-speculative-load-hardening -fno-builtin-memcpy -fno-builtin-memset -ffreestanding -mrdrnd -Wno-missing-braces -Wno-parentheses -Wno-unknown-pragmas -Wno-conversion -Wno-unused-parameter -Wno-sign-compare -Wno-dangling-else -Wno-ignored-attributes -Wno-logical-op-parentheses -Wno-string-plus-int -Wno-typedef-redefinition -Wno-unneeded-internal-declaration -m64 -fPIE -nostdinc -fstack-protector-strong -fvisibility=hidden -fno-omit-frame-pointer -ffunction-sections -fdata-sections -ftls-model=local-exec /showIncludes -o libc\CMakeFiles\oelibc.dir\__\3rdparty\musl\musl\src\search\twalk.c.obj -c ..\..\3rdparty\musl\musl\src\search\twalk.c"

fatal error: error in backend: Undefined temporary symbol
```

https://oe-jenkins-tf.westeurope.cloudapp.azure.com/blue/organizations/jenkins/pipelines%2FAzure-Windows/detail/Azure-Windows/277/pipeline/79

**Comment by anakrish** [comment]
@BRMcLaren -O0 flag is not being passed to twalk.c as seen from the log in issue description. It is likely because when compiling in Windows CMAKE_COMPILER_ID does not match clang (it is MSVC). We could just add the -O0 flag for twalk.c if we are compiling for win32.



cc: @manojrupireddy @mingweishih

**Comment by mingweishih** [comment]
It should be a bug as @anakrish described. And given that we cannot directly decide the version of clang in Windows, we agree on just adding -O0 flag to twalk.c if its on Windows.

**Comment by BRMcLaren** [comment]
Running validation: https://oe-jenkins-tf.westeurope.cloudapp.azure.com/job/CI-CD_Infrastructure/job/OpenEnclave-E2E-Testing/258/

@mingweishih is the expected result of the above fix to also resolve clang-8 failures on Linux running in the RelWithDebInfo configuration along with the code coverage fix?
