### ISSUE TITLE
Add Ubuntu 2004 support and drop 1604 support in the v0.14 OE release in  2021(currently targeted for March 2021)

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#3625]
Intel is adding support for Ubuntu 2004 and will be releasing packages for the same. OE SDK will release Ubuntu 2004 packages in V0.14 and drop Ubuntu 1604 support on the same release
- [x] update changelog to signal deprecation of Ubuntu 1604
- [x] send email to community
- [x] Add 2004 to CI
- [x] Drop 1604 from CI
- [x] Update docs to remove 1604 and add docs for 2004

**Comment by BRMcLaren** [comment]
@radhikaj Do we have an eta from Intel on the support of the 20.04 sgx packages?
