### ISSUE TITLE
can't use openssl EVP_Decrypt functions inside enclave

### ISSUE THREAD

**Issue by johnvenn** [openenclave/openenclave#3660]
Tried to use gcm_decrypt inside OE enclave as in :
https://wiki.openssl.org/index.php/EVP_Authenticated_Encryption_and_Decryption

compiled the code, there were errors:
FILE, va_list not identified. 

I checked the header files in corelibc, <stdarg.h> and <stdio.h>, those vars are renamed as OE_FILE and OE_VA_LIST

Is there any recommendation on how to use EVP decrypt/encrypt function inside enclave?

**Comment by mingweishih** [comment]
Typical enclave applications should not use corelibc unless you are developing libraries for SDK internal. Can you provide more information regarding your scenario?

**Comment by mingweishih** [comment]
Currently, the following OpenSSL test has been ran and succeeded in OE.

https://github.com/openssl/openssl/blob/ea7a58a60659d12d102ec78af4d6c3e589347150/test/evp_test.c

Can you also check if the APIs you want to use are part of this test?

**Comment by johnvenn** [comment]
thanks, mingwei.

The APIs I was trying to use is in the test cases evp_test.c. But I think evp_test.c is the code running outside enclave?

I was trying to use EVP_CIPHER_decrypt as the internal funtion in an OE SDK lib(protected code loader ).

**Comment by mingweishih** [comment]
> thanks, mingwei.
> 
> The APIs I was trying to use is in the test cases evp_test.c. But I think evp_test.c is the code running outside enclave?
> 
> I was trying to use EVP_CIPHER_decrypt as the internal funtion in an OE SDK lib(protected code loader ).

The test code is running inside the enclave and uses oelibc instead of corelibc. Is there a requirement that PCL does not use oelibc (i.e., musl c)?

**Comment by johnvenn** [comment]
> > thanks, mingwei.
> > The APIs I was trying to use is in the test cases evp_test.c. But I think evp_test.c is the code running outside enclave?
> > I was trying to use EVP_CIPHER_decrypt as the internal funtion in an OE SDK lib(protected code loader ).
> 
> The test code is running inside the enclave and uses oelibc instead of corelibc. Is there a requirement that PCL does not use oelibc (i.e., musl c)?

thanks a lot, mingwei. I didn't realize I need to try to use oelibc instead of corelibc. I will have a try .

**Comment by dthaler** [comment]
> I didn't realize I need to try to use oelibc instead of corelibc. I will have a try .

Yes that's a common confusion due to lack of documentation on this topic.
