### ISSUE TITLE
In-enclave quote/report verification uses untrusted time for collateral verification

### ISSUE THREAD

**Issue by flxflx** [openenclave/openenclave#3698]
Hi,
we came across the following while looking into enclave-to-enclave remote attestation.

`oe_verify_report_internal()` invokes `oe_verify_sgx_quote()` with `input_validation_time = NULL`:
https://github.com/openenclave/openenclave/blob/ab69ff71dede60317426d739e170289e32706994/enclave/sgx/report.c#L108-L112

This leads to `input_validation_time` being read from `sgx_endorsements`:

https://github.com/openenclave/openenclave/blob/e9646d5d0fb877581d9342b539d703be2704c520/common/sgx/quote.c#L515-L530

The time in the endorsements is read from the host:

https://github.com/openenclave/openenclave/blob/24239a6070c9fff79a3f137d4a04904470c37891/common/sgx/endorsements.c#L78

In consequence, as far as I can tell, the freshness of collaterals like `tcbInfo` is always checked against an untrusted timestamp coming from the host. An attacker could thus make an enclave accept a quote from a vulnerable machine by manipulating local time. 

It is not clear to me what a solution could look like. Maybe one could have a verifier plugin that uses a trusted online time source.

Thoughts?

**Comment by flxflx** [comment]
Just realized that the experimental `oe_verify_evidence()` supports setting a custom time via `policies`.

**Comment by yentsanglee** [comment]
The attester, who generates the quote, appends local time to endorsement output which is informational and unverified. The relying parties/verifiers do not need the endorsement input to verify evidence. If the verifier chooses to take endorsement input, all endorsements are exposed by claims after calling oe_verify_evidence() and decision can be made by the relying party whether to trust the sources or not.

If the verifier is running on a vulnerable machine whose local time is manipulated, I think the entire system should be treated untrusted.

**Comment by radhikaj** [comment]
Lets get inputs from @flxflx.

**Comment by radhikaj** [comment]
The verifier behavior and app requirements should be documented.

**Comment by flxflx** [comment]
Hi Radhikja and Yen :-)

Sorry, my initial post may wasn't very precise. In a nutshell, we have a project where we're doing enclave-to-enclave attestation. Thus we consider the local time of the verifier to be untrusted. As `oe_verify_report()` apparently always uses local time to check freshness one shouldn't use it for enclave-to-enclave attestation.

I agree that this is mostly a documentation issue. It's good to see that `oe_verify_evidence()` allows for a custom timestamp coming potentially from trusted sources (e.g., a remote time server). We'll proceed with `oe_verify_evidence()`.

Thanks!
