### ISSUE TITLE
App devs can debug a Windows app hosting an ELF enclave built with Open Enclave

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#37]
Requires #35.
Once we have a working OpenEnclave stack on Windows, we need to implement a custom debugging solution for it as enclaves will be ELF binaries hosted in a Windows PE process, and the existing Windows debuggers do not handle ELF symbol parsing, nor understand the stack stitching needed for the enclave stack.

This is currently being pursued with the [Windbg team](https://microsoft.visualstudio.com/OS/_workitems/edit/13705309) to add support in windbg for stack-stitched debugging with OE ELF enclaves.

- [ ] Windbg supports debugging ELF enclaves on Windows (External)
- [ ] #38 Document Windows debugging instructions

**Comment by radhikaj** [comment]
This is now complete.
