### ISSUE TITLE
Simplify the steps to set up OE SDK to run on non-ACC Machines

### ISSUE THREAD

**Issue by yentsanglee** [openenclave/openenclave#3705]
Steps to set up OE SDK on non-ACC machines are described [here](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/NonAccMachineSGXLinuxGettingStarted.md)

The request is to simplify the process by adding a script to make the experience more friendly and avoid human error.

Related issue - #3658

**Comment by radhikaj** [comment]
@BRMcLaren  is working on setting up containers for developer environment. Please sync with him to see if this can be accomplished in a similar manner.

**Comment by BRMcLaren** [comment]
@yentsanglee We are working on getting dev containers up and running, the experience would then be to grab the image from https://hub.docker.com/u/openenclave and run locally. These containers contain all the dependencies for developing and running the oesdk. 

Given this, would you still like a script or would this suffice?

**Comment by yentsanglee** [comment]
Script for this seems unnecessary. Closing the issue.
