### ISSUE TITLE
Error during install the nuget package from 0.12.0 release

### ISSUE THREAD

**Issue by lzha101** [openenclave/openenclave#3710]
Just have a try to install the nuget package from 0.12 release 
https://github.com/openenclave/openenclave/releases/download/v0.12.0/open-enclave.0.12.0.nupkg

with the command from [here](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Windows.md#download-and-install-the-open-enclave-sdk-nuget-package) and got below error message: 

>   File path: C:\Users\lzha101\Desktop\test\installer\open-enclave.0.12.0.nupkg'.
>   The file is not a valid nupkg. File path: C:\Users\lzha101\Desktop\test\installer\open-enclave.0.12.0.nupkg
>   End of Central Directory record could not be found.
> 

Also tried it in Visual Studio -> Nuget Package Manager, it also reports the package is not a valid nuget package.

**Comment by radhikaj** [comment]
@lzha101 there seems to have been an upload error and over the weekend I did another upload. Thanks for pointing this out and please try again and let us know. Thanks

**Comment by rs--** [comment]
Verified the new upload; @lzha101 please let us know if there are further issues, thanks!
