### ISSUE TITLE
Question about remote attestation

### ISSUE THREAD

**Issue by hyunsooda** [openenclave/openenclave#3720]
Hi,
Two questions were popped in my mind by struggling to try demonstrate remote attestation in multiple platforms.

1. In ACC, we do not need any dependencies such as PCCS server and API KEY required to query to IAS, which are necessary in non-ACC machine to demonstrate remote attestation. How it is correctly work in ACC without PCCS server and API KEY?

2. Is there a way to demonstrate remote attestation with Intel SGX Driver(i.e, `/dev/isgx`, not `/dev/sgx`)? It does not work for now. 

Thank you.

**Comment by radhikaj** [comment]
@yentsanglee will respond to first question and @MWShan will respond to the second one.

**Comment by yentsanglee** [comment]
> 1. In ACC, we do not need any dependencies such as PCCS server and API KEY required to query to IAS, which are necessary in non-ACC machine to demonstrate remote attestation. How it is correctly work in ACC without PCCS server and API KEY?

DCAP stands for Data Center Attestation Primitives which provides SGX attestation support targeted for data centers, cloud services providers and enterprises.

If you follow OE installation doc such as [this](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md), a DCAP component [az-dcap-client](https://github.com/microsoft/azure-dcap-client) is installed along with OE SDK. az-dcap-client retrieves information needed for remote attestation from Azure PCCS service. Azure PCCS service serves all VMs running in Azure. In other clouds or a stand-alone platforms, such PCCS service has to be specified or set up for remote attestation to work. The document [Configure OE SDK SGX on Linux in non-ACC Machines](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/NonAccMachineSGXLinuxGettingStarted.md) describes the steps needed to set up a local PCCS server which retrieves certificates and collateral from Intel PCCS server. API key is needed to access Intel PCCS server.

**Comment by hyunsooda** [comment]
Hi @yentsanglee ,
Is there a centralized server in ACC that can be delegated from az-dcap-client so that user does not need to setup the PCCS server and issue a new API KEY?

**Comment by yentsanglee** [comment]
@hyunsooda  Yes, Azure cloud has its own API KEY to access Intel server and caches all necessary information. `az-dcap-client` accesses the cache in Azure for users without key.

**Comment by MWShan** [comment]
The /dev/isgx driver, which must be used on systems which do not support flexible launch control, requires the use of legacy launch control.  Legacy launch control does not support the generation of quotes for ECDSA based attestation (used in DCAP); however, it does support EPID based quoting for remote attestation via EPID.

**Comment by hyunsooda** [comment]
Hi @MWShan,
Does OE provide APIs quote generation and verification based on EPID scheme?

**Comment by shnwc** [comment]
Yes, the `oe_get_evidence()` generates EPID evidence, as commented in header file [attestation/sgx/evidence.h](https://github.com/openenclave/openenclave/blob/master/include/openenclave/attestation/sgx/evidence.h), and described in design document [Attestation_API_Proposal.md](https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/Attestation_API_Proposal.md#summary).

Adding @jdbeaney, as this is related to issue #3658

**Comment by hyunsooda** [comment]
In [attestation sample](https://github.com/openenclave/openenclave/tree/master/samples/attestation), I simply changed the value of global variable `sgx_remote_uuid` from `OE_FORMAT_UUID_SGX_ECDSA` to `OE_FORMAT_UUID_SGX_EPID_UNLINKABLE`. but error occurred and says that the verifier's plugin seems not existed (line 31). Also, document says that there is no plan to implement for verification EPID evidence.
https://github.com/openenclave/openenclave/blob/05161c74addb73d2728f270631449e25228afcb0/docs/DesignDocs/Attestation_API_Proposal.md#proposed-v01x-implementation
> Currently there is no plan to implement verifier plugins for verification of EPID evidence. 

Can I generate only evidence, not for verify based on EPID? because IAS is the only one that can verify quote generated IVS. then, It means that I should make evidence using OE and implement the verification process personally?


  1 host/attestation_host sgxremote ./enclave_a/enclave_a.signed ./enclave_b/enclave_b.signed
  2 Enclave1: ***../common/crypto.cpp(80): mbedtls initialized.
  3 Enclave2: ***../common/crypto.cpp(80): mbedtls initialized.
  4 Enclave2: ***../common/dispatcher.cpp(80): get_enclave_format_settings
  5 Enclave2: ***../common/attestation.cpp(39): oe_verifier_get_format_settings failed
  6 Enclave2: ***../common/dispatcher.cpp(84): get_enclave_format_settings failed
  7 Enclave2: ***../common/dispatcher.cpp(106): get_enclave_format_settings failed.
  8 Enclave1: ***../common/crypto.cpp(94): mbedtls cleaned up.
  9 Enclave2: ***../common/crypto.cpp(94): mbedtls cleaned up.
 10 Host: Creating two enclaves
 11 Host: Enclave library ./enclave_a/enclave_a.signed
 12 2020-11-18T15:35:21+0900.991192Z [(H)INFO] tid(0x7fcb67744c00) | Processor supports AVX instructions [/source/host/sgx/linux/xstate.c:_is_xgetbv_supported:33]
 13 2020-11-18T15:35:21+0900.991327Z [(H)INFO] tid(0x7fcb67744c00) | Value of XFRM to be set in enclave is 7
 14  [/source/host/sgx/sgxload.c:_detect_xfrm:121]
 15 2020-11-18T15:35:22+0900.003630Z [(H)INFO] tid(0x7fcb67744c00) | Loading libsgx_enclave_common.so.1
 16  [/source/host/sgx/sgx_enclave_common_wrapper.c:_load_sgx_enclave_common_impl:110]
 17 2020-11-18T15:35:22+0900.003999Z [(H)INFO] tid(0x7fcb67744c00) | Loaded libsgx_enclave_common.so.1
 18  [/source/host/sgx/sgx_enclave_common_wrapper.c:_load_sgx_enclave_common_impl:126]
 19 Host: Enclave successfully created.
 20 Host: Enclave library ./enclave_b/enclave_b.signed
 21 2020-11-18T15:35:22+0900.238873Z [(H)INFO] tid(0x7fcb67744c00) | Processor supports AVX instructions [/source/host/sgx/linux/xstate.c:_is_xgetbv_supported:33]
 22 2020-11-18T15:35:22+0900.238881Z [(H)INFO] tid(0x7fcb67744c00) | Value of XFRM to be set in enclave is 7
 23  [/source/host/sgx/sgxload.c:_detect_xfrm:121]
 24 Host: Enclave successfully created.
 25 
 26 
 27 Host: ********** Attest enclave_a to enclave_b **********
 28 
 29 Host: Requesting enclave_b format settings
 30 2020-11-18T15:35:22+0900.624043Z [(E)INFO] tid(0x7fcb67744c00) | enclave_b.signed:got verifiers_length=4 plugins [/source/common/sgx/verifier.c:oe_verifier_initialize:904]
 31 2020-11-18T15:35:22+0900.624058Z [(E)ERROR] tid(0x7fcb67744c00) | enclave_b.signed::OE_NOT_FOUND [/source/common/attest_plugin.c:oe_verifier_get_format_settings:687]
 32 Host: get_format_settings failed. OE_OK
 33 Host: attestation failed with 1
 34 Host: Terminating enclaves
 35 2020-11-18T15:35:22+0900.624156Z [(E)INFO] tid(0x7fcb67744c00) | enclave_a.signed:attesters is NULL [/source/enclave/sgx/attester.c:oe_attester_shutdown:485]
 36 2020-11-18T15:35:22+0900.624164Z [(E)INFO] tid(0x7fcb67744c00) | enclave_a.signed:verifiers is NULL [/source/common/sgx/verifier.c:oe_verifier_shutdown:930]
 37 Host: Enclave successfully terminated.
 38 2020-11-18T15:35:22+0900.628425Z [(E)INFO] tid(0x7fcb67744c00) | enclave_b.signed:attesters is NULL [/source/enclave/sgx/attester.c:oe_attester_shutdown:485]
 39 2020-11-18T15:35:22+0900.628434Z [(E)INFO] tid(0x7fcb67744c00) | enclave_b.signed:free verifiers_length=4 plugins [/source/common/sgx/verifier.c:oe_verifier_shutdown:935]
 40 Host: Enclave successfully terminated.
 41 Host:  failed 
 42 Makefile:24: recipe for target 'runsgxremote' failed

**Comment by shnwc** [comment]
> Can I generate only evidence, not for verify based on EPID? because IAS is the only one that can verify quote generated IVS. then, It means that I should make evidence using OE and implement the verification process personally?

Verification of EPID evidence is not in the scope of the OE SDK. There is an [end-to-end sample project](https://software.intel.com/content/www/us/en/develop/articles/code-sample-intel-software-guard-extensions-remote-attestation-end-to-end-example.html) that shows how EPID-based remote attestation can be implemented. 

@hyunsooda I believe this also answers your question 2.

**Comment by hyunsooda** [comment]
Thanks for your kind response. All questions are resolved. Let me close this thread.
