### ISSUE TITLE
VS extension 0.12 in VS marketplace is broken

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#3725]
https://github.com/openenclave/openenclave/blob/master/devex/vsextension/vsix-release-process.md documents the release process, but there seems to have been some error or step missed when generating the package now deployed in the marketplace, which is broken.

Its extension.vsixmanifest correctly references open-enclave-cross.0.12.0.nupkg, but the package instead still contains open-enclave-cross.0.11.0-rc1-cbe4dedc-2.nupkg instead of open-enclave-cross.0.12.0.nupkg, so it can't find the nuget package embedded.

Step 2 in the release process document should have caused it to be updated, but that step either was missed or it failed somehow.  This is a regression from the 0.11 extension.

**Comment by CodeMonkeyLeet** [comment]
@radhikaj this is already being worked on by Rob, tagging you for awareness for backporting to v0.12 release.
