### ISSUE TITLE
Does OE intercept mmap()?

### ISSUE THREAD

**Issue by hyunsooda** [openenclave/openenclave#3728]
Hi, 
I was wondering that how OE intercepts `mmap()`, which is called inside of `malloc()`. Please see the example(ecall) below.
```
void enclave_malloc() {
    char* tmp_mem = (char*)malloc(sizeof(char)*32);
    char* tmp_mem2 = oe_host_malloc(sizeof(char)*32);
    char* tmp_str = "malloc data!";
    char* tmp_str2 = "oe_host_malloc data!";
    strncpy(tmp_mem, tmp_str, strlen(tmp_str));
    strncpy(tmp_mem2, tmp_str2, strlen(tmp_str2));
}
```
Two area were allocated, one is allocated using  `malloc()`, another one is `oe_host_malloc()`. In Heap memory, I could see the content of `tmp_mem2` ("oe_host_malloc data!"), but the content of `tmp_mem` ("malloc data!") was not visible.

The function [oe_host_malloc](https://github.com/openenclave/openenclave/blob/36c0303cf92ff206f270ac89d7b3cd721d83fa76/host/ocalls/ocalls.c#L9) just calls standard `malloc()`, therefore its content can be seen in Heap, but the behavior of `malloc()` is hidden detail to me for now. Where can I check the intercept mechanism? (high-level explanation or code).

Thank you

**Comment by anakrish** [comment]
Within an enclave, `malloc` allocates objects in enclave memory whereas `oe_host_malloc` allocates objects in host memory.

`malloc` is implemented via [pluggable allocators](https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/PluggableAllocators.md). OE currently allows `dlmalloc` or `snmalloc` to be used as the allocators.

These allocators may not themselves use `mmap` since they are developed or tweaked to work within enclaves.

To understand the allocation process, you could put a breakpoint in `oe_malloc` 
https://github.com/openenclave/openenclave/blob/79860b766a3ba4f07be8e136e32e10ac73c56f5b/enclave/core/malloc.c#L23

**Comment by CodeMonkeyLeet** [comment]
Leaving this as untriaged while we wait to see if this has addressed @hyunsooda's question.

**Comment by hyunsooda** [comment]
Hi @anakrish, thanks for your kind response.
I forgot the compile option (`-nostdlib`) and `oelibc` library has own `malloc` function that calls `oe_malloc()` which also calls `dlamlloc()`.

1. Where can I see the code that allocates enclave pages by calling IOCTLs to sgx driver? I checked `3rdparty/dlmalloc` but it seems not actually related to enclave page allocation.

2. Can you explain differentiation between common syscalls (like `malloc()`, `fopen()`, etc) and OE host functions which starting prefix with `oe_host`? In case of this issue, `malloc()` allocates EPC memory, but `oe_host_malloc` allocates host memory. Is there a document that describes case by case differentiation between origin syscall and `oe_syscall*`?

Thank you

**Comment by anakrish** [comment]
> I forgot the compile option (`-nostdlib`) and `oelibc` library has own `malloc` function that calls `oe_malloc()` which also calls `dlmalloc()`.

If you are using Makefile based workflow instead of cmake, you could use pkgconfig to make sure that the correct compiler flags are used for compiling/building enclaves. The Makefiles of the samples have examples:
https://github.com/openenclave/openenclave/blob/8ea5970bc93d039eed5a5ecdd2c7bc1e0759690f/samples/file-encryptor/enclave/Makefile#L6-L7


> 
>     1. Where can I see the code that allocates enclave pages by calling IOCTLs to sgx driver? I checked `3rdparty/dlmalloc` but it seems not actually related to enclave page allocation.
> 

OE SDK currently supports only SGX1 and the direct interactions with the SGX drivers happens only during enclave creation time.
Enclave memory is allocated by calling the `enclave_create` function in libsgx_enclave_common library.
https://github.com/openenclave/openenclave/blob/0d1a1af71a43d5e4b0a5b4f115426d8f75788df7/host/sgx/sgx_enclave_common_wrapper.c#L161



>
>     2. Can you explain differentiation between common syscalls (like `malloc()`, `fopen()`, etc) and OE host functions which starting prefix with `oe_host`? In case of this issue, `malloc()` allocates EPC memory, but `oe_host_malloc` allocates host memory. Is there a document that describes case by case differentiation between origin syscall and `oe_syscall*`?

The system calls are implemented within the enclave whenever possible and the rest are forwarded to the host.
Memory allocation happens entirely within the enclave using the enclave heap, whereas fopen would make an ocall to open a file on the host. The following document By @mingweishih lists each C library call and the system call it can make:
https://github.com/openenclave/openenclave/blob/master/docs/SystemEdls.md

Can you let us know what you are trying to implement? That way we could help you better.

**Comment by hyunsooda** [comment]
First of all, I didn't well deliver my mean, that is the fact that `oelibc` has own malloc function that calls `oe_malloc()`. Also, I have the flags you provided.

Anyway, I'd like to clear my questions in this comment again:
1. The function `malloc()` in enclave retrieves pre-allocated memory(`VALID` bit is zero, which means, this page is not used currently) in EPC. I'd like to see that code. it is just studying purpose how OE address this.

2. Actually, my question was only one, but an additional one is just popped from your last comment. 

> The system calls are implemented within the enclave whenever possible and the rest are forwarded to the host.

Can I assume that the [functions listed](https://github.com/openenclave/openenclave/blob/master/docs/SystemEdls.md) have own implementation without the support of OS if the column of `Dependent syscall` is not system call of Linux? If this is yes, It seems that there is no alternative system call support in OE currently.

**Comment by mingweishih** [comment]
> First of all, I didn't well deliver my mean, that is the fact that `oelibc` has own malloc function that calls `oe_malloc()`. Also, I have the flags you provided.
> 

Both `oe_malloc` and `malloc` on the enclave side uses the same implementation of the heap allocator (as @anakrish mentioned, we provide `dlmalloc` or `snmalloc` as a link-time choice).

> Anyway, I'd like to clear my questions in this comment again:
> 
> 1. The function `malloc()` in enclave retrieves pre-allocated memory(`VALID` bit is zero, which means, the page is not used currently) in EPC. I'd like to see that code. it is just studying purpose how OE address this.

I guess you're referring to how the heap allocator manages/uses the pre-allocated EPC memory that is configured at the build time. Take dlmalloc for example, there is an initialization function that set the address range of the heap:

https://github.com/openenclave/openenclave/blob/8ea5970bc93d039eed5a5ecdd2c7bc1e0759690f/3rdparty/dlmalloc/allocator.c#L68

> 2. Actually, my question was only one, but an additional one is just popped from your last comment.
> 
> > The system calls are implemented within the enclave whenever possible and the rest are forwarded to the host.
> 
> Can I assume that the [functions listed](https://github.com/openenclave/openenclave/blob/master/docs/SystemEdls.md) have own implementation without the support of OS if the column of `Dependent syscall` is not system call of Linux? If this is yes, It seems that there is no alternative system call support in OE currently.

No, OE does not have own implementation of syscalls but provide simply a layer/wrapper that depends on the host (i.e., can be either Linux or Windows). However, we do allow user to write implement hooks that override the syscall implementation, see the following example:

https://github.com/openenclave/openenclave/blob/8ea5970bc93d039eed5a5ecdd2c7bc1e0759690f/tests/mbed/enc/enc.c#L175

**Comment by hyunsooda** [comment]
Hi @mingweishih, thanks for your kind response. My second question is resolved.

> I guess you're referring to how the heap allocator manages/uses the pre-allocated EPC memory that is configured at the build time. Take dlmalloc for example, there is an initialization function that set the address range of the heap:

Yes, your guess is right. What is the exact definition of Heap in your context? I assume that you didn't say about host's heap.
I'm very confusing now.  SGXv1 does not support dynamic allocation, I noticed that most of sgx framework initializes EPC memory to max size(128MB or 256MB) at start up so that make use of page scheduling for best performance even if those areas are not used. I specified that I'd like to check the code that allocates into EPC memory, but `3rdpary/dlmalloc` seems not include this part.

**Comment by mingweishih** [comment]
> Hi @mingweishih, Thanks for your kind response. My second question is resolved.
> 
> > I guess you're referring to how the heap allocator manages/uses the pre-allocated EPC memory that is configured at the build time. Take dlmalloc for example, there is an initialization function that set the address range of the heap:
> 
> Yes, your guess is right. What is the exact definition of Heap in your context? I assume that you didn't say about host's heap.

malloc/oe_malloc in the enclave uses its own heap (EPC memory). Only the `oe_host_malloc` (which does an OCall and eventually invoke the malloc on the host) uses the heap on the host.

> I'm confusing now. SGXv1 does not support dynamic allocation, I noticed that most of sgx framework initializes EPC memory to max size(128MB or 256MB) at start up so that make use of physical memory for best performance even if those areas are not used. I specified that I'd like to check the code that allocates into EPC memory, but `3rdpary/dlmalloc` seems not include this part.

In OE, the heap size of an enclave is specified via a configuration file:
https://github.com/openenclave/openenclave/blob/8ea5970bc93d039eed5a5ecdd2c7bc1e0759690f/samples/helloworld/enclave/helloworld.conf#L6
During the enclave initialization, the given size of EPC pages will be allocated.
`oe_allocator_init` I mentioned earlier simply set that memory range as the heap, which is independent from host's heap.

If you're talking about how the host allocates the EPC pages, please refer to code in 
 https://github.com/openenclave/openenclave/blob/master/host/sgx/sgxload.c#L308.
In general, the host will call into Intel's SGX driver to allocate the EPC pages based on the configuration file.

**Comment by hyunsooda** [comment]
If I understand your comment correctly:
- The Heap, you said, is the pre-allocated pages by configuration file at initialization phase of enclave.
- The memory allocation in enclave dynamically is achived by picking pre-allocated memory, which is performed in `dlmalloc()`.
- The function `oe_allocator_init` is called at initialization phase of enclave to set range of sgx heap specficied in confugraiton file.
- If we call `malloc()` in enclave, then `dlmalloc()` will be called and pick the memory inside of range which was set right above step.

**Comment by mingweishih** [comment]
> If I understand your comment correctly:
> 
> * The Heap, you said, is the pre-allocated pages by configuration file at initialization phase of enclave.
> * The dynamic memory allocation in enclave is achived by picking pre-allocated memory, which is performed in `dlmalloc()`.
> * The function `oe_allocator_init` is called at initialization phase of enclave to set range of sgx heap specficied in confugraiton file.
> * If we call `malloc()` in enclave, then `dlmalloc()` will be called and pick the memory inside of range which was set right above step.

That's correct!

**Comment by hyunsooda** [comment]
Thank you for your kind response. @mingweishih  @anakrish. Let me close this thread.

**Comment by mingweishih** [comment]
> Thank you for your kind response. @mingweishih @anakrish. Let me close this thread.

You're welcome. Fee free to let us know if there is any further question.
