### ISSUE TITLE
Visual Studio 2019 compilation problems

### ISSUE THREAD

**Issue by wintersteiger** [openenclave/openenclave#3734]
After upgrading to the latest VS2019 and Windows SDK (as well as pulling OE master), I now get lots of instances of this:

```
[39/2560] Building C object tests\syscall\tool\CMakeFiles\rmdir.dir\rmdir_win32.c.obj
FAILED: tests/syscall/tool/CMakeFiles/rmdir.dir/rmdir_win32.c.obj
C:\PROGRA~2\MICROS~1\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS /wd4566 /wd4200 /MDd /Zi /Ob0 /Od /RTC1 /WX /W3 -std:c11 /showIncludes /Fotests\syscall\tool\CMakeFiles\rmdir.dir\rmdir_win32.c.obj /Fdtests\syscall\tool\CMakeFiles\rmdir.dir\rmdir.pdb /FS -c ..\tests\syscall\tool\rmdir_win32.c
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9461): error C2220: the following warning is treated as an error
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9461): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9461): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
```

The warning is correct in that the offending macro does indeed contain a `defined`.

I'm never sure that the various bits of my Windows setup are in sync. Could someone verify that they suffer from the same problem? If so, I suppose we should disable that warning or figure out the right `#defines`  and/or compiler switches to add.

**Comment by radhikaj** [comment]
We should test in CI with the latest VS2019 version.

**Comment by radhikaj** [comment]
Find the VS version that corresponds to msvc version 14.28.29333.
@wintersteiger can you please tell us the version of VS you have installed?

**Comment by dthaler** [comment]
VS 16.8.2 has MSVC 14.28.29333

**Comment by wintersteiger** [comment]
That's right, it's VS 16.8.2 with 

```
...>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29334 for x64
```

and Windows SDK 10.0.19041.0.

I just checked and I still get those errors on a clean build of master with 

```
cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug -DNUGET_PACKAGE_PATH=... -DCMAKE_INSTALL_PREFIX:PATH=... -DCPACK_GENERATOR=NuGet
ninja -j8
```

**Comment by Mojicode** [comment]
I have the same issue, how to fix this problem?

**Comment by Mojicode** [comment]
> I have the same issue, how to fix this problem?

I add [/wd5105] flag for CMAKE_CXX_FLAGS and CMAKE_C_FLAGS to avoid this warning, for me , it works.
