### ISSUE TITLE
App dev on Windows has a documented developer tooling story for Open Enclave 

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#377]
The doc/GettingStarted.Windows.md documents Windows support as an experimental feature for Open Enclave today. This document needs to be updated with appropriate guidelines and tooling recommendations to walk through building an app on Windows. 

This experience is currently documented around getting started instructions for using CMake with Visual Studio 2017 and WSL remoting to build and test a Windows host app with enclave binaries.

This is related to producing CMake samples tracked in #378.
This has a dependency on the Windows debugging story tracked in #37.

**Comment by radhikaj** [comment]
Fixed in https://github.com/openenclave/openenclave/pull/2232
