### ISSUE TITLE
App devs can refer to samples for building converged Windows/Linux enclave apps 

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#378]
To support developers who want to run converged enclave binaries on Windows & Linux, we would need to add CMake samples that illustrate how to configure a project that can be built purely on Linux, or on Windows for the host with VS2017 remoting to Linux for building the ELF enclaves. 

Related to Windows documentation for developer experience, #377

Requires #1194

**Comment by radhikaj** [comment]
Fixed in https://github.com/openenclave/openenclave/commit/3f2d0ae9eced9907eb04576416689b8bb5aeb363#diff-63eb31af3d294687e7be93ca2425166c
