### ISSUE TITLE
Remote attestation across Azure Cloud and IBM Cloud

### ISSUE THREAD

**Issue by sword03** [openenclave/openenclave#3788]
Supposed I deploy two enclaves, one on Azure and the other on IBM cloud,  developed with openenclave sdk. 

Can these two enclave do remote attestation with each other?

Now I found it as follows：

![image](https://user-images.githubusercontent.com/13059372/102750719-44eb5080-43a1-11eb-8007-be3c88cc7152.png)

**Comment by yentsanglee** [comment]
A general implementation for using Intel DCAP outside Azure can be configured if you follow [this](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/NonAccMachineSGXLinuxGettingStarted.md) document.

**Comment by yentsanglee** [comment]
@sword03 Does the above comment answer your question?

**Comment by radhikaj** [comment]
Hi @sword03, does the above comment answer your question? I am closing this issue for now. Please reopen if your question is not answered.
