### ISSUE TITLE
New Repository for Open Enclave Security Works (CodeQL and Fuzzing)

### ISSUE THREAD

**Issue by mrragava** [openenclave/openenclave#3791]
We need a new repository for Open Enclave specific security automation projects (CodeQL static analysis, Fuzzing and binary analysis) which will be used in SAST/DAST pipelines.
It was recommended to host as a separate repo in a PR review (https://github.com/openenclave/openenclave/pull/3731#discussion_534616204)

Can we name the repo as (https://github.com/openenclave/openencalve-security) ?

1. Issues can be tracked in openencalve-security repo.
2. SIG-CI could oversee the relevant aspects of this repo.
3. The individuals responsible for maintaining this repo will be depicted by it's owners list. (ACC-Security Team)

**Comment by dthaler** [comment]
"encalve" should be "enclave" in the repo name

**Comment by radhikaj** [comment]
Some follow up questions:
Is this ongoing work or would it be one time contribution?
Are there multiple owners for the repo? Please state the owners. We recommend creating SIG-Security, so SIG-Security has the ability to approve PRs.
Can you please propose 3 members who would review PRs and respond to issues?

**Comment by mrragava** [comment]
1. This repo will host OE fuzzing projects, supported tools and additional CodeQL queries to accommodate new changes in OE codebase. It will be an ongoing work.
2. Owners: swamymsft (Swamy), douglasmaciver (Douglas) and mrragava (Ragavan)
3. Reviewers: Simon, Anand, swamymsft (Swamy), douglasmaciver (Douglas) and mrragava (Ragavan)

**Comment by radhikaj** [comment]
Created repo. Closing issue.
