### ISSUE TITLE
Could host-verify process also be used from kernel-mode?

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#3804]
Potential scenario: want to make an enclave be similar to a kernel trusted module, so that even a local admin can’t tamper with it.

Making making ECALLs/OCALLs would be ok to do from an unprivileged user mode host app/library if needed to act as a proxy from the kernel, if we don’t support ECALLs from kernel-mode (do we?).

However an end-to-end secure channel from the kernel to the enclave would be needed for communication, where the kernel would need to verify an enclave’s evidence, much like host-verify works.

Question is whether there are any blockers today to making the host side of host-verify work in kernel-mode, or whether there are hardware limitations or gaps that would need to be filled before this could be enabled.

**Comment by shnwc** [comment]
> Making making ECALLs/OCALLs would be ok to do from an unprivileged user mode host app/library if needed to act as a proxy from the kernel, if we don’t support ECALLs from kernel-mode (do we?).

ECALLs can only be invoked from user mode.

@MWShan @haitaohuang feel free to comment.

**Comment by CodeMonkeyLeet** [comment]
From the [SIG-attestation](https://hackmd.io/Xj6GpDSKSwuz5cZgQ0yg1A#20-January-2021-1000-AM-PST) meeting, closing this question out with the answers provided:

* The host-verify library itself is mostly just crypto code that could be run inside the enclave. However, it was not designed to and may require at least the following changes:
   * Remove any dependencies that will not run in kernel
   * Adapt choice of crypto to depend on kernel crypto module 
* The host-verify library itself is designed to only do remote attestation and has a dependency on the DCAP libraries for SGX.
   * Kernel can launch a user mode process to run the necessary enclaves (which are user-mode only) for this.
   * Similarly, kernel would have to fetch and cache its own PCK certs for the verification, which would be its own custom implementation for plugin and service. 
   * If local attestation is needed, the same model can be extended to run a custom enclave to handle the local enclave validation.
      * This would be new custom code since host-verify does not support local attestation today.
      * Alternatively, remote attestation evidence could be checked to see if it originates from the same device by verifying the signing key in the quote against the key used by the kernel trusted instance.

**Comment by dthaler** [comment]
Adding my notes from the SIG-attestation meeting:
* If the kernel does not care whether the enclave is local or remote, then remote attestation can be done similar to how host-verify works. (see Simon's notes)
* If the kernel does need to know that the enclave is local, there are a couple of ways that could work:
    A) Local attestation from an enclave that the kernel knows is on the local machine (e.g., hosted in a process launched by the kernel)
    B) Remote attestation but look at the Platform Provisioning Identifier (PPID) which is present in the evidence and verify it matches the PPID of the local platform
