### ISSUE TITLE
oe_get_attestation_certificate_with_evidence is insufficient for security

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#3820]
Reported by Alan Jowett:

> The evidence needs to contain both the public key of the cert as well as the nonce supplied by the verifier.
> 
> Without the nonce, we lack liveness.
> Without the public key, we lack a binding to the TLS channel.
> 
> The problem with the oe_get_attestation_certificate_with_evidence is that it doesn’t have an option to pass in a provided nonce.

Indeed this requirement is called out in https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/AttestationApiRequirements.md and does not appear to be met by `oe_get_attestation_certificate_with_evidence()`, unlike `oe_get_evidence()` which has a custom claims buffer as input.

Can we mark `oe_get_attestation_certificate_with_evidence()` as obsolete?

**Comment by yentsanglee** [comment]
`oe_get_attestation_certificate_with_evidence()` does not include the input parameter to pass in nonce to `oe_get_evidence(..., optional_parameters, ...)`.

**Comment by mingweishih** [comment]
Will discuss this issue on the sig-attestation meeting.

**Comment by shnwc** [comment]
@dthaler @yentsanglee @ryanhsu19 an related question: should the function `oe_verify_attestation_certificate_with_evidence()` take the same optional input parameters as `oe_verify_evidence()`, i.e. endorsements and policies?

**Comment by dthaler** [comment]
> @dthaler @yentsanglee @ryanhsu19 an related question: should the function `oe_verify_attestation_certificate_with_evidence()` take the same optional input parameters as `oe_verify_evidence()`, i.e. endorsements and policies?

In my opinion, yes.
