### ISSUE TITLE
unstrusted code in shared library + oe_terminate_enclave on instance created 

### ISSUE THREAD

**Issue by flothia** [openenclave/openenclave#3823]
Hi all,

To facilitate me the handling of untrusted code generated by oeedger8r, i compiled it in a shared library, and then load it in a main code using dlopen("ulib_name.so", RTLD_NOW|RTLD_GLOBAL).
The ecalls performed on it works fine, but i am not able to call _oe_terminate_enclave_ on the instance of the enclave created :
 -> segmentation fault : **[(H)ERROR] tid(0x7ffff5253700) | enclave=0xf000a020
 [/source/openenclave/host/sg//enclavemanager.c:oe_remove_enclave_instance:140]**

I suspect a problem linked to the shared namespace but i am not able to resolve it.
Do you have an idea to resolve it ?

Thanks in advance.

**Comment by anakrish** [comment]
Can you run objdump on both the main program as well as the shared librard report back? `c:oe_remove_enclave_instance` removes the enclave from a global `oe_enclave_list_head`. We first want to make sure that the same list instance is accessed by both the main executable and the shared library.


```bash
objdump -t echo_host | grep oe_enclave_list_head
00000000004ace68 l     O .bss   0000000000000008              oe_enclave_list_head
```

**Comment by flothia** [comment]
As result of these commands :
`objdump -t main_prog | grep oe_enclave_list_head
0000000000715170 l     O .bss	0000000000000008              oe_enclave_list_head`
`objdump -t ulib.so | grep oe_enclave_list_head -> nothing`

**Comment by anakrish** [comment]
That is good.

Can you double check that the same enclave is not being terminated twice?
Looking at the code, one scenario where line 140 can get hit and print that message would be if the enclave does not exist in the global list.
https://github.com/openenclave/openenclave/blob/57c224925df6df7e65bfdd81dd8cd78fc06c8be6/host/sgx/enclavemanager.c#L99

**Comment by flothia** [comment]
@anakrish 
My bad on the previous result of command (i checked the wrong shared library).
Finally, the result is :
objdump -t main_prog | grep oe_enclave_list_head 
0000000000715170 l O .bss 0000000000000008 oe_enclave_list_head

objdump -t lib_untrusted.so | grep oe_enclave_list_head 
00000000002757c8 l     O .bss	0000000000000008              oe_enclave_list_head

So, for what you mentioned above, the main instance and the shared library doesn't access the same list instance.

**Comment by anakrish** [comment]
Ok. That explains the behavior.

Are you building the SDK from source? If so, can remove `static` and add `OE_EXPORT` to the variables here:
https://github.com/openenclave/openenclave/blob/8f6691ef4927477f17ea7f338c57ab561fb7ffe5/host/sgx/enclavemanager.c#L10-L11

**Comment by flothia** [comment]
No, i don't build the SDK from source.
Is there an alternative to the building from source ?

**Comment by anakrish** [comment]
Let me think about if there is an easy solution for this.

**Comment by anakrish** [comment]
You could remove `liboehost.a` as a linker dependency when building `lib_untrusted.so`. 
The following might also need to be done:
- If you get compile errors about missing headers, you'd have to manually add the path to the headers to cmake/make
- Allow building with undefined symbols. That way `oe_remove_enclave_instance` can be undefined in `lib_unstrused.so`, and it would get resolved to the definition in `main_prog`.

**Comment by mingweishih** [comment]
@flothia do you have any follow-up on this issue?

**Comment by flothia** [comment]
The solution of @anakrish worked perfectly !
Thanks.
