### ISSUE TITLE
Document how to use inproc attestation

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#3843]
Open enclave SDK is moving to use out of proc attestation by default with this PR: https://github.com/openenclave/openenclave/pull/3806

We need to document how developers can use in proc attestation now and after the DCAP driver is available in the kernel.

**Comment by yentsanglee** [comment]
Also if quote gen failure is from invalid configuration such as missing AESM libraries, clearly log error and possible solutions and return unique error.
