### ISSUE TITLE
Question about evidence 

### ISSUE THREAD

**Issue by hyunsooda** [openenclave/openenclave#3860]
In [attestation example](https://github.com/openenclave/openenclave/tree/master/samples/attestation),

> An important feature of oe_get_evidence() is that you can pass in application specific data as the custom_claims_buffer parameter to be signed into the evidence. This is limited to 64 bytes in SGX. As illustrated in the sample, you sign arbitrarily large data into the evidence by first hashing it and then passing it to the oe_get_evidence() method.

1-1. I passed custom claim buffer over 64byte, and it works. I tried to find a macro associated with custom claim buffer length, but it seems not to exists.
1-2. Whenever I called ```oe_get_evidence()```, the ```setting_size``` is always zero. so I'm currently passing just NULL if the settings_size is zero. It works. Why is it always zero? when is not zero?
1-3.

> In this sample, the enclave signs the hash of an ephemeral public key into its evidence, which the challenger can then use to encrypt a response to it

The claim is the hash of the verifier's public key in this example. We got only the hash of the public key, not the public key. How we encrypt the message what we want to send to the intended user in the future?

1-4.

> At this point, the challenger knows that the evidence originated from an enclave running in a TEE, and that the information in the evidence can be trusted.

Challenger should be replaced by verifier?

1-5. What endorsement buffer stands for? Is there a use case?

2-1. Does Openssl libraries(```-loecryptoopenssl -lopensslssl -lopensslcrypto -loelibc -loesyscall -loecore```) dedicated for Openenclave perform entirely in enclave if the functions doesn't involve filesystem like ```BIO_new_file()```? 

Thank you

**Comment by yentsanglee** [comment]
1-1
API definition
oe_result_t oe_get_evidence(
    const oe_uuid_t* format_id,
    uint32_t flags,
    const void* custom_claims_buffer,
    size_t custom_claims_buffer_size,
    const void* optional_parameters,
    size_t optional_parameters_size,
    uint8_t** evidence_buffer,
    size_t* evidence_buffer_size,
    uint8_t** endorsements_buffer,
    size_t* endorsements_buffer_size);

The 3rd parameter is for custom claim and the 4th one is for custom claim size. What is your scenario?

1-2
The `setting_size` is for verifier of the format to pass in challenge to be embedded in the evidence. It's typically from calling oe_verifier_get_format_settings() on the verifier's side. For SGX ECDSA format, it's always 0. For SGX local format, it is verifier's target info. It's up of the design of the evidence format. See “[Semantics of Custom Claims and Optional Parameters](https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/NotesOnAttestationAPI.md#semantics-of-custom-claims-and-optional-parameters)” section and attestation sample.

1-3
It's easier to include public key in the evidence. That way after evidence is verified, messages can be encrypted. If only the hash is included in the evidence and the public key was sent separately, make sure you verify the public key with the hash.

1-4
Challenger in this context is a relying party. In some cases, verifier and relying party can be one entity. Please refer to  [Remote Attestation Procedure Architecture](https://tools.ietf.org/html/draft-ietf-rats-architecture-01).

1-5
Endorsement is supporting material for evidence attestation. Please refer to Remote Attestation Procedure Architecture mention above.

**Comment by yentsanglee** [comment]
@mingweishih or @anakrish do you have answer for question 2-1?

**Comment by hyunsooda** [comment]
Hi @yentsanglee, thanks for your answer.

The question numbers omitted are solved.

1-1. 
> An important feature of oe_get_evidence() is that you can pass in application specific data as the custom_claims_buffer parameter to be signed into the evidence. This is limited to 64 bytes in SGX. As illustrated in the sample, you sign arbitrarily large data into the evidence by first hashing it and then passing it to the oe_get_evidence() method.

The 4th parameter is the size of the 3rd parameter and it has a limited size of 64bytes as specified above, but I passed 64 bytes over and it works. This is a discrepancy in the documentation. I also tried to find a constant macro of claim buffer's maximum length but I didn't find it.

1-3. Yes, we can include public key in evidence in **custom claim buffer** and I also tested this method and works but, its behavior is also the discrepancy in the documentation since custom claim buffer can be 64 bytes at most as raised questions 1-1. 

1-2. In perspective of RA, Can custom claim buffer be used as a challenge by equivalent security semantic instead of ```format_setting``` when the verifier does not have CPU enabled-SGX?

Additional 1. The term of TEE agnostic appears in many documents in many times. Can you unpack what this term means?

**Comment by dthaler** [comment]
> 1-4
> Challenger in this context is a relying party. In some cases, verifier and relying party can be one entity. Please refer to [Remote Attestation Procedure Architecture](https://tools.ietf.org/html/draft-ietf-rats-architecture-01).

That is incorrect, challenger should indeed be replaced by verifier.   Evidence is always appraised by a verifier, never a relying party.  It is true that verifier and RP can be one entity, but even in that case evidence is appraised by the verifier part, as explained in the RATS architecture linked above.

**Comment by radhikaj** [comment]
Add links to RATS arch docs and update docs.

**Comment by dthaler** [comment]
> Additional 1. The term of TEE agnostic appears in many documents in many times. Can you unpack what this term means?

It means TEE-vendor agnostic.  It means the point is independent of which TEE is in place, whether SGX or OP-TEE or whatever else.

**Comment by mingweishih** [comment]
> 2-1. Does Openssl libraries(`-loecryptoopenssl -lopensslssl -lopensslcrypto -loelibc -loesyscall -loecore`) dedicated for Openenclave perform entirely in enclave if the functions doesn't involve filesystem like `BIO_new_file()`?
> 

The OpenSSL libraries shipped by OE do run entirely inside the enclave. We explicitly block some fs-related APIs for security reasons (please refer to https://github.com/openenclave/openenclave/blob/master/docs/OpenSSLSupport.md#openssl-apismacros).

**Comment by yentsanglee** [comment]
> Hi @yentsanglee, thanks for your answer.
> 
> The question numbers omitted are solved.
> 
> 1-1.
> 
> > An important feature of oe_get_evidence() is that you can pass in application specific data as the custom_claims_buffer parameter to be signed into the evidence. This is limited to 64 bytes in SGX. As illustrated in the sample, you sign arbitrarily large data into the evidence by first hashing it and then passing it to the oe_get_evidence() method.
> 
> The 4th parameter is the size of the 3rd parameter and it has a limited size of 64bytes as specified above, but I passed 64 bytes over and it works. This is a discrepancy in the documentation. I also tried to find a constant macro of claim buffer's maximum length but I didn't find it.
> 
> 1-3. Yes, we can include public key in evidence in **custom claim buffer** and I also tested this method and works but, its behavior is also the discrepancy in the documentation since custom claim buffer can be 64 bytes at most as raised questions 1-1.
> 
> 1-2. In perspective of RA, Can custom claim buffer be used as a challenge by equivalent security semantic instead of `format_setting` when the verifier does not have CPU enabled-SGX?
> 
> Additional 1. The term of TEE agnostic appears in many documents in many times. Can you unpack what this term means?

The 64 byte limitation only applies to evidence format OE_FORMAT_UUID_LEGACY_REPORT_REMOTE and  OE_FORMAT_UUID_RAW_SGX_QUOTE_ECDSA. We will clarify this in the documentation.

Yes, customer claim buffer can be used as challenge. Verifier does no have to run in SGX-enabled hardware.

**Comment by hyunsooda** [comment]
Thank you @yentsanglee ! let me close
