### ISSUE TITLE
OpenSSL headers in OE package can break apps

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#3868]
Since openssl was not supported in earlier versions, applications that did the work themselves to use openssl within their application can break with OE v0.14 since the headers appear in the SDK and are thus in the path even when OE is using mbedtls.  That is, if the app uses one openssl version and the OE openssl package is a different version, the headers won't match.

This is particularly an issue with the VS extension which forces the OE path to be before any app-supplied include paths.

One possible fix might be to fix the VS extension to put the OE path at the end (instead of the beginning) of the include search path, so an app can easily override it.  Another possible approach would be to put the openssl headers somewhere you have to opt-in to get via a different path.

**Comment by radhikaj** [comment]
The same problem exists for mbedtls.
