### ISSUE TITLE
Is there a way to allow the enclave to terminate itself after finishing computation?

### ISSUE THREAD

**Issue by JoFrost** [openenclave/openenclave#3883]
Hey there, 

I was wondering if there is any way for the enclave to terminate itself, but without using `oe_abort` from the enclave? 

I am doing some calculations on my enclave, but I would like to make sure the enclave is erased after calculation is over, and I would like the enclave to call it and not the host to reduce the chance of the host keeping the enclave around.

I have tried using `oe_abort`, but it seems to exit without giving to the host the final result which does not fit our use case as we need to yield a final result to the host, then make the enclave inaccessible, or even delete it.

Is there an elegant way to allow the enclave to return a value, and have the same effect as oe_abort, which is preventing the host from making any more call to the enclave (pretty much like `terminate_enclave` but done from the enclave)?

**Comment by radhikaj** [comment]
@JoFrost 
Is this a multi threaded scenario?
Can you please give us more details around your scenario?

**Comment by fchinchilla** [comment]
Hi.

After completing the call inside the enclave, control returns to the untrusted application. At this point you would like to automatically destroy the enclave - is this correct?

**Comment by JoFrost** [comment]
In our scenario, the enclave provides some computation on a client's data. It is not multi threaded. At the end of the analysis of the data by the enclave, we wish to return the value to the host, which will forward it to the client, but at the same time make sure that the enclave is no longer callable to reduce the exposure of the secrets used by the enclave.

In our head, we would like the enclave to return the result to the host after the final computation, and self lock itself. We do not want to rely on the host to remove the enclave, but we would prefer to allow the enclave to block itself once it has finished computing the value on the client’s data.

We could find some dirty ways to do it, such as having a variable `is_locked` that starts as false, and once computation is done we set it to true, and if true we simply exit every. This is not elegant and could also be a source of errors. 
So we were just wondering if there is an elegant way to allow an enclave to self lock after returning a final value to the host.

**Comment by anakrish** [comment]
Would the following work for you?
- Within ecall
   - Perform computation
   - make ocall to store the result
   - call oe_abort

**Comment by JoFrost** [comment]
@anakrish That's a great solution, it will suit our needs perfectly, thank you!

**Comment by anakrish** [comment]
Great. Closing this issue for now. Feel free to reopen if needed.
