### ISSUE TITLE
Add test for verifying enclave config_id/config_svn fields in evidence claims for SGX

### ISSUE THREAD

**Issue by yentsanglee** [openenclave/openenclave#3903]
Test case in #3799 does not cover the verification of the  enclave config_id/config_svn are identical to evidence claim `OE_CLAIM_SGX_CONFIG_ID` and `OE_CLAIM_SGX_CONFIG_SVN`.

A test case is needed to verify the new fields when executed in supported hardware (I.e SGX Icelake).

For technical details, refer to #3054 SGX: Enable basic Key Separation and Sharing Support.

Related to #3890 and #3723

**Comment by radhikaj** [comment]
@yentsanglee Are config_id/config_svn SGX specific?

**Comment by yentsanglee** [comment]
> @yentsanglee Are config_id/config_svn SGX specific?
> If so, why?

config_id/config_svn are defined by SGX. Other TEEs may or may not have similar init-time claim input. All definitions added in PR #3799 are all SGX specific - OE_SGX_ENCLAVE_CONFIG_DATA, oe_sgx_enclave_setting_config_data, etc.

**Comment by yentsanglee** [comment]
Assigned to @manojrupireddy to complete the test coverage of PR #3799.
