### ISSUE TITLE
Question about "OE_REENTRANT_ECALL"

### ISSUE THREAD

**Issue by hyunsooda** [openenclave/openenclave#3932]
I have faced ```OE_REENTRANT_ECALL``` error when I do like below.

* ecall_* : functions in enclave-side
* host_* : functions in host-side
```
t0:     ecall_func1() // ecall_func1() calls ocall(host_func1())
t1:             host_func1()   // host_func calls another ecall (ecall_func2)
t2:     ecall_func2()  // Occurs ```OE_REENTRANT_ECALL```
```

After getting this issue, I was searching that whether Ecall is a reentrant function or not, but it seems hard to find about that.
So, I'm wondering whether this issue is purposely born from your own team or an underlying problem of sgx. If it is latter, I really appreciate it if you can give an associated reference.

Thank you

**Comment by anakrish** [comment]
OE SDK does not allow an ocall to make an ecall back into the enclave. Such calls are considered reentrant and  raise OE_REENTRANT_ECALL error. Reentrant ecalls were deemed to increase the attack surface in security review and hence were disabled.

**Comment by dthaler** [comment]
OP-TEE does not allow this either

**Comment by anakrish** [comment]
@hyunsooda Can you describe your use case?

**Comment by hyunsooda** [comment]
Hi all,

@dthaler  Thank  you
@anakrish What you mean the "use case"? Just I have faced  ```OE_REENTRANT_ECALL``` error when I followed the function call flow like the code snippet above exactly. That's all.

**Comment by hyunsooda** [comment]
After some search on this and I thought somethings. The root cause is to prevent attacks, the type of bypassing control flow . And also ecall cannot expect the behavior of the host function in fundamentally.
For simple example,
```
t0:     ecall_func1()
t1:             host_func1() 
t2:     ecall_func2() 
```
Attacker can change the return address of ```host_func1()``` to ```ecall_func1()```. It simply destroys the enclave program by incurring stackoverflow. And there are maybe many malicious cases.
If you don't have further comments on this, you can close this thread or I will.

**Comment by anakrish** [comment]
@hyunsooda Your reasoning is spot on. It opens up possibility for many attack scenarios.

Closing for now.
