### ISSUE TITLE
Support release mode enclaves

### ISSUE THREAD

**Issue by jxyang** [openenclave/openenclave#3953]
All OE samples and tests create debug mode enclaves with the flag in the config file:
```
Debug=1
```
And when creating the enclave on the host side, this flag is always passed to `oe_create_enclave`:
```
OE_ENCLAVE_FLAG_DEBUG
```
Which is described by OE documentation as:

> The flag allows the enclave to be created without the enclave binary being signed. It also gives a developer permission to debug the process and get access to enclave memory. What this means is ** DO NOT SHIP CODE WITH THE OE_ENCLAVE_FLAG_DEBUG ** because it is unsecure. What it does give is the ability to develop your enclave more easily. Before you ship the code you need to have a proper code signing story for the enclave shared library.

Since `OE_ENCLAVE_FLAG_DEBUG` is not recommended for production usage, ideally,  `oe_create_enclave` should automatically  determine the release/debug mode of the given enclave application without relying on a user supplied flag. If that requires major rework, at the minimum, we need to provide an API in OE to read a signed enclave application and determine its release/debug mode, and provide a sample/test to show its usage.

**Comment by jxyang** [comment]
@radhikaj @anakrish

**Comment by dthaler** [comment]
@jxyang my understanding is that Debug=1 means it's valid to load _with or without_ the OE_ENCLAVE_FLAG_DEBUG flag, and Debug=0 means it must be loaded with the OE_ENCLAVE_FLAG_DEBUG clear.   So one cannot automatically determine the mode of the application without the user supplied flag.

A reasonable developer experience is to first test an enclave with Debug=1, OE_ENCLAVE_FLAG_DEBUG set, then with Debug=1, OE_ENCLAVE_FLAG_DEBUG clear (which does not require recompiling the enclave), and then finally with Debug=0 (which does not require recompiling the host application).  This order also accommodates cases where the host and enclave are developed by different organizations.

A host developer can see whether Debug is 0 or 1 for an enclave in binary form by doing "oesign dump -e <enclave>"

Does this answer your questions?   If so we can make sure the documentation is clarified.

**Comment by jxyang** [comment]
@dthaler The expectation doesn't quite match the Mystikos user experience. That means we have to ship two versions of Mystikos, one for loading Debug=1 user applications, one for Debug=0 user applications. Ideally, we want this setting to be transparent to users.

My understanding is that `oesign` stores the debug flag in one ELF section of the .so file, and it should be possible to parse the section and make the determination given a .so file, which is received by `oe_create_enclave`.

**Comment by jxyang** [comment]
Related issue in Mystikos: https://github.com/deislabs/mystikos/issues/279

**Comment by dthaler** [comment]
If I understand your response, that's an issue for Mystikos not OE SDK, which is for a wide variety of application developers not just Mystikos.   Mystikos can choose to disallow Debug=1, OE_ENCLAVE_FLAG_DEBUG clear if Mystikos wants, but OE SDK should not.

**Comment by jxyang** [comment]
Just to make sure, do you agree that this is technically possible? @dthaler

**Comment by dthaler** [comment]
I agree it is technically possible for Mystikos to do the same thing that "oesign dump" does to read the Debug= flag and then use it when Mystikos calls oe_create_encalve to set the `OE_ENCLAVE_FLAG_DEBUG` based on the parity.

Doing anything in OE itself would be harmful to the development flow in my opinion.

**Comment by dthaler** [comment]
@jxyang If there were a flag like OE_ENCLAVE_FLAG_AUTODEBUG which means to have FLAG_DEBUG set if Debug=1 and FLAG_DEBUG clear if Debug=0 on the enclave being loaded, would that meet your needs?

**Comment by jxyang** [comment]
Yes, that's exactly what I wanted.

**Comment by mingweishih** [comment]
@dthaler's idea sounds like an easy fix. I can make a quick PR for that if needed.
