### ISSUE TITLE
Include symbol files in the Windows release packages

### ISSUE THREAD

**Issue by yentsanglee** [openenclave/openenclave#3959]
Symbol files help customers debug. It will be helpful to include symbol files in the release package and add label to release source snapshot.

**Comment by dthaler** [comment]
Per triage meeting, symbols are already part of the Linux release packages but not Windows

**Comment by dthaler** [comment]
Question: what binaries is this about?  is this about oeedger8r, oesign, oesgx?  Or what?

**Comment by mingweishih** [comment]
@yentsanglee please follow-up regarding the request and we'll come back to this next week.

**Comment by LarryOsterman** [comment]
Scenario: Customer needs to debug OpenEnclave code.

Expected Result: Stepping into the OE code points me to OE code with full symbols.

Actual Result: Stepping into the OE code points me to assembly code with no symbolic information.

That makes it insanely hard to debug OE, and the diagnostics produced by OE are so coarse grained, it's critical that we be able to debug the OE binaries.

This applies to all binaries that OE includes in its source level packages.

**Comment by yentsanglee** [comment]
@anakrish If Windows apps call oe_verify_evidence() for example inside enclave, how do the developers debug into OE code?

**Comment by RRathna** [comment]
Verified that stepping into oe_create_enclave() brings up assembly instruction. @mingweishih @radhikaj

**Comment by radhikaj** [comment]
Fixed by #4052
