### ISSUE TITLE
Add attestation evidence verification errors and claims for cases that need SW hardening and HW config

### ISSUE THREAD

**Issue by yentsanglee** [openenclave/openenclave#3969]
SGX quote verification returns these TCB status:

- UpToDate
- SWHardeningNeeded
- ConfigurationNeeded
- ConfigurationAndSWHardeningNeeded
- OutOfDate
- OutOfDateConfigurationNeeded
- Revoked

However, OE evidence verification returns OE_OK for success case and OE_TCB_LEVEL_INVALID for the above error cases.

Ask:

1. For `oe_verify_evidence` to return more granular (non-SGX specific) errors to cover the different error cases.
2. For `oe_verify_evidence` to return `tcbStatus`, `tcbDate` and `advisoryIDs` claims of the matching tcbLevel. `tcbDate` represents the date and time when the TCB level was certified not to be vulnerable. `advisoryIDs` contains the advisory IDs describing vulnerabilities.
3. For `oe_verify_evidence` to log descriptive statements for each of the error above. Ensure attestation tests print clear error messages and suggestions at failure. Related to #3885.
4. Describe return values of `oe_verify_evidence` in the header file for Doxygen.

Reference - [SGX PCS Certificate](https://sbx.api.portal.trustedservices.intel.com/documentation#pcs-certificate-v3)

**Comment by yentsanglee** [comment]
Today `oe_verify_evidence` returns OE_OK for TCB status "UpToDate" and "SWHardeningNeeded". This logic has to be preserved to ensure backward compatibility.

**Comment by dthaler** [comment]
> Today `oe_verify_evidence` returns OE_OK for TCB status "UpToDate" and "SWHardeningNeeded". This logic has to be preserved to ensure backward compatibility.

We don't need to ensure backward compatibility with apis marked as experimental.  However, OE_OK is the right return value for UpToDate and SWHardeningNeeded (and the other ones).

**Comment by yentsanglee** [comment]
Resolved by #4014
