### ISSUE TITLE
Include libcxxrt headers in installation

### ISSUE THREAD

**Issue by octaviansima** [openenclave/openenclave#3983]
We are attempting to use OpenEnclave with a project that requires including the cxxabi.h header. This can be found in the source code [here](https://github.com/openenclave/openenclave/blob/master/3rdparty/libcxxrt/libcxxrt/src/cxxabi.h), but it is currently not being provided in the installation. Is it possible to include this file (and probably the rest of the headers in libcxxrt) in `/opt/openenclave/include/openenclave/3rdparty`? I saw this old issue https://github.com/openenclave/openenclave/issues/1650 with the same request that seems to have been forgotten. If this is not a priority but you think it is a valid addition to the project, I am happy to submit a PR.

**Comment by radhikaj** [comment]
libxxrt is not exposed publicly typically. We dont publish the libxxrt lib either.
What is the use case for this?
