### ISSUE TITLE
Support Azure DCAP 1.9

### ISSUE THREAD

**Issue by yentsanglee** [openenclave/openenclave#4003]
OE script installs Azure DCAP NuGet package 1.6.0 which is almost a year old. Version [1.9.0](https://www.nuget.org/packages/Microsoft.Azure.DCAP/1.9.0) was recently released and it includes Icelake support. OE should consider moving to Azure DCAP 1.9.0.

Note - Azure DCAP 1.9.0 package for Linux is not available yet.

**Comment by radhikaj** [comment]
Linux package will be available on the 25th of May 2021.

**Comment by CyanDevs** [comment]
This was completed back in May 2021.
