### ISSUE TITLE
Question: File Encryptor, encrypt the data with other encryption methods and then send it to the enclave

### ISSUE THREAD

**Issue by DylanWangWQF** [openenclave/openenclave#4005]
Question 1:
I have checked the [APIs and Libs](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/APIs_and_Libs.md), `fstream` is not supported inside the enclave in the latest version.
Can we send a `JSON` object to the enclave? [(json.hpp)](https://github.com/nlohmann/json/blob/develop/include/nlohmann/json.hpp)

Question 2:
Can we encrypt the data with other encryption methods (e.g., homomorphic encryption, HE), then send the ciphertext to the enclave? (In this case, we have to enable the enclave to encrypt and decrypt the data with HE)

**Comment by radhikaj** [comment]
fstream is not supported as of now. @radhikaj to file an issue for question 1.
Answers to both questions is yes. 
Q2 You would write edl and pass in data using buffers/string.
