### ISSUE TITLE
Incompatible OpenSSL DLL

### ISSUE THREAD

**Issue by yentsanglee** [openenclave/openenclave#4009]
Multiple OpenSSL DLLs exist in the system:

1. C:\oe_prereqs\OpenSSL\x64\debug\bin\libcrypto-1_1-x64.dll
2. C:\oe_prereqs\OpenSSL\x64\release\bin\libcrypto-1_1-x64.dll
3. C:\Program Files\Git\mingw64\bin\libcrypto-1_1-x64.dll
4. C:\Program Files\Git\mingw64\libexec\git-core\libcrypto-1_1-x64.dll

The one in `C:\Program Files\Git\mingw64\bin` is set higher in %PATH% but it is not compatible with the library in `C:\oe_prereqs\OpenSSL`. As a result, if tool oecert (who calls `PEM_read_bio_X509` and `X509_print_ex_fp`) is launched, exception occurs:

```
Debug Assertion Failed!
File: minkernel\crts\ucrt\src\appcrt\Iowio\write.cpp
Line: 50
Expression: (_osfile(fh) & FOPEN)
```

Repo steps:
1. Following [GettingStarted Doc](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsSGX1FLCGettingStarted.md) to clone and build the repo.
2. C:\Users\yen\openenclave\build\x64-Debug\output\bin> .\oegenerate.exe -f sgx_ecdsa -v

**Comment by radhikaj** [comment]
@yentsanglee If you remove C:\oe_prereqs\OpenSSL\ from the path, do you still hit issues?

**Comment by yentsanglee** [comment]
`C:\oe_prereqs\OpenSSL\` is not in the PATH but `C:\oe_prereqs\OpenSSL\bin` is. However, `C:\oe_prereqs\OpenSSL\bin` folder does not exist so removing it does not change anything.

**Comment by yentsanglee** [comment]
The workaround is to remove these folders from PATH
1. C:\Program Files\Git\mingw64\bin
2. C:\Program Files\Git\mingw64\libexec\git-core

and add one of these folders to PATH
1. C:\oe_prereqs\OpenSSL\x64\release\bin\
2. C:\oe_prereqs\OpenSSL\x64\debug\bin\

**Comment by yentsanglee** [comment]
One of my question - these DLLs are all version 1.1. Why are they not compatible?

**Comment by BRMcLaren** [comment]
> The workaround is to remove these folders from PATH
> 
> 1. C:\Program Files\Git\mingw64\bin
> 2. C:\Program Files\Git\mingw64\libexec\git-core
> 
> and add one of these folders to PATH
> 
> 1. C:\oe_prereqs\OpenSSL\x64\release\bin\
> 2. C:\oe_prereqs\OpenSSL\x64\debug\bin\

When I did this, I was not able to build the SDK. It is a workaround to using binary. Were you able to build the SDK with the path changes?

**Comment by BRMcLaren** [comment]
@yentsanglee That's a good point. I took a look into C:\Program Files\Git\mingw64\bin\libcrypto-1_1-x64.dll, seems to be version 1.1.1g. Whereas the version we are using of open SSL has 1.1.1-dev of libcrypto-1_1-x64.dll

**Comment by ryanhsu19** [comment]
Recently MAA has contacted me a couple times due to this incompatible OpenSSL error. This was assigned to Brett, but he had already left. Could it be fixed so that no workaround is needed?
