### ISSUE TITLE
Rename oecert tool

### ISSUE THREAD

**Issue by ryanhsu19** [openenclave/openenclave#4012]
Since `oecert` is used to generate not only certificates but also reports and evidence in different formats, and we have another tool `oeverify` for verifying evidence, we would like to propose a new name for it, e.g., `oegen`. See the discussion in [PR 4008](https://github.com/openenclave/openenclave/pull/4008#issuecomment-839927526).

**Comment by mingweishih** [comment]
Can we do this as part of v0.16 release?

cc @radhikaj  @yentsanglee
