### ISSUE TITLE
oegenerate doesn't generate open enclaves

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#4027]
The name "oegenerate" is misleading since it does not in fact generate open enclaves.
To have a good developer experience, rather than an confusing one, the naming is important.
If the tool does things specific to attestation, then it needs a name specific to attestation, not one that implies it generates projects.    oeedger8r generates stubs from IDL, and the VS and VS Code extensions generate projects from templates, and neither of those are called oegenerate, hence the confusion.

**Comment by dthaler** [comment]
This issue is a regression in a sense, caused by PR #4008

**Comment by mingweishih** [comment]
cc @yentsanglee @ryanhsu19 @qiucwang

**Comment by yentsanglee** [comment]
This tool generates attestation evidence in the format of SGX ECDSA, legacy remote report, and certificate. Considering other similar tools are named as "oe(verb)", I'd suggest we follow the same naming convention.

@dthaler Any suggestion?

**Comment by dthaler** [comment]
We have "oesgx" and sgx is not a verb, and "oeedger8r", and edger8r is not a verb.

We have "oesign" which signs an enclave, and "oeverify" which verifies an enclave in a sense, so "oe(verb)" is only ok for intransitive verbs, or transitive verbs where "enclave" is the direct object, and since "enclave" is not the object here I don't think that convention is appropriate here regardless of the verb.

"oetestattest" or "oetestevidence" would be more accurate according to the current README (which makes it clear it's just a debugging utility, not something that acts on real enclaves like oesign does).

**Comment by yentsanglee** [comment]
The output of "oegenerate" can be the input of "oeverify". It will be great if the name implies the two tools are provided as a pair.

**Comment by radhikaj** [comment]
Please address this in v0.17.0.
