### ISSUE TITLE
Question about EPC memory usage

### ISSUE THREAD

**Issue by hyunsooda** [openenclave/openenclave#4035]
In a limited SGX environment(<= 128MB), we sometimes want to query the EPC memory usage periodically and in real-time(like ```htop```).
For example, application A has many threads and a series of workloads with limited memory(<= 128MB). we want to know which combination has typically maximized performance as well as the point, where saturation raises.
So, is there a method to query EPC memory(or other metrics) in real-time? (fortanix example: https://fortanix.com/blog/2020/02/monitoring-intel-sgx-enclaves/)

Thank you

**Comment by anakrish** [comment]
@bodzhang

**Comment by bodzhang** [comment]
As I understand, neither Intel's DCAP SGX driver, nor the Linux kernel 5.11 native SGX support provides any interface to query application's EPC usage statistics or EPC paging status. I think cgroup is the right way to manage EPC usage and expose certain system level statistics. In the ongoing Linux Kernel Mailing List discussion on SGX virtualization support, cgroup topic was [brought up](https://lore.kernel.org/lkml/20210326170223.GH25229@zn.tnic/) already.

**Comment by hyunsooda** [comment]
I get it. Thank you
