### ISSUE TITLE
Samples still use deprecated oe_verify_attestation_certificate_with_evidence(), do not illustrate use of oe_verify_attestation_certificate_with_evidence_v2()

### ISSUE THREAD

**Issue by achamayou** [openenclave/openenclave#4048]
From https://github.com/openenclave/openenclave/releases/tag/v0.16.0 release notes:

> oe_verify_attestation_certificate_with_evidence() has been deprecated because it has been deemed insufficient for security. Use the new, experimental oe_verify_attestation_certificate_with_evidence_v2() instead to generate a self-signed certificate for use in the TLS handshaking process.

The sample under https://github.com/openenclave/openenclave/tree/master/tests/attestation_plugin_cert claims:

> Implement get_tls_cert(), which calls oe_get_attestation_certificate_with_evidence_v2() API to generate a requested certificate based on a given format UUID
> Call oe_verify_attestation_certificate_with_evidence_v2() on the generated certificate before returning from get_tls_cert call

But it is still calling the old API on both the enclave (https://github.com/openenclave/openenclave/blob/master/tests/attestation_plugin_cert/enc/enc.cpp#L201) and the host side (https://github.com/openenclave/openenclave/blob/master/tests/attestation_plugin_cert/host/host.cpp#L129).

It would be a lot nicer for users if:

1. The release notes explained why the old version is insecure
2. The release notes pointed to documentation that explained what the new arguments are and what role they play in verification
3. There was a sample that illustrated their use

**Comment by radhikaj** [comment]
Thanks for the suggestions @achamayou . @yentsanglee, can we add some information to the changelog for #1 and #2 suggested above?

**Comment by yentsanglee** [comment]
@ryanhsu19 can you please add info to change as suggested by @radhikaj.

**Comment by radhikaj** [comment]
@achamayou, we will update the sample for v0.18.

**Comment by ryanhsu19** [comment]
@radhikaj Since it is weird to add it to the changed section for v0.17 (because, technically, it is not a change), we will have to revise old changelogs for the first time (for v0.15 more specifically). What do you think? If it is fine, then we will proceed and open a PR for it.

**Comment by achamayou** [comment]
@radhikaj thank you, having a reference sample will be very helpful.
