### ISSUE TITLE
OE-Fuzzing: AddressSanitizer detected "allocation-size-too-big" scenario 

### ISSUE THREAD

**Issue by mrragava** [openenclave/openenclave#4058]
=================================================================
==25110==ERROR: AddressSanitizer: requested allocation size 0x457f0000002cd000 (0x457f0000002cf000 after adjustments for alignment, red zones etc.) exceeds maximum supported size of 0x10000000000 (thread T0)
    #0 0x54ede5 in memalign /oe-llvm/compiler-rt/lib/asan/asan_malloc_linux.cc:171:3
    #1 0x627580 in oe_memalign /openenclave-security/sut/openenclave/host/memalign.c:16:12
    #2 0x6b9ca0 in _initialize_image_segments /openenclave-security/sut/openenclave/host/sgx/loadelf.c:255:32
    #3 0x6afe45 in _load_elf_image /openenclave-security/sut/openenclave/host/sgx/loadelf.c:440:5
    #4 0x69aaf4 in _load_primary_image /openenclave-security/sut/openenclave/host/sgx/loadelf.c:1427:5
    #5 0x697507 in oe_load_elf_enclave_image /openenclave-security/sut/openenclave/host/sgx/loadelf.c:1446:5
    #6 0x693bc9 in oe_load_enclave_image /openenclave-security/sut/openenclave/host/sgx/load.c:63:13
    #7 0x66343b in oe_sgx_build_enclave /openenclave-security/sut/openenclave/host/sgx/create.c:815:9
    #8 0x67928a in oe_create_enclave /openenclave-security/sut/openenclave/host/sgx/create.c:1159:5
    #9 0x58a315 in oe_create_create_enclave /openenclave-security/build/fuzzing_build/src/dynamic/fuzzing/create/host/create_u.c:7291:12
    #10 0x57eaae in CreateEnclave(char const*) /openenclave-security/build/fuzzing_build/../../src/dynamic/fuzzing/create/host/host.cpp:27:14
    #11 0x57f4ad in LLVMFuzzerTestOneInput /openenclave-security/build/fuzzing_build/../../src/dynamic/fuzzing/create/host/host.cpp:81:19
    #12 0x45608a in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /oe-llvm/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:533:15
    #13 0x455a25 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /oe-llvm/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:455:3
    #14 0x45710b in fuzzer::Fuzzer::MutateAndTestOne() /oe-llvm/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:670:19
    #15 0x457dc5 in fuzzer::Fuzzer::Loop(std::Fuzzer::vector<std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> >, fuzzer::fuzzer_allocator<std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> > > > const&) /oe-llvm/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:801:5
    #16 0x44f581 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /oe-llvm/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:760:6
    #17 0x4742c2 in main /oe-llvm/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #18 0x7f5dfe006bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310

==25110==HINT: if you don't care about these errors you may set allocator_may_return_null=1
SUMMARY: AddressSanitizer: allocation-size-too-big /oe-llvm/compiler-rt/lib/asan/asan_malloc_linux.cc:171:3 in memalign

**Comment by mrragava** [comment]
[allocation-size-too-big.zip](https://github.com/openenclave/openenclave/files/6573041/allocation-size-too-big.zip)

**Comment by manojrupireddy** [comment]
@mrragava The image size is deemed to be too big because of fuzzing the program headers of the elf file here https://github.com/openenclave/openenclave/blob/master/host/sgx/loadelf.c#L255. Not sure if we can add any checks around it to avoid this error. Any idea on who defines the maximum supported size for memalign. Is it OS/ musl library dependent?

**Comment by mrragava** [comment]
Not a security issue.  Generally "allocation-size-too-big" is useful when allocation size is calculated from more than one source. In this scenario it is ELF image_size which does not makes sense to check against MAX_MEM. mmap/memalign will fail anyway. 
@anakrish @mingweishih Is it worth checking against max enclave size or EPC size of the platform ? Would it be an overkill ?

**Comment by anakrish** [comment]
I don't think it is valuable to check against the EPC size in oe_memalign/oe_create_enclave since enclave creation would fail gracefully anyways in such a scenario with appropriate error codes returned by Intel's libsgx_enclave_common library.

**Comment by manojrupireddy** [comment]
can we close this issue then? I cannot think a specific check that we can add to prevent this.

**Comment by mrragava** [comment]
I agree we can close this issue.

**Comment by anakrish** [comment]
Closing based on discussion. Can be reopened if needed.
