### ISSUE TITLE
OpenEnclave deb package not available

### ISSUE THREAD

**Issue by ryanleh** [openenclave/openenclave#4099]
Just today I started getting the following error when attempting to `sudo apt install openenclave`:
```
Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/pool/main/o/open-enclave/open-enclave_0.16.1_amd64.deb  404
```
It appears to be an issue with `packages.microsoft.com` but just wanted to bring this to people's attention in case it's actually something else.

**Comment by CyanDevs** [comment]
Hi @ryanleh thanks for bringing this up. We are aware of the repository issue and the relevant people are working to resolve the issue.

**Comment by CyanDevs** [comment]
Repository is functioning again, and apt can install open-enclave.

**Comment by ryanleh** [comment]
Hi, apt is now working non-deterministically for this package in our CI. Sometimes it works fine as normal, sometimes the download from `packages.microsoft` takes upwards of 20 minutes, and sometimes it errors with `Connection Failed`. So I don't believe the issue is completely resolved?

**Comment by CyanDevs** [comment]
@ryanleh There may have been some troublesome mirrors lingering yesterday. Could you confirm whether you are still experiencing the issue today?

**Comment by ryanleh** [comment]
It seems to be working now - albeit still a little slow occasionally but I'm assuming that's just due to some cold caches. Thank you!
