### ISSUE TITLE
g++ link error base on openenclave

### ISSUE THREAD

**Issue by superajun-wsj** [openenclave/openenclave#4110]
when I use g++ link some .a files to a .so, I encountered a problem:

 ECC_JNI.cpp:(.text.Java_sun_security_ec_ECDSASignature_signDigest+0x56): undefined reference to `operator new[](unsigned long)'
/usr/local/bin/ld: ECC_JNI.cpp:(.text.Java_sun_security_ec_ECDSASignature_signDigest+0x16a): undefined reference to `operator delete[](void*)'
/usr/local/bin/ld: ECC_JNI.cpp:(.text.Java_sun_security_ec_ECDSASignature_signDigest+0x177): undefined reference to `operator delete[](void*)'
/usr/local/bin/ld: ECC_JNI.cpp:(.text.Java_sun_security_ec_ECDSASignature_signDigest+0x184): undefined reference to `operator delete[](void*)'
/usr/local/bin/ld: ECC_JNI.cpp:(.text.Java_sun_security_ec_ECDSASignature_signDigest+0x2d9): undefined reference to `operator new[](unsigned long)'
/usr/local/bin/ld: ECC_JNI.cpp:(.text.Java_sun_security_ec_ECDSASignature_signDigest+0x304): undefined reference to `operator new[](unsigned long)'
/usr/local/bin/ld: ECC_JNI.cpp:(.text.Java_sun_security_ec_ECDSASignature_signDigest+0x457): undefined reference to `operator delete[](void*)'

is it because openenclave didn't provide symbol 'new' or 'delete' please?

**Comment by anakrish** [comment]
@superajun-wsj 

> when I use g++ link some .a files to a .so

Couple of questions:
- By .so, are you trying to create an enclave or some other shared library?
- Are the .a files preexisting or did you compile them from source using the openenclave c++/c headers?

**Comment by superajun-wsj** [comment]
1.  I am sorry, it's not a .so, it's a sgx enclave.
2. the .a file are preexisting.

**Comment by anakrish** [comment]
@superajun-wsj 

The pre-existing archives have most likely been compiled against the platforms C++ library (generally GNU libc++) and hence they are not compatible with OE's C++ library which is based on LLVM C++ library.

There are few choices to proceed further
- Recompile the archive from source using OE SDK's C++ and C headers instead of the default GNU C/C++ headers.
- Use a lift-and-shift solution like [Mystikos](https://github.com/deislabs/mystikos) which is based on OE SDK

**Comment by superajun-wsj** [comment]
> @superajun-wsj
> 
> The pre-existing archives have most likely been compiled against the platforms C++ library (generally GNU libc++) and hence they are not compatible with OE's C++ library which is based on LLVM C++ library.
> 
> There are few choices to proceed further
> 
> * Recompile the archive from source using OE SDK's C++ and C headers instead of the default GNU C/C++ headers.
> * Use a lift-and-shift solution like [Mystikos](https://github.com/deislabs/mystikos) which is based on OE SDK

is it possibly to use g++/gcc to build openenclave sdk while not clang(llvm) please??

**Comment by anakrish** [comment]
Yes, by specifying CC=gcc and CXX=g++ before invoking cmake, OpenEnclave SDK can be built using g++/gcc.

However, that will not still allow pre-existing libstdc++ based archives to be used with Open Enclave SDK. Open Enclave SDK uses llvm's libcxx as the enclave-side C++ library irrespective of which compiler is used.

> ECC_JNI.cpp:(.text.Java_sun_security_ec_ECDSASignature_signDigest+0x56): undefined reference to operator new[](unsigned long)' /usr/local/bin/ld: ECC_JNI.cpp:(.text.Java_sun_security_ec_ECDSASignature_signDigest+0x16a): undefined reference to operator delete'

You seem to using an archive related to Java. Therefore I'd recommend that you give Mystikos a try since I supports many runtimes to be run within an enclave: https://github.com/deislabs/mystikos/tree/main/samples

CC @vtikoo @jxyang

**Comment by superajun-wsj** [comment]
> Yes, by specifying CC=gcc and CXX=g++ before invoking cmake, OpenEnclave SDK can be built using g++/gcc.
> 
> However, that will not still allow pre-existing libstdc++ based archives to be used with Open Enclave SDK. Open Enclave SDK uses llvm's libcxx as the enclave-side C++ library irrespective of which compiler is used.
> 
> > ECC_JNI.cpp:(.text.Java_sun_security_ec_ECDSASignature_signDigest+0x56): undefined reference to operator new[](unsigned long)' /usr/local/bin/ld: ECC_JNI.cpp:(.text.Java_sun_security_ec_ECDSASignature_signDigest+0x16a): undefined reference to operator delete'
> 
> You seem to using an archive related to Java. Therefore I'd recommend that you give Mystikos a try since it supports many runtimes to be run within an enclave: https://github.com/deislabs/mystikos/tree/main/samples
> 
> CC @vtikoo @jxyang

But it seems c program runs well based on openenclave from now on.

**Comment by anakrish** [comment]
OpenEnclave uses MUSL on the enclave-side. So if you use an archive that has been built against GLIBC, there could be obscure runtime errors. So long as the code does not use implementation defined structures, the archive has a higher chance of working even if it has been compiled against a different libc.

In case of C++, different standard C++ libraries are not binary compatible. Hence it is not generally possible to compile C++ code against one standard library and then use the object file with another standard C++ library.

**Comment by superajun-wsj** [comment]
> OpenEnclave uses MUSL on the enclave-side. So if you use an archive that has been built against GLIBC, there could be obscure runtime errors. So long as the code does not use implementation defined structures, the archive has a higher chance of working even if it has been compiled against a different libc.
> 
> In case of C++, different standard C++ libraries are not binary compatible. Hence it is not generally possible to compile C++ code against one standard library and then use the object file with another standard C++ library.

Got it now, Thank you very much for your professional comments.
