### ISSUE TITLE
'openenclave/internal/syscall/sys/syscall.h' file not found

### ISSUE THREAD

**Issue by DylanWangWQF** [openenclave/openenclave#4148]
After the build, the layout of openenclave is shown as below:
```
dylan@dylan-OptiPlex-7070:/opt/openenclave/include/openenclave$ ls
3rdparty  advanced  attestation  bits  corelibc  debugmalloc.h  edger8r  edl  enclave.h  host.h  host_verify.h  log.h  seal.h  sgx  trace.h
```
It seems that the `internal` header directory is not installed in `/opt/openenclave/include/openenclave`. When run the enclave code, shows cannot find `syscall.h` file .
```
fatal error: 'openenclave/internal/syscall/sys/syscall.h' file not found
#include <openenclave/internal/syscall/sys/syscall.h>
```

**Comment by mingweishih** [comment]
We intentionally don't ship the internal header directory as part of release packages. Those headers are used "internally" only. May I know why do you need to use this specific header?

**Comment by DylanWangWQF** [comment]
@mingweishih 
This issue is related to another issue https://github.com/openenclave/openenclave/issues/4127#issuecomment-875531987

It seems that this header is unnecessary for me, Sorry about that. Closing this issue.
