### ISSUE TITLE
tls between enclave and untrusted app limit set to 1024 bytes for reading

### ISSUE THREAD

**Issue by flothia** [openenclave/openenclave#4154]
Hi,

After settling a tls tunnel between an enclave and a untrusted app, it seems that reading is limited to 1024.
I have checked that all my structures allocated for reading were larger than 1024 bytes.
Should i still investigate on my own code, or there is a limit set by OE with mbedtls ?

Thanks in advance,

**Comment by mingweishih** [comment]
I can't recall there is such limitation. Can you share more information on your implementation?

**Comment by flothia** [comment]
My implementation :

Server side : a python app using a mbedtls plugin, and providing raw data to store inside enclave
Client side (enclave) : based on _ssl_client1.c_ code provided by the official mbedtls plugin, integrated to OE
Unstruted app : make the ECALL to pull packet from tls channel (i.e _mbedtls_net_recv_ set in _mbedtls_ssl_set_bio_)

Tests performed :
	- Server side really send more than 1024 bytes -> OK (tested with another client side in python)
	- client side is able to exchange more than 1024 bytes via TLS -> OK (tested with a enclaved tls server based on _ssl_server.c code_)

**Comment by flothia** [comment]
Ok, i found the problem.
It was nothing related to TLS, but related to my ocall printing function. The maximum bytes to display was set to BUFSIZ, which is set to 1024.
