### ISSUE TITLE
mmap and munmap support

### ISSUE THREAD

**Issue by superajun-wsj** [openenclave/openenclave#4166]
is it possible that openenclave supports mmap and munmap operatation please?

**Comment by anakrish** [comment]
OE does not currently support mmao and mummap. If your enclave really needs these syscalls to work,  I'd encourage you to give [mystikos](https://github.com/deislabs/mystikos) a try. Mystikos is based on OE and supports mmap and munmap, and a whole bunch of other syscalls that OE currently does not support.

**Comment by superajun-wsj** [comment]
ok, we will have a try about mystikos, thank you very much.

**Comment by anakrish** [comment]
@superajun-wsj What parameters are you passing to mmap? Do you need file-mapping support?

**Comment by radhikaj** [comment]
Limited support for mmap and munmap in https://github.com/openenclave/openenclave/pull/4170

**Comment by superajun-wsj** [comment]
> @superajun-wsj What parameters are you passing to mmap? Do you need file-mapping support?

Hi anakrish，we don't need file-mapping supporting, only memory reserver, allocate and free is enough for us.

**Comment by superajun-wsj** [comment]
Hi radhikaj, it seems intel sgx sdk provider similar function(https://github.com/intel/linux-sgx/blob/master/common/inc/sgx_rsrv_mem_mngr.h), could you please implement it in openenclave please?

**Comment by mingweishih** [comment]
> Hi radhikaj, it seems intel sgx sdk provider similar function(https://github.com/intel/linux-sgx/blob/master/common/inc/sgx_rsrv_mem_mngr.h), could you please implement it in openenclave please?

The implementation in the intel SGX SDK is based on an out-of-tree driver with EDMM support. However, OE's plan is waiting on the EDMM feature gets upstream in the Linux kernel (refer to the workflow proposal in #3991).

**Comment by superajun-wsj** [comment]
> > Hi radhikaj, it seems intel sgx sdk provider similar function(https://github.com/intel/linux-sgx/blob/master/common/inc/sgx_rsrv_mem_mngr.h), could you please implement it in openenclave please?
> 
> The implementation in the intel SGX SDK is based on an out-of-tree driver with EDMM support. However, OE's plan is waiting on the EDMM feature gets upstream in the Linux kernel (refer to the workflow proposal in #3991).

Got it, thank you very much.
