### ISSUE TITLE
oe_create_enclave crashes on non-sgx machine

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#4174]
When the simulation bit is clear, oe_create_enclave on 0.17.1 throws an exception on a non-sgx-capable machine:

> 2021-07-19T15:46:06-0700.581682Z [(H)ERROR] tid(0x3f34) | Failed to load sgx_enclave_common.dll
>  [C:\source\openenclave\host\sgx\sgx_enclave_common_wrapper.c:_load_sgx_enclave_common_impl:130]
> 2021-07-19T15:46:06-0700.582197Z [(H)ERROR] tid(0x3f34) | Terminating host application. [C:\source\openenclave\host\sgx\sgx_enclave_common_wrapper.c:_load_sgx_enclave_common_impl:139]

With the simulation bit set, it works.  Instead of throwing an exception, it should instead gracefully fail.
This is a regression from 0.14.

**Comment by dthaler** [comment]
Update: with the simulation bit set, it works only when no breakpoints are set.  Setting a breakpoint results in:

> Exception thrown at 0x000001B1266AB1FB (MyEnclave1.elf.signed) in ConsoleApplication2.exe: 0xC0000005: Access violation reading location 0x0000000000000028.

**Comment by dthaler** [comment]
@anakrish Any suggestions?

**Comment by anakrish** [comment]
@dthaler I've created a PR to gracefully error out when simulate flag is not specified on a non-sgx machine. #4186 

I've created a separate issue to investigate the Windows Debugger breakpoint issue. #4185
