### ISSUE TITLE
Question about the  use of multi-thread in host nad enclave

### ISSUE THREAD

**Issue by DylanWangWQF** [openenclave/openenclave#4176]
Hi, team!
Is this scenario reasonable?
**Scenario**: Run the application in multi-cores. That is, one thread controls the host, another thread controls the enclave, then transforms the information between host and enclave.
**Motivation**: I want the host to execute some other tasks when the enclave is executing the task.

Is there any similar sample in OE to help us understand the use of this?

**Comment by TaihuLight** [comment]
Does you find this kind of example? I also want to stduy from this type of example.

**Comment by mingweishih** [comment]
This sounds like the switchless call features to me: https://github.com/openenclave/openenclave/tree/master/samples/switchless.
Is this for performance purposes or something else?
