### ISSUE TITLE
Does OE support random_device now ?

### ISSUE THREAD

**Issue by DylanWangWQF** [openenclave/openenclave#4180]
Hi, Team!
The Document shows that random_device is not supported now.
random | Partial | Supported as part of C++11. Unsupported class: random_device.
-- | -- | --

But in the given example. it's used:
https://github.com/openenclave/openenclave/blob/cd72fd7069488ba6f453c8f5f47bd9fd9a6e6c0d/tests/thread_local/enc/enc.cpp#L39

**Comment by anakrish** [comment]
CC: @mingweishih

**Comment by radhikaj** [comment]
Based on docs - random device is not supported, but the tests use it.
