### ISSUE TITLE
Use vDSO interface  to handle SGX enclave exceptions

### ISSUE THREAD

**Issue by haitaohuang** [openenclave/openenclave#4194]
Linux kernel version 5.11+ with built-in support for SGX includes vDSO APIs defined in https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/tree/arch/x86/include/uapi/asm/sgx.h?h=x86/sgx#n79.
 It turns all exceptions raised inside a enclave or at EENTER/ERESUME into a synchronous callback. This has advantages over asynchronous signal which is not convenient for libraries. Therefore, the  vDSO interface is the recommended way for handling SGX exception.  Robust EDMM implementation would also require using this interface, see discussion in #3755.

To use the vDSO iinterface, OE host side runtime needs to do following.
1. At initialization (e.g., in a constructor) detect vDSO support in kernel
    - this can be done using getauxval(AT_SYSINFO_EHDR) to get the vdso base address and then walk the vDSO ELF headers and symbol table to get the symbol address for  __vdso_sgx_enter_enclave. See [this example](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/tree/tools/testing/selftests/sgx/main.c?h=x86/sgx#n197)
2. if vDSO interface dected, do not register the signal handler for SGX. 
3. Implement a vDSO wrapper for all ECalls, switch all ECall flows go through this wrapper (replacing oe_enter) . 
4. Implement vDSO user handler callback receiving register values and a 'run' object with fields for in-out. See definition in the header file linked above. The handler should proceed as following.
-  If run.function == EENTER, error case, should be treated as if enclave loses EPC context due to power events. Set error code in run.userdata, return 0 to vDSO. ECall wrapper return status stored in run.userdata.
-  If run.function == EEXIT, return 0 if it is a normal ECall return; If it is an OCall, do call frame stitching for debug, invoke OCall bridge, do marshalling for OCall return params/status, and return EENTER. 
-  If run.function == ERESUME, exception happened inside enclave or at ERESUME,  invoke enclave side exception handler either make a special ECall thru ECall wrapper,  or setup registers and marshalling for exception handler,  return EENTER to vDSO to do nested EENTER.

**Comment by radhikaj** [comment]
@dthaler  asked a question - On Windows is it a synchronous callback or an asynchronous signal?

**Comment by radhikaj** [comment]
This is an internal interface between OE SDK and the kernel.

**Comment by haitaohuang** [comment]
@radhikaj This is Linux only.  No need for a Windows issue.
