### ISSUE TITLE
`oesign` failing after upgrade from OE 0.12.0 to 0.17.1

### ISSUE THREAD

**Issue by octaviansima** [openenclave/openenclave#4216]
Hi, we are trying to update our project from 0.12.0 to 0.17.1 and running into the following error:
```
~$ oesign sign -e libenclave.so -c Enclave.conf -k key.pem
2021-08-04T17:31:38+0000.699963Z [(H)ERROR] tid(0x7fdc72818b80) | Failed to locate the module. Please place the module under the same directory as the enclave binary. (oe_result_t=OE_NOT_FOUND) [/source/openenclave/host/sgx/loadelf.c:_load_dependent_image:1396]
2021-08-04T17:31:38+0000.699992Z [(H)ERROR] tid(0x7fdc72818b80) | :OE_NOT_FOUND [/source/openenclave/host/sgx/loadelf.c:oe_load_elf_enclave_image:1448]
2021-08-04T17:31:38+0000.700213Z [(H)ERROR] tid(0x7fdc72818b80) | :OE_NOT_FOUND [/source/openenclave/host/sgx/load.c:oe_load_enclave_image:63]
2021-08-04T17:31:38+0000.700220Z [(H)ERROR] tid(0x7fdc72818b80) | :OE_NOT_FOUND [/source/openenclave/tools/oesign/oeinfo.c:oe_read_oeinfo_sgx:27]
oesign ERROR: Failed to load enclave: libenclave_trusted.so: result=OE_NOT_FOUND (0x9)
```

The error message is not particularly helpful. What does "module" mean in this context and why would it need to be in the same folder as the `libenclave.so` binary? I tried compiling and signing the hello world example and that worked as intended.

**Comment by mingweishih** [comment]
This is likely due to that your enclave binary has dependencies on shared libraries. The recent update provides a limited support on it, but it's not recommended for general uses. That is, the enclave binary should be statically linked.

Can you do
$ ldd libenclave.so
and check the output?

**Comment by octaviansima** [comment]
It looks like it's being linked against some shared system libraries:
```
~$ ldd libenclave_trusted.so
        linux-vdso.so.1 (0x00007ffe33577000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8e2a3fe000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8e2a00d000)
        /lib/ld64.so.1 => /lib64/ld-linux-x86-64.so.2 (0x00007f8e2b7ce000)
```

I don't understand why though, since we are linking against the OE version of this library as well as passing `-nostdlib` and `-nodefaultlibs` as linker flags:
`set(ENCLAVE_LINK_FLAGS "-Wl,--no-undefined -nostdlib -nodefaultlibs -nostartfiles -Wl,-Bstatic -Wl,-Bsymbolic -Wl,--no-undefined -Wl,-pie -Wl,--export-dynamic -Wl,--defsym,__ImageBase=0")`

**Comment by mingweishih** [comment]
> Hi @mingweishih, thanks for such a quick response.
> 
> It looks like it's being linked against some shared system libraries:
> 
> ```
> ~$ ldd libenclave.so
>         linux-vdso.so.1 (0x00007ffe33577000)
>         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8e2a3fe000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8e2a00d000)
>         /lib/ld64.so.1 => /lib64/ld-linux-x86-64.so.2 (0x00007f8e2b7ce000)
> ```
> 
> I don't understand why though, since we are linking against `openenclave::oelibc` as well as passing `-nostdlib` and `-nodefaultlibs` as linker flags:
> `set(ENCLAVE_LINK_FLAGS "-Wl,--no-undefined -nostdlib -nodefaultlibs -nostartfiles -Wl,-Bstatic -Wl,-Bsymbolic -Wl,--no-undefined -Wl,-pie -Wl,--export-dynamic -Wl,--defsym,__ImageBase=0")`
> 
> It's odd that this just started failing after upgrading from 0.12.0, I was aware that the binary should not have any dependency on any shared libraries.

I notice that your enclave binary are in the .so form. Can you provide more detail on how your .so file are compiled and linked?

**Comment by octaviansima** [comment]
This is more or less the code:
```
add_compile_options(-m64 -fstack-protector -Wno-unused-parameter -Wno-unused-variable -Wl,--no-undefined -Wl,-nostdlib -Wl,-nodefaultlibs -Wl,-nostartfiles -Wl,-Bstatic -Wl,--no-undefined)

add_compile_definitions(OE_API_VERSION=2 FMT_USE_INT128=0)

include_directories(${OE_INCLUDEDIR}/openenclave/3rdparty ${CMAKE_CURRENT_BINARY_DIR})

link_directories(${OE_LIBDIR} ${OE_LIBDIR}/openenclave/enclave)

link_libraries(openenclave::oeenclave
               openenclave::oecrypto${OE_CRYPTO_LIB}
               openenclave::oelibc
               openenclave::oelibcxx
               openenclave::oecore)

add_library(enclave_trusted STATIC ${SOURCES}) # ${SOURCES} is a list of of .cpp files and one .S file

set_target_properties(enclave_trusted 
                      PROPERTIES
                      POSITION_INDEPENDENT_CODE OFF)

target_link_libraries(enclave_trusted PRIVATE 
                      static_library_1
                      static_library_2
                      static_library_3)

target_include_directories(enclave_trusted
                           PRIVATE
                           SYSTEM
                           ${DUCKDB_DIR}/src/include)

```

If I make `enclave_trusted` an executable, running `ldd` still shows the same shared libraries.

**Comment by mingweishih** [comment]
> This is more or less the code:
> 
> ```
> add_compile_options(-m64 -fstack-protector -Wno-unused-parameter -Wno-unused-variable -Wl,--no-undefined -Wl,-nostdlib -Wl,-nodefaultlibs -Wl,-nostartfiles -Wl,-Bstatic -Wl,--no-undefined)
> 
> add_compile_definitions(OE_API_VERSION=2 FMT_USE_INT128=0)
> 
> include_directories(${OE_INCLUDEDIR}/openenclave/3rdparty ${CMAKE_CURRENT_BINARY_DIR})
> 
> link_directories(${OE_LIBDIR} ${OE_LIBDIR}/openenclave/enclave)
> 
> link_libraries(openenclave::oeenclave
>                openenclave::oecrypto${OE_CRYPTO_LIB}
>                openenclave::oelibc
>                openenclave::oelibcxx
>                openenclave::oecore)
> 
> add_library(enclave_trusted STATIC ${SOURCES}) # ${SOURCES} is a list of of .cpp files and one .S file
> 
> set_target_properties(enclave_trusted 
>                       PROPERTIES
>                       POSITION_INDEPENDENT_CODE OFF)
> 
> target_link_libraries(enclave_trusted PRIVATE 
>                       static_library_1
>                       static_library_2
>                       static_library_3)
> 
> target_include_directories(enclave_trusted
>                            PRIVATE
>                            SYSTEM
>                            ${DUCKDB_DIR}/src/include)
> ```
> 
> If I make `enclave_trusted` an executable, running `ldd` still shows the same shared libraries.

Is the `enclave_trusted` the enclave binary you want to get?
Can you check what are the actual compile/link commands?

**Comment by octaviansima** [comment]
Yes, it's `enclave_trusted`. Those are also as expected, we are only linking against other static libraries.
Example of a file being compiled:
```
 Building CXX object enclave/thirdparty/externallib/src/parser/statement/CMakeFiles/externallib_statement.dir/call_statement.cpp.o
cd /home/os/code/target/cpp/enclave/thirdparty/externallib/src/parser/statement && /usr/bin/c++ 
-Dexternallib -Dexternallib_BUILD_LIBRARY -Dexternallib_MAIN_LIBRARY
-Dexternallib_NO_THREADS=1 -DFMT_USE_INT128=0 -DOE_API_VERSION=2
-DOE_BUILD_ENCLAVE -DSPDLOG_NO_THREAD_ID
-I/home/os/code/target/cpp/_deps/mc2_serialization-build/flatbuffers/include
-I/home/os/code/src/cpp/common -I/home/os/code/src/cpp/app -I/home/os/code/src/cpp/enclave
-I/home/os/code/target/cpp/enclave -I/home/os/code/target/cpp/_deps/spdlog-src/include
-I/home/os/code/target/cpp/enclave/flatbuffers/include
-I/home/os/code/src/cpp/enclave/thirdparty/externallib/src/include
-I/home/os/code/src/cpp/enclave/thirdparty/externallib/third_party/fmt/include
-I/home/os/code/src/cpp/enclave/thirdparty/externallib/third_party/hyperloglog
-I/home/os/code/src/cpp/enclave/thirdparty/externallib/third_party/re2
-I/home/os/code/src/cpp/enclave/thirdparty/externallib/third_party/miniz
-I/home/os/code/src/cpp/enclave/thirdparty/externallib/third_party/utf8proc/include
-I/home/os/code/src/cpp/enclave/thirdparty/externallib/third_party/miniparquet
-I/home/os/code/src/cpp/enclave/thirdparty/externallib/third_party/concurrentqueue
-I/home/os/code/src/cpp/enclave/thirdparty/externallib/third_party/pcg
-I/home/os/code/src/cpp/enclave/thirdparty/externallib/third_party/tdigest
-I/home/os/code/src/cpp/enclave/thirdparty/externallib/src/parser/../../third_party/libpg_query/include
-I/home/os/code/src/cpp/enclave/thirdparty/externallib/src/parser/../../third_party/libpg_query
-isystem /opt/openenclave/include -isystem /opt/openenclave/include/openenclave/3rdparty
-isystem /opt/openenclave/include/openenclave/3rdparty/libcxx -isystem
/opt/openenclave/include/openenclave/3rdparty/libc
  -O3 -DNDEBUG -O3 -DNDEBUG     -m64 -Wno-unused-parameter -Wno-unused-variable
-fvisibility=hidden -fpie -fstack-protector -Wl,--no-undefined -nostdlib -nodefaultlibs -nostartfiles
-Wl,-Bstatic -Wl,-Bsymbolic -Wl,-pie -Wl,--export-dynamic -Wl,--defsym,__ImageBase=0
-Wno-error -fPIE -nostdinc -fstack-protector-strong -fno-omit-frame-pointer -ffunction-sections
-fdata-sections -ftls-model=local-exec -nostdinc++ -std=c++11 -o
CMakeFiles/externallib_statement.dir/call_statement.cpp.o -c
/home/os/code/src/cpp/enclave/thirdparty/externallib/src/parser/statement/call_statement.cpp
```

The final linking command:
```
Linking CXX shared library libenclave_trusted.so
cd /home/os/code/target/cpp/enclave && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/enclave_trusted.dir/link.txt --verbose=1
/usr/bin/c++ -fPIC -O3 -DNDEBUG  -shared -Wl,-soname,libenclave_trusted.so -o libenclave_trusted.so
<---CMakeFiles/enclave_trusted.dir/{.o files}--->
CMakeFiles/enclave_trusted.dir/enclave_t.c.o
-L/opt/openenclave/lib
-L/opt/openenclave/lib/openenclave/enclave
/opt/openenclave/lib/openenclave/enclave/liboeenclave.a
/opt/openenclave/lib/openenclave/enclave/liboecryptombedtls.a
/opt/openenclave/lib/openenclave/enclave/liboelibc.a
/opt/openenclave/lib/openenclave/enclave/liboelibcxx.a
/opt/openenclave/lib/openenclave/enclave/liboecore.a
thirdparty/externallib/src/libexternallib_enclave.a
../_deps/utils_1.a
../_deps/utils_2.a
-ldl thirdparty/externallib/third_party/fmt/libfmt.a
thirdparty/externallib/third_party/libpg_query/libpg_query.a
thirdparty/externallib/third_party/re2/libexternallib_re2.a
thirdparty/externallib/third_party/miniz/libminiz.a
thirdparty/externallib/third_party/utf8proc/libutf8proc.a
thirdparty/externallib/third_party/hyperloglog/libhyperloglog.a
/opt/openenclave/lib/openenclave/enclave/liboeenclave.a
/opt/openenclave/lib/openenclave/enclave/liboecryptombedtls.a
/opt/openenclave/lib/openenclave/enclave/libmbedtls.a
/opt/openenclave/lib/openenclave/enclave/libmbedx509.a
/opt/openenclave/lib/openenclave/enclave/libmbedcrypto.a
/opt/openenclave/lib/openenclave/enclave/liboelibcxx.a
/opt/openenclave/lib/openenclave/enclave/liboelibc.a
/opt/openenclave/lib/openenclave/enclave/liboesyscall.a
/opt/openenclave/lib/openenclave/enclave/liboecore.a
-nostdlib -nodefaultlibs -nostartfiles -Wl,--no-undefined,-Bstatic,-Bsymbolic,--export-dynamic,-pie,--build-id 
-Wl,-z,noexecstack -Wl,-z,now -Wl,-gc-sections
```

It seems that at least VDSO in the final binary should always be present? https://stackoverflow.com/questions/58657036/where-is-linux-vdso-so-1-present-on-the-file-system. But I'm confused why this is occurring in this specific build as opposed to others where it was not.

**Comment by octaviansima** [comment]
Figured this out, it was the `-ldl` flag. Thanks for the help!
