### ISSUE TITLE
Compilation error on attestation

### ISSUE THREAD

**Issue by Zildj1an** [openenclave/openenclave#4226]
I am getting the following compilation error on Ubuntu 20.04 (kernel 5.11, cmake 3.21.1, linux sgx driver v2.11):

```
Processing /opt/openenclave/share/pkgconfig/../../include/openenclave/edl/sgx/attestation.edl.
error: /opt/openenclave/share/pkgconfig/../../include/openenclave/edl/sgx/attestation.edl:56:14 `out' is invalid for user defined type `format_ids_t*'
make[2]: *** [Makefile:31: build] Error 1
```
Can I just remove the [out] restriction?

Thanks!

**Comment by anakrish** [comment]
@Zildj1an Can you confirm if you are using edger8r from /opt/openenclave/bin ?

@mingweishih Does edger8r have the restriction that `out` cannot be used for user defined type?

**Comment by mingweishih** [comment]
@Zildj1an, likely that you're using an older version of oeedger8r binary. Can you try to do an update?

**Comment by mingweishih** [comment]
How revisit this issue next triage meeting to see the question is answered.

**Comment by Zildj1an** [comment]
@mingweishih thanks, updating oeedger8r solved it!
