### ISSUE TITLE
One Way Attestation Question

### ISSUE THREAD

**Issue by jonahrosenblum** [openenclave/openenclave#4250]
Hi, I have a question about OE and attestation. The system I am trying to design has a central server with an enclave that collects data remotely from several different users on separate machines and aggregates all the data into the enclave. The idea I had was to have each remote user attest the enclave, verify trustworthiness and identity, and receive the public key it should use to encrypt the data locally before sending it over.

In this system, data only flows _into_ the central server with an enclave, so I did not think the remote users who are sending data would need an enclave of their own. I tried to rewrite the attestation sample so that it only requires one enclave but could not get the attestation to work unless it was done in an enclave. Is it possible for a remote user to attest the central server's enclave without an enclave of its own or is this not possible/unsafe to do?

**Comment by mingweishih** [comment]
> Hi, I have a question about OE and attestation. The system I am trying to design has a central server with an enclave that collects data remotely from several different users on separate machines and aggregates all the data into the enclave. The idea I had was to have each remote user attest the enclave, verify trustworthiness and identity, and receive the public key it should use to encrypt the data locally before sending it over.
> 
> In this system, data only flows _into_ the central server with an enclave, so I did not think the remote users who are sending data would need an enclave of their own. I tried to rewrite the attestation sample so that it only requires one enclave but could not get the attestation to work unless it was done in an enclave. Is it possible for a remote user to attest the central server's enclave without an enclave of its own or is this not possible/unsafe to do?

Can you elaborate on which parts did not work? Have you check the [hostverify sample](https://github.com/openenclave/openenclave/tree/master/samples/host_verify) and see if that meets your goal?

**Comment by yentsanglee** [comment]
@jonahrosenblum What you described is supported. You can check out "attested_tls" sample for the secure channel establishment between clients and server. Evidence verification can be done without an enclave as @mingweishih pointed out.

**Comment by jonahrosenblum** [comment]
Ok, looking over the hostverify example this might work for what we need. Where can I learn more information about SGX reports/evidence/certificates, etc. (what is the difference between the three, where do they come from, etc.)? Once I understand this part I believe this issue will be resolved.
