### ISSUE TITLE
support pthread_attr_getstack in enclave

### ISSUE THREAD

**Issue by superajun-wsj** [openenclave/openenclave#4253]
Hi, I hope to get current thread's stack information in enclave, for example, stack's base address and stack size... is there only way to do it please? 

int pthread_attr_getstack(const pthread_attr *a, void ** addr, int *size)

**Comment by anakrish** [comment]
There is no documented way to implement it. This is something that needs to be added to OE SDK.

To unblock, you can use the following **undocumented/internal APIs** to implement the function:

```c
// C functions. Prefix with extern "C" if used in C++ code.
#include <pthread.h>
void* oe_sgx_get_td(void);
void* td_to_tcs(const void* td);

extern const volatile  oe_sgx_enclave_properties_t oe_enclave_properties_sgx;

int pthread_attr_getstack(const pthread_attr_t* attr, void** stackaddr, size_t* stacksize)
{
    (void)attr;

    if (stackaddr)
    {
	void* td = oe_sgx_get_td();
	void* tcs = td_to_tcs(td);
	*stackaddr = (void*)((uint64_t)tcs - 4096);
    }
    if (stacksize)
    {
	// return hard coded stack size.
	*stacksize = (size_t)oe_enclave_properties_sgx.header.size_settings.num_stack_pages * 4096;
    }
	
    return 0;
}

```

I'm curious, why do you need to know the stack information from within the enclave?

**Comment by superajun-wsj** [comment]
@anakrish Thank you very much, you always give me a large help, thank you again. Except  pthread_attr_getstack, could openenclave export other pthread related symbols please? for example, pthread_condattr_init pthread_condattr_setclock and so on.

**Comment by anakrish** [comment]
@superajun-wsj 

For pthread_create, join etc you can try out this *experimental* PR https://github.com/openenclave/openenclave/pull/4230
For other missing functions, I'd suggest that you try to pull in the functions from MUSL.

I'll talk to the team and try to get pthread functions prioritized.

**Comment by superajun-wsj** [comment]
@anakrish 
Got it, Thank you very much.

**Comment by radhikaj** [comment]
Dup of https://github.com/openenclave/openenclave/issues/3859
