### ISSUE TITLE
Installation of Open Enclave on arm64 fails

### ISSUE THREAD

**Issue by Zildj1an** [openenclave/openenclave#4255]
I'm following the Open Enclave SDK installation tutorial [here](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_20.04.md) for Ubuntu 20.04, but I cannot install the open-enclave package (the package manager apt does not locate it). I believe that is is because after adding the keys I get when doing the apt update:

```
20 packages can be upgraded. Run 'apt list --upgradable' to see them.
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://download.01.org/intel-sgx/sgx_repo/ubuntu focal InRelea
se' doesn't support architecture 'arm64'
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://apt.llvm.org/focal llvm-toolchain-focal-10 InRelease' do
esn't support architecture 'arm64'
```

What am I missing? Thanks in advance.

**Comment by radhikaj** [comment]
We dont have a package for arm64. Please let us know if you would like to contribute to this.
@Zildj1an  - can you please confirm that you are developing for ARM

**Comment by radhikaj** [comment]
Radhika to fix https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_20.04.md to say it is SGX specific in the filename and title.

**Comment by Zildj1an** [comment]
So, how would you recommend me to get the SDK installed on arm64, even if there is no full support? Manual installation might do?
