### ISSUE TITLE
Manual installation of Open Enclave

### ISSUE THREAD

**Issue by Zildj1an** [openenclave/openenclave#4263]
I have to do manual installation, so I cloned the repo and built with `cmake .` I would like to move the appropriate contents to /opt/openenclave. Is there any way I can do that automatically?

**Comment by mingweishih** [comment]
after the clone, do the following to build and install to /opt/
```
mkdir build
cd build
cmake ..
make -j8
sudo make install
```

**Comment by Zildj1an** [comment]
Thanks!!
