### ISSUE TITLE
High percision timing library in enclave

### ISSUE THREAD

**Issue by joydddd** [openenclave/openenclave#4274]
Hi, I wonder if there is a library I can use on enclave to time function calls to microsecond level. I tried high_resolution_clock::now() and clock() from <time.h>. The first one cause enclave to crash, the second one throw link error. Any suggestions?

**Comment by Parsifal0** [comment]
> It is currently not possible to obtain high-precision timer within the enclave. The `rdtsc` instruction is illegal in SGX1. Making ocalls to query the timer on the host side may not be appropriate since making an ocall itself is an expensive operation, and hence would affect the timing measurements. One approach I can think of is to have a variable in host memory that is continuously updated with the current timer value using a host thread. The enclave can then read the contents of this variable instead of making an ocall. CC: @MWShan @fchinchilla @bodzhang

Does OE support `rdtsc` on SGX2 platforms? I tried to issua an `rdtsc` instruction inside the enclave (SGX2 platform) but got an **OE_ENCLAVE_ABORTING** error.

**Comment by Parsifal0** [comment]
> > > It is currently not possible to obtain high-precision timer within the enclave. The `rdtsc` instruction is illegal in SGX1. Making ocalls to query the timer on the host side may not be appropriate since making an ocall itself is an expensive operation, and hence would affect the timing measurements. One approach I can think of is to have a variable in host memory that is continuously updated with the current timer value using a host thread. The enclave can then read the contents of this variable instead of making an ocall. CC: @MWShan @fchinchilla @bodzhang
> > 
> > 
> > Does OE support `rdtsc` on SGX2 platforms? I tried to issua an `rdtsc` instruction inside the enclave (SGX2 platform) but got an **OE_ENCLAVE_ABORTING** error.
> 
> I didn't see issues with `rdtsc` in SGX2 machine myself. Can you confirm that your environment uses SGX2?

Sorry for the inconvinence. I mistakenly thought that Ice Lake processors are all shipped with SGX2, and later I found that my CPU only supports SGX1.  Now I am also trying to find a way to access time inside enclaves without much transition overhead. Thanks for your reply.

**Comment by hyunsooda** [comment]
Hi @mingweishih, 

I have just one question from your comment. Could you let me know the specific CPU of your SGX2 machine is? Also, is there an entire table that lists CPUs that support SGX2 machines?

**Comment by radhikaj** [comment]
Please see https://www.intel.com/content/www/us/en/support/articles/000058764/software/intel-security-products.html.

**Comment by hyunsooda** [comment]
Thanks for reference @radhikaj
