### ISSUE TITLE
Question about sgx_emmt support

### ISSUE THREAD

**Issue by joydddd** [openenclave/openenclave#4290]
I'm using OE SDK on Intel SGX. I wonder if I can use `sgx_emmt` , `sgx_gdb` & Intel Vtune? 
I've tried to run sample/helloworld with sgx_gdb and `enable sgx_emmt` but there is no memory peak usage output. 
The SGX SDK suggest that `sgx_emmt` output is triggered by `sgx_destroy_enclave()`, I wonder if `oe_terminate_enclave()` in OE SDK does this.

**Comment by mingweishih** [comment]
I the think `sgx_emmt` is the feature of Intel SGX SDK.

@anakrish can you confirm?

**Comment by anakrish** [comment]
OE SDK doesn't not implement Intel SDK functions. Therefore sgx_emmt, sgx_gdb won't work.

For debugging, you can use oegdb which is similar to sgx_gdb.

To find out memory usage statistics, the following API is provided:
https://github.com/openenclave/openenclave/blob/31618a18a8d4f64c30d212aaa998a79874158ceb/include/openenclave/advanced/mallinfo.h#L49

Does this meet your needs?

**Comment by joydddd** [comment]
> OE SDK doesn't not implement Intel SDK functions. Therefore sgx_emmt, sgx_gdb won't work.
> 
> For debugging, you can use oegdb which is similar to sgx_gdb.
> 
> To find out memory usage statistics, the following API is provided:
> 
> https://github.com/openenclave/openenclave/blob/31618a18a8d4f64c30d212aaa998a79874158ceb/include/openenclave/advanced/mallinfo.h#L49
> 
> Does this meet your needs?

Yes! That's awesome.

**Comment by joydddd** [comment]
Does open enclave provide ocall, ecall counter? I'm trying to anaylize where these calls are from and what are they(especially system ocalls).

**Comment by mingweishih** [comment]
> Does open enclave provide ocall, ecall counter? I'm trying to anaylize where these calls are from and what are they(especially system ocalls).

No, we don't have such counters yet. But it's fairly straight forward to so by modifying the source code and build the customized SDK locally.

**Comment by radhikaj** [comment]
@joydddd, can you please use the work around from @mingweishih to unblock work on your end?
