### ISSUE TITLE
multi thread ecall support

### ISSUE THREAD

**Issue by superajun-wsj** [openenclave/openenclave#4295]
Hi, I write a demo that make two threads which created in host ecalls into enclave. And I observe the two thread's stack base  address and stack end address in enclave with oe-gdb tool, I found that stack base address and stack end address between two threads are all the same, it surprize me very much. Do you know why is it please?

**Comment by mingweishih** [comment]
What's your enclave configuration? The NumTCS should be equal or greater than the number of enclave threads you want to use.

**Comment by superajun-wsj** [comment]
my enclave configuration NumTCS is 8, much large then two thread in my demo.

**Comment by mingweishih** [comment]
> my enclave configuration NumTCS is 8, much larger then two thread in my demo.

Can you provide more detail with your demo and debug information? Each enclave thread should use its own stack.

**Comment by superajun-wsj** [comment]
I am sorry, maybe I made some mistake,  I will check it carefully. Thank you very much.
