### ISSUE TITLE
Unable to install Intel SGX DCAP Driver

### ISSUE THREAD

**Issue by aanand2300** [openenclave/openenclave#4296]
Hi,
I was following - [Install the Open Enclave SDK (Ubuntu 18.04)](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md) and I'm stuck in the Step 2. Here is the information about my CPU architecture:

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               158
Model name:          Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz
Stepping:            9
CPU MHz:             800.037
CPU max MHz:         4200.0000
CPU min MHz:         800.0000
BogoMIPS:            7599.80
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            8192K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d

And running `dmesg | grep -i sgx` cmd returns:

[1285382.283510] isgx: loading out-of-tree module taints kernel.
[1285382.283541] isgx: module verification failed: signature and/or required key missing - tainting kernel
[1285382.284234] intel_sgx: Intel SGX Driver v2.11.0
[1285382.284247] intel_sgx INT0E0C:00: EPC bank 0x90200000-0x95f80000
[1285382.285287] intel_sgx:  can not reset SGX LE public key hash MSRs
[1285382.285344] intel_sgx: second initialization call skipped

Running the `cpuid | grep -i sgx` cmd, I figured out that my system supports SGX1 but not FLC

Has anyone come across this or knows what could be the issue and how to resolve it? Any help is much appreciated.
Thanks in advance.

**Comment by radhikaj** [comment]
You cannot use a DCAP driver on a legacy platform that does not support FLC. You can use the legacy driver which is out of tree.
Can you please provide the output of cpuid. This will enable us to tell if the platform could support FLC.

**Comment by radhikaj** [comment]
@MWShan @jbdelcuv, thanks for the help.

**Comment by aanand2300** [comment]
Thanks @radhikaj  and @jbdelcuv for your response. Yes, it doesn't support FLC. Here is the output of `cpuid | grep -i sgx`
SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = false
   SGX capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = false

**Comment by MWShan** [comment]
The Out-of-Tree driver should be able to load on this platform.  It is sgx_linux_x64_driver_2.11.0_2d2b795.bin located here: [https://download.01.org/intel-sgx/sgx-linux/2.15/distro/ubuntu18.04-server](url)

For more details, please see "Out-of-Tree Driver Installation" in this document Intel_SGX_SW_Installation_Guide_for_Linux.pdf located here: [https://download.01.org/intel-sgx/sgx-linux/2.15/docs/](url)  

Note that using a non-FLC platform with the Out-of-Tree driver puts some limits on the type of attestation supported and the ability to sign/launch production (non-debug) enclaves.

**Comment by aanand2300** [comment]
Thanks @MWShan. I installed Out of Tree driver that you mentioned

**Comment by aanand2300** [comment]
Going a step back, I had another issue. In the same guide [Install the Open Enclave SDK (Ubuntu 18.04)](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md), I was following instructions in Platform requirements to [clone and build OE SDK](Install the Open Enclave SDK (Ubuntu 18.04)) since my device only supports SGX without FLC. I was able to Build successfully but when I tried to Run unit tests using `ctest`, some of my unit tests failed. Final section of the output is as follows:

96% tests passed, 20 tests failed out of 554

Total Test time (real) = 807.78 sec

The following tests did not run:
	275 - tests/report_attestation_without_enclave (Skipped)

The following tests FAILED:
	  1 - samples (Failed)
	 81 - tests/mbedtls_tls_e2e (Child aborted)
	 82 - tests/openssl_tls_e2e (Child aborted)
	 89 - tests/attestation_cert_api_mbedtls (Failed)
	 90 - tests/attestation_cert_api_openssl (Failed)
	 91 - tests/attestation_plugin_mbedtls (Child aborted)
	 92 - tests/attestation_plugin_openssl (Child aborted)
	 93 - tests/attestation_plugin_cert_mbedtls (Failed)
	 94 - tests/attestation_plugin_cert_openssl (Failed)
	103 - tests/debug-signed (Failed)
	104 - tests/nodebug-signed (Failed)
	274 - tests/report (Failed)
	518 - openssl_unsupported_baseline (Failed)
	546 - tests/child_process_ecall (Child aborted)
	547 - tests/child_process_destroy (Child aborted)
	548 - tests/child_process_create (Child aborted)
	549 - tests/child_process_create_more (Child aborted)
	550 - tests/sgx_zerobase_macro_only (Failed)
	551 - tests/sgx_zerobase_conf_only (Failed)
	552 - tests/sgx_zerobase_prop_macro_disable_conf_enable (Failed)
Errors while running CTest

Any suggestions why these tests fail and what can be done to resolve them?

**Comment by radhikaj** [comment]
Please see comment here: https://github.com/openenclave/openenclave/issues/4300#issuecomment-971477043 and https://github.com/openenclave/openenclave/issues/4300#issuecomment-972470671
These failures are expected in the legacy SGX driver and should be skipped when running on a non FLC device.
