### ISSUE TITLE
How to check the impact of EPC paging on my OE application?

### ISSUE THREAD

**Issue by DylanWangWQF** [openenclave/openenclave#4298]
Hi,
I'm running my applications on Ubuntu18.04, in a single CPU thread.
Is there a method to check when is it exceeds the limited EPC (i.e., 128MB) and the impact on the performance (e.g, how much drop)?

For example, if I increase the matrix size inside the enclave, when will it exceed the limited EPC?
I set `NumHeapPages=500000` and increase the matrix size,  it shows that the runtime increases linearly, cannot get any information about EPC paging.

**Comment by DylanWangWQF** [comment]
As explained in https://github.com/openenclave/openenclave/issues/4290 , **OE SDK doesn't not implement Intel SDK functions. Therefore sgx_emmt, sgx_gdb won't work.**

Is there any example to show how to use this (https://github.com/openenclave/openenclave/blob/31618a18a8d4f64c30d212aaa998a79874158ceb/include/openenclave/advanced/mallinfo.h#L49)?

**Comment by radhikaj** [comment]
See related issue https://github.com/openenclave/openenclave/issues/3002

**Comment by radhikaj** [comment]
Intel is trying to provide a kernel patch to measure EPC that is not yet upstreamed.
OE SDK does not support sgx_emmt that Intel SDK supports.

**Comment by DylanWangWQF** [comment]
The result is almost linear, does it prove that EPC paging cost in this sample is relatively low? (when exceeding PRM, ie, 111.473 MB, 133.25 MB...)

**Comment by anakrish** [comment]
@DylanWangWQF `oe_allocator_mallinfo` provides only the allocator statistics; it does not show SGX EPC paging. Your statistics show a linear increase in memory allocated by the enclave's allocator; it does not show how much EPC paging has happened in the background. As @radhikaj mentioned, EPC measurement requires a kernel patch from Intel.

**Comment by DylanWangWQF** [comment]
@anakrish 
OK. I get it. 
I try to explore the performance drop (ie, runtime increase) caused by EPC paging. 
As shown in the allocator statistics,  when allocated memory exceeds 157 MB or even larger (1000MB, 2000MB), it should trigger EPC paging although we cannot measure the details of EPC paging, right?
But the runtime increases linearly, what I understand is that only a small amount of paging is triggered and did not drastically reduce the performance, right?

**Comment by DylanWangWQF** [comment]
BTW, is there any plan to provide some tools like sgx_emmt for OE?

**Comment by DylanWangWQF** [comment]
Hi, @anakrish 
`oe_allocator_mallinfo` provides concrete allocator statistics or approximate results?

**Comment by anakrish** [comment]
The information is provided by the underlying allocator libraries - dlmalloc or snmalloc. Both provide quite accurate statistics.

**Comment by DylanWangWQF** [comment]
OK, I get it. Thanks!

**Comment by DylanWangWQF** [comment]
@anakrish 
I don’t know if it’s appropriate to ask the blow question here. I encountered an interesting problem.
**Problem:** The following two figures show the runtime and peak allocated heap size. When `x=90`, the runtime drastically increases which seems to be affected by EPC paging.
But as shown in the heap size figure, when `x=60`,  `heap size=98MB`. So, EPC paging should happen at this point (`x=60`). My EPC is limited to 128 MB, but the actual size should be around 90MB.

**Question:** Am I misunderstanding `oe_allocator_mallinfo `? The recorded memory usage by this API cannot represent the real memory usage inside the enclave?
<img width="457" alt="截屏2021-11-11 19 05 37" src="https://user-images.githubusercontent.com/26397284/141246487-46c785d9-782e-44fa-bc7b-745dda17a033.png">
<img width="452" alt="截屏2021-11-11 19 05 46" src="https://user-images.githubusercontent.com/26397284/141246523-1ae1751e-e889-4a14-b466-32b905e47a20.png">
