### ISSUE TITLE
File handling from the enclave

### ISSUE THREAD

**Issue by dgiantsidi** [openenclave/openenclave#4303]
Hi,

My application needs to access persistent files (using POSIX interface) to read/write data. The file handling should be done from a trusted function that runs inside the enclave.
By default, the enclave cannot open persistent files (open() returns error code 2 – file does not exist). 
How could I enable that? Is there any option to the conf file I could add?

Best,
Dimitra

**Comment by radhikaj** [comment]
You can do file I/O side an enclave. For an example on how to use files, see https://github.com/openenclave/openenclave/blob/cd72fd7069488ba6f453c8f5f47bd9fd9a6e6c0d/docs/UsingTheIOSubsystem.md and https://github.com/openenclave/openenclave/blob/cd72fd7069488ba6f453c8f5f47bd9fd9a6e6c0d/tests/syscall/hostfs/enc/enc.c#L16 

You can mount an absolute path from the host file system.

    if (oe_load_module_host_file_system() != OE_OK)
    {
        fprintf(stderr, "oe_load_module_host_file_system() failed\n");
        exit(1);
    }

   
    if (mount("/", "/", OE_HOST_FILE_SYSTEM, 0, NULL) != 0)
    {
        fprintf(stderr, "mount() failed\n");
        exit(1);
    }

**Comment by radhikaj** [comment]
Please reopen if you have more questions
