### ISSUE TITLE
Confusing return values from mmap

### ISSUE THREAD

**Issue by wintersteiger** [openenclave/openenclave#4329]
In the 0.17.5 release, `mmap` still returns `EPERM` to indicate that it is not implemented/supported. This is confusing because `EPERM` is `+1`, which looks like a valid pointer to `0x01` to existing applications. It would be nice if this could be changed to return `-1` (or `MAP_FAILED`) to indicate an error in the usual way.

Similarly, in `master`, it returns `0` when some checks fail, e.g. [here](https://github.com/openenclave/openenclave/blob/7b87ea741367ba27f1b42290b9c4dd3d8cad7b00/libc/mman.c#L181), which would easily be fixed by setting `void* ptr = MAP_FAILED;`.

CC @letmaik

**Comment by mingweishih** [comment]
@anakrish can you take a look?

**Comment by wintersteiger** [comment]
No, I don't have a small example, this was part of a larger integration.

In 0.17.5, `mmap` returns `EPERM` here: https://github.com/openenclave/openenclave/blob/f0b8d789983db0f72a1851e463f5537918cc58d8/libc/syscalls.c#L36 and `EPERM == 0x01`, instead of `NULL` or `MAP_FAILED`. 

I think the code in master has changed since my initial report. I agree, that `return MAP_FAILED;` looks perfectly fine.

**Comment by anakrish** [comment]
Great. I will close this issue.
