### ISSUE TITLE
Sealing/Unsealing with NULL additional data results in `OE_INVALID_PARAMETER`

### ISSUE THREAD

**Issue by octaviansima** [openenclave/openenclave#4334]
When following the docs at https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/SealingAPI.md, I noticed that using NULL additional data actually results in `oe_seal` and `oe_unseal` returning `OE_INVALID_PARAMETER`. It looks like the check here: https://github.com/openenclave/openenclave/blob/cd72fd7069488ba6f453c8f5f47bd9fd9a6e6c0d/enclave/core/seal.c#L119

is failing due to `oe_is_within_enclave` returning false if the pointer supplied is NULL:

https://github.com/openenclave/openenclave/blob/cd72fd7069488ba6f453c8f5f47bd9fd9a6e6c0d/include/openenclave/enclave.h#L101

It looks like the other optional params to sealing/unsealing would also fail this check if supplied as NULL.

**Comment by mingweishih** [comment]
I will take a look

**Comment by RRathna** [comment]
PR #4398 would fix this
