### ISSUE TITLE
Maintainers have code coverage information as a metric of Open Enclave SDK quality

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#437]
Preferably before GA, maintainer of the Open Enclave repo should have some kind of code coverage metric to inform intuitions about the state of testing over the code base. This story tracks the investigation into appropriate tools (e.g. gcov/lcov)

This should be done after #353 is complete as Clang may provide other options or require additional tweaking for code coverage (e.g. incorporate llvm-cov into the workflow)

**Comment by mingweishih** [comment]
Close per #2984. For supporting code coverage on Windows and improve the accuracy of the code coverage, we can open new issues to track them.
