### ISSUE TITLE
"Enclave not authorized to run" even when running as root

### ISSUE THREAD

**Issue by xanderdunn** [openenclave/openenclave#4377]
I just ported an SGX project from Intel SDK to OpenEnclave SDK. Everything compiles and links correctly. However, at runtime when I call to create the enclave from the host app, I get this error:
```
[error_driver2api sgx_enclave_common.cpp:273] Enclave not authorized to run, .e.g. provisioning enclave hosted in app without access rights to /dev/sgx_provision. You need add the user id to group sgx_prv or run the app as root.
2022-02-14T22:06:28-0500.276228Z [(H)ERROR] tid(0x7fd9d2693780) | enclave_load_data failed (addr=0xa1016000, prot=0x3, err=0x6) (oe_result_t=OE_PLATFORM_ERROR) [/home/xander/dev/openenclave/host/sgx/sgxload.c:oe_sgx_load_enclave_data:697]
2022-02-14T22:06:28-0500.276247Z [(H)ERROR] tid(0x7fd9d2693780) | :OE_PLATFORM_ERROR [/home/xander/dev/openenclave/host/sgx/loadelf.c:_add_segment_pages:652]
2022-02-14T22:06:28-0500.276251Z [(H)ERROR] tid(0x7fd9d2693780) | :OE_PLATFORM_ERROR [/home/xander/dev/openenclave/host/sgx/loadelf.c:_add_pages:685]
2022-02-14T22:06:28-0500.276256Z [(H)ERROR] tid(0x7fd9d2693780) | :OE_PLATFORM_ERROR [/home/xander/dev/openenclave/host/sgx/create.c:oe_sgx_build_enclave:980]
2022-02-14T22:06:28-0500.276529Z [(H)ERROR] tid(0x7fd9d2693780) | :OE_PLATFORM_ERROR [/home/xander/dev/openenclave/host/sgx/create.c:oe_create_enclave:1207]
ERROR: Failed to initialize enclave with error code 21
```

I've tried both running it as my user, which is a member of `sgx_prv`:
```
$ grep "sgx_prv" /etc/group
sgx_prv:x:115:aesmd,xander
```
As well as trying to run it as root with `sudo ./build/my_app`. From `htop`, the user is correctly shown as root:
```
6303 root       20   0  496M 10160  8840 S  0.0  0.0  0:00.00 ./build/my_app
```

The creation invocation:
```c++
oe_enclave_t* global_eid;
...
  if (main_thread_id == std::this_thread::get_id()) {
      printf("This is the main thread\n");
  }
  ret = oe_create_Enclave_enclave(enclave_file_path.c_str(),
                                      OE_ENCLAVE_TYPE_SGX,
                                      OE_ENCLAVE_FLAG_DEBUG,
                                      NULL,
                                      0,
                                      &global_eid);
```
The above print statement confirms it's being called on the main thread.

And the Enclave/Enclave.conf:
```
Debug=1
NumHeapPages=36864
NumStackPages=64
NumTCS=3
ProductID=1
SecurityVersion=1
```

Furthermore, I can successfully run other OpenSDK enclaves without issue. I've run the full OpenEnclave test suite successfully on this machine, and I am successfully running another OpenEnclave project of mine on the same machine. It works both as a `sudo` call and as a regular user call. There is something specific to the above project that is preventing the enclave from being provisioned. Any thoughts on what may be preventing enclave provisioning permission, or further debugging steps?

**Comment by anakrish** [comment]
Does your enclave by any chance have the provisioning bit set in its attributes?
See details here:
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/driver/linux/README.md#launching-an-enclave-with-provision-bit-set

**Comment by xanderdunn** [comment]
Thanks for your help. I read the section on the provisioning bit, but I didn't understand how to set the provisioning bit in an enclave's attributes. Do you know where I should look to see if this is being set?

**Comment by xanderdunn** [comment]
Something in my Makefile was causing this. Something about how it was being built. I don't know exactly what it was, but by swapping out my Makefile with the Makefiles from OpenEnclave's attested_tls sample and modifying the Makefiles to suit my project, I was able to build, run, and create the enclave without seeing this permission error.
