### ISSUE TITLE
Bug: oe_seal additional_data parameter Cannot Be NULL

### ISSUE THREAD

**Issue by xanderdunn** [openenclave/openenclave#4384]
The `additional_data` parameter of `oe_seal` is described as optional:
>      * @param[in] additional_data Optional additional data to be included in
>      * authentication (MAC calculation). If not \c NULL, \c oe_seal() guarantees
>      * that the whole \p additional_data buffer resides in enclave memory.

The Sealing design doc [here](https://github.com/openenclave/openenclave/blob/cd72fd7069488ba6f453c8f5f47bd9fd9a6e6c0d/docs/DesignDocs/SealingAPI.md#sealing-and-unsealing) gives a minimal usage example where `additional_data` is set to `NULL`:
```c++
#include <openenclave/seal.h>

oe_result_t seal_my_data(
    const uint8_t* data,
    size_t data_size,
    uint8_t** blob,
    size_t* blob_size)
{
    const oe_seal_setting_t seal_settings[] = {
        OE_SEAL_SET_POLICY(OE_SEAL_POLICY_PRODUCT),
    };
    return oe_seal(
        NULL,
        seal_settings,
        sizeof(seal_settings) / sizeof(*seal_settings),
        data,
        data_size,
        NULL,
        0,
        blob,
        blob_size);
}
```

However, the implementation of `oe_seal` makes this check:
```c++
if (... ||
       !oe_is_within_enclave(additional_data, additional_data_size))
        return OE_INVALID_PARAMETER;
```
See [here](https://github.com/openenclave/openenclave/blob/cd72fd7069488ba6f453c8f5f47bd9fd9a6e6c0d/enclave/core/seal.c#L119)

A simple test shows that this will return `false` when `additional_data == NULL`:
```c++
     if (oe_is_within_enclave(NULL, 0)) {
         printf("Within enclave\n");
     } else {
         printf("Not within enclave\n");
     }
```
Indeed, at runtime the output I see is `Not within enclave`.

The above `!` makes this true, so it returns `OE_INVALID_PARAMETER` despite the fact that the API indicates `NULL` is a valid input here.

So, I try this:
```c++
const uint8_t* additional_data[0];
size_t additional_data_size = 0;
```

Which passes the above check, but now this check fails:
```c++
(additional_data == NULL) != (additional_data_size == 0)
```

It appears the only situation where `oe_seal` works is when `additional_data` is non-null and contains more than 0 bytes. The data-sealing sample only attempts this scenario.

**Comment by mingweishih** [comment]
Thanks for your report! Please let us know if you want to contribute a fix.

**Comment by RRathna** [comment]
PR #4398 fixes this issue. Please verify and re-open if not.
