### ISSUE TITLE
Intel SGX server how to enable in azure.

### ISSUE THREAD

**Issue by sevenbitsyogi** [openenclave/openenclave#4396]
![Screenshot from 2022-02-28 19-45-41](https://user-images.githubusercontent.com/56574509/156011040-f1ed3898-16a7-4b2f-9ec9-e25737efe370.png)
How to enable SGX server in ubuntu azure virtual Machine?

**Comment by radhikaj** [comment]
Please see https://docs.microsoft.com/en-us/azure/confidential-computing/confidential-computing-enclaves
You need to select a VM SKU that supports SGX.

**Comment by radhikaj** [comment]
Please let us know if you have further questions.

**Comment by sevenbitsyogi** [comment]
@radhikaj In azure UI where I select VM SKU?

**Comment by dthaler** [comment]
> @radhikaj In azure UI where I select VM SKU?

See https://docs.microsoft.com/en-us/azure/confidential-computing/quick-create-portal (which is linked from the page Radhika mentioned above) which I think answers your question in the walkthrough.
