### ISSUE TITLE
Enable RIPEMD-160 in OpenSSL

### ISSUE THREAD

**Issue by xanderdunn** [openenclave/openenclave#4409]
Bitcoin uses RIPEMD-160 to create an address, so we need access to this function. The OpenEnclave port of OpenSSL has this disabled, as described [here](https://github.com/openenclave/openenclave/blob/master/docs/OpenSSLSupport.md).

**Comment by xanderdunn** [comment]
It was easy enough for us to bring this functionality into our project via a bitcoin library implementation. Happy to close this if it's not a priority.

**Comment by mingweishih** [comment]
Close this issue for now.
