### ISSUE TITLE
Are OpenEnclave APT Repo Builds LVI Mitigated?

### ISSUE THREAD

**Issue by xanderdunn** [openenclave/openenclave#4411]
[This](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_18.04.md) README describes installing OpenEnclave SDK via an apt repo rather than from source.

[This](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1FLCGettingStarted.md) README describes extra build flags for building OpenEnclave SDK with LVI mitigation:
```
cmake -G "Ninja" .. \
-DLVI_MITIGATION=ControlFlow \
-DLVI_MITIGATION_BINDIR=/usr/local/lvi-mitigation/bin
```

Are the apt repo builds of OpenEnclave built with these LVI mitigations? I believe both the DCv2 and DCv3 Intel processors on Azure are affected by the LVI vulnerability, so is there any reason a non-LVI mitigated build of OpenEnclave SDK would be needed?

**Comment by mingweishih** [comment]
We do provide LVI-mitigated libraries and build tools for users to opt-in. We don't enforce the mitigation by default because of the impact of the run-time performance is huge.

Please refer to: https://github.com/openenclave/openenclave/tree/master/samples/helloworld#prerequisites-1
The helloworld sample should illustrate how to enable LVI mitigation.

**Comment by xanderdunn** [comment]
Ok thanks I believe this answers my question - the OpenEnclave apt repo builds are not built with the LVI mitigations, so we'll need to build from source if we want that. Thanks, I'll follow the instructions you linked.

**Comment by mingweishih** [comment]
> Ok thanks I believe this answers my question - the OpenEnclave apt repo builds are not built with the LVI mitigations, so we'll need to build from source if we want that. Thanks, I'll follow the instructions you linked.

Not exactly. The OE apt packages do provide LVI-mitigated libraries and tool. It's that the user need to adopt them to build the enclave.

If you check the repo, you can find:
```
/opt/openenclave/lib/openenclave/enclave$ ls
libmbedcrypto-lvi-cfg.a       liboedebugmalloc.a           liboelibcxx-lvi-cfg.a
libmbedcrypto.a               liboeenclave-lvi-cfg.a       liboelibcxx.a
libmbedtls-lvi-cfg.a          liboeenclave.a               liboesnmalloc-lvi-cfg.a
libmbedtls.a                  liboehostepoll-lvi-cfg.a     liboesnmalloc.a
libmbedx509-lvi-cfg.a         liboehostepoll.a             liboesymcryptengine.a
libmbedx509.a                 liboehostfs-lvi-cfg.a        liboesyscall-lvi-cfg.a
liboecore-lvi-cfg.a           liboehostfs.a                liboesyscall.a
liboecore.a                   liboehostresolver-lvi-cfg.a  libopensslcrypto-lvi-cfg.a
liboecryptombedtls-lvi-cfg.a  liboehostresolver.a          libopensslcrypto.a
liboecryptombedtls.a          liboehostsock-lvi-cfg.a      libopensslssl-lvi-cfg.a
liboecryptoopenssl-lvi-cfg.a  liboehostsock.a              libopensslssl.a
liboecryptoopenssl.a          liboelibc-lvi-cfg.a          objects-Debug
liboedebugmalloc-lvi-cfg.a    liboelibc.a                  objects-RelWithDebInfo
```

Those with -lvi-cfg.a are the libraries with mitigation. However, you need to follow the instruction so that your enclave will link against them.

**Comment by xanderdunn** [comment]
I see, I have a better understanding now. The apt package installs both versions of the libraries and the build system for our project needs to make sure the correct ones are chosen. I think [this](https://github.com/openenclave/openenclave/blob/master/samples/helloworld/enclave/Makefile#L8) is the critical step in the project you linked.

**Comment by mingweishih** [comment]
> I see, I have a better understanding now. The apt package installs both versions of the libraries and the build system for our project needs to make sure the correct ones are chosen. I think [this](https://github.com/openenclave/openenclave/blob/master/samples/helloworld/enclave/Makefile#L8) is the critical step in the project you linked.

That's correct!
