### ISSUE TITLE
does openenclave plan to design compatibility with vm-based tee please?

### ISSUE THREAD

**Issue by superajun-wsj** [openenclave/openenclave#4427]
As we know, openenclave supports both sgx tee and trustzone tee, and it's host-enclave partition programming model. My question is that, how do you think about coming vm-based tee such as TDX please? Is host-enclave partition programming model still suitable to TDX tee please?

**Comment by anakrish** [comment]
@bodzhang @radhikaj

**Comment by radhikaj** [comment]
@superajun-wsj, the goal of OE SDK is to be TEE agnostic and support multiple TEEs. The OE APIs themselves can be used for a VM-based TEE. The partitioned model of OE can make sense for VM based TEEs in certain scenarios. 
What scenarios did you have in mind. Please let us know if you would like to contribute this feature.

**Comment by superajun-wsj** [comment]
@radhikaj thank you for your response. I have no plan to contribute to this feature, just have this question, now I get the answer from you, thanks again.
