### ISSUE TITLE
Building OE with Visual Studio 2019 fail unexpectedly

### ISSUE THREAD

**Issue by mingweishih** [openenclave/openenclave#4436]
While the [documentation](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/WindowsSGX1FLCGettingStarted.md#buildinginstallation-on-windows-using-developer-command-prompt) says that the OE can be built with VS 2019. However, we got a report that users had encountered build failures with it. Need further investigation.

**Comment by anakrish** [comment]
It could be due to  compiler upgrades in Visual Studio updates. Do we have error logs?

**Comment by mingweishih** [comment]
Here is one example

![MicrosoftTeams-image](https://user-images.githubusercontent.com/58993167/160673640-18f729ab-2f7d-4e3a-8600-13230857fb1f.png)

**Comment by CyanDevs** [comment]
Apparently, we are using VS 2017 in CI so it definitely doesn't catch this. We should update it.
https://github.com/openenclave/openenclave/blob/master/scripts/install-windows-prereqs.ps1#L418-L419

**Comment by mingweishih** [comment]
Let's enable the test on CI, and then we can investigate more on the failure.

**Comment by CyanDevs** [comment]
Resolved by https://github.com/openenclave/openenclave/pull/4521 and https://github.com/openenclave/openenclave/pull/4625
