### ISSUE TITLE
Ansible Script Installs Old Version of Intel SGX DCAP Driver on Ubuntu 18.04

### ISSUE THREAD

**Issue by xanderdunn** [openenclave/openenclave#4463]
The latest Ubuntu 18.04 DCAP driver from Intel is 1.41, see [here](https://download.01.org/intel-sgx/sgx-dcap/1.13/linux/distro/ubuntu18.04-server/). 

However, the Ansible script `scripts/ansible/oe-contributors-acc-setup.yml` described [here](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1FLCGettingStarted.md#install-project-requirements) installs version 1.35 of the Intel SGX DCAP Driver.
The version is defined in the Ansible config files [here](https://github.com/openenclave/openenclave/blob/master/scripts/ansible/roles/linux/intel/vars/ubuntu/bionic.yml#L5), although the version for Ubuntu 20.04 appears to be the latest.

**Comment by radhikaj** [comment]
Hey @xanderdunn,

The canonical image on Azure VMs has 1.33 version of driver. The script is consistent with this. This can be overridden by developers and a newer drive can be installed after ansible has run.

**Comment by radhikaj** [comment]
Please reopen if you have follow up questions.

**Comment by xanderdunn** [comment]
Do you know why it is intentionally kept behind latest? Unless there’s an 18.04-specific bug it seems like using old drivers for security critical applications is not the right choice.
