### ISSUE TITLE
R_X86_64_IRELATIV

### ISSUE THREAD

**Issue by aep** [openenclave/openenclave#4469]
glibc emits a bunch of R_X86_64_IRELATIV relocations. i think its a jump table for cpu specific implementions of things like strcmp

```
000000f421d0  000000000025 R_X86_64_IRELATIV                    a110c0

19627: 0000000000a110c0    85 FUNC    LOCAL  DEFAULT    7 strcmp_ifunc

```

should these be implemented in the loader or can gcc be told to not emit those?

**Comment by anakrish** [comment]
@aep What are the compiler flags used to compile the code?

**Comment by aep** [comment]
not idea, that's hidden inside gccgo.
all i added was "-ftls-model=local-exec"

would have to strace the call to gcc i guess, but what am i looking for?

**Comment by aep** [comment]
not much interesting here. i passed -ftls-model=local-exec 

```
"/usr/bin/gcc", "-I", "/src", "-fPIC", "-m64", "-pthread", "-fmessage-length=0", "-fdebug-prefix-map=/tmp/go-build"..., "-gno-record-gcc-switches", "-I", "/tmp/go-build1553405746/b001/", "-g", "-O2", "-ftls-model=local-exec", "-fpic", "-I/src/build/php-8.1.4", "-I/src/build/php-8.1.4/Zend", "-I/src/build/php-8.1.4/main", "-I/src/build/php-8.1.4/TSRM", "-o", "/tmp/go-build1553405746/b001/_x0"..., "-c", "demo.cgo2.c"
```

**Comment by aep** [comment]
here's a trivial repro

```C
//test.c
#include <stdio.h>
#include <string.h>

int main(void)
{
    char tmp[10];
    char target[10];
    fgets(tmp, 10, stdin);
    strcpy(target, tmp);
}

```

```
gcc -o test -static test.c
```

```
i guess gcc passes -static somewhere.
but without -static you get a R_X86_64_COPY on stdin, which is also not supported
```

https://github.com/openenclave/openenclave/blob/b2db393080ddb25e1462bce1bb27ee2fe470c9be/host/sgx/elf.c#L1917

**Comment by aep** [comment]
Btw I tried linking musl instead of glibc which has no such relocs, but all the syscalls fail. So I guess oe somehow ties into glibc symbols directly rather than catching syscalls?

**Comment by aep** [comment]
uh wait, you HAVE to use musl?

this is strange because ego https://github.com/edgelesssys/ego specifically links the hosts gnu libc and i have no idea how thats supposed to work at all.

i'll open a bug in ego.

**Comment by anakrish** [comment]
> uh wait, you HAVE to use musl?
Yes, OE links enclaves with its own C library (MUSL based). For that reason, when an enclave is compiled, `-nostdinc` option is passed to prevent inclusion of standard headers (and platform's glibc headers).

Your specific issue is best followed up at ego repository.

**Comment by anakrish** [comment]
I'm closing this issue for now. Go programs is not something OE natively supports. Feel free to reopen after follow up at ego repository.

**Comment by aep** [comment]
yep thanks for pointing me in the right direction.
