### ISSUE TITLE
Linking library to enclave code

### ISSUE THREAD

**Issue by cknabs** [openenclave/openenclave#4533]
# Issue
I'm using Visual Studio 2019 and the OpenEnclave VS extension, and I'm trying to link an external library (.lib file and .h headers). 

I've created a VS solution as described in [the tutorial](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/VisualStudioWindows.md), and I've set the appropriate include/library paths in the project settings (as described [here](https://docs.microsoft.com/en-us/cpp/build/adding-references-in-visual-cpp-projects)). 

I can then use the library without issue in my `App.cpp` file (the one on the host, which sets up and connects to the enclave). 
However, linking fails when I try to include the library in my `enclave_ecalls.cpp` file (the code running on the enclave). 
The error message I get is `ld.lld : error : unable to find library -lseal-4.0.lib`. 

I also tried to add `-L<MY_LIB_PATH>` to the "Additional Compiler Options" (Configuration Properties > Open Enclave Clang), as well as to the compiler options (Configuration Properties > C/C++ > Command Line > Additional Options), and to the linker options (Configuration Properties > Linker > Command Line > Additional Options) to no avail.

How can one link a library to be used inside an enclave?

# More info
Visual Studio 19 on Windows 10, SGX1 support (without FLC)
The library in question is [SEAL](https://github.com/microsoft/SEAL)

# Steps to reproduce

1. Create a new VS OpenEnclave project as described in the [the tutorial](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/VisualStudioWindows.md). 
2. Select a library file `LIB_PATH\mylib.lib` and header files `HEADER_PATH\*.h`
3. Set include and library paths for the `App` project as described [here](https://docs.microsoft.com/en-us/cpp/build/adding-references-in-visual-cpp-projects)
4. Include library in `App.cpp` and some code that calls it; the code compiles and runs
5. Set include and library paths for the `Enclave` project
6. Build fails, because the library cannot be found by the linker

**Comment by radhikaj** [comment]
Open Enclave uses Linux archive libs inside the enclave. You can only link to a .a file inside the enclave. Please see samples for how you would link against a .a inside the enclave. The .a would need to be compiled with the right set of flags.
