### ISSUE TITLE
Dependapot - update-types can be used with `ignore`, not with `allow`

### ISSUE THREAD

**Issue by radhikaj** [openenclave/openenclave#4545]
Dependabot is complaining about yml here: https://github.com/openenclave/openenclave/pull/4444 and https://github.com/openenclave/openenclave/pull/4445 and #4442

**Comment by dthaler** [comment]
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file for docs on what config options are legal.
