### ISSUE TITLE
SGX under VMWare Virtual Machine (SGX is not enabled in IA32_FEATURE_CONTROL MSR)

### ISSUE THREAD

**Issue by verd1c** [openenclave/openenclave#4552]
Hi, I own a i7 6700 CPU that has Intel SGX enabled through the BIOS. I am trying to install openenclave inside of a Ubuntu 18 Virtual Machine running on top of VMWare on Windows 11. However, after installing the driver, I get the following error:

```
SGX is not enabled in IA32_FEATURE_CONTROL MSR
```

what could this be? Am I not able to get SGX passthrough inside the VM? Will I have to dualboot instead to achieve my needs?

**Comment by anakrish** [comment]
@MWShan, do you have documentation on using SGX with VMWare?

**Comment by MWShan** [comment]
VMware has provided documentation here: [https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-C81950B5-CD0A-40CA-9945-1104A92F4455.html#securing-virtual-machines-with-intel-software-guard-extensions-0] and a blog here: [https://blogs.vmware.com/vsphere/2020/04/vsphere-7-vsgx-secure-enclaves.html](url)
