### ISSUE TITLE
oe_get_evidence: get SGX linkable EPID evidence format but return "OE_NOT_FOUND"

### ISSUE THREAD

**Issue by pw0rld** [openenclave/openenclave#4599]
Hello, I want to get the SGX linkable EPID evidence format, but I get an error.
I saw the [docs](https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/Attestation_API_Proposal.md), in openenclave, it supports the use oe_get_evidence to get linkable EPID but not oe_verify_evidence to verify it.
I search for the example of how to use oe_get_evidence in GitHub and found it in this [code file](https://github.com/openenclave/openenclave/blob/master/tests/attestation_plugin/enc/enc.c#L327).
Here is the code I copied
```
    TRACE_ENCLAVE("Here is epid linkable uuid");
    uint8_t* evidence_epid = nullptr;
    size_t evidence_epid_size;
    uint8_t* endorsements_epid = nullptr;
    size_t endorsements_epid_size = 0;
    static const oe_uuid_t _epid_linkable_uuid = {
        OE_FORMAT_UUID_SGX_EPID_LINKABLE};

    result = oe_get_evidence(
            &_epid_linkable_uuid,
            0,
            NULL,
            0,
            NULL,
            0,
            &evidence_epid,
            &evidence_epid_size,
            &endorsements_epid,
            &endorsements_epid_size);
        if (result != OE_OK)
        {
            TRACE_ENCLAVE(
                "Here is epid linkable uuid failed %s", oe_result_str(result));
            // goto exit;
        }
    TRACE_ENCLAVE("END is epid linkable uuid");
    exit(1);

```
The result:
```
Enclave1: ***/home/cooper/Desktop/openenclave/samples/attestation/common/attestation.cpp(70): Here is epid linkable uuid
Enclave1: ***/home/cooper/Desktop/openenclave/samples/attestation/common/attestation.cpp(94): Here is epid linkable uuid failed OE_NOT_FOUND
Enclave1: ***/home/cooper/Desktop/openenclave/samples/attestation/common/attestation.cpp(97): END is epid linkable uuid
```

But I get a "OE_NOT_FOUND" error.
So, is there a pre-requisite I missing? 
Any advice on using EPID linkable uuid? Thanks.

**Comment by mingweishih** [comment]
Can you check if you're using DCAP out-of-process mode (i.e., `SGX_AESM_ADDR` env variable is defined)? See https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/SGX_QuoteEx_Integration.md#host-side-plugin-library-link-with-the-sgx-dcap-and-quote-ex-libraries for more details.

**Comment by pw0rld** [comment]
> Can you check if you're using DCAP out-of-process mode (i.e., `SGX_AESM_ADDR` env variable is defined)? See https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/SGX_QuoteEx_Integration.md#host-side-plugin-library-link-with-the-sgx-dcap-and-quote-ex-libraries for more details.

Oh. Thanks. I set the variable `SGX_AESM_ADDR `.  And oe_get_evidence successful.
