### ISSUE TITLE
cmake error on Symcrypt

### ISSUE THREAD

**Issue by Eremiel** [openenclave/openenclave#4603]
root@t2:~/openenclave/build# cmake -G "Unix Makefiles" ..
-- Build type: Debug
CMake Warning at cmake/compiler_settings.cmake:15 (message):
  The GCC support on x86 platforms has been deprecated.  Build problems may
  occur.  Consider using Clang instead.
Call Stack (most recent call first):
  CMakeLists.txt:267 (include)

-- Not using CCache
CMake Warning at cmake/compiler_settings.cmake:85 (message):
  Spectre 1 mitigation NOT supported.
Call Stack (most recent call first):
  CMakeLists.txt:267 (include)

-- Valgrind not found
-- Looking for crypto library - found
-- Looking for dl library - found
CMake Error at 3rdparty/symcrypt_engine/CMakeLists.txt:121 (message):
  Cannot find clang intrinstics header (required by SymCrypt OpenSSL engine)

-- Configuring incomplete, errors occurred!
See also "/root/openenclave/build/CMakeFiles/CMakeOutput.log".
See also "/root/openenclave/build/CMakeFiles/CMakeError.log".

error log says:
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /root/openenclave/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_d05b9/fast && /usr/bin/make -f CMakeFiles/cmTC_d05b9.dir/build.make CMakeFiles/cmTC_d05b9.dir/build
make[1]: Entering directory '/root/openenclave/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_d05b9.dir/src.c.o
/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD   -std=gnu11 -o CMakeFiles/cmTC_d05b9.dir/src.c.o   -c /root/openenclave/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_d05b9
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d05b9.dir/link.txt --verbose=1
/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD    CMakeFiles/cmTC_d05b9.dir/src.c.o  -o cmTC_d05b9
/usr/bin/ld: CMakeFiles/cmTC_d05b9.dir/src.c.o: in function `main':
src.c:(.text+0x46): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x52): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x63): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_d05b9.dir/build.make:87: cmTC_d05b9] Error 1
make[1]: Leaving directory '/root/openenclave/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_d05b9/fast] Error 2

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /root/openenclave/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_2f81c/fast && /usr/bin/make -f CMakeFiles/cmTC_2f81c.dir/build.make CMakeFiles/cmTC_2f81c.dir/build
make[1]: Entering directory '/root/openenclave/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_2f81c.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -std=gnu11 -o CMakeFiles/cmTC_2f81c.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.16/Modules/CheckFunctionExists.c
Linking C executable cmTC_2f81c
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2f81c.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_2f81c.dir/CheckFunctionExists.c.o  -o cmTC_2f81c  -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_2f81c.dir/build.make:87: cmTC_2f81c] Error 1
make[1]: Leaving directory '/root/openenclave/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_2f81c/fast] Error 2

Can anyone help me to solve this issue?

**Comment by mingweishih** [comment]
Can you try to use clang-10 instead of gcc?

**Comment by radhikaj** [comment]
closing issue. Please reopen if you are unable to use clang-10
