### ISSUE TITLE
In Windows, calling oe_set_enclave_log_level() after oe_terminate_enclave() causes segfault

### ISSUE THREAD

**Issue by RRathna** [openenclave/openenclave#4604]
A call to the API oe_set_enclave_log_level() is made after oe_terminate_enclave() had been called on the enclave. The expected behavior is to return OE_NOT_FOUND. But, in windows, the enclave struct somehow holds garbage value and proceeds to access the enclave's ecall table array. This leads to a segmentation fault.

**Comment by radhikaj** [comment]
This is by design. You cannot call an enclave API after the enclave is terminated. Do see if you can check if the enclave is terminated in oe_set_enclave_log_level
