### ISSUE TITLE
Stack/Heap Pages Exceeding EPC Size

### ISSUE THREAD

**Issue by jonahrosenblum** [openenclave/openenclave#4628]
Using information from [this page](https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/buildandsign.md) I know that we can set the number of pages on the stack/heap when building our enclave application. Here is my question: if I am using a machine with SGX 1 enabled (and therefore a max EPC of 128 MB) why am I able to set the number of stack/heap pages to exceed 128 MB without an error occurring? I have tested with up to ~600 MB worth of heap pages and was actually able to allocate ~600 MB worth of pages in my application despite supposedly being capped at 128 MB. Is there something I am missing? I was told that paging was not possible in SGX 1, but maybe I was misinformed?

**Comment by anakrish** [comment]
On Linux, the sgx driver supports EPC paging which allows creating enclaves that take up more memory than the EPC limit.

**Comment by jonahrosenblum** [comment]
@anakrish Ok this clears up a lot. One last quick question: is `NumHeapPages` the upper limit on the number of head pages (the application can allocate up to this number) or is it the number of heap pages that are allocated and given to the enclave when it is created and then all dynamic allocations are pulled from this pool.

**Comment by anakrish** [comment]
Between the two, it is more the former. It is the total number of pages in the heap within the enclave. If the enclave allocates more memory than is available in the enclave's heap, then malloc will fail once the heap has been exhausted.
However, keep in mind that the pages in the enclave's heap may not be resident in memory; they will be swapped in and out by EPC paging logic in the driver.
