### ISSUE TITLE
Ctest not working after installing open enclave sdk

### ISSUE THREAD

**Issue by Kshitij0910** [openenclave/openenclave#4634]
After running ctest to test open enclave SDK only 12% test cases passed.
I am running this on Ubuntu 18.04.
Any help is appreciated.

**Comment by anakrish** [comment]
Can you share the failures?

**Comment by Kshitij0910** [comment]
https://p.ip.fi/Q5EM <-- Here are the test cases that failed
https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SGX1FLCGettingStarted.md
I am try to execute the commands mentioned in the above readme file. (In simulation mode)

**Comment by Kshitij0910** [comment]
https://p.ip.fi/vhrD <-- This is the logtest.log file
How do I enter SGX mode? (My machine does support SGX)

**Comment by radhikaj** [comment]
You need a machine with SGX to use SGX mode.

**Comment by radhikaj** [comment]
Hi @Kshitij0910 , From the log you shared it looks like simulation mode is not turned on.
On a non SGX machine, please use https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/Contributors/SimulatorGettingStarted.md
Can you try OE_SIMULATION=1 ctest when running on a non SGX machine?

> get_driver_type /home/sgx/jenkins/linux-ubuntuServer-release-build-trunk-217/build_target/PROD/label/Builder-UbuntuSrv18/label_exp/ubuntu64/linux-trunk-opensource/psw/urts/linux/edmm_utility.cpp:116] Failed to open Intel SGX device.
: /home/kshitij/openenclave/tests/tools/oesign/test-enclave/host/host.c(65): error: oe_create_crypto_enclave(): result=21
2022-09-24T05:07:14+0530.868296Z [(H)ERROR] tid(0x7fafdd9dcb80) | enclave_create with ENCLAVE_TYPE_SGX1 type failed (err=0x1) (oe_result_t=OE_PLATFORM_ERROR) [/home/kshitij/openenclave/host/sgx/sgxload.c:oe_sgx_create_enclave:454]

**Comment by Kshitij0910** [comment]
Hi, @radhikaj, running OE_SIMULATION=1 ctest worked. Thank you.
