### ISSUE TITLE
OE is launching provisioning enclaves when provisioning key is not needed

### ISSUE THREAD

**Issue by octaviansima** [openenclave/openenclave#4636]
Hi all, we recently updated our machines to Ubuntu 20.04, ~~which contains SGX driver version 1.41~~ which contains the in-kernel DCAP driver (Linux kernel 5.15), and are now running into the following issue in the `oe_create_..._enclave` call:

```
[error_driver2api sgx_enclave_common.cpp:261] Enclave not authorized to run, .e.g. provisioning enclave hosted in app without access rights to /dev/sgx_provision. You need add the user id to group sgx_prv or run the app as root.
[load_pce ../pce_wrapper.cpp:188] Error, call sgx_create_enclave for PCE fail [load_pce], SGXError:4004.
```

According to the SGX docs [here](https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/driver/linux#launching-an-enclave-with-provision-bit-set), there are stricter checks in driver 1.41 to avoid launching provisioning enclaves that are not part of the `sgx_prv` user group. I can add the user to that group as a hotfix, and confirmed that worked, but it's not clear to me why OE would be attempting to launch a provisioning enclave in the first place (we are signing the enclave binary with our own key using `oesign`). 

I did notice there are docs on setting [the provisioning bit manually](https://github.com/openenclave/openenclave/blob/cd72fd7069488ba6f453c8f5f47bd9fd9a6e6c0d/docs/GettingStartedDocs/IntelSDKPortingGuideLinux.md#supported-enclave-settings-by-intel-sgx-sdk-for-linux-and-open-enclave-sdk), but I want to avoid using SGX-specific features for compatibility. Any help is appreciated, thanks.

**Comment by mingweishih** [comment]
The requirement is enforced by the Intel dependencies, not OE. 
Also, the SGX drivers are typically built in with expected settings (including the user group, etc) to the recent Linux kernel.
@MWShan can you chime in?

**Comment by octaviansima** [comment]
@MWShan I just checked, and it seems like `SGX_AESM_ADDR=1` on my machine, which prompts for out-of-process quote generation. The problem was actually that some processes attempting to launch enclaves did not inherit that environment variable, and as a result were attempting to perform in-process quote generation. That itself was failing because we're not installing the quote-ex library. Thanks for the great help, closing.
