### ISSUE TITLE
SPECTRE flags not applied when LVI mitigations are enabled

### ISSUE THREAD

**Issue by wintersteiger** [openenclave/openenclave#4641]
[Here](https://github.com/openenclave/openenclave/blob/95062ffefdbcbd6d9369ea9b0ba0ad4f86768654/cmake/openenclave-config.cmake.in#L156) the spectre mitigation flags are added to the compile options of `openenclave::oecore`, but not for  `openenclave::oecore-lvi-cfg`.

Is this by design (e.g. LVI mitigations also take care of spectre) or is this a bug?

**Comment by anakrish** [comment]
CC @mingweishih

**Comment by mingweishih** [comment]
No, this looks like something we missed when supporting LVI mitigation.
