### ISSUE TITLE
update oeciteam/oe-helloworld:latest image

### ISSUE THREAD

**Issue by mythi** [openenclave/openenclave#4650]
this runs on a pretty old SGX SDK.

**Comment by mingweishih** [comment]
cc @CyanDevs

**Comment by CyanDevs** [comment]
Hi @mythi,

We no longer maintain the images on our Docker Hub. Please see this [list of images available](https://github.com/openenclave/openenclave/blob/master/DOCKER_IMAGES.md) instead.

**Comment by mythi** [comment]
I found that list but could not find any pre-built samples in them.

**Comment by CyanDevs** [comment]
On any Ubuntu oetools container you can install the open-enclave package and look at the samples there. For example:

```
apt-get update
apt-get install open-enclave
cd /opt/openenclave/share/openenclave/samples/
```
```

**Comment by mythi** [comment]
My use case is to deploy a prebuilt enclave in a kubernetes cluster but with this it's not possible.

**Comment by mythi** [comment]
Closing as wontfix
