### ISSUE TITLE
When will v0.18.4 be published to the focal apt repo?

### ISSUE THREAD

**Issue by cam-schultz** [openenclave/openenclave#4661]
It has been over 24 hours since the release was published on Github, but `sudo apt install open-enclave=0.18.4` cannot find version `0.18.4`.

**Comment by anakrish** [comment]
CC: @CyanDevs @radhikaj

**Comment by radhikaj** [comment]
It should be out on 11/10 end of day PST. Thanks.

**Comment by cam-schultz** [comment]
Thank you!
