### ISSUE TITLE
 SGX AESM service unavailable

### ISSUE THREAD

**Issue by lili8808** [openenclave/openenclave#4678]
I am going to run attestion sample in open enclave. I have installed aesm service on my VM (Azure cloud VM) :
`sudo systemctl status aesmd.service
● aesmd.service - Intel(R) Architectural Enclave Service Manager
     Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-01-09 07:38:27 UTC; 5h 55min ago
   Main PID: 779 (aesm_service)
      Tasks: 4 (limit: 9529)
     Memory: 8.1M
     CGroup: /system.slice/aesmd.service
             └─779 /opt/intel/sgx-aesm-service/aesm/aesm_service

Jan 09 07:38:24 sgx-n03 systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
Jan 09 07:38:27 sgx-n03 aesm_service[726]: aesm_service: warning: Turn to daemon. Use "--no-daemon" option to execute in foreground.
Jan 09 07:38:27 sgx-n03 systemd[1]: Started Intel(R) Architectural Enclave Service Manager.
Jan 09 07:38:27 sgx-n03 aesm_service[779]: The server sock is 0x5604ab1e4020`

but when I want to run attestion sample in open enclave :
`~/openenclave/samples/attestation$ make runsgxremote
host/attestation_host sgxremote ./enclave_a/enclave_a.signed ./enclave_b/enclave_b.signed
Host: Creating two enclaves
Host: Enclave library ./enclave_a/enclave_a.signed
Enclave1: ***../common/crypto.cpp(80): mbedtls initialized.
Host: Enclave successfully created.
Host: Enclave library ./enclave_b/enclave_b.signed
Enclave2: ***../common/crypto.cpp(80): mbedtls initialized.
Host: Enclave successfully created.
Host: environment variable SGX_AESM_ADDR is set

Host: ********** Attest enclave_a to enclave_b **********

Host: Requesting enclave_b format settings
Enclave2: ***../common/dispatcher.cpp(79): get_enclave_format_settings
Host: Requesting enclave_a to generate a targeted evidence with an encryption key
Enclave1: ***../common/dispatcher.cpp(133): get_evidence_with_public_key
2023-01-09T13:28:37+0000.423195Z [(H)ERROR] tid(0x7ff150a10f40) | SGX AESM service unavailable (oe_result_t=OE_SERVICE_UNAVAILABLE) [/source/openenclave/host/sgx/sgxquote.c:_load_quote_ex_library_once:479]
Enclave1: ***../common/attestation.cpp(94): oe_serialize_custom_claims
Enclave1: ***../common/attestation.cpp(105): serialized custom claims buffer size: 121
2023-01-09T13:28:37+0000.428556Z [(H)ERROR] tid(0x7ff150a10f40) | Failed to load SGX quote-ex library
 (oe_result_t=OE_SERVICE_UNAVAILABLE) [/source/openenclave/host/sgx/sgxquote.c:oe_sgx_qe_get_target_info:688]
2023-01-09T13:28:37+0000.429187Z [(H)ERROR] tid(0x7ff150a10f40) | :OE_SERVICE_UNAVAILABLE [/source/openenclave/host/sgx/quote.c:sgx_get_qetarget_info:37]
Enclave1: ***../common/attestation.cpp(121): oe_get_evidence failed.(OE_SERVICE_UNAVAILABLE)
Enclave1: ***../common/dispatcher.cpp(153): get_evidence_with_public_key failed
Host: get_evidence_with_public_key failed. OE_OK
Host: attestation failed with 1
Host: Terminating enclaves
Enclave1: ***../common/crypto.cpp(94): mbedtls cleaned up.
Host: Enclave successfully terminated.
Enclave2: ***../common/crypto.cpp(94): mbedtls cleaned up.
Host: Enclave successfully terminated.
Host:  failed 
make: *** [Makefile:27: runsgxremote] Error 1`
does any body know the problem?
Thanks

**Comment by mingweishih** [comment]
What VM size did you use?

**Comment by radhikaj** [comment]
closing, please reopen if you are still facing issues
