### ISSUE TITLE
Upgrade to OpenSSL 1.1.1t

### ISSUE THREAD

**Issue by michaelkaplan13** [openenclave/openenclave#4697]
OpenSSL has announced the release of version 1.1.1t that address a high severity security vulnerability (see [here](https://www.openssl.org/news/secadv/20230207.txt)).

It may already be on your radar, but is there a date we can expect a new release that uses the latest OpenSSL version?

**Comment by anakrish** [comment]
Addressed by https://github.com/openenclave/openenclave/pull/4695

**Comment by radhikaj** [comment]
V0.18.5 is now out
