### ISSUE TITLE
App devs can obtain and use Open Enclave SDK on Windows via packaged install

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#47]
To ease adoption of the SDK, we should provide a binary and library drop that does not require non-contributors to build the OpenEnclave project. 

- [x] Define OE SDK package for Windows (nuget?)
- [x] Document OE SDK install and usage instructions for Windows (a la [install_oe_sdk.md](https://github.com/Microsoft/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk.md))

This is related to story #371

**Comment by radhikaj** [comment]
Nuget packages are now available for Windows. Closing.
