### ISSUE TITLE
Investigate missing _oe_handle_main after Clang-11 update

### ISSUE THREAD

**Issue by CyanDevs** [openenclave/openenclave#4704]
From https://github.com/openenclave/openenclave/pull/4690/files#diff-190f89e976b4400d8230f67f46575bbf5bf6d002bf77d9ea0fbac32f68a6d499

`_oe_handle_main` is missing in tests/backtrace/host/host.cpp after upgrading to Clang-11
It still exists when building with Clang-10

**Comment by asvrada** [comment]
This test passes when OE is built with clang-10 and clang-11.

**Comment by asvrada** [comment]
The problem is caused by this line: https://github.com/openenclave/openenclave/blob/774d065ab2c45c58ed967ff7d189d64a910d13d2/enclave/core/CMakeLists.txt#L142
