### ISSUE TITLE
Possible user experience issues building applications with LVI mitigation enabled

### ISSUE THREAD

**Issue by asvrada** [openenclave/openenclave#4712]
Here are some possible issues related to using LVI mitigation that end user could encounter. Listing them here for future reference.

### How to reproduce
1. Run `script/lvi-mitigation/install_lvi_mitigation_bindir`
2. `mkdir build && cd build && cmake ..`
3. Again run `cmake .. -DLVI_MITIGATION=ControlFlow -DLVI_MITIGATION_BINDIR=/path/to/lvi_mitigation_bin`
4. Compile with `cmake --build .`

### Issue
When the build directory is not freshly configured to use ControlFlow-GNU, custom compiler is not picked up.
During compiling, it would use the default toolchain (compiler/linker located at /usr/bin, for example), and causing errors like `/usr/bin/as: unrecognized option '-mlfence-before-indirect-branch=register'`.

A freshly configured build directory means, running `cmake .. -DLVI_MITIGATION=ControlFlow ...` immediately after creating the build directory. If one has an existing build directory configured with other compiling settings, and later try to enable LVI Mitigation, then this error would occur.

### Cause
Probably some cached CMake variables are hindering the process to set custom compilers.

### Fix
Add `--fresh` to `cmake` command when configuring LVI mitigation options.

> For example  
> `cmake .. --fresh -DLVI_MITIGATION=ControlFlow ...`

**TODO: We should reflect this in the document.**

---

There is no issue when building subdirectory `samples/` when building OpenEnclave as a whole. But if a real client, installs OpenEnclave, then tries to build their project with LVI mitigation enabled, the following issues occur.

## ⚠️ 2. When building samples + ControlFlow, OpenEnclave-LVI-Mitigation not found

This happens for both `ControlFlow-GNU` and `ControlFlow-Clang` option.

### How to reproduce
This is common for every sample under `samples/`, I will use `helloworld/` for example.

1. Install OE, for example to `/opt/openenclave/`
2. `cd samples/helloworld && mkdir build && cd build`
3. `cmake .. -DLVI_MITIGATION=ControlFlow-Clang`

### Issue
There seems to be no template CMake project provided to users on how to import/use lvi mitigation-related cmake file. Assume they check `samples/helloworld` for how to set up LVI mitigation, they will use `find_package(OpenEnclave-LVI-Mitigation CONFIG REQUIRED)`, which produces the following error:

```
CMake Error at CMakeLists.txt:10 (find_package):
  Could not find a package configuration file provided by
  "OpenEnclave-LVI-Mitigation" with any of the following names:

    OpenEnclave-LVI-MitigationConfig.cmake
    openenclave-lvi-mitigation-config.cmake

  Add the installation prefix of "OpenEnclave-LVI-Mitigation" to
  CMAKE_PREFIX_PATH or set "OpenEnclave-LVI-Mitigation_DIR" to a directory
  containing one of the above files.  If "OpenEnclave-LVI-Mitigation"
  provides a separate development package or SDK, be sure it has been
  installed.
```

### Cause
With OpenEnclave installed at `/opt/openenclave`, `openenclave-lvi-mitigation-config.cmake` can be found at `/opt/openenclave/lib/openenclave/cmake`. But this path is not added to CMake search path.

### Fix
Run `. /opt/openenclave/share/openenclave/openenclaverc` to include the search path.

~~**TODO: We should reflect this in the document.**~~
Already covered https://github.com/openenclave/openenclave/blob/master/samples/BuildSamplesLinux.md

## 🪲 3. When building samples with ControlFlow-Clang, clang-11 is not enforced

Possible error output:
> cc: error: unrecognized command line option ‘-mlvi-cfi’

### How to reproduce
1. Build OE with `-DLVI_MITIGATION=ControlFlow-Clang`
1. `cd samples/helloworld && mkdir build && cd build`
2. `cmake .. --fresh -DLVI_MITIGATION=ControlFlow-Clang`
3. `cmake --build .`

### Issue
If not specified by user, cmake might not use Clang-11 by default, causing LVI mitigation flags to error out.

### Cause
For `ControlFlow-Clang`, `configure_lvi_mitigation_build.cmake` is not included by `openenclave-lvi-mitigation-config.cmake.in`.

### Fix
TODO: we should modify `configure_lvi_mitigation_build.cmake` so that it works for Clang-11.

**Comment by asvrada** [comment]
Work in progress.

**Comment by asvrada** [comment]
For cross-compiling OE and user project with different LVI mitigation options

### OE uses ControlFlow-Clang but client uses ControlFlow-GNU
Client project won't compile.



### OE uses ControlFlow-GNU but client uses ControlFlow-Clang
To be tested

**Comment by radhikaj** [comment]
also if samples are built with ControlFlow, then default to ControlFlow-Clang.

**Comment by radhikaj** [comment]
We should not break users who were previously just specifying "ControlFlow".

**Comment by CyanDevs** [comment]
One more issue to add -- encountered an issue on Ubuntu 18.04 and running on ControlFlow-Clang with the HelloWorld sample from a packaged OE DEB.

```
[ 40%] Linking C executable enclave
cd /opt/openenclave/share/openenclave/samples/helloworld/build/enclave && /usr/local/cmake-3.13.1-Linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/enclave.dir/link.txt --verbose=1
/usr/local/lvi-mitigation/lvi_mitigation_bin/clang-11 -O2 -g -DNDEBUG   CMakeFiles/enclave.dir/enc.c.o CMakeFiles/enclave.dir/helloworld_t.c.o  -o enclave /opt/openenclave/lib/openenclave/enclave/liboeenclave-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/liboecryptombedtls-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/liboelibc-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/libmbedtls-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/libmbedx509-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/libmbedcrypto-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/liboelibc-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/liboesyscall-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/liboecore-lvi-cfg.a -nostdlib -nodefaultlibs -nostartfiles -Wl,--no-undefined,-Bstatic,-Bsymbolic,--export-dynamic,-pie,--build-id -Wl,-z,noexecstack -Wl,-z,now -Wl,-gc-sections
/usr/bin/ld: /opt/openenclave/lib/openenclave/enclave/liboeenclave-lvi-cfg.a(report.c.o): unable to initialize decompress status for section .debug_loc
/usr/bin/ld: /opt/openenclave/lib/openenclave/enclave/liboeenclave-lvi-cfg.a(report.c.o): unable to initialize decompress status for section .debug_loc
/opt/openenclave/lib/openenclave/enclave/liboeenclave-lvi-cfg.a: error adding symbols: File format not recognized
clang: error: linker command failed with exit code 1 (use -v to see invocation)
enclave/CMakeFiles/enclave.dir/build.make:117: recipe for target 'enclave/enclave' failed
make[2]: *** [enclave/enclave] Error 1
make[2]: Leaving directory '/opt/openenclave/share/openenclave/samples/helloworld/build'
CMakeFiles/Makefile2:193: recipe for target 'enclave/CMakeFiles/enclave.dir/all' failed
make[1]: *** [enclave/CMakeFiles/enclave.dir/all] Error 2
make[1]: Leaving directory '/opt/openenclave/share/openenclave/samples/helloworld/build'
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Investigation so far: adding the option `-link-lvi-mitigation` resolves the issue, but it may not be the appropriate option to add as it seems to relate to the custom binaries used in ControlFlow-GNU. One can find the `-link-lvi-mitigation` option from the following block of code (when GLIBC > 2.27): https://github.com/openenclave/openenclave/blob/master/cmake/apply_lvi_mitigation.cmake#L57-L69

**Comment by asvrada** [comment]
> One more issue to add -- encountered an issue on Ubuntu 18.04 and running on ControlFlow-Clang with the HelloWorld sample from a packaged OE DEB.
> 
> ```
> [ 40%] Linking C executable enclave
> cd /opt/openenclave/share/openenclave/samples/helloworld/build/enclave && /usr/local/cmake-3.13.1-Linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/enclave.dir/link.txt --verbose=1
> /usr/local/lvi-mitigation/lvi_mitigation_bin/clang-11 -O2 -g -DNDEBUG   CMakeFiles/enclave.dir/enc.c.o CMakeFiles/enclave.dir/helloworld_t.c.o  -o enclave /opt/openenclave/lib/openenclave/enclave/liboeenclave-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/liboecryptombedtls-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/liboelibc-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/libmbedtls-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/libmbedx509-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/libmbedcrypto-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/liboelibc-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/liboesyscall-lvi-cfg.a /opt/openenclave/lib/openenclave/enclave/liboecore-lvi-cfg.a -nostdlib -nodefaultlibs -nostartfiles -Wl,--no-undefined,-Bstatic,-Bsymbolic,--export-dynamic,-pie,--build-id -Wl,-z,noexecstack -Wl,-z,now -Wl,-gc-sections
> /usr/bin/ld: /opt/openenclave/lib/openenclave/enclave/liboeenclave-lvi-cfg.a(report.c.o): unable to initialize decompress status for section .debug_loc
> /usr/bin/ld: /opt/openenclave/lib/openenclave/enclave/liboeenclave-lvi-cfg.a(report.c.o): unable to initialize decompress status for section .debug_loc
> /opt/openenclave/lib/openenclave/enclave/liboeenclave-lvi-cfg.a: error adding symbols: File format not recognized
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> enclave/CMakeFiles/enclave.dir/build.make:117: recipe for target 'enclave/enclave' failed
> make[2]: *** [enclave/enclave] Error 1
> make[2]: Leaving directory '/opt/openenclave/share/openenclave/samples/helloworld/build'
> CMakeFiles/Makefile2:193: recipe for target 'enclave/CMakeFiles/enclave.dir/all' failed
> make[1]: *** [enclave/CMakeFiles/enclave.dir/all] Error 2
> make[1]: Leaving directory '/opt/openenclave/share/openenclave/samples/helloworld/build'
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> ```
> 
> Investigation so far: adding the option `-link-lvi-mitigation` resolves the issue, but it may not be the appropriate option to add as it seems to relate to the custom binaries used in ControlFlow-GNU. One can find the `-link-lvi-mitigation` option from the following block of code (when GLIBC > 2.27): https://github.com/openenclave/openenclave/blob/master/cmake/apply_lvi_mitigation.cmake#L57-L69

Thanks for the log. Is the packaged OE built with ControlFlow-GNU?

**Comment by CyanDevs** [comment]
> Thanks for the log. Is the packaged OE built with ControlFlow-GNU?

Good thinking, this was the issue and is related to mixing the different ControlFlow options. Building the package with with ControlFlow-Clang and running the sample with the same will run successfully. Thanks @asvrada !
