### ISSUE TITLE
Can I use openssl in enclave? 

### ISSUE THREAD

**Issue by ChampionNan** [openenclave/openenclave#4723]
I've known how to call mbedtls related api in enclave, but can I use openssl in enclave as well? 
What should I do? 
Thanks!

**Comment by mingweishih** [comment]
You should be able to just use OpenSSL as-is. See https://github.com/openenclave/openenclave/blob/master/samples/file-encryptor/enclave/openssl_src/encryptor.cpp for an example.

**Comment by ChampionNan** [comment]
Thanks! How about using other third-party libraries in enclave, which are not supported currently? Is that possible?
