### ISSUE TITLE
Stack Check Failure Seeding `mbedtls` `hmac_drbg`

### ISSUE THREAD

**Issue by bhoberman** [openenclave/openenclave#4726]
Hi Open Enclave devs, I'm working on some code that sets up an `mbedtls` `hmac_drbg` instance. The code is as follows:

```C++
DRBG::DRBG(gsl::span<const uint8_t> entropy_seed) {
    if (entropy_seed.empty()) {
        constexpr std::array<uint8_t, sizeof("Seeding")> custom{"Seeding"};
        mbedtls_hmac_drbg_seed(
            drbg_.get(),
            mbedtls_md_info_from_type(MBEDTLS_MD_SHA256),
            mbedtls_entropy_func, entropy_.get(), custom.data(), custom.size());
    } else {
        mbedtls_hmac_drbg_seed_buf(
            drbg_.get(),
            mbedtls_md_info_from_type(MBEDTLS_MD_SHA256),
            entropy_seed.data(), entropy_seed.size());
    }
}
```

Where `drbg_` is an RAII wrapper around an `mbedtls_hmac_drbg_context` and `entropy_` is an RAII wrapper around an `mbedtls_entropy_context`. As far as I can tell, this is correct/intended usage: it works linked against `mbedtls-2.28.1` in non-enclave code, but inside the enclave, it's stopped working.

The function executes fine, but when this constructor returns, it results in stack smashing and a program crash via `__stack_chk_fail`. I've also experienced `mbedtls_hmac_drbg_seed` resulting in a deadlock, [which occurs here](https://github.com/openenclave/openenclave-mbedtls/blob/6e64bc81683ffa5c107c089391941d42324759e6/library/entropy.c#L351).

I'd like to know if there's any known enclave issues that might cause this, thanks! This issue seems to appear only when we link in other libraries (even header-only ones).

**Comment by anakrish** [comment]
@bhoberman 

Thanks for reporting this issue. I've a few questions:
1. How many stack pages are configured for your enclave?
2. Can you share the output of `objdump -h path/to/enclave`?
3. Are multiple enclave threads (ecalls) active when you notice the stack check failure or the deadlock?
4. Are `entropy_`, `drbg_` global variables or thread-local variables?
5. Is there a small reproduction example?

**Comment by radhikaj** [comment]
Please provide a repro so we can investigate. Please reopen when a repro is available.
