### ISSUE TITLE
Clarification for LVI mitigation mixed builds

### ISSUE THREAD

**Issue by jumaffre** [openenclave/openenclave#4745]
Following the recent changes to enable mixed LVI mitigation builds (#4715), the documentation indicates that an enclave app can be built against a released OE (built with GNU mitigations) with `clang-11` using the `-DLVI_MITIGATION=ControlFlow-Clang -DLVI_MITIGATION_BINDIR=/path/to/lvi_mitigation_bin` flags (see [doc](https://github.com/openenclave/openenclave/tree/master/samples/helloworld#mixing-lvi-mitigation)). 

However, the only action required by a user to build an LVI-mitigated app with `clang-11` is to pass the `-mlvi-cfi` flag:https://github.com/openenclave/openenclave/blob/78cbe4958cefb740194065009cdb856e3bd433fe/cmake/apply_lvi_mitigation.cmake#L40

Passing the `-DLVI_MITIGATION=ControlFlow-Clang -DLVI_MITIGATION_BINDIR=/path/to/lvi_mitigation_bin` flags and having the GNU LVI toolchain installed seem to be unnecessary requirements to enable LVI mitigations for `clang-11` apps. 

Should/could this be clarified in the documentation and/or could a simple version of `apply_lvi_mitigation()` be accessible to apps built with `clang-11` without having to install the `OpenEnclave-LVI-Mitigation` package?

**Comment by radhikaj** [comment]
@jumaffre , do you think we need to address more in this issue? Can we close it?
