### ISSUE TITLE
Clarification about `oe_attester_shutdown` on the attestation example

### ISSUE THREAD

**Issue by gemini-15** [openenclave/openenclave#4758]
When trying to reproduce the attestation example, I stumbled upon the attestation code present at : `attestation.cpp` at https://github.com/openenclave/openenclave/blob/master/samples/attestation/common/attestation.cpp. 
The confusion is that we use `oe_attester_initialize` function at the definition of `Attestation::generate_attestation_evidence`. But, we never finish by freeing the memory related to it in the exit. 
Instead, we use the `oe_attester_shutdown()` function when defining the `Attestation::attest_attestation_evidence` method. Which doesn't make so much sense to me because the we never initialize the attester to begin with?! 

Is this normal?

**Comment by radhikaj** [comment]
@asvrada can you please investigate and respond?

**Comment by gemini-15** [comment]
Hello @asvrada Is there any update on this?

**Comment by asvrada** [comment]
Hi, please let me know if I interpret your question correctly, are you not sure about the usage of `oe_attester_initialize` and `oe_attester_shutdown`?

The more detailed explanation is here [Attestation_API_Proposal.md](https://github.com/openenclave/openenclave/blob/master/docs/DesignDocs/Attestation_API_Proposal.md), under section "Use cases for evidence generation"

From a user's perspective, one only needs to call `oe_attester_initialize` and `oe_attester_shutdown` once, before and after APIs that depends on attesters like `oe_get_evidence` or `oe_get_attestation_certificate_with_evidence_v2`

Code flow would look like so

```
result = oe_attester_initialize(); // Check result == OE_OK

...

// Call APIs that uses attesters
oe_get_evidence(a, b, c, d, ...);
oe_get_attestation_certificate_with_evidence_v2(a, b, c, d, ...);

...

// Before program exits, clean up internal resources
oe_attester_shutdown();
```

`oe_attester_initialize` and `oe_attester_shutdown` can be called anywhere in your program, as they will operate on internal memories, so you do not need to explicitly maintain the memory. If you are interested, feel free to check its implementation like attest plugin registration here: https://github.com/openenclave/openenclave/blob/master/common/sgx/verifier.c#L1120C1-L1126

**Comment by gemini-15** [comment]
Thank You for the explanation. It's clearer now.
