### ISSUE TITLE
Unable to enable intel SGX on hyper-v (Win 11)  ubuntu 20.04 machine

### ISSUE THREAD

**Issue by yontyon** [openenclave/openenclave#4776]
I've followed https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/HyperVLinuxVMSetup.md in order to enable sgx on my hyper-v ubuntu vm (20.04 LTS). 
After successfully running `Set-VMSgx -VmName "Ubuntu 20.04 LTS" -SgxEnabled $True -SgxSize 32`, when starting the VM again I get the following error:
```
An error occurred while attempting to start the selected virtual machine(s).
'Ubuntu 20.04 LTS' failed to start.
'Ubuntu 20.04 LTS' could not initialize.
Failed to create partition: The hypervisor could not perform the operation because an invalid parameter was specified. (0xC0350005).
'Ubuntu 20.04 LTS' failed to start. (Virtual machine ID 04552AC8-1B90-4E37-9B5D-CF34365502AD)
'Ubuntu 20.04 LTS' failed to start worker process: The hypervisor could not perform the operation because an invalid parameter was specified. (0xC0350005). (Virtual machine ID 04552AC8-1B90-4E37-9B5D-CF34365502AD)
'Ubuntu 20.04 LTS' could not initialize. (Virtual machine ID 04552AC8-1B90-4E37-9B5D-CF34365502AD)
Failed to create partition: The hypervisor could not perform the operation because an invalid parameter was specified. (0xC0350005).
```
Do I miss anything here?
Thanks

**Comment by yontyon** [comment]
@anakrish yes.
After disabling sgx (by passing false in the PS command) the machine starts as usual

**Comment by anakrish** [comment]
Can you try a smaller EPC size say `Set-VMSgx -VmName "Ubuntu 20.04 LTS" -SgxEnabled $True -SgxSize 8` and see if the VM starts?

**Comment by yontyon** [comment]
Still not working…

**Comment by anakrish** [comment]
The VM is Generation 2 and secure boot has been disabled?
