### ISSUE TITLE
Ephemeral `OE_SGX_QUOTE_LIBRARY_ERROR` during enclave evidence generation

### ISSUE THREAD

**Issue by octaviansima** [openenclave/openenclave#4790]
Hi, we have been running into `OE_SGX_QUOTE_LIBRARY_ERROR` non-deterministically when calling `oe_get_evidence`. Calling it multiple times per process will have the same result, but retrying on another run typically fixes it. This has been happening more recently since we updated our OE version from 0.17.1 to 0.18.5, so wondering if updating again would help?

### Environment

Azure DCsv3 machines running Ubuntu 20.04 and OE 0.18.5. We are also using out of process quote generation (`SGX_AESM_ADDR`=1), if that makes a difference.

**Comment by mingweishih** [comment]
The error code indicates the dependencies to the Intel packages.  What `libsgx-quote-ex` version do you use?

**Comment by octaviansima** [comment]
Thanks for the quick response -- we are using `2.19.100.3-focal1` which I believe [is the latest](https://download.01.org/intel-sgx/latest/linux-latest/distro/ubuntu18.04-server/debian_pkgs/libs/libsgx-quote-ex/)

**Comment by mingweishih** [comment]
Can you paste more logs regarding the `OE_SGX_QUOTE_LIBRARY_ERROR`?

**Comment by octaviansima** [comment]
Here is the error logging from OE:
```
2023-06-28T04:19:21+0000.643182Z [(H)ERROR] tid(0x7f5349dfd700) | SGX quote-ex failure: _load_quote_ex_library_once() sgx_get_supported_att_key_id_num() status=SGX_ERROR_SERVICE_TIMEOUT num=0
 (oe_result_t=OE_SGX_QUOTE_LIBRARY_ERROR) [/source/openenclave/host/sgx/sgxquote.c:_load_quote_ex_library_once:487]
2023-06-28T04:19:21+0000.647275Z [(H)ERROR] tid(0x7f5349dfd700) | Failed to load SGX quote-ex library
 (oe_result_t=OE_SGX_QUOTE_LIBRARY_ERROR) [/source/openenclave/host/sgx/sgxquote.c:oe_sgx_qe_get_target_info:688]
2023-06-28T04:19:21+0000.647281Z [(H)ERROR] tid(0x7f5349dfd700) | :OE_SGX_QUOTE_LIBRARY_ERROR [/source/openenclave/host/sgx/quote.c:sgx_get_qetarget_info:37]
2023-06-28T04:19:21+0000.925696Z [(H)ERROR] tid(0x7f5349dfd700) | Failed to load SGX quote-ex library
 (oe_result_t=OE_SGX_QUOTE_LIBRARY_ERROR) [/source/openenclave/host/sgx/sgxquote.c:oe_sgx_qe_get_target_info:688]
```

**Comment by mingweishih** [comment]
```
Jun 01 23:43:10 pkrvm0w1xgqlhjy aesm_service[14526]: [get_driver_type edmm_utility.cpp:116] Failed to open Intel SGX device.
Jun 01 23:43:10 pkrvm0w1xgqlhjy aesm_service[14526]: [get_driver_type edmm_utility.cpp:116] Failed to open Intel SGX device
```

Looks suspicious. Which Linux kernel version do you use? Also, can you check if the path `/dev/sgx/enclave` or `/dev/sgx_enclave` exists?

**Comment by octaviansima** [comment]
Closing this -- our issue was actually that 24 different enclaves were hitting the AESM service, and some were failing because the timeout is set to be 15 seconds (evidence generation itself via `oe_get_evidence` was taking ~1 second). Our workaround was to use in-process quote generation
