### ISSUE TITLE
Embedding a file as a resource before signing?

### ISSUE THREAD

**Issue by joshua-oss** [openenclave/openenclave#4812]
I have a list of allowed public keys that get hard-coded into my enclave at compile time.

Is there a way to attach the allowed keys to the binary after compilation but before signing, so that my deployment pipelines don't need to compile from scratch every time the allowed keys are changed?

One way presumably would be to use `objcopy` to convert the keys to an obj file, and then link. But this still requires invocation of the linker.  I'm wondering if there is some facility built into the OE SDK to handle this scenario?

**Comment by mingweishih** [comment]
> I have a list of allowed public keys that get hard-coded into my enclave at compile time.
> 
> Is there a way to attach the allowed keys to the binary after compilation but before signing, so that my deployment pipelines don't need to compile from scratch every time the allowed keys are changed?
> 
> One way presumably would be to use `objcopy` to convert the keys to an obj file, and then link. But this still requires invocation of the linker. I'm wondering if there is some facility built into the OE SDK to handle this scenario?

This sounds like binary/elf editing --- you basically need to modify the binary directly while preserving the elf format. Also, after the edition, your application code needs to know where to find the inserted keys. It should be doable but sounds a bit hacky IMO, which is not generally recommended in practice.
