### ISSUE TITLE
  Will openenclave be simpler in terms of software development than SGX SDK? 

### ISSUE THREAD

**Issue by digitalinformation** [openenclave/openenclave#4823]
Hello, I have recently been doing blockchain privacy protection based on trusted execution environment, can OpenEnclave act as an alternative to SGX SDK? Will it be simpler in terms of software development than SGX SDK? Do you have any references or suggested documentation to get started in the Linux environment?

**Comment by mingweishih** [comment]
Yes, OpenEnclave can be an alternative to Intel SGX SDK. You can find the document to setup the environment on https://github.com/openenclave/openenclave/blob/master/docs/GettingStartedDocs/install_oe_sdk-Ubuntu_20.04.md.

Samples (https://github.com/openenclave/openenclave/tree/master/samples) should serve as great examples of how a software development looks like with OpenEnclave.

**Comment by radhikaj** [comment]
Thanks @digitalinformation, please reopen if you have more questions
