### ISSUE TITLE
The following error occurs when installing Open Enclave:

### ISSUE THREAD

**Issue by digitalinformation** [openenclave/openenclave#4872]
The following error occurs when installing Open Enclave:
![b3bac0ddf4e912fefd0d8db508814831](https://github.com/openenclave/openenclave/assets/94784449/227d6f7f-d842-4302-ba27-683ddb7a169c)

**Comment by CyanDevs** [comment]
Hi @digitalinformation following your other issue #4873 as you do not have Launch Control enabled, I believe you need a different driver called the Intel SGX driver which does not use DCAP. Please see https://github.com/intel/linux-sgx-driver
