### ISSUE TITLE
how to start the SGX function in the Linux system

### ISSUE THREAD

**Issue by digitalinformation** [openenclave/openenclave#4873]
Hello, my computer model is intel i7 8700k, in the BIOS only support software mode to start the sgx function, how to enable the sgx function in the linux system, enter the command line to display as follows:
![QQ图片20231114210725](https://github.com/openenclave/openenclave/assets/94784449/3925a6b9-afcb-47c8-a00f-8386b5e9a1ff)

**Comment by CyanDevs** [comment]
Hi @digitalinformation normally if your processor and BIOS supports SGX and Launch Control, you will be able to enable that in your BIOS. If you do not see such a setting then it is likely not supported on your system. I would suggest you take a closer look at your workstation's system to see if SGX and Launch Control are fully supported.
