### ISSUE TITLE
Azure Security can sign their Open Enclave binaries through ESRP 

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#525]
Azure security team will be building their enclave attestation service on top of Open Enclave and will need to have their production enclave binary signed by ESRP-owned signing keys. This creates new requirements for the oesign tool:

- [x] oesign needs to run on Windows (#837)
    - AzSec uses CDPX to build their enclave apps and the CDPX orchestration hooks into CloudBuild signing in the host which runs on Windows, even though they are building ELF OE enclave binaries.

- [ ] oesign needs to support digest signing (#2089)
    - ESRP is a privileged and restricted signing environment and cannot ingest oesign to run it on their backend.
    - Implementation of the digest signing feature will solve production signing in the general case and will also apply to ESRP as they already have a digest signing workflow.

**Comment by andschwa** [comment]
@johnkord @lilyfang I am not sure I should be assigned here, unless you want this done after #1031. This doesn't appear to be a v0.5 item.

**Comment by andschwa** [comment]
@soccerGB From triage meeting: can you get the requirements and update this issue? Thanks!

**Comment by radhikaj** [comment]
@yakman2020 @BRMcLaren I think you are working on this. If it is done, can you please close it?

**Comment by BRMcLaren** [comment]
Closing, completed.
