### ISSUE TITLE
Open Enclave does not call __init_libc which breaks several libc features

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#565]
Per @ihaller's observation:

> Looking into the TLS error, it seems to me that the function __init_libc is never called anywhere from OpenEnclave. And the only parts of its contents that do get replicated in the OpenEnclave initialization are the calls to the constructors. If this is the case, then the following are not initialized:
> * Static TLS of musl (__init_tls): this I understand is a design choice and understood by the team.
> * Stack protector cookie (__init_ssp): this will make the stack protector mostly meaningless and should be documented as an unsupported feature as security-conscious developers would be interested in using it.
> * The global musl configuration (_libc struct): some interesting things here, including a thread count which if left at 0 will break musl malloc once it is in use (will disable locking within the allocator).
> * Some other globals: no idea what these are.
> * It looked to me like the _[libc.secure]_ flag is related to the glibc secure execution mode, which is in general triggered for an SUID binary, but can also be set for other executables. I don’t know what happens, but it seems as if the polling is checking for redirection of stdin/stdout/stderr and exiting if it detects it?

@mikbras confirms that we currently only call global initializers, and this issue tracks investigating what is needed to incorporate the rest of these:
* No call to `__init_tls` is tracked as part of #538 for what would be needed to support `thread_local`
* No call to `__init_ssp` is tracked as part of #81 for what would be needed to support stack protector cookies.
* OE may not be using the thread count in libc since we use dlmalloc & oe_thread instead of MUSL malloc & pthreads, but we need to verify this.
    * We also need to investigate the impact of failing to check/set the various libc.auxv values and libc.secure.
* We need to further investigate whether the remaining globals not being initialized has an impact; current intuition is that there would not be legitimate use cases for them inside the enclave. Likely not a problem, but it is important to understand them because they are used internal to MUSL. We should make sure that code outside of it has no visibility to them:
    * __environ
    * __hwcap
    * __sysinfo
    * __progname (seems to be aliased on program_invocation_short_name for example, which is part of errno.h)
        * One option is to skip linking in libc.c and replace it with a stub in the enclave libc, but that will be musl-specific instead of being usable across different libc implementations.

**Comment by jhand2** [comment]
Fully documented and implemented necessary libc initialization here: #2420

**Comment by radhikaj** [comment]
@jhand2 Can I close this?

**Comment by jhand2** [comment]
Even though this is documented, its technically still implemented in #2428. But I don't think #2428 will be going in in the short term. An option to wrap this up in the short term is to treat libc as a special case and not as a generic module.

**Comment by radhikaj** [comment]
Documentation added. Closing out for now.
