### ISSUE TITLE
GRPC/TLS based enclave-to-enclave communication

### ISSUE THREAD

**Issue by dthaler** [openenclave/openenclave#848]
OP-TEE (and possibly other TEEs) support the ability to make an ECALL to an enclave, from within another enclave (as opposed to its host).   In OP-TEE the call never involves host code at all, because there’s actually a lightweight “OS” inside the TEE that handles such calls.  In Intel’s SDK, there are specific APIs that underneath do enclave-to-enclave calls (sgx_create_pse_session() etc.), but presumably do so via host code that the app developer never sees.

The point is there’s a reason to be able to call a version of the following three “host” APIs from within a different enclave:
•	oe_create_enclave
•	oe_ecall (which is internal)
•	oe_terminate_enclave

I can’t think of any reason for the syntax to need to be any different than what is already in host.h, though.  Thus, I would recommend either:
a)	moving oe_create_enclave and oe_terminate_enclave under the common “bits” directory where other common calls are, or
b)	duplicate them in enclave.h if there’s a reason for the syntax to be different.

On SGX, calling oe_create_enclave from inside another enclave could simply forward to the host library which would internally call oe_create_enclave.  The risk is that the host could change some of the arguments, but presumably that’s solvable via local attestation.

**Comment by anakrish** [comment]
We need to carefully design such an enclave-to-enclave calling API in regards to the security guarantees that it would provide. 
For example, in SGX the call would have to go through the host and therefore the host can see all the day that is being transferred from one enclave to the other.

**Comment by gupta-ak** [comment]
To do local attestation, we need a secure way to know the other enclave's identity beforehand. I don't think just using the enclave file name is reliable since the host can simply replace the requested file. So, the calling enclave needs to figure out how to get an authentic `target_info`. 

After you can do local attestation and generate a shared encryption key via DH key exchange. After that, you can execute ECALLs in another enclave via an OCALL -> ECALL and use the key to create an encryption channel. I guess it would be similar to RPC over TLS.

It seems possible to do, but it will be tricky to get everything right.

**Comment by dthaler** [comment]
Correct, you need a secure channel to the other enclave's identity.   I would argue that same concept would apply to normal host->enclave ECALLS, and the generated oe_create_<foo>_enclave() code should even take that into account.

**Comment by anakrish** [comment]
Enclave filename may not be sufficient to uniquely identify and enclave. In SGX, many enclaves can be instantiated from the same enclave binary. Each instantiated enclave has a unique identity (local report).

**Comment by lilyfang** [comment]
We will add Enclave-to-Enclave communication. However, we will not support the direct enclave-to-enclave ECALLs at this moment. There are many cases that we need to think through first.

**Comment by lilyfang** [comment]
Just this bug to track enclave-to-enclave communication. Once we understand more about enclave-to-enclave ECALL requirements, will open a new issue to track.

**Comment by radhikaj** [comment]
TLS is being tracked by https://github.com/microsoft/openenclave/issues/1325 
GRPC is going to be available after v0.6, so moving this

**Comment by radhikaj** [comment]
We are still debating whether GRPC or CURL should be supported inside the enclave. Moving this to backlog . Will move to milestone after we have definite requirements from partner or customer

**Comment by radhikaj** [comment]
@achamayou has added the implementation of a CURL lib that can be used inside an enclave.
https://github.com/openenclave/openenclave-curl
We also now support enclave TLS.
