### ISSUE TITLE
Add TEE-provided PRNG implementation to oe_random

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [openenclave/openenclave#892]
Per #888, there is a request for `sgx_read_rand` parity functionality provided inside an enclave for use by an enclave app. This issue tracks implementing the `oe_random` function to provide that directly instead of using an indirection to enclave crypto library as it does today.

**Comment by dthaler** [comment]
To be clear, I think this issue does not track any change to the API surface, but rather changing the implementation under the public API surface tracked by issue #832

**Comment by CodeMonkeyLeet** [comment]
Renamed for clarity.

**Comment by radhikaj** [comment]
@mingweishih Please follow up with @CodeMonkeyLeet for this issue.

**Comment by mingweishih** [comment]
Fixed by #2497.
