### ISSUE TITLE
Factor out ELF-specific backtrace handling

### ISSUE THREAD

**Issue by mikbras** [openenclave/openenclave#961]
@CodeMonkeyLeet : Future work: We should file an issue around factoring out the ELF-specific handling of backtrace symbols into windows/Linux source files instead of inline in ocalls.c

Also we need to support backtraces on Windows.

**Comment by gupta-ak** [comment]
Note that the windows backtrace will have to be a bit different since msvc seems to use rbp as a general purpose register.

**Comment by mikbras** [comment]
The backtrace handling on the host side is only enable for Linux:
```
static char** _backtrace_symbols(
    oe_enclave_t* enclave,
    void* const* buffer,
    int size)
{
    char** ret = NULL;

#if defined(__linux__)
...
#endif
```

If we remove this, it will work fine for Windows as well.
