### ISSUE TITLE
oeedger8r: Generate/Enforce edge function signature validity

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#977]
Currently the enclave compiled in linux is used in windows. 
This introduces issues if the edge functions use non-portable types.
Eg:
  long is 4 bytes in Windows, but 8 bytes in Linux.
  wchar_t is 2 bytes in Windows, but 4 bytes in Linux.
  long double is 8 byes in Windows, but 16 bytes in Linux.
Issues could also arise if compiler options are used to influence the size of primitive types.

We should ideally generate type type checking meta-data (say the sizeof each argument, the size of the marshaling struct, the offsets of the fields of the marshaling struct etc) for each function on both the host and the enclave.
When an enclave is created, it  can pass in the meta-data on the host side over to the enclave so that enclave can perform type validation for the edger functions and react appropriately to type mismatch.

**Comment by johnkord** [comment]
@anakrish Tagging you to resolve this duplicate bug
