### ISSUE TITLE
Debugger: enter.s nested_exit stores invalid pointer in ocall_context

### ISSUE THREAD

**Issue by anakrish** [openenclave/openenclave#992]
@bmhsieh found out that https://github.com/Microsoft/openenclave/blob/master/enclave/core/sgx/enter.S#L202
pops the constructed oe_ocall_context_t and therefore the value stored by _oe_notify_nested_exit_start is invalid after that.

This part of the debugger implementation needs to be revisited.

@mikbras @CodeMonkeyLeet @anitagov

**Comment by anitagov** [comment]
Fixed the link in the description as the enter.S moved into the sgx directory.
@johnkord - I believe this is a "non-trivial" bug which needs to be fixed.

**Comment by johnkord** [comment]
@anakrish Is this fixed? If not, should we plan for this in the 0.6 milestone?

**Comment by anakrish** [comment]
I think this is a non-issue. From what I remember the object on the stack is only used to notify the debugger for stack-stitching; doesn't matter if the object becomes invalid after than. Will look at this again for v0.6

**Comment by yakman2020** [comment]
@anand if this is still real pls reopen in 0.7

**Comment by anakrish** [comment]
This is not an issue. This will most likely be simplified with our debugger work for v0.7
